### DISCUSSION TITLE
Selector Terms for AMI Minimum Age

### DISCUSSION THREAD

**Discussion by lnattrass** [aws/karpenter-provider-aws#8996] [Feature Requests]
### Description

** READ BEFORE CONTINUING: If your issue is not specific to AWS, please cut a ticket in [kubernetes-sigs/karpenter](https://github.com/kubernetes-sigs/karpenter/issues/new/choose).

**What problem are you trying to solve?**
It would be great if I could specify the minimum age of an AMI, so that an AMI can be run in staging for a while before it goes to production.

**How important is this feature to you?**
We just had a production outage due to a [bad AMI](https://github.com/awslabs/amazon-eks-ami/issues/1551).
While we can build a delay mechanism on top using automation/pipeline/etc, a "minimumAge" seems simpler to manage operationally. 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by hamishforbes** [comment]
I'm running into the same bad AMI issue.
My immediate idea for a fix was to add a `NotIn` term to the AMI selector for the bad AMI id, but thats not possible

**Comment by jonathan-innis** [comment]
Somewhat relates to #4769 and #1495 which want to alter the AMI selection logic; though, the requirements here are slightly different.

> It would be great if I could specify the minimum age of an AMI, so that an AMI can be run in staging for a while before it goes to production

Were you using the default AMI that was passed through with the `AMIFamily` or were you specifying specific AMIs in the `amiSelectorTerms`? In either case, I'd imagine that it would probably make sense to have an `amiMinimumAge` field in the `EC2NodeClass` spec to control filtering out AMIs based on age regardless of what gets selected by the `amiFamily` or the `amiSelectorTerms`. I doubt that you would want to define this per-term.

> My immediate idea for a fix was to add a NotIn term to the AMI selector for the bad AMI id

Agree that this might also be something that would be nice to have. Since these terms are meant to perform a matching mechanism against the instance types that we choose to launch with, one idea here is that we allow a requirements section in the `amiSelectorTerms` that shows which amis match-up with which instance types if you wanted to get really specific like

```yaml
amiSelectorTerms:
- tags: 
        karpenter.sh/discovery: ${CLUSTER_NAME}
  requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["c5.large"]
```

so you could exclude an AMI indirectly by doing

```yaml
- tags: 
        karpenter.sh/discovery: ${CLUSTER_NAME}
- id: ${BAD_AMI_ID}
   requirements:
   - key: "node.kubernetes.io/instance-type"
      operator: DoesNotExist
```

That's obviously more indirect for the use-case, so one other alternative is that we create something like an `exclude/include` field in the API block like

```yaml
- tags: 
        karpenter.sh/discovery: ${CLUSTER_NAME}
- id: ${BAD_AMI_ID}
   exclude/reject: true
```

Realistically, I think the `NotIn` operator syntax may be too flexible for what we need here, since we aren't working with labels in the selection logic. Particularly, I'm not sure how we would represent tags as a `key` if we took-up a similar syntax to `matchExpressions` from `nodeAffinity`.
