### ISSUE TITLE
Support for `aws.amazon.com/neuroncore`

### ISSUE THREAD

**Issue by kwon-jaehong** [aws/karpenter-provider-aws#3555]
### Tell us about your request

Is there any way to schedule "aws.amazon.com/neuroncore" in karpenter?

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I am trying to configure ML model MSA in EKS environment.
In addition, we plan to operate the service using the AWS 'inf1' instance.
Each service configured a pod using one **"aws.amazon.com/neuroncore"**.

Example code.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: image:0.1        
        resources:
          limits:
            cpu: 1000m
            memory: 1500Mi
            aws.amazon.com/neuroncore: 1
          requests:
            cpu: 800m
            memory: 1000Mi
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsAfterEmpty: 100
  ttlSecondsUntilExpired: 6000
  limits:
    resources:
      cpu: 100
      aws.amazon.com/neuron: 100
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [inf1]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [xlarge, 2xlarge]
  providerRef:
    name: my-provider
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: my-provider
spec:
  subnetSelector:
    kubernetes.io/cluster/demo: owned
  securityGroupSelector:
    kubernetes.io/cluster/demo: owned
```

When I apply the code, it outputs the following error.

karpenter pod error message:
```
controller 2023-03-07T07:48:40.081Z    ERROR    controller.provisioning    Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"aws.amazon.com/neuroncore":"1","cpu":"800m","memory":"1Gi","pods":"1"} and requirements karpenter.sh/capacity-type In [on-demand], karpenter.k8s.aws/instance-family In [inf1], karpenter.k8s.aws/instance-size In [2xlarge xlarge], kubernetes.io/arch In [amd64], karpenter.sh/provisioner-name In [default]    {"commit": "5d4ae35-dirty", "pod": "app/example-app-866f9cb8dd-xqqjj"}  
```   

**But if I set the resource request of "Deployment" to "aws.amazon.com/neuron" as follows, it works fine.**      

```
apiVersion: apps/v1
kind: Deployment
            .
            .
            .
            aws.amazon.com/neuron: 1
            .
            .
            .
```

[From the karpenter documentation ](https://karpenter.sh/v0.20.0/concepts/instance-types/ )there is no resource "aws.amazon.com/neuroncore" in the inf1 instance family.   

Is there any other way to schedule "aws.amazon.com/neuroncore" in karpenter?

### Are you currently working around this issue?

Temporarily, we want to use the pod resource request as "aws.amazon.com/neuron".   

However, I think that using one neuron-chip (four neuron cores) in a small ML model is inefficient and a waste of resources.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
