### ISSUE TITLE
When scaling up (by 1 node), Karpenter adds 2 nodes instead, and one appears to get "stuck"

### ISSUE THREAD

**Issue by armenr** [aws/karpenter-provider-aws#3725]
### Version

__Karpenter Version:__ v0.27.1

__Kubernetes Version:__ v1.24

### Expected Behavior

No "stuck" nodes that cause pod creation to stall.

### Actual Behavior

Cluster goes from 1 node to 3 nodes, but one of the nodes is referenced by instanceID and is essentially "stuck"...which causes pods to get stuck as well.

### Stuck "node"

```
❯ kubectl get nodes
NAME                                          STATUS     ROLES    AGE     VERSION
i-00507629e749f767e                           NotReady   <none>   3m10s                                                        # Karpenter created this
ip-172-17-19-136.us-west-2.compute.internal   Ready      <none>   2m51s   v1.24.11-eks-a59e1f0     # Karpenter created this
ip-172-17-21-105.us-west-2.compute.internal   Ready      <none>   38h     v1.24.11-eks-a59e1f0
```

### Stuck pods
![Screenshot 2023-04-08 at 8 48 53 AM](https://user-images.githubusercontent.com/7662191/230703775-473bc3ba-0371-400a-8617-c2578786f567.png)

### Steps to Reproduce the Problem

- EKS cluster running release 1.24 
- Latest Karpenter release (0.27.1)

### Karpenter values:

```
settings:
  aws:
    clusterEndpoint: {{ .Values.k8s.K8S_CLUSTER_ENDPOINT }}
    clusterName: {{ .Values.cloud.CLOUD_ENV }}
    defaultInstanceProfile: {{ .Values.karpenter.KARPENTER_INSTANCE_PROFILE_ID }}
    enablePodENI: true
    nodeNameConvention: resource-name
serviceAccount:
  create: true
  name: karpenter
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.cloud.CLOUD_ACCOUNT_ID }}:role/{{ .Values.cloud.CLOUD_ENV }}-{{ .Release.Namespace }}-karpenter"
    eks.amazonaws.com/sts-regional-endpoints: "true"
replicas: 1

additionalAnnotations:
    argocd.argoproj.io/sync-wave: {{ .Values.appConfig.syncWave | quote }}
```

### Karpenter provisioner:

```
---
# Source: 5k_karpenter_provisioners/templates/patched_resources.yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-68"
    meta.helm.sh/release-name: karpenter-provisioners
    meta.helm.sh/release-namespace: kube-system
  name: default
spec:
  instanceProfile: v3-ops-1-KarpenterInstanceProfile
  securityGroupSelector:
    Name: v3-ops-1-eks-node
  subnetSelector:
    Name: v3-ops-1-private*
  tags:
    Name: v3-ops-1-scaled-compute
    karpenter.sh/discovery: v3-ops-1
---
# Source: 5k_karpenter_provisioners/templates/patched_resources.yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-68"
    meta.helm.sh/release-name: karpenter-provisioners
    meta.helm.sh/release-namespace: kube-system
  name: default
spec:
  consolidation:
    enabled: true
  labels:
    vpc.amazonaws.com/has-trunk-attached: "false"
  providerRef:
    name: default
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: node.kubernetes.io/instance-type
    operator: NotIn
    values:
    - c1.medium
    - c1.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - c3.large
    - c3.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - c4.large
    - c4.xlarge
    - cc2.8xlarge
    - d2.2xlarge
    - d2.4xlarge
    - d2.8xlarge
    - d2.xlarge
    - f1.16xlarge
    - f1.2xlarge
    - f1.4xlarge
    - g2.2xlarge
    - g2.8xlarge
    - g3.16xlarge
    - g3.4xlarge
    - g3.8xlarge
    - g3s.xlarge
    - h1.16xlarge
    - h1.2xlarge
    - h1.4xlarge
    - h1.8xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - i2.xlarge
    - i3.16xlarge
    - i3.2xlarge
    - i3.4xlarge
    - i3.8xlarge
    - i3.large
    - i3.xlarge
    - i4i.large
    - m1.large
    - m1.medium
    - m1.small
    - m1.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - m2.xlarge
    - m3.2xlarge
    - m3.large
    - m3.medium
    - m3.xlarge
    - m4.10xlarge
    - m4.16xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.large
    - m4.xlarge
    - p2.16xlarge
    - p2.8xlarge
    - p2.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - r3.large
    - r3.xlarge
    - r4.16xlarge
    - r4.2xlarge
    - r4.4xlarge
    - r4.8xlarge
    - r4.large
    - r4.xlarge
    - t1.micro
    - t2.2xlarge
    - t2.large
    - t2.medium
    - t2.micro
    - t2.nano
    - t2.small
    - t2.xlarge
    - t3.2xlarge
    - t3.large
    - t3.medium
    - t3.micro
    - t3.nano
    - t3.small
    - t3.xlarge
    - t3a.2xlarge
    - t3a.large
    - t3a.medium
    - t3a.micro
    - t3a.nano
    - t3a.small
    - t3a.xlarge
    - t4g.2xlarge
    - t4g.large
    - t4g.medium
    - t4g.micro
    - t4g.nano
    - t4g.small
    - t4g.xlarge
    - u-12tb
    - u-18tb
    - u-6tb
    - u-6tb
    - u-9tb
    - x1.16xlarge
    - x1.32xlarge
    - x1e.16xlar
    - x1e.2xlarge
    - x1e.32xlar
    - x1e.4xlarge
    - x1e.8xlarge
    - x1e.xlarge
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
