### ISSUE TITLE
Karpenter could not schedule pods with specific labels

### ISSUE THREAD

**Issue by tomerleib** [aws/karpenter-provider-aws#4085]
### Version

__Karpenter Version:__ v0.27.5

__Kubernetes Version:__ v1.25.10-eks-c12679a

### Expected Behavior

I was testing Karpenter for per-application team usage and used the examples from here:
https://aws.github.io/aws-eks-best-practices/karpenter/#create-provisioners-that-are-mutually-exclusive-or-weighted.
I was expecting Karpenter to scale my nodes when there are pending pods.

### Actual Behavior

My application pods are stuck in pending. 
When I look at the logs, I can see the following errors:
```bash
karpenter-799794b4f-jzz7l controller 2023-06-20T12:44:38.209Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "test-provisioner", incompatible requirements, label "app1" does not have known values	{"commit": "698f22f-dirty", "pod": "default/test-app-5c6cc4b6f9-gm7gf"}
```

### Steps to Reproduce the Problem

Deploy the example with the changes in my code, scale it, and test it.

### Resource Specs and Logs

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test-provisioner
  labels:
    app1: test-app
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
      - g5.2xlarge
      - g5.xlarge
      - g4dn.xlarge
      - g4dn.2xlarge                
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: default
  consolidation:
    enabled: true
  taints:
  - effect: NoSchedule
    key: "dedicated"
    value: "gpuGroup"
```

* Deployment Spec
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app1: test-app
    env: vcp-dev
  name: test-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app1: test-app
      env: vcp-dev
  template:
    metadata:
      labels:
        app1: test-app
        env: vcp-dev
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "app1"
                  operator: "In"
                  values: ["test-app"]
      tolerations:
      - key: "dedicated"
        operator: "Exists"
        effect: "NoSchedule"
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
