### ISSUE TITLE
Failing to start new instances in some AZs with weird error

### ISSUE THREAD

**Issue by TheEdgeOfRage** [aws/karpenter-provider-aws#4165]
### Description

**Observed Behavior**:

We use karpenter to manage nodes for a couple of StatefulSets (multiple Trino clusters) in our k8s cluster. These stateful sets always have a constant number of pods, but the number of sets differs based on demand (it has to be done this way). One node will be assigned exactly one pod (+daemonsets), since the pods are allowed to use up a whole node. We have an operator that scales the number of statefulsets based on demand and handles rollout of new versions. So when we have a new version, there will be a large spike in new pods before we delete the old statefulsets. Also, all of the pods of a given statefulset have to be deployed in a single AZ due to latency requirements.

The problem we're having, is that we use m7g.8xlarge instances and apparently AWS has limited capacity at times in eu-west-1. Especially during new version rollouts, we have seen this error pop up at times for some of the machines:

```
creating instance, insufficient capacity, with fleet error(s), InsufficientInstanceCapacity: We currently do not have sufficient m7g.8xlarge capacity in the Availability Zone you requested (eu-west-1c). Our system will be working on provisioning additional capacity.
```

This is understandable and can usually be avoided by moving to a different AZ or just waiting a bit.
Yesterday though, we've tried deploying a new version and all except one pod managed to get assigned a node and ran successfully. We thought that the last one would get eventually scheduled, but then came back this morning to find it still in pending and the following being printed by karpenter:

```
incompatible with provisioner "trino", daemonset overhead={"cpu":"340m","memory":"272Mi","pods":"6"}, no instance type satisfied resources {"cpu":"340m","memory":"111696212672","pods":"7"} and requirements karpenter.sh/capacity-type In [on-demand], karpenter.k8s.aws/instance-category In [c m r], node.kubernetes.io/instance-type In [m7g.8xlarge], kubernetes.io/arch In [amd64 arm64], kubernetes.io/os In [linux], karpenter.k8s.aws/instance-generation Exists >2, dunetech.io/nodegroup In [trino], karpenter.sh/provisioner-name In [trino], topology.kubernetes.io/zone DoesNotExist (no instance type met the scheduling requirements or had a required offering);
```

We tried to delete the pod and restart karpenter, but that did not help. We tried starting an instance of that type manually on that AZ through the EC2 console which was successful, so it should not be AWS being out of capacity. Then we tried deploying the statefulset to a separate AZ. In that case we got the previous error again about capacity not being available. After reverting it back to the first AZ, more pods started getting stuck in pending and fewer nodes got started. I believe 12/30 managed to get started, with the remaining being stuck with the same error on karpenter.

For now, we have reverted to m6g.8xlarge and that seems to have resolved the issue and all pods are happy now, but we're still unsure about the cause of the error on karpenter and whether it's related to AWS or something on the karpenter side. The DEBUG logs don't show any additional information, just that one ERROR line.

The weird part is that when there's capacity problems, karpenter does recognize the instance type and tries to start it, but fails at the "creating instance" step. Here it seems to fail before that, while it's looking up the instance type, as if the type itself stops existing.

**Expected Behavior**:

I would expect karpenter to either fail with a capacity error or successfully create an instance, not get stuck in this weird in-between state.

**Reproduction Steps** (Please include YAML):

AWSNodeTemplate:
```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: query-engine
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      throughput: 125
      volumeSize: 50Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      throughput: 125
      volumeSize: 100Gi
      volumeType: gp3
  securityGroupSelector:
    Name: prod_cluster-node
  subnetSelector:
    karpenter.sh/discovery: prod_cluster
  tags:
    karpenter.sh/discovery: prod_cluster
status:
  amis:
  - id: ami-074fbfeace58964ae
    name: bottlerocket-aws-k8s-1.27-x86_64-v1.14.1-842c7134
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
  - id: ami-03c9c3a3d3c1a0252
    name: bottlerocket-aws-k8s-1.27-nvidia-x86_64-v1.14.1-842c7134
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: Exists
  - id: ami-03c9c3a3d3c1a0252
    name: bottlerocket-aws-k8s-1.27-nvidia-x86_64-v1.14.1-842c7134
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: Exists
  - id: ami-081beb63677be952e
    name: bottlerocket-aws-k8s-1.27-nvidia-aarch64-v1.14.1-842c7134
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: Exists
  - id: ami-081beb63677be952e
    name: bottlerocket-aws-k8s-1.27-nvidia-aarch64-v1.14.1-842c7134
    requirements:
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: Exists
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
  - id: ami-06a0a3d809f3dc5b2
    name: bottlerocket-aws-k8s-1.27-aarch64-v1.14.1-842c7134
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
  securityGroups:
  - id: sg-REDACTED
    name: prod_cluster-node20220520093637109600000010
  subnets:
  - id: subnet-REDACTED
    zone: eu-west-1c
  - id: subnet-REDACTED
    zone: eu-west-1b
  - id: subnet-REDACTED
    zone: eu-west-1a
```

Provisioner:
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: trino
spec:
  labels:
    dunetech.io/nodegroup: trino
  providerRef:
    name: query-engine
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
    - arm64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
    - m
    - r
  - key: karpenter.k8s.aws/instance-generation
    operator: Gt
    values:
    - "2"
  taints:
  - effect: NoSchedule
    key: dunetech.io/nodegroup
    value: trino
  ttlSecondsAfterEmpty: 60
```

StatefulSet:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: workers
spec:
  replicas: 15
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dunetech.io/nodegroup
                operator: In
                values:
                - trino
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - m7g.8xlarge
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                - on-demand
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - eu-west-1b
      containers:
      - image: ...
        imagePullPolicy: IfNotPresent
        name: container
        resources:
          requests:
            memory: 111411M # adjusted for our instance type and daemonsets
      tolerations:
      - effect: NoSchedule
        key: dunetech.io/nodegroup
        operator: Equal
        value: trino
```

**Versions**:
- Chart Version: v0.28.0
- Kubernetes Version (`kubectl version`): v1.27.2-eks-c12679a

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
