### ISSUE TITLE
Leader election 

### ISSUE THREAD

**Issue by nalshamaajc** [aws/karpenter-provider-aws#4168]
### Description

**Observed Behavior**:
Randomly getting the below errors. The incident involved frequent deprovisioning and service outage noting that PDBs are set.
```
E0626 20:00:18.625437       1 leaderelection.go:367] Failed to update lock: Put "[https://172.20.0.1:443/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election](https://172.20.0.1/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election)": context deadline exceeded
E0626 19:38:37.928683       1 leaderelection.go:330] error retrieving resource lock karpenter/karpenter-leader-election: Get "[https://172.20.0.1:443/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election](https://172.20.0.1/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election)": net/http: TLS handshake timeout
E0626 19:35:58.115419       1 leaderelection.go:330] error retrieving resource lock karpenter/karpenter-leader-election: Get "[https://172.20.0.1:443/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election](https://172.20.0.1/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election)": http2: client connection lost
```
![Pasted Graphic 9](https://github.com/aws/karpenter/assets/114491638/1394e56b-1381-47bd-bd7d-19beaa2cbe26)

and another set of logs that are weird and are asking me to file a report

```
"level":"ERROR","time":"2023-06-29T14:15:21.662Z","logger":"controller.pod_state","message":"invariant violated registering host port usage, IP=0.0.0.0 Port=8125 Proto=UDP conflicts with existing HostPort configuration IP=0.0.0.0 Port=8125 Proto=UDP, please file an issue","commit":"d7e22b1-dirty","pod”:”xxxx/xxxx-djkh9"}

2
{"level":"ERROR","time":"2023-06-29T14:15:21.688Z","logger":"controller.pod_state","message":"invariant violated registering host port usage, IP=0.0.0.0 Port=8125 Proto=UDP conflicts with existing HostPort configuration IP=0.0.0.0 Port=8125 Proto=UDP, please file an issue","commit":"d7e22b1-dirty","pod”:”xxxx/xxxx-djkh9"}
```

Pods were restarting

![Pasted Graphic 5](https://github.com/aws/karpenter/assets/114491638/9af7c456-a930-43d9-96a9-04c4609abb7a)

We scaled the karpenter deployment to 4. Still seeing some weird logs.

- I see 2 logs which I'd like to know more about and how they might relate to the incident.
`failed to renew lease`
`client-side throttling`
![image](https://github.com/aws/karpenter/assets/114491638/5957c318-91d0-4ec7-9f26-26ce11bfeff6)

- Apparently this was the leader or trying to be.
What does panic mean in the logs and why was there so many timeouts. It shouldn't be normal to see that much errors right?
![image](https://github.com/aws/karpenter/assets/114491638/9277c396-ce48-4c9d-b724-840912bce4a2)

**Expected Behavior**:
Not getting these errors
**Reproduction Steps** (Please include YAML):
No clear steps so far
**Versions**: 
- Chart Version:  v0.27.3
- Kubernetes Version (`kubectl version`): v1.25.9-eks-5f89878
- Node OS Version: Bottlerocket OS 1.14.1 (aws-k8s-1.25)   5.15.108

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
How much memory and cpu are you giving Karpenter? What kind of scale is your cluster running under? Typically we are seeing client-side throttling or logs like this when there are extremely large scale-ups or there are a lot of events on your cluster all happening at one time.

**Comment by nalshamaajc** [comment]
@jonathan-innis The resource limits were left as default (non set). In terms of scale we currently have 1394 pods which is everything on the cluster, 37 nodes managed by Karpenter, and 8 nodes for critical workloads (like Karpenter) that are under a Managed Node Group. Well in terms of events we are migrating some services to the cluster, but I don't think that was the case for the incident that is being addressed in this issue.

**Comment by shay-ul** [comment]
Hi @jonathan-innis, we are experiencing this as well:
```
2023-07-27T02:35:23.658Z	ERROR	controller	error retrieving resource lock karpenter/karpenter-leader-election: Get "https://172.20.0.1:443/apis/coordination.k8s.io/v1/namespaces/karpenter/leases/karpenter-leader-election": context deadline exceeded
	{"commit": "c3d4e73-dirty"}
```
We have a large cluster (scales up to over 700 nodes). I increased the Karpenter resource reuqests this is still happening.

```
          resources:
            requests:
              cpu: "2"
              memory: 2Gi
```

**Comment by roimor** [comment]
im having the same issue as above :(

**Comment by ellistarn** [comment]
Digging into this. @nalshamaajc, you absolutely should be setting cpu/memory, or you may get client side throttling. Given the other reports, I think there may be something going on with the EKS Control Plane. I'll raise this with the team. In the meantime, please submit a support ticket to EKS to diagnose these client timeouts.

**Comment by shay-ul** [comment]
HI @ellistarn , I have opened a support ticket - 13461296631. If you need any logs/details attached there, let us know.

**Comment by flavono123** [comment]
- Chart Version: v0.27.5
- Kubernetes Version (kubectl version): v1.24.16-eks-2d98532
- Node OS Version: AL2

having same issue on the above env, only about `failed to renew lease`. hope to solve soon

**Comment by jonathan-innis** [comment]
It may be worth trying out a `FlowSchema` here where the coordination APIs for Karpenter are prioritized so that the apiserver is less likely to drop leader election requests during periods of high traffic

```
apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: FlowSchema
metadata:
  name: karpenter-leader-election
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 300
  priorityLevelConfiguration:
    name: leader-election
  rules:
  - resourceRules:
    - apiGroups:
      - ""
      namespaces:
      - '*'
      resources:
      - endpoints
      - configmaps
      verbs:
      - get
      - create
      - update
    - apiGroups:
      - coordination.k8s.io
      namespaces:
      - '*'
      resources:
      - leases
      verbs:
      - get
      - create
      - update
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: '*'
        namespace: karpenter
```

**Comment by jonathan-innis** [comment]
I think it might also make sense to assign the `workload-high` priority to _any_ request coming from the Karpenter controller as well

```yaml
apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: FlowSchema
metadata:
  name: karpenter-service-account
spec:
  distinguisherMethod:
    type: ByNamespace
  matchingPrecedence: 1000
  priorityLevelConfiguration:
    name: workload-high
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: karpenter
        namespace: karpenter
```
