### ISSUE TITLE
How do I use karpenter in helmfile?

### ISSUE THREAD

**Issue by naruse666** [aws/karpenter-provider-aws#4485]
I'm helm beginner.
## Question
I would like to define in helmfile the commands that are executed in get started [deploy-karpenter](https://karpenter.sh/docs/getting-started/migrating-from-cas/#deploy-karpenter).

Here is the helmfile I wrote.
```
# helmfile.yaml
repositories:
  - name: karpenter
    url: public.ecr.aws/karpenter/karpenter
    oci: true

releases:
  - name: karpenter
    namespace: karpenter
    chart: karpenter/karpenter
    version: "v0.29.2"
    values:
     - ./values.yaml
```

```
# values.yaml
{{- $clusterName := "karpenter-demo" }}

serviceAccount:
  annotations: {
    eks.amazonaws.com/role-arn: "<role-arn>"
  }

settings:
  aws:
    clusterName: {{ $clusterName }}
    defaultInstanceProfile: <InstanceProfile>
controller:
  resources:
    requests:
      cpu: 1
      memory: 1G
    limits:
      cpu: 1
      memory: 1G
```

When I do this, I get the following error
How do I write the correct helmfile?

## Error
```
Pulling public.ecr.aws/karpenter/karpenter/karpenter:v0.29.2
in ./helmfile.yaml: [release "karpenter": command "/opt/homebrew/bin/helm" exited with non-zero status:

PATH:
  /opt/homebrew/bin/helm

ARGS:
  0: helm (4 bytes)
  1: pull (4 bytes)
  2: oci://public.ecr.aws/karpenter/karpenter/karpenter (50 bytes)
  3: --version (9 bytes)
  4: v0.29.2 (7 bytes)
  5: --destination (13 bytes)
  6: /var/folders/5h/bzsg6m6s0514v9s9v_k84_340000gq/T/helmfile1162408419/karpenter/karpenter/karpenter/v0.29.2 (105 bytes)
  7: --untar (7 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: public.ecr.aws/karpenter/karpenter/karpenter:v0.29.2: not found

COMBINED OUTPUT:
  Error: public.ecr.aws/karpenter/karpenter/karpenter:v0.29.2: not found]
```

**Comment by njtran** [comment]
I haven't used a helmfile myself personally, but it looks like your oci path is wrong. I think you have one more "karpenter" in your oci path than necessary.

This should be the right path: `oci://public.ecr.aws/karpenter/karpenter`

Refer to the helm command here for more info: https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#4-install-karpenter

**Comment by njtran** [comment]
If you look at the getting started guide, it just does `helm upgrade`, but it looks like you have `helm diff upgrade`. It looks like you're having general issues with your installation, where I think you'd be able to get more help from the community to find others who use helmfiles to deploy Karpenter - you should message in the slack channel [here](https://kubernetes.slack.com/archives/C02SFFZSA2K).

**Comment by gazal-k** [comment]
Please look at the error carefully. There's an extra `/karpenter` in the repository section of your helmfile.

It should be:
```
repositories:
  - name: karpenter
    url: public.ecr.aws/karpenter
    oci: true
```

**Comment by gazal-k** [comment]
Please try this instead:

```yaml
repositories:
- name: karpenter
  url: public.ecr.aws/karpenter
  oci: true

releases:
- name: karpenter
  namespace: karpenter 
  chart: karpenter/karpenter
  version: v0.29.2
  values:
    - ./values.yaml
```
