### ISSUE TITLE
Passing kubelet configuration for topology-manager-policy

### ISSUE THREAD

**Issue by zm-alex** [aws/karpenter-provider-aws#4740]
### Description

This is more of a question.

For our EKS worker nodes, we usually add to the kubelet configuration the following:

```
--cpu-manager-policy=static --topology-manager-policy=single-numa-node
```

Looking at the doc for Karpenter, it doesn't seem to include the option to set these configurations. Is there a way for us to pass in kubelet configs in the provisioner? Or is there a plan to add this feature?

I'm currently using Karpenter v0.29.2

Thanks!

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
You can try to pass in the kubelet configuration using [userData](https://karpenter.sh/docs/concepts/node-templates/#specuserdata) field on the `AWSNodeTemplate`

**Comment by zm-alex** [comment]
@engedaam thanks!

Will you happen to have an example of how you will do this?

I tried adding the user data with the kubelet arguments but the Node never got into a ready state and I couldn't see any logs from the EC2 that indicate what went wrong. I did see however that the EKS bootstrap script to add the kubelet arguments ran two times with different arguments

I have the following userdata

```
  userData: |
    #!/bin/bash -xe
    export CLUSTER_NAME={{ .tags.Name }}
    export CLUSTER_ENDPOINT=$(aws eks describe-cluster --name $CLUSTER_NAME --query cluster.endpoint --output text)
    export CLUSTER_CA=$(aws eks describe-cluster --name $CLUSTER_NAME --query cluster.certificateAuthority --output text)
    exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
    /etc/eks/bootstrap.sh $CLUSTER_NAME --apiserver-endpoint $CLUSTER_ENDPOINT --b64-cluster-ca $CLUSTER_CA \
    --kubelet-extra-args '--cpu-manager-policy=static --topology-manager-policy=single-numa-node'
```

This is my provisioner spec

```
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    containerRuntime: containerd
    maxPods: 234
  labels:
    node_type: t3-medium
    workload: test
  limits:
    resources:
      cpu: '200'
      memory: 2000Gi
  providerRef:
    name: t3-medium-provisioner
  requirements:
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
        - t3
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values:
        - medium
  taints:
    - effect: NoSchedule
      key: node_type
      value: t3-medium
    - effect: NoSchedule
      key: workload
      value: test
```

This is my node template 

```
spec:
  amiFamily: AL2
  amiSelector:
    'aws::ids': ami-04e4715dd39e31d8b
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 200Gi
        volumeType: gp3
  detailedMonitoring: true
  securityGroupSelector:
    karpenter.sh/discovery: dev-us-east-1
  subnetSelector:
    karpenter.sh/discovery: dev-us-east-1
  tags:
    Managed_by: zoomai-kites-karpenter
    Name: dev-us-east-1
    cluster: dev
    cluster_name: dev-us-east-1
  userData: >
    #!/bin/bash -xe

    export CLUSTER_NAME=kites-dev-us-east-1

    export CLUSTER_ENDPOINT=$(aws eks describe-cluster --name $CLUSTER_NAME
    --query cluster.endpoint --output text)

    export CLUSTER_CA=$(aws eks describe-cluster --name $CLUSTER_NAME --query
    cluster.certificateAuthority --output text)

    exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console)
    2>&1

    /etc/eks/bootstrap.sh $CLUSTER_NAME --apiserver-endpoint $CLUSTER_ENDPOINT
    --b64-cluster-ca $CLUSTER_CA \

    --kubelet-extra-args '--cpu-manager-policy=static
    --topology-manager-policy=single-numa-node'
```

Any advice or pointers will be appreciated! Thanks!
