### ISSUE TITLE
I need to add an extra disk, how do I turn on the EBS optimization option for it?

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter-provider-aws#5053]
### Description

env:
```
karpenter: v0.31.1
eks: v1.25
```

my  AWSNodeTemplate  disk part
```
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 80Gi
        deleteOnTermination: true
        encrypted: true
        iops: 3000
        throughput: 125
```
