### ISSUE TITLE
Nodes never get provisioned for my workload

### ISSUE THREAD

**Issue by DevopsCareer** [aws/karpenter-provider-aws#5176]
Hello,
I am noticing following error in karpenter logs 
`
2023-11-28T04:21:33.262Z	DEBUG	controller.machine.lifecycle	terminating due to registration ttl	{"commit": "322822a", "machine": "first-karpenter-provisioner-cn-northwest-1-xxxx", "provisioner": "first-karpenter-provisioner-cn-northwest-1", "ttl": "15m0s"}
2023-11-28T04:21:33.664Z	INFO	controller.machine.termination	deleted machine	{"commit": "322822a", "machine": "first-karpenter-provisioner-cn-northwest-1-xxxx", "provisioner": "first-karpenter-provisioner-cn-northwest-1", "node": "", "provider-id": "aws:///cn-northwest-1a/i-0030xxxxx"}`

It never launches a ec2 instance for my workloads.

If I do `kubectl describe machine first-karpenter-provisioner-cn-northwest-1-xxxx`
I see 
` `` Conditions:
    Last Transition Time:  2023-11-28T04:52:02Z
    Message:               Node not registered with cluster
    Reason:                NodeNotFound
    Status:                False
    Type:                  MachineInitialized
    Last Transition Time:  2023-11-28T04:52:02Z
    Status:                True
    Type:                  MachineLaunched
    Last Transition Time:  2023-11-28T04:52:02Z
    Message:               Node not registered with cluster
    Reason:                NodeNotFound
    Status:                False
    Type:                  Ready
    Last Transition Time:  2023-11-28T04:52:02Z
    Message:               Node not registered with cluster
    Reason:                NodeNotFound
    Status:                False
    Type:                  MachineRegistered```

**Comment by jmdeal** [comment]
Can you tell if the EC2 instance was created and was unable to join the cluster? Could you also provide the provisioner, node template, and machine specs for that node?

**Comment by rubel-ahammad** [comment]
I am also facing the same issue. EC2 instances gets created and after 15 minutes they gets terminated and new instances gets created. Also, Nodes are not joining the cluster. I am on Karpenter v0.29.2 and EKS 1.27.

Machine objects in Kubernetes are being created and deleted automatically after every 15 minutes.

**Comment by marcustut** [comment]
Having this issue too, I am on Karpenter v0.32.1 and EKS 1.25. The following is my nodepool:

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: ...
spec:
  template:
    spec:
      requirements:
        # This is to tell the nodepool to scale for these nodegroups
        - key: name
          operator: In
          values: ["ng-...", "ng-..."]
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t4g"]
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values: ["nano", "micro", "small"]
      nodeClassRef:
        name: default
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: 24h # One day
```

The nodeclaim:

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodeClaim
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "12456489189921768695"
    karpenter.sh/managed-by: ...
    karpenter.sh/nodepool-hash: "12393960163388511505"
  creationTimestamp: "2023-12-01T15:25:13Z"
  finalizers:
  - karpenter.sh/termination
  generateName: ...-
  generation: 1
  labels:
    karpenter.k8s.aws/instance-category: t
    karpenter.k8s.aws/instance-cpu: "2"
    karpenter.k8s.aws/instance-encryption-in-transit-supported: "false"
    karpenter.k8s.aws/instance-family: t4g
    karpenter.k8s.aws/instance-generation: "4"
    karpenter.k8s.aws/instance-hypervisor: nitro
    karpenter.k8s.aws/instance-memory: "4096"
    karpenter.k8s.aws/instance-network-bandwidth: "256"
    karpenter.k8s.aws/instance-size: medium
    karpenter.sh/capacity-type: on-demand
    karpenter.sh/nodepool: ...
    kubernetes.io/arch: arm64
    kubernetes.io/os: linux
    name: ng-...
    node.kubernetes.io/instance-type: t4g.medium
    topology.kubernetes.io/region: ap-south-1
    topology.kubernetes.io/zone: ap-south-1a
  name: execution-backtest-hl66t
  ownerReferences:
  - apiVersion: karpenter.sh/v1beta1
    blockOwnerDeletion: true
    kind: NodePool
    name: execution-backtest
    uid: 0e84bc6c-b885-4fe6-b0df-9b97ced44284
  resourceVersion: "25259933"
  uid: abe15339-115f-493a-8524-b10e30a34147
spec:
  nodeClassRef:
    name: default
  requirements:
  - key: karpenter.k8s.aws/instance-size
    operator: NotIn
    values:
    - micro
    - nano
    - small
  - key: karpenter.sh/nodepool
    operator: In
    values:
    - ...
  - key: name
    operator: In
    values:
    - ng-cybotrade-execution
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - t4g.2xlarge
    - t4g.large
    - t4g.medium
    - t4g.xlarge
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - t4g
  resources:
    requests:
      cpu: 705m
      memory: 888Mi
      pods: "5"
status:
  allocatable:
    cpu: 1930m
    ephemeral-storage: 17Gi
    memory: 3187Mi
    pods: "17"
  capacity:
    cpu: "2"
    ephemeral-storage: 20Gi
    memory: 3729Mi
    pods: "17"
  conditions:
  - lastTransitionTime: "2023-12-01T15:25:14Z"
    message: Node not registered with cluster
    reason: NodeNotFound
    status: "False"
    type: Initialized
  - lastTransitionTime: "2023-12-01T15:25:14Z"
    status: "True"
    type: Launched
  - lastTransitionTime: "2023-12-01T15:25:14Z"
    message: Node not registered with cluster
    reason: NodeNotFound
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-12-01T15:25:14Z"
    message: Node not registered with cluster
    reason: NodeNotFound
    status: "False"
    type: Registered
  imageID: ami-05569960828390e35
  providerID: aws:///ap-south-1a/i-0c3687dd23f4d1051

```

**Comment by marcustut** [comment]
```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Ubuntu # AL2 does not support arm64 with GPU (cause error when karpenter trying to discover nodes)
  role: "KarpenterNodeRole-$CLUSTER_NAME"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "$CLUSTER_NAME"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "$CLUSTER_NAME"
```

> Karpenter will delete and recreate machines every 15 minutes if the node fails to join the cluster, so that behavior is expected. There are quite a few reasons why a node may be unable to join. @marcustut @rubel-ahammad, could the two of you share your `EC2NodeClass` (and other karpenter resources)?

**Comment by rubel-ahammad** [comment]
> Karpenter will delete and recreate machines every 15 minutes if the node fails to join the cluster, so that behavior is expected. There are quite a few reasons why a node may be unable to join. @marcustut @rubel-ahammad, could the two of you share your `EC2NodeClass` (and other karpenter resources)?

Please note, the karpenter configuration was working for more than a month or two for me. We didn't update anything in the aws eks as well as in the karpenter side. This morning after deploying a build we noticed that it cannot register any new node. Same thing happened in two different aws instances of eks in two different regions.

**Comment by marcustut** [comment]
> > Karpenter will delete and recreate machines every 15 minutes if the node fails to join the cluster, so that behavior is expected. There are quite a few reasons why a node may be unable to join. @marcustut @rubel-ahammad, could the two of you share your `EC2NodeClass` (and other karpenter resources)?
> 
> Please note, the karpenter configuration was working for more than a month or two for me. We didn't update anything in the aws eks as well as in the karpenter side. This morning after deploying a build we noticed that it cannot register any new node. Same thing happened in two different aws instances of eks in two different regions.

I have similar scenarios, it was working for the past two weeks and it only started to happen on 30th Nov

**Comment by jmdeal** [comment]
Are you both using the `Ubuntu` AMI Family? Yesterday's release of the Ubuntu AMI is broken, the issue is being tracked [here](https://bugs.launchpad.net/cloud-images/+bug/2045311). It's supposed to be fixed in the latest AMI release (this morning) but we're still seeing the same failures in our end to end tests with the new release. Are you able to pin your AMI to the latest working release?

**Comment by marcustut** [comment]
> Are you both using the `Ubuntu` AMI Family? Yesterday's release of the Ubuntu AMI is broken, the issue is being tracked [here](https://bugs.launchpad.net/cloud-images/+bug/2045311). It's supposed to be fixed in the latest AMI release (this morning) but we're still seeing the same failures in our end to end tests with the new release. Are you able to pin your AMI to the latest working release?

Yes, I am using the `Ubuntu` AMI Family, is there a way to override to an older release in the configuration?

**Comment by jmdeal** [comment]
Yep, you can specify AMIs using [AMI Selector Terms](https://karpenter.sh/docs/concepts/nodeclasses/#specamiselectorterms). Here's an example with the last working 1.28 AMI:
```yml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Ubuntu
  role: KarpenterNodeRole-${CLUSTER_NAME}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
  amiSelectorTerms:
    - name: ubuntu-eks/k8s_1.28/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20231128
```

**Comment by marcustut** [comment]
> Yep, you can specify AMIs using [AMI Selector Terms](https://karpenter.sh/docs/concepts/nodeclasses/#specamiselectorterms). Here's an example with the last working 1.28 AMI:
> 
> ```yaml
> apiVersion: karpenter.k8s.aws/v1beta1
> kind: EC2NodeClass
> metadata:
>   name: default
> spec:
>   amiFamily: Ubuntu
>   role: KarpenterNodeRole-${CLUSTER_NAME}
>   subnetSelectorTerms:
>     - tags:
>         karpenter.sh/discovery: ${CLUSTER_NAME}
>   securityGroupSelectorTerms:
>     - tags:
>         karpenter.sh/discovery: ${CLUSTER_NAME}
>   amiSelectorTerms:
>     - name: ubuntu-eks/k8s_1.28/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20231128
> ```

Thanks for this it indeed created a new node however I was stuck with the `waiting on cluster sync` logs instead.

```ndjson
{"level":"INFO","time":"2023-12-02T10:00:30.879Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"1072d3b","pods":"cybotrad[319/3345$
n/cybotrade-live-testnet-7c1de2d0-e77a-496b-9acb-c4d2611db185","duration":"10.544037ms"}                                                                                
{"level":"INFO","time":"2023-12-02T10:00:30.879Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"1072d3b","nodeclaims":
1,"pods":1}                                                                                                                                                             
{"level":"INFO","time":"2023-12-02T10:00:30.892Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"1072d3b","nodepool":"execution-backtest","no
declaim":"execution-backtest-k2nrs","requests":{"cpu":"705m","memory":"888Mi","pods":"5"},"instance-types":"t4g.2xlarge, t4g.large, t4g.medium, t4g.xlarge"}            
{"level":"DEBUG","time":"2023-12-02T10:00:31.138Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"1072d3b","nodeclaim":"executi
on-backtest-k2nrs","nodepool":"execution-backtest","launch-template-name":"karpenter.k8s.aws/7271799625920063270","id":"lt-06a06b63d89f2a15f"}                          
{"level":"DEBUG","time":"2023-12-02T10:00:31.264Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"1072d3b","nodeclaim":"executi
on-backtest-k2nrs","nodepool":"execution-backtest","launch-template-name":"karpenter.k8s.aws/6726714525130882434","id":"lt-056a6a05bdeee51bc"}                          
{"level":"DEBUG","time":"2023-12-02T10:00:31.374Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"1072d3b","nodeclaim":"executi
on-backtest-k2nrs","nodepool":"execution-backtest","launch-template-name":"karpenter.k8s.aws/8939340277022366150","id":"lt-00ce885aca6977266"}                          
{"level":"INFO","time":"2023-12-02T10:00:33.215Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"1072d3b","nodeclaim":"execution-bac
ktest-k2nrs","nodepool":"execution-backtest","provider-id":"aws:///ap-south-1c/i-0d4925ba02bb2e70c","instance-type":"t4g.medium","zone":"ap-south-1c","capacity-type":"o
n-demand","allocatable":{"cpu":"1930m","ephemeral-storage":"17Gi","memory":"3187Mi","pods":"17"}}                                                                       
{"level":"DEBUG","time":"2023-12-02T10:01:30.467Z","logger":"controller.disruption","message":"discovered subnets","commit":"1072d3b","subnets":["subnet-0cda8deadef1e60
96 (ap-south-1a)","subnet-09e82e6783728847d (ap-south-1c)","subnet-03a4962a64e7634b8 (ap-south-1b)","subnet-066769e6d9cb3182b (ap-south-1c)","subnet-0a63d98a23c592ec2 (
ap-south-1b)","subnet-041d53b6f26165a78 (ap-south-1a)"]}                                                                                                                
{"level":"DEBUG","time":"2023-12-02T10:01:50.520Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:01:50.850Z","logger":"controller.provisioner","message":"waiting on cluster sync","commit":"1072d3b"}                            
{"level":"DEBUG","time":"2023-12-02T10:01:51.521Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:01:52.522Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:01:53.523Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:01:54.524Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:01:55.526Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:01:56.527Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:01:57.528Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:01:58.530Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:01:59.530Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:00.531Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:00.850Z","logger":"controller.provisioner","message":"waiting on cluster sync","commit":"1072d3b"}                            
{"level":"DEBUG","time":"2023-12-02T10:02:01.532Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:02.534Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:03.534Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:04.536Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:05.537Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:06.538Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:07.539Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:08.540Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:09.541Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:10.542Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}                             
{"level":"DEBUG","time":"2023-12-02T10:02:10.852Z","logger":"controller.provisioner","message":"waiting on cluster sync","commit":"1072d3b"}                            
{"level":"DEBUG","time":"2023-12-02T10:02:11.543Z","logger":"controller.disruption","message":"waiting on cluster sync","commit":"1072d3b"}
```

**Comment by vjkancherla** [comment]
Hello @jmdeal, I am seeing the same behaviour as OP on Karpenter 0.29.2 and EKS v1.27. I was wondering if you can shed any light on the issue for me please? Thank you in advance.

Here is my AWSNodeTemplate:
```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default-nt
spec:
  instanceProfile: ${module.eks_blueprints_addons.karpenter.node_instance_profile_name}
  subnetSelector:
    karpenter.sh/discovery: ${local.eks_cluster}
  securityGroupSelector:
    karpenter.sh/discovery: ${local.eks_cluster}
```

And, here is my Provisioner:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-prov
spec:
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["t", "c", "m", "r"]
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ["2"]
  providerRef:
    name: default-nt
```

Here is the output from `k describe machines.karpenter.sh default-prov-nsfwg`:

```
onditions:
    Last Transition Time:  2023-12-04T14:22:27Z
    Message:               Node not registered with cluster
    Reason:                NodeNotFound
    Status:                False
    Type:                  MachineInitialized
    Last Transition Time:  2023-12-04T14:22:27Z
    Status:                True
    Type:                  MachineLaunched
    Last Transition Time:  2023-12-04T14:22:27Z
    Message:               Node not registered with cluster
    Reason:                NodeNotFound
    Status:                False
    Type:                  MachineRegistered
    Last Transition Time:  2023-12-04T14:22:27Z
    Message:               Node not registered with cluster
    Reason:                NodeNotFound
    Status:                False
    Type:                  Ready
  Provider ID:             aws:///eu-west-2a/i-0d54c05480129ad66
```

**Comment by rubel-ahammad** [comment]
I was also facing this issue on Karpenter 0.29.2 and EKS v1.27. I have
tested just a while ago and everything is working fine for me.

**Comment by jmdeal** [comment]
@marcustut Are ec2 instances successfully being created and not joining the cluster? If they are are you able to take a look at the kubelet logs and see what could be preventing them? Same question for @vjkancherla.

**Comment by vjkancherla** [comment]
Hi @jmdeal, many thanks for your reply. The behaviour for me is:

- EC2 instance is launched
- "Machine" resource remains not-ready
- "Machine" resource contains the message - "Node not registered with cluster"
- The instance is terminated with in seconds

The whole set of events keep happening in an endless loop.

I am not sure how to grab the kublet logs. Any guidance on this would be appreciated.

PS: I am also exploring the options outlined in this [issue](https://github.com/aws/karpenter/issues/4935) as a possible issue.

Thank you.

**Comment by jmdeal** [comment]
@vjkancherla are you hitting this issue here: https://karpenter.sh/docs/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume? The symptoms sound similar to what we've seen with other users hitting this.

**Comment by vjkancherla** [comment]
Hi @jmdeal, I think you maybe right about my issue being what's described in - https://karpenter.sh/docs/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume.

As a test, I assigned AdminAccess policy to the IAM role that the Karpenter's service account is associated with. The nodes are now being successfully provisioned, without any issues.

We have EBS encryption enabled at the region level. 

I don't quite understand the fix recommended in the troubleshooting link. The example policy given there is already applied to AWS managed Key that is used for EBS encryption. Your guidance would be appreciated.

Thank you.

**Comment by jonathan-innis** [comment]
Closing since this appears to be solved now.

**Comment by nalshamaajc** [comment]
I'm on Karpenter v0.31.5 and migrating to v0.32.10, with EKS 1.29.
I'm almost done with the migration, and I'm testing it, I'm facing some weird behavior where the nodepool creates a nodeClaim but does not create the node.

The logs are not providing any useful information about the issue other than reporting that the nodeClaim is being created.

I get the below in the nodeClaim status section

```
status:
  allocatable:
    cpu: 7910m
    ephemeral-storage: 107Gi
    memory: 14162Mi
    pods: '58'
    vpc.amazonaws.com/pod-eni: '38'
  capacity:
    cpu: '8'
    ephemeral-storage: 120Gi
    memory: 15155Mi
    pods: '58'
    vpc.amazonaws.com/pod-eni: '38'
  conditions:
    - lastTransitionTime: '2024-05-30T13:31:00Z'
      message: Node not registered with cluster
      reason: NodeNotFound
      status: 'False'
      type: Initialized
    - lastTransitionTime: '2024-05-30T13:31:00Z'
      status: 'True'
      type: Launched
    - lastTransitionTime: '2024-05-30T13:31:00Z'
      message: Node not registered with cluster
      reason: NodeNotFound
      status: 'False'
      type: Ready
    - lastTransitionTime: '2024-05-30T13:31:00Z'
      message: Node not registered with cluster
      reason: NodeNotFound
      status: 'False'
      type: Registered
  imageID: ami-0fe93db2c62573b1a
  providerID: 'aws:///us-west-2c/i-0f84d19de2821fd6c'
```
Though I don't see any new nodes being created as shown below
```
kubectl get nodes
NAME                STATUS                     ROLES    AGE     VERSION
compute.internal    Ready                      <none>   2d18h   v1.29.1-eks-61c0bbb
compute.internal    Ready,SchedulingDisabled   <none>   37d     v1.29.1-eks-61c0bbb
compute.internal    Ready                      <none>   64d     v1.29.1-eks-61c0bbb
compute.internal    Ready                      <none>   2d23h   v1.29.0-eks-a5ec690
compute.internal    Ready                      <none>   64d     v1.29.1-eks-61c0bbb
compute.internal    Ready                      <none>   37d     v1.29.1-eks-61c0bbb
compute.internal    Ready                      <none>   64d     v1.29.1-eks-61c0bbb
```
Also noticed this log
```
"level":"DEBUG","time":"2024-05-30T13:46:01.646Z","logger":"controller.nodeclaim.lifecycle","message":"terminating due to registration ttl","commit":"f0eb822","nodeclaim":"default-hbgnd","nodepool":"default","ttl":"15m0s"}
I'm at the phase where I taint the old provisioner and will follow that with shifting the workloads to the new nodePool API.  Is it related to this issue, I use BottleRocketOS, are there any broken releases? 
```
PS: the behavior in my case is somewhat different where the EC2 instance is launched and is not terminated immediately but never joins the cluster.
