### ISSUE TITLE
ec2nodeclass blockdevice mapping does not support virtualName

### ISSUE THREAD

**Issue by runningman84** [aws/karpenter-provider-aws#5180]
### Description

**Observed Behavior**:
I looks like you cannot specify a virtualName in karpenter:
```
strict decoding error: unknown field "spec.blockDeviceMappings[1].virtualName"
```

**Expected Behavior**:
Support similar parameters like https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html#instance-block-device-mapping
We might also want to disable a volume with a NoDevice parameter.

**Reproduction Steps** (Please include YAML):

```
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: bottlerocket-instance-store
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 4Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    virtualName: "ephemeral0"
```

**Versions**:
- Chart Version: 0.32.2
- Kubernetes Version (`kubectl version`): 1.28.x

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

This is linked to this idea: https://github.com/bottlerocket-os/bottlerocket/issues/3613
