### ISSUE TITLE
Is consolidationPolicy a new feature of v0.32?

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter-provider-aws#5204]
### Description

- Q1. Is this a new feature of v0.32?
I can't seem to find the related configuration for v0.31?
```
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
```

- Q2. Currently using v0.31.2 Is it recommended to upgrade to the latest v0.32 version?
