### ISSUE TITLE
Avoid flapping between spot and on-demand instances (in case of 'no capacity'/'capacity is fine' state flapping on AWS side).

### ISSUE THREAD

**Issue by AndrzejWisniewski** [aws/karpenter-provider-aws#5250]
### Description

**What problem are you trying to solve?**

Let's assume we have karpenter configuration to start first spot instances (many types) and as fallback on-demand (["spot","on-demand"]). I most cases all works fine (we start spot instances + if there is 'no spot capacity' in AWS we get "spot interruption" events + then karpenter replaces spot instance within on-demand instances + when spot instances are available again karpenter replaces on-demand with spot). We have some kind of issue when AWS makes changes between 'no spot capacity' and 'spot capacity is fine' states very often (e.g. few times in 30 minutes). In such case we observer such steps:
1. karpenter starts spot instances (there is a spot capacity in AWS)
2. after e.g. 5 minutes karpenter gets 'spot interruption' events (there is no spot capacity in AWS)
3. karpenter replaces spot to on-demand
4. after e.g. next 5 minutes karpenter finds out that spot instances are available again (there is a spot capacity in AWS)
5. karpenter replaces on-demand back to spot instance
6. go to 1 (few times such loop) ...

Of course every time all pods are terminated and started again. We have properly set our PDB and in 'normal' working time it can work somehow. The biggest issue is when we had such situation (with flapping between  'no spot capacity' and 'spot capacity is fine') during deployments :/ as mostly it's finished with deployment timeout (we still starting/terminating new/old pods and deployment can not be finished). 

Would be great to have some auto-checking if capacity is flapping and avoid change instances back to spot in such cases. 
As it can be not so easy 🤔 maybe you can provide e.g. some karpenter variable where we can set the time (hour:min) when we try to go back to spot instances if we got fallback to ondemand during last 24h (in this way we can live with on-demand (pay more but with the stable situation) and decide which hour:minute is for us the best to test (automatically) if all is fine now).

**How important is this feature to you?**

Very important and painful. 
In case of such issues we have to check deployment issues (to check why it's failing) and reconfigure karpenter manually (change type of instances from ["spot","on-demand"] to ["on-demand"] so we have a workaround but we have to do it manually + wait some time after such chanage and reconfigure karpenter manually to have ["spot","on-demand"] again + if there is still issue back to ["on-demand"] and again and again ...

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Can you show the full provisioner including the filtering of instance types?

**Comment by bwagner5** [comment]
It could be that Karpenter is flapping the capacity based on the spot interruption event if you are only flexible to a few instance types. When Karpenter handles a spot interruption we cache the instance type as being unavailable for a few minutes (3 min, I believe) https://github.com/aws/karpenter-provider-aws/blob/main/pkg/controllers/interruption/controller.go#L197

**Comment by AndrzejWisniewski** [comment]
Hi @tzneal and @bwagner5 Tx for checking that 🙏 

I can fully understand that we can add more instance types (e.g.  c*, m*, r*, I* and more) and then probably we will not touch the 'no spot capacity issue' but the question is if we can do something if we have configuration like below (not 1-2 types but more) and it's flapping ? 🙏 🤔 ...

Our requirement section:
```
  requirements:
    - key: "karpenter.k8s.aws/instance-family"
      operator: In
      values: ["c6i","c6a","c7i","c7a","m6i","m6a","m7i","m7a"]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: ["8xlarge", "12xlarge", "16xlarge"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-west-2a", "us-west-2b", "us-west-2c"]
    - key: "kubernetes.io/os"
      operator: In
      values: ["linux"]
```
