### ISSUE TITLE
Karpenter is incompatible with FSX CSI driver fsx.csi.aws.com/agent-not-ready:NoExecute startup taint

### ISSUE THREAD

**Issue by ajayvohra2005** [aws/karpenter-provider-aws#5293]
### Description

**Observed Behavior**:

[FSx CSI Driver node startup taint](https://github.com/kubernetes-sigs/aws-fsx-csi-driver/blob/master/docs/install.md#configure-node-startup-taint) can't be used with Karpenter

There are potential race conditions on node startup (especially when a node is first joining the cluster) where pods/processes that rely on the FSx for Lustre CSI Driver can act on a node before the FSx for Lustre CSI Driver is able to start up and become fully ready. To combat this, the FSx for Lustre CSI Driver contains a feature to automatically remove a taint from the node on startup. Users can taint their nodes when they join the cluster and/or on startup, to prevent other pods from running and/or being scheduled on the node prior to the FSx for Lustre CSI Driver becoming ready.

This feature is activated by default, and one can use the taint `fsx.csi.aws.com/agent-not-ready:NoExecute` (any effect will work, but NoExecute is recommended) to use this feature.

**The use of  `fsx.csi.aws.com/agent-not-ready:NoExecute` is not possible with Karpenter**, because tainting  a NodePool with `fsx.csi.aws.com/agent-not-ready:NoExecute` prevents Karpenter from spinning up a node from the NodePool.  If one does not use the  `fsx.csi.aws.com/agent-not-ready:NoExecute` taint, then, depending on the race-condiiton outcome, one gets  `UnexpectedAdmissionError` error on the scheduled Pod. 

**Expected Behavior**:

Karpenter should ignore `fsx.csi.aws.com/agent-not-ready:NoExecute` taint while determining affinity for a NodePool, because this taint is going to be automatically removed by the FSx CSI. Perhaps, `agent-not-ready` taints should be ignored for all cases, with the assumption the agent will automatically remove them when ready.

**Reproduction Steps** (Please include YAML):

It is very hard to offer an easily reproducible test case, because it is entirely based on a race condition.

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`): 0.32.3

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Have you looked at using the startup taints on the NodePool?

```
      # Provisioned nodes will have these taints, but pods do not need to tolerate these taints to be provisioned by this
      # NodePool. These taints are expected to be temporary and some other entity (e.g. a DaemonSet) is responsible for
      # removing the taint after it has finished initializing the node.
      startupTaints:
        - key: fsx.csi.aws.com/agent-not-ready
          effect: NoExecute
```
