### ISSUE TITLE
Pods on Karpenter Nodes cannot assume IAM role

### ISSUE THREAD

**Issue by vvash94** [aws/karpenter-provider-aws#5310]
### Description

**Observed Behavior**:
Pods which run on nodes created by Karpenter dont seem to be getting IAM roles passed to them. Here is a test pod running on an EC2 which was created by Karpenter
`
-bash-4.4$ kubectl exec -it test -- sh
sh-4.2# aws sts get-caller-identity

Unable to locate credentials. You can configure credentials by running "aws configure".
`
This is our first time using Karpenter so not so sure if we are missing something.

**Expected Behavior**:
Pods on the same cluster which run on managed node groups are able to get the identity as expected.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: v0.33.0
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you share the EC2NodeClass and the NodePool that you used to provision the nodes?

**Comment by vvash94** [comment]
Thanks for the quick response. Here you go:

`
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: infra-node-class
spec:
  amiFamily: AL2
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 100Gi
      encrypted: true
      deleteOnTermination: true
    rootVolume: true
  instanceProfile: "devops-karpenter-instance-profile"
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "devops-eks-cluster"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: "devops-eks-cluster"
  - tags:
      kubernetes.io/cluster/devops-eks-cluster: "owned"
  tags:
    Name: devops-eks-worker-node-infra
    Environment: Dev
    CreateSource: Automation
---
kind: NodePool
metadata:
  name: infra-node-pool
spec:
  template:
    spec:
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: ["c", "m"]
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values: ["2"]
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values: ["2", "4", "8", "16"]
      - key: karpenter.k8s.aws/instance-memory
        operator: In
        values: ["4096", "8192", "16384", "32768"]
      nodeClassRef:
        name: infra-node-class
      taints:
      - effect: NoSchedule
        key: node-group-role
        value: infrastructure-node
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 336h
`

**Comment by vvash94** [comment]
I can see that the nodes are getting the right role attached to them. Just the pods cant use them

**Comment by vvash94** [comment]
The only difference I can see between the nodes is that the Karpenter one uses IMDSv2. 

I cant straight up curl http://169.254.169.254/latest/meta-data/iam/info

I need to get the token and then it goes through. Might that be an issue?

**Comment by vvash94** [comment]
That was it. I set metadataOptions.httpTokens to optional and now the pods can get the IAM role. 

I guess my question now is what are the recommeded settings when IMDSV2 is enabled?

**Comment by engedaam** [comment]
I believe you would need to use [IRSA](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-enable-IAM.html) or [Pod Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) to assume the role when using IMDSv2. Are these set for your pods?

**Comment by vvash94** [comment]
@engedaam No these are not. I will look into these. Thanks for the help.

**Comment by ricardorqr** [comment]
@vvash94 Have you fixed this problem?

**Comment by ricardorqr** [comment]
Hi everyone,

I'm having the same problem. I have an EKS cluster with 2 nodes. One node is managed by node group and Karpenter manages the second node. PODs within the node in the node group can assume roles. PODs within the node managed by Karpenter are not able to assume roles.

Here is an example. This is the POD within the node groups.
```sh
bash-4.2# aws sts get-caller-identity
{
    "UserId": "SDFGBSFGBSFGBSFGBSFG:i-123456789",
    "Account": "123456789",
    "Arn": "arn:aws:sts::123456789:assumed-role/us-east-2-vdmdev-network1-node-group-role/i-123456789"
}
bash-4.2#
```

This is the POD within the node managed by Karpenter.
```sh
bash-4.2# aws sts get-caller-identity

Unable to locate credentials. You can configure credentials by running "aws configure".
bash-4.2# 
```

I checked the roles attached to both nodes and they have `AmazonS3FullAccess` policy attached. 

Here is my EC2NodeClass
```yaml
    apiVersion: karpenter.k8s.aws/v1
    kind: EC2NodeClass
    metadata:
      name: default
    spec:
      amiSelectorTerms:
        - alias: al2@v20241205
      role: "${module.karpenter.node_iam_role_name}"
      subnetSelectorTerms:
        - tags:
            karpenter.sh/discovery: "${local.eks-name}"
      securityGroupSelectorTerms:
        - tags:
            karpenter.sh/discovery: "${local.eks-name}"
```

And here is my NodePool,
```yaml
    apiVersion: karpenter.sh/v1
    kind: NodePool
    metadata:
      name: default
    spec:
      template:
        spec:
          requirements:
            - key: kubernetes.io/arch
              operator: In
              values: ["amd64"]
            - key: kubernetes.io/os
              operator: In
              values: ["linux"]
            - key: karpenter.sh/capacity-type
              operator: In
              values: ["${local.karpenter-capacity-type}"]
            - key: karpenter.k8s.aws/instance-category
              operator: In
              values: ["c", "m", "r"]
            - key: karpenter.k8s.aws/instance-generation
              operator: Gt
              values: ["2"]
          nodeClassRef:
            group: karpenter.k8s.aws
            kind: EC2NodeClass
            name: default
          expireAfter: 720h # 30 * 24h = 720h
      limits:
        cpu: 1000
      disruption:
        consolidationPolicy: WhenEmptyOrUnderutilized
        consolidateAfter: 1m
```

ANy idea what this might be?
