### ISSUE TITLE
All nodes replaced due to drift after upgrade from v0.32.2 -> v0.33.0

### ISSUE THREAD

**Issue by joshuabaird** [aws/karpenter-provider-aws#5373]
### Description

**Observed Behavior**:
After an upgrade from v0.32.2 to v0.33 -- we observed that all nodes were replaced due to drift within seconds of each other.  This happened in multiple clusters:

```
disrupting via drift replace, terminating 1 candidates ip-10-50-32-243.ec2.internal/m7i-flex.xlarge/spot and replacing with spot node from types m6id.xlarge, m5d.xlarge, r7a.xlarge, r6a.xlarge, r5a.xlarge and 25 other(s)
```

In every occasion, all nodes replaced were m7i-flex -- I'm not sure if this is relevant or not.  

**Expected Behavior**:

Nodes should not have been drifted.

**Reproduction Steps** (Please include YAML):

Upgrade from v0.32.2 to v0.33.0 and observe nodes being replaced.

NodePool:

```
  spec:
    disruption:
      consolidationPolicy: WhenUnderutilized
      expireAfter: 168h
    limits:
      cpu: 1000
      memory: 256Gi
    template:
      spec:
        nodeClassRef:
          name: default
        requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
          - spot
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
          - m
          - c
          - r
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
          - medium
          - large
          - xlarge
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
          - "4"
          - "8"
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values:
          - nitro
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1a
          - us-east-1b
          - us-east-1c
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
```

I have also attached logs from the upgrade/disruption.
[karp-extract-2023-12-19T18_37_27.511Z.csv](https://github.com/aws/karpenter-provider-aws/files/13719223/karp-extract-2023-12-19T18_37_27.511Z.csv)

**Versions**:
- Chart Version: v0.33.0
- Kubernetes Version (`kubectl version`): 1.28/EKS

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> In every occasion, all nodes replaced were m7i-flex

Do you know if this is just because you had `m7i-flex` instances on the cluster or were there other nodes on the cluster that did not get drifted on the upgrade?

**Comment by joshuabaird** [comment]
> > In every occasion, all nodes replaced were m7i-flex
> 
> Do you know if this is just because you had `m7i-flex` instances on the cluster or were there other nodes on the cluster that did not get drifted on the upgrade?

I don't actually know.  All nodes in both clusters that upgraded just happen to have _only_  `m7i-flex` for some reason.  What are the chances of that?

**Comment by jonathan-innis** [comment]
Huh, so it's unclear here whether this is related to `m7i-flex` or whether this is directly related to the upgrade.

**Comment by njtran** [comment]
Can you share a larger subset of the logs and the EC2NodeClass you're using?

**Comment by jonathan-innis** [comment]
+1, can we get the raw logs? Looking over the CSV that was shared, I'm just seeing a couple logs on drift and then a shutdown signal that is being sent that makes it seem like the Karpenter pods crashed on startup.

**Comment by joshuabaird** [comment]
I'm guessing there is a lot of `m7i-flex` availability right now because it's a new-ish instance type -- which is why I guess we had a bunch of them.  One of the replaced nodes is in fact a `m7i-flex` though -- so, it would seem Karpenter is still considering `m7i-flex` for this NodePool.

**Comment by joshuabaird** [comment]
> Can you share a larger subset of the logs and the EC2NodeClass you're using?

EC2NodeClass:

```
  spec:
    amiFamily: Bottlerocket
    metadataOptions:
      httpEndpoint: enabled
      httpProtocolIPv6: disabled
      httpPutResponseHopLimit: 2
      httpTokens: required
    role: Karpenter-use1-production-01-20230905200841507700000005
    securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: use1-production-01
    subnetSelectorTerms:
    - tags:
        Type: private
    tags:
      karpenter.sh/discovery: use1-production-01
  status:
    amis:
    - id: ami-0d34ea6796ecf0833
      name: bottlerocket-aws-k8s-1.28-aarch64-v1.17.0-53f322c2
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: DoesNotExist
      - key: karpenter.k8s.aws/instance-accelerator-count
        operator: DoesNotExist
    - id: ami-092cfaacb91744323
      name: bottlerocket-aws-k8s-1.28-nvidia-x86_64-v1.17.0-53f322c2
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: Exists
    - id: ami-092cfaacb91744323
      name: bottlerocket-aws-k8s-1.28-nvidia-x86_64-v1.17.0-53f322c2
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-accelerator-count
        operator: Exists
    - id: ami-08011c866ca323f43
      name: bottlerocket-aws-k8s-1.28-nvidia-aarch64-v1.17.0-53f322c2
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: Exists
    - id: ami-08011c866ca323f43
      name: bottlerocket-aws-k8s-1.28-nvidia-aarch64-v1.17.0-53f322c2
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: karpenter.k8s.aws/instance-accelerator-count
        operator: Exists
    - id: ami-0836c04ec6785db32
      name: bottlerocket-aws-k8s-1.28-x86_64-v1.17.0-53f322c2
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: DoesNotExist
      - key: karpenter.k8s.aws/instance-accelerator-count
        operator: DoesNotExist
    instanceProfile: use1-production-01_15843455441266977890
```
