### ISSUE TITLE
two GPU pods deploys a much larger node

### ISSUE THREAD

**Issue by jinzishuai** [aws/karpenter-provider-aws#5379]
### Description

** READ BEFORE CONTINUING: If your issue is not specific to AWS, please cut a ticket in [kubernetes-sigs/karpenter](https://github.com/kubernetes-sigs/karpenter/issues/new/choose).

I am trying to deploy two pods of
```yaml
            resources:
              requests:
                cpu: "2"
                memory: "13Gi"
                nvidia.com/gpu: "1" # Request one NVIDIA GPU
```

**Observed Behavior**:
When two pods are deployed together,  I ended up with a `g5.12xlarge` AWS instance which has 4 GPU. 
If I deploy one pod at a time, I ended up with two `g5.xlarge` AWS instances each with a single GPU. I think this is the preferred behavior since it cost less than half of 4-GPU situation.

**Expected Behavior**:

Karpenter is smart enough to deploy two GPU nodes instead of a single node with 4 GPUs.

**Reproduction Steps** (Please include YAML):

Deploy this Raycluster (but you don't have to)
```yaml
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: gpu-raycluster
  namespace: ray-gpu
spec:
  rayVersion: "2.8.1" # Ray version to use
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      port: "6379"
      dashboard-host: "0.0.0.0"
    template:
      spec:
        containers:
          - name: ray-head
            image: jinzishuai/ray-train-dreambooth:2.8.1-py310-gpu
            ports:
              - containerPort: 6379
              - containerPort: 8265 # dashboard
            resources:
              requests:
                cpu: "2"
                memory: "13Gi"
                nvidia.com/gpu: "1" # Request one NVIDIA GPU
              limits:
                cpu: "2"
                memory: "15Gi"
                nvidia.com/gpu: "1" # Limit one NVIDIA GPU
            volumeMounts:
              - name: persistent-storage
                mountPath: /data
        volumes:
          - name: persistent-storage
            persistentVolumeClaim:
              claimName: efs-claim
  workerGroupSpecs:
    - groupName: worker-group
      replicas: 0
      minReplicas: 0
      maxReplicas: 3
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: jinzishuai/ray-train-dreambooth:2.8.1-py310-gpu
              resources:
                requests:
                  cpu: "1"
                  memory: "10Gi"
                  nvidia.com/gpu: "1" # Request one NVIDIA GPU
                limits:
                  cpu: "2"
                  memory: "15Gi"
                  nvidia.com/gpu: "1" # Limit one NVIDIA GPU
              volumeMounts:
                - name: persistent-storage
                  mountPath: /data
          volumes:
            - name: persistent-storage
              persistentVolumeClaim:
                claimName: efs-claim
```

**Versions**:
- Chart Version:
```
╰─❯ helm list -n karpenter
NAME         	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                	APP VERSION
karpenter-crd	karpenter	1       	2023-12-08 14:39:45.470687 -0700 MST	deployed	karpenter-crd-v0.33.0	0.33.0     
```
- Kubernetes Version (`kubectl version`):
```
╰─❯ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.8-eks-8cb36c9

╰─❯ helm version
version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.21.4"}
```
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
