### ISSUE TITLE
Reconciler Error after upgrading to 0.32.4 from 0.31.3

### ISSUE THREAD

**Issue by pdeva** [aws/karpenter-provider-aws#5381]
### Description

** READ BEFORE CONTINUING: If your issue is not specific to AWS, please cut a ticket in [kubernetes-sigs/karpenter](https://github.com/kubernetes-sigs/karpenter/issues/new/choose).

**Observed Behavior**:
I followed the upgrade steps, and i am seeing this:
![Screenshot 2023-12-21 at 12 30 39 PM](https://github.com/aws/karpenter-provider-aws/assets/3190176/0f900b39-a551-4d35-9c1c-3afcd38cc71c)

**Expected Behavior**:
shouldnt have errors

**Reproduction Steps** (Please include YAML):

this is how my typical EC2NodeClass definition is. Note that the `instanceProfile` used here is the same one that was used in `settings.aws.defaultInstanceProfile` helm chart setting in 0.31.3. I am not sure if this is the way to do it or if i should do something different..

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: default
spec:
  amiFamily: Bottlerocket
  instanceProfile: Karpenter-k1-20230123211248751700000007
  securityGroupSelectorTerms:
    - tags:
        Name: k1-node
        karpenter.sh/discovery: k1
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "true"
  tags:
    karpenter.sh/discovery: k1
```

this is the helm chart configuration (deployed via argocd):

```
    helm:
      releaseName: karpenter
      parameters:
        - name: "logLevel"
          value: "info"
        - name: "logConfig.logLevel.controller"
          value: "info"
        - name: "controller.resources.requests.cpu"
          value: "100m"
        - name: "controller.resources.limits.cpu"
          value: "100m"
        - name: "controller.resources.requests.memory"
          value: "300Mi"
        - name: "controller.resources.limits.memory"
          value: "300Mi"
        - name: 'serviceAccount.annotations.eks\.amazonaws\.com/role-arn'
          value: "arn:aws:iam::694546277223:role/KarpenterIRSA-k1-20230123211248186100000006"
        - name: "settings.clusterName"
          value: "k1"
        - name: "settings.clusterEndpoint"
          value: "https://9AE717F0F637ACE4F8A68AB07F30A55B.sk1.us-east-1.eks.amazonaws.com"
        - name: "settings.interruptionQueueName"
          value: "Karpenter-k1"
```

**Versions**:
- Chart Version: 0.32.4
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
