### ISSUE TITLE
failed to list *v1.ConfigMap: configmaps is forbidden

### ISSUE THREAD

**Issue by noamgreen** [aws/karpenter-provider-aws#5383]
### Description

** READ BEFORE CONTINUING: If your issue is not specific to AWS, please cut a ticket in [kubernetes-sigs/karpenter](https://github.com/kubernetes-sigs/karpenter/issues/new/choose).

Upgrade from X.32 to X.33.1 i see an error i think in the role 
"failed to list *v1.ConfigMap: configmaps is forbidden"

i try to move to kube-system namespace and i start getting this error 

```
karpenter-5f56b5cbdb-kmw9n controller W1223 13:13:45.929442       1 reflector.go:535] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:karpenter:karpenter-manager" cannot list resource "configmaps" in API group "" in the namespace "karpenter"
karpenter-5f56b5cbdb-kmw9n controller E1223 13:13:45.929491       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:karpenter:karpenter-manager" cannot list resource "configmaps" in API group "" in the namespace "karpenter"

karpenter-5f56b5cbdb-kmw9n controller {"level":"INFO","time":"2023-12-23T13:11:40.929Z","logger":"controller","message":"k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1.ConfigMap: configmaps is forbidden: User \"system:serviceaccount:karpenter:karpenter-manager\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"karpenter\"","commit":"56aaec1"}
```

```yaml
        replicas: 1
        logLevel: info
        logConfig:
          enabled:
            logLevel:
              # -- Global log level, defaults to 'info'
              global: info
              # -- Controller log level, defaults to 'info'
              controller: info
              # -- Error log level, defaults to 'error'
              webhook: error
        serviceAccount:
          create: true
          name: "karpenter-manager"
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::ZZZZZZZZZZZ:role/karpenter-manager"
        controller:
          env:
            - name: AWS_REGION
              value: us-east-1
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus-operator
        settings:
          clusterEndpoint: https://.gr7.us-east-1.eks.amazonaws.com
          clusterName:eks-dev
          interruptionQueue: sqs-k'''
```

**Versions**:
- Chart Version:  0.32.3
- Kubernetes Version (`kubectl version`): v1.26.11-eks-8cb36c9

 side note ** i am not sure why you note push the helm chart version the code is in 0.33 and the chart in 0.32 

in any case i try to go back yo 0.32
