### ISSUE TITLE
Unable to launch vt1 with amd.com/ama_u30 limit on pod

### ISSUE THREAD

**Issue by dcarrion87** [aws/karpenter-provider-aws#5403]
### Description

**Observed Behavior**:

When launching pod with limit amd.com/ama_u30 = 1 and constraining to vt1.3xlarge 

> {"level":"ERROR","time":"2023-12-29T08:13:48.025Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"stream\", daemonset overhead={\"cpu\":\"150m\",\"pods\":\"3\"}, no instance type satisfied resources {\"amd.com/ama_u30\":\"1\",\"cpu\":\"150m\",\"pods\":\"4\"} and requirements karpenter.sh/nodepool In [stream], node.kubernetes.io/instance-type In [vt1.3xlarge] (no instance type has enough resources)","commit":"1072d3b","pod":"default/stream-stream1-5f4dd5745c-2gv2s"}

Removing the `amd.com/ama_u30` limit allows pod to launch but device plugin never mounts devices.

**Expected Behavior**:

Ability for Karpenter to recognise amd.com/ama_u30 for vt1 instances or just ignore it for launching purposes.

**Reproduction Steps** (Please include YAML):

Create node pool. E.g.:

```
    apiVersion: karpenter.sh/v1beta1
    kind: NodePool
    metadata:
      name: stream
    spec:
      template:
        spec:
          nodeClassRef:
            name: stream
          taints:
            - key: stream
              effect: NoSchedule
          requirements:
            - key: "node.kubernetes.io/instance-type"
              operator: In
              values: ["vt1.3xlarge"]
      limits:
        cpu: 9999
      disruption:
        consolidationPolicy: WhenEmpty
        consolidateAfter: "3600s"
```

Try assign a pod with `amd.com/ama_u3` and vt1.3xlarge requirement. E.g.:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      hostNetwork: true
      hostPID: true
      terminationGracePeriodSeconds: 0
      containers:
      - name: test
        image: ubuntu:22.04
        command: ["/bin/sh", "-c", "while true; do sleep 1; done"]
        resources:
          limits:
            amd.com/ama_u30: 1
      tolerations:
      - key: "stream"
        effect: "NoSchedule"
      nodeSelector:
        "node.kubernetes.io/instance-type": "vt1.3xlarge"
```

**Versions**:
- Chart Version: 0.32
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
