### ISSUE TITLE
Karpenter is failing to provision Windows nodes

### ISSUE THREAD

**Issue by sunwarior** [aws/karpenter-provider-aws#5404]
### Description

Hi, I am trying to provision windows nodes in EKS cluster, everything is done according to following tutorial
https://aws.amazon.com/blogs/containers/karpenter-now-supports-windows-node-groups/ with changes according to new karpenter version.

**Observed Behavior**:
Karpenter is failing to provision nodes with following ERROR

`karpenter-karpenter-67fbcf9bd9-f4lkn {"level":"DEBUG","time":"2023-12-29T10:07:07.016Z","logger":"controller.provisioner","message":"181 out of 643 instance types were excluded because they would breach limits","commit":"a70b39e","nodepool":"amd64-windows2022"}`

`{"level":"ERROR","time":"2023-12-29T10:07:07.017Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"amd64-windows2022\", daemonset overhead={\"cpu\":\"30m\",\"memory\":\"120Mi\",\"pods\":\"1\"}`

**Expected Behavior**:
Windows node provision

**Reproduction Steps** (Please include YAML):

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  targetNamespace: karpenter
  interval: 15m
  chart:
    spec:
      chart: karpenter
      version: v0.33.1
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: karpenter
      interval: 10m
  values:
    env:
      - name: DISABLE_WEBHOOK
        value: true
    replicas: 2
    nodeSelector:
      eks.amazonaws.com/nodegroup: static-managed-nodegroup
    serviceAccount:
      create: true
      name: "karpenter"
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxxxx:role/core-services-eks-karpenter
    settings:
      clusterName: "core_services_eks"
      clusterEndpoint: "https://xxxxxxxxxxxxxxxxxxxx"
      defaultInstanceProfile: "KarpenterNodeInstanceProfile-core-services-eks"
      interruptionQueueName: karpenter_interruption
    logLevel: debug
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: amd64-windows2022
spec:
  template:
    metadata:
      labels:
        runner-type: amd64-windows2022
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: kubernetes.io/os
          operator: In
          values: ["windows"]    
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["eu-central-1a", "eu-central-1b"]
      nodeClassRef:
        name: amd64-windows2022
      taints:
        - key: gitlab-runners
          effect: NoSchedule
  disruption:
    expireAfter: 24h
    consolidationPolicy: WhenEmpty
    consolidateAfter: 60s
  limits:
    cpu: 50
	

apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: amd64-windows2022
spec:
  role: KarpenterNodeRole-core-services-eks
  amiFamily: Windows2022
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required 
  blockDeviceMappings:
    - deviceName: /dev/sda1
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        iops: 3000
        encrypted: false
        deleteOnTermination: true
        throughput: 125
  subnetSelectorTerms:
    - id: "subnet-xxxxxxxxxxxxxxxx"
  securityGroupSelectorTerms:
    - id: "sg-xxxxxxxxxxxxxxxx"

  tags:
    Name: amd64-windows2022
	

apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-server-iis-simple-2022
  namespace: windows-apps
spec:
  selector:
    matchLabels:
      app: windows-server-iis-simple-2022
  replicas: 1
  template:
    metadata:
      labels:
        app: windows-server-iis-simple-2022
    spec:
      containers:
        - name: windows-server-iis-simple-2022
          image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2022
          imagePullPolicy: IfNotPresent
          command:
            - powershell.exe
            - -command
            - while(1){sleep 2; ping -t localhost;}
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      nodeSelector:
        kubernetes.io/os: windows
```

**Versions**:
- Chart Version: v0.33.1
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
