### ISSUE TITLE
Nodes are created but never join to the cluster

### ISSUE THREAD

**Issue by dbaltor** [aws/karpenter-provider-aws#5405]
### Description

**Observed Behavior**:
Karpenter successfully creates a new VM but it doesn't join to the cluster. After 15 minutes, the VM is destroyed and a new one is provisioned and the cycle repeats.

The EC2 instance state is `Running` and their Status check is `2/2 checks passed`.

Interestingly, this is also happening with Karpenter v0.30.0 (using the previous API) and it was working before. The only difference I can think of is that I've upgraded EKS from 1.27 to 1.28.

**Expected Behavior**:
The newly-provisioned VM to become a cluster node

**Reproduction Steps** (Please include YAML):

Here's my Karpenter configuration (in Terraform):
```
resource "kubectl_manifest" "karpenter_node_pool" {
  yaml_body = <<-YAML
# This example NodePool will provision general purpose instances
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: general-purpose
  annotations:
    kubernetes.io/description: "General purpose NodePool for generic workloads"
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]          
      nodeClassRef:
        name: default
YAML
}

resource "kubectl_manifest" "karpenter_ec2_node_class" {
  yaml_body = <<-YAML
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  annotations:
    kubernetes.io/description: "General purpose EC2NodeClass for running Amazon Linux 2 nodes"
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: ${module.karpenter.role_name}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${module.eks.cluster_name}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${module.eks.cluster_name}"
  tags:
    karpenter.sh/discovery: ${module.eks.cluster_name}  
YAML

}
```
I have tried to pin an Ubuntu AMI as suggested in [here](https://github.com/aws/karpenter-provider-aws/issues/5176#issuecomment-1836767941) without success.
```
  amiFamily: Ubuntu
  amiSelectorTerms:
    - name: ubuntu-eks/k8s_1.28/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20231128 
```

**Versions**:
- Chart Version: 0.33.1
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4-eks-8cb36c9
```

Might be related to https://github.com/aws/karpenter-provider-aws/issues/5176

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
