### ISSUE TITLE
Issue Upgrading Karpenter from 0.32 to 0.33 with EKS 1.27 and Helm

### ISSUE THREAD

**Issue by daasol** [aws/karpenter-provider-aws#5410]
### Description

Hello, I am currently using Karpenter version 0.27 and looking to upgrade to **version 0.33** since I am using EKS version 1.27. 
However, due to significant changes in the CRDs from Karpenter 0.32 onwards, I opted to initially upgrade to version 0.32 to ensure rollback capability.

The upgrade to 0.32 went smoothly without major issues. **But, when attempting to upgrade from version 0.32 to 0.33 using Helm charts, I encountered the following error logs in the controller.**

**If I roll back to version 0.32, it works normally, as the upgrade to version 0.33 does not function correctly.**

**Observed Behavior**:
- Karpenter controller is in a running state, but it fails the probe's health check. Eventually, it ends up in a CrashLoopBackOff state.
- It is attempting to perform operations with the *v1alpha5.Machine API related to Machine. It's puzzling why it's trying to call Machine despite all the webhooks related to Machine having been removed.

controller log 

```
{"level":"ERROR","time":"2023-12-29T06:56:29.908Z","logger":"controller","message":"k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1alpha5.Machine: failed to list *v1alpha5.Machine: machines.karpenter.sh is forbidden: User \"system:serviceaccount:blah-karpenter-namespace:karpenter\" cannot list resource \"machines\" in API group \"karpenter.sh\" at the cluster scope\n","commit":"3a61217"}
{"level":"DEBUG","time":"2023-12-29T06:56:48.473Z","logger":"controller.controller-runtime.healthz","message":"healthz check failed","commit":"3a61217","checker":"manager","error":"failed to sync caches"}
{"level":"INFO","time":"2023-12-29T06:57:25.873Z","logger":"controller","message":"k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1alpha5.Machine: machines.karpenter.sh is forbidden: User \"system:serviceaccount:blah-karpenter-namespace:karpenter\" cannot list resource \"machines\" in API group \"karpenter.sh\" at the cluster scope\n","commit":"3a61217"}
{"level":"ERROR","time":"2023-12-29T06:57:25.873Z","logger":"controller","message":"k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1alpha5.Machine: failed to list *v1alpha5.Machine: machines.karpenter.sh is forbidden: User \"system:serviceaccount:blah-karpenter-namespace:karpenter\" cannot list resource \"machines\" in API group \"karpenter.sh\" at the cluster scope\n","commit":"3a61217"}
```

**Expected Behavior**:
I have ensured that my setup is 100% identical to the Karpenter 0.33 chart available on GitHub, which leads me to believe it should upgrade smoothly. However, I am encountering several errors, including probe failures and issues with the Machine API.

**Reproduction Steps** (Please include YAML):
Apart from this, it is identical to the Karpenter 0.33 version chart provided on GitHub.
The only difference from the GitHub Karpenter 0.33 chart in my setup is that I am using IRSA (IAM Roles for Service Accounts). It works well with IRSA.

```
 $ k describe sa karpenter  -n blah-karpenter-namespace
Name:                karpenter
Namespace:           blah-karpenter-namespace
Labels:              app=karpenter
                     app.kubernetes.io/instance=karpenter
                     app.kubernetes.io/managed-by=Helm
                     app.kubernetes.io/name=karpenter
                     app.kubernetes.io/version=0.32.0
                     argocd.argoproj.io/instance=blah-blah-cluster-name
                     helm.sh/chart=karpenter-0.32.0
                     infra-service=true
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::blah-blah-account:role/blah-blah-karpenter-role-name
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>
```

For the upgrade process, 
I used Argocd and Helm charts. We have an App Of Apps structure in Argocd. 
I modified the existing Karpenter chart(ver. 0.32) by removing the CRDs that were no longer in use and then deployed it. 
However, I realized that Helm does not manage the lifecycle of CRDs. I created a separate chart for the updated Karpenter CRDs and installed it.
+ I applied the CRDs using kubectl apply. ([like this](https://karpenter.sh/preview/upgrading/upgrade-guide/#crd-upgrades))
+ Also I created and deployed a separate CRD chart. ([like this](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts))

**Versions**:
- Chart Version: 0.33.0
- Kubernetes Version (`kubectl version`):  v1.27.8-eks-8cb36c9

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by daasol** [comment]
Hi, After you pointed out that the controller logs matched the ECR version of 0.32, I revisited the Helm chart's tag. 

However, despite it being [version 0.33.1](https://github.com/aws/karpenter-provider-aws/releases/tag/v0.33.1), the `controller.image.tag` was still pointing to v0.32.3. 
Even in the chart downloaded from this release version, it was still referencing version 0.32. Shouldn't this part be modified to point to version 0.33.x? 
Please confirm.
```
controller:
  image:
    # -- Repository path to the controller image.
    repository: public.ecr.aws/karpenter/controller
    # -- Tag of the controller image.
    **tag: v0.32.3**
    # -- SHA256 digest of the controller image.
    digest: sha256:afa0d0fd5ac375859dc3d239ec992f197cdf01f6c8e3413e3845a43c2434621e
  # -- Additional environment variables for the controller pod.
  env: []
  # - name: AWS_REGION
  #   value: eu-west-1
  envFrom: []
  # -- Resources for the controller pod.
  resources: {}
```
Thank you!! I was able to resolve the issue.

**Comment by jonathan-innis** [comment]
> Even in the chart downloaded from this release version, it was still referencing version 0.32. Shouldn't this part be modified to point to version 0.33.x

I just pulled the latest artifact from the artifact store with `helm pull oci://public.ecr.aws/karpenter/karpenter --version v0.33.1 --untar` and see that `controller.image.tag` is correctly set to `v0.33.1`. 

```yaml
controller:
  image:
    # -- Repository path to the controller image.
    repository: public.ecr.aws/karpenter/controller
    # -- Tag of the controller image.
    tag: v0.33.1
    # -- SHA256 digest of the controller image.
    digest: sha256:7f484951baf70d1574d6408be3947a3ca5f54463c2d1f29993b492e7e916ef11
```

Is it possible that you are pulling your chart from another location other than the OCI artifact store?
