### ISSUE TITLE
karpenter duplicate create new machine for a pending pod

### ISSUE THREAD

**Issue by wy0824** [aws/karpenter-provider-aws#5429]
### Description

**Observed Behavior**:
We use the v0.29.2 karpenter in our cluster, sometimes we find karpenter creates a new machine to solve the pending pod, but the node creation is slow, so when in the next reconcile, karpenter finds the pod is still pending, and creates a new machine again, it will make useless cost. We config the ttlSecondsAfterEmpty as 300 seconds, the empty node will recycle, but it will make one hour's billing.
**Expected Behavior**:
only one node should be create for a pending pod.
**Reproduction Steps** (Please include YAML):
test deployment yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-pod-test-m5a
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy-pod-test-m5a
      topoName: dummy-pod-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dummy-pod-test-m5a
        topoName: dummy-pod-test
    spec:
      containers:
        - name: dummy
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 10m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: karpenter.sh/provisioner-name
                    operator: In
                    values:
                      - test
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5a.xlarge
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: topoName
                    operator: In
                    values:
                      - dummy-pod-test
              topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
      priorityClassName: low-priority
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              topoName: dummy-pod-test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```
provisioner yaml:
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  labels:
    k8slens-edit-resource-version: v1alpha5
  name: test
spec:
  labels:
    common-k8s: 'true'
  limits:
    resources:
      cpu: '64'
      memory: 256Gi
  providerRef:
    name: test
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
        - m5a
        - m6a
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values:
        - large
        - xlarge
        - 2xlarge
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
  ttlSecondsAfterEmpty: 300
```
log detail:
```bash
$ kubectl logs -n karpenter karpenter-68b84676b6-rh5dk -c controller -f | grep 'created machine'
```
`2024-01-05T07:34:52.463Z        INFO    controller.provisioner  created machine {"commit": "34d50bf-dirty", "provisioner": "test", "requests": {"cpu":"566m","memory":"692Mi","pods":"9"}, "instance-types": "m5a.xlarge"}
2024-01-05T07:37:12.485Z        INFO    controller.provisioner  created machine {"commit": "34d50bf-dirty", "provisioner": "test", "requests": {"cpu":"566m","memory":"692Mi","pods":"9"}, "instance-types": "m5a.xlarge"}`
```shell
$ kubectl describe pod dummy-pod-nathan-test-m5a-5cb66c898c-7nt66 -n default
```
``` 
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  3m35s                default-scheduler  0/23 nodes are available: ***
  Normal   Nominated         84s (x2 over 3m34s)  karpenter          Pod should schedule on: machine/nathan-test-srqnn
  Normal   Scheduled         10s                  default-scheduler  Successfully assigned default/dummy-pod-nathan-test-m5a-5cb66c898c-7nt66 to ip-10-52-114-177.us-west-2.compute.internal
  Normal   Pulling           8s                   kubelet            Pulling image "public.ecr.aws/eks-distro/kubernetes/pause:3.7"
  Normal   Pulled            7s                   kubelet            Successfully pulled image "public.ecr.aws/eks-distro/kubernetes/pause:3.7" in 751.267684ms (751.277324ms including waiting)
  Normal   Created           7s                   kubelet            Created container dummy
  Normal   Started           6s                   kubelet            Started container dummy
```

**Versions**:
- Chart Version:v0.29.2
- Kubernetes Version (`kubectl version`):1.25

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
