### ISSUE TITLE
Karpenter v0.33.1 does not delete node

### ISSUE THREAD

**Issue by MartinsVi** [aws/karpenter-provider-aws#5469]
### Description

**Observed Behavior**:
Karpenter is not deleting empty nodes with `consolidationPolicy: WhenEmpty`

**Expected Behavior**:
Nodes should be deleted when there are no workloads running.

**Reproduction Steps** (Please include YAML):
create "spot-standard" node pool and "standard" node class
```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: spot-standard
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  limits:
    cpu: "300"
    memory: 1000Gi
  template:
    metadata:
      labels:
        spot: "true"
    spec:
      nodeClassRef:
        name: standard
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - c
            - m
            - r
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - "2"
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
      taints: []
  weight: 100
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: standard
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
  detailedMonitoring: false
  role: eks-poc-karpenter-nodes
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: 'staging-hq-staging-poc'
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: 'staging-hq-staging-poc'
  tags:
    Name: eks-staging-hq-staging-poc
```

Deploy sample application
```bash
cat <<EOF | kubectl create -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
EOF
```
Karpenter spins-up new node and the deployment succeeds.
```
{"level":"DEBUG","time":"2024-01-14T16:11:13.674Z","logger":"controller.provisioner","message":"25 out of 749 instance types were excluded because they would breach limits","commit":"a70b39e","nodepool":"spot-standard"}
{"level":"INFO","time":"2024-01-14T16:11:13.699Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"a70b39e","pods":"default/nginx-deployment-9645f99cd-9sgjz","duration":"26.139762ms"}
{"level":"INFO","time":"2024-01-14T16:11:13.699Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"a70b39e","nodeclaims":1,"pods":1}
{"level":"INFO","time":"2024-01-14T16:11:13.721Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"a70b39e","nodepool":"spot-standard","nodeclaim":"spot-standard-h78xg","requests":{"cpu":"100m","pods":"3"},"instance-types":"c3.large, c3.xlarge, c4.large, c4.xlarge, c5.2xlarge and 95 other(s)"}
{"level":"DEBUG","time":"2024-01-14T16:11:13.892Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"a70b39e","nodeclaim":"spot-standard-h78xg","launch-template-name":"karpenter.k8s.aws/13806346250160050262","id":"lt-0d66fefde3cc3b492"}
{"level":"DEBUG","time":"2024-01-14T16:11:14.037Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"a70b39e","nodeclaim":"spot-standard-h78xg","launch-template-name":"karpenter.k8s.aws/7812652202182042337","id":"lt-0a81931eaaab5f7a7"}
{"level":"DEBUG","time":"2024-01-14T16:11:14.189Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"a70b39e","nodeclaim":"spot-standard-h78xg","launch-template-name":"karpenter.k8s.aws/911609528111237033","id":"lt-085aa0c3afab6dbc2"}
{"level":"DEBUG","time":"2024-01-14T16:11:14.325Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"a70b39e","nodeclaim":"spot-standard-h78xg","launch-template-name":"karpenter.k8s.aws/13529838340447534344","id":"lt-0101c99861e9d200a"}
{"level":"DEBUG","time":"2024-01-14T16:11:14.459Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"a70b39e","nodeclaim":"spot-standard-h78xg","launch-template-name":"karpenter.k8s.aws/6520128743766042746","id":"lt-02b75c12a2c0175ce"}
{"level":"INFO","time":"2024-01-14T16:11:16.683Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"a70b39e","nodeclaim":"spot-standard-h78xg","provider-id":"aws:///eu-west-1c/i-07a99efc918a0df2a","instance-type":"c7a.medium","zone":"eu-west-1c","capacity-type":"spot","allocatable":{"cpu":"940m","ephemeral-storage":"493706490675","memory":"1451Mi","pods":"8"}}
{"level":"DEBUG","time":"2024-01-14T16:11:47.318Z","logger":"controller.nodeclaim.lifecycle","message":"registered nodeclaim","commit":"a70b39e","nodeclaim":"spot-standard-h78xg","provider-id":"aws:///eu-west-1c/i-07a99efc918a0df2a","node":"ip-10-27-2-172.eu-west-1.compute.internal"}
{"level":"INFO","time":"2024-01-14T16:12:00.064Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"a70b39e","nodeclaim":"spot-standard-h78xg","provider-id":"aws:///eu-west-1c/i-07a99efc918a0df2a","node":"ip-10-27-2-172.eu-west-1.compute.internal"}
```
Delete deployment `kubectl delete deployment nginx-deployment`
The only pods that remain on node belong to kube-proxy & calico-node daemonsets, but karpenter does not delete the node

Snippet of kubeclt describe node ...
```
ProviderID:                   aws:///eu-west-1c/i-07a99efc918a0df2a
Non-terminated Pods:          (3 in total)
  Namespace                   Name                             CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                             ------------  ----------  ---------------  -------------  ---
  calico-system               calico-node-4hb84                0 (0%)        0 (0%)      0 (0%)           0 (0%)         8m52s
  calico-system               calico-typha-55894f5786-hgjmp    0 (0%)        0 (0%)      0 (0%)           0 (0%)         8m51s
  kube-system                 kube-proxy-r8c99                 100m (10%)    0 (0%)      0 (0%)           0 (0%)         8m52s
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests    Limits
  --------                    --------    ------
  cpu                         100m (10%)  0 (0%)
  memory                      0 (0%)      0 (0%)
  ephemeral-storage           0 (0%)      0 (0%)
  hugepages-1Gi               0 (0%)      0 (0%)
  hugepages-2Mi               0 (0%)      0 (0%)
  attachable-volumes-aws-ebs  0           0
Events:
  Type     Reason                   Age                    From             Message
  ----     ------                   ----                   ----             -------
  Normal   Starting                 8m49s                  kube-proxy
  Normal   Starting                 8m54s                  kubelet          Starting kubelet.
  Warning  InvalidDiskCapacity      8m54s                  kubelet          invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory  8m54s (x2 over 8m54s)  kubelet          Node ip-10-27-2-172.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    8m54s (x2 over 8m54s)  kubelet          Node ip-10-27-2-172.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     8m54s (x2 over 8m54s)  kubelet          Node ip-10-27-2-172.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced  8m54s                  kubelet          Updated Node Allocatable limit across pods
  Normal   RegisteredNode           8m52s                  node-controller  Node ip-10-27-2-172.eu-west-1.compute.internal event: Registered Node ip-10-27-2-172.eu-west-1.compute.internal in Controller
  Normal   NodeReady                8m40s                  kubelet          Node ip-10-27-2-172.eu-west-1.compute.internal status is now: NodeReady
  Normal   DisruptionBlocked        8m39s                  karpenter        Cannot disrupt Node: Nominated for a pending pod
  Normal   Unconsolidatable         8m19s                  karpenter        NodePool "spot-standard" has consolidation disabled
```

Also, no errors or hints on why karpenter is not deleting the node in remaining log messages:
```
{"level":"INFO","time":"2024-01-14T16:12:00.064Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"a70b39e","nodeclaim":"spot-standard-h78xg","provider-id":"aws:///eu-west-1c/i-07a99efc918a0df2a","node":"ip-10-27-2-172.eu-west-1.compute.internal"}
{"level":"DEBUG","time":"2024-01-14T16:12:33.124Z","logger":"controller","message":"deleted launch template","commit":"a70b39e","id":"lt-0101c99861e9d200a","name":"karpenter.k8s.aws/13529838340447534344"}
{"level":"DEBUG","time":"2024-01-14T16:12:33.206Z","logger":"controller","message":"deleted launch template","commit":"a70b39e","id":"lt-02b75c12a2c0175ce","name":"karpenter.k8s.aws/6520128743766042746"}
{"level":"DEBUG","time":"2024-01-14T16:12:33.282Z","logger":"controller","message":"deleted launch template","commit":"a70b39e","id":"lt-0d66fefde3cc3b492","name":"karpenter.k8s.aws/13806346250160050262"}
{"level":"DEBUG","time":"2024-01-14T16:12:33.369Z","logger":"controller","message":"deleted launch template","commit":"a70b39e","id":"lt-0a81931eaaab5f7a7","name":"karpenter.k8s.aws/7812652202182042337"}
{"level":"DEBUG","time":"2024-01-14T16:12:33.474Z","logger":"controller","message":"deleted launch template","commit":"a70b39e","id":"lt-085aa0c3afab6dbc2","name":"karpenter.k8s.aws/911609528111237033"}
{"level":"DEBUG","time":"2024-01-14T16:14:31.646Z","logger":"controller.disruption","message":"discovered instance types","commit":"a70b39e","count":749}
{"level":"DEBUG","time":"2024-01-14T16:14:32.009Z","logger":"controller.disruption","message":"discovered subnets","commit":"a70b39e","subnets":["subnet-059bb0dd130791324 (eu-west-1a)","subnet-07c67435a4b50667a (eu-west-1a)","subnet-06ad3adcd3e0ee9aa (eu-west-1c)","subnet-0eb462e8340c222e3 (eu-west-1b)","subnet-0bffc06ae2b7dba51 (eu-west-1c)","subnet-01e9603adfe2e54b9 (eu-west-1b)"]}
{"level":"DEBUG","time":"2024-01-14T16:19:34.015Z","logger":"controller.disruption","message":"discovered instance types","commit":"a70b39e","count":749}
{"level":"DEBUG","time":"2024-01-14T16:24:36.139Z","logger":"controller.disruption","message":"discovered instance types","commit":"a70b39e","count":749}
```

**Versions**:
- Chart Version: 0.33.1
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.24.12
Kustomize Version: v4.5.4
Server Version: v1.24.17-eks-8cb36c9
```
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
