### ISSUE TITLE
EC2NodeClass can't be validated without `role`

### ISSUE THREAD

**Issue by tskinner-oppfi** [aws/karpenter-provider-aws#5477]
### Description

**Observed Behavior**:

CI tools (`kubeconform`) that validate CRDs fail to validate EC2NodeClass with an `instanceProfile` value and no `role`.

Because of the [kubebuild annotations](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/apis/v1beta1/ec2nodeclass.go#L64) indicating that it can't be an empty string and that it is a string (not a pointer to string), as far as the CRD goes, role must always have a value. 

This doesn't affect Karpenter functionality as the [validation logic](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/apis/v1beta1/ec2nodeclass_validation.go#L70-L75) isn't really tied to the CRD definition.

Is there anyway to fix this? The kubebuild annotations don't seem to support this kind of behavior (one of multiple fields must not be empty) with the structure of the current CRD.

The output of the reproduction steps is 

```
k8s/infrastructure-custom/base/karpenter/node-class.yaml - EC2NodeClass default is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec' does not validate with https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/karpenter.k8s.aws/ec2nodeclass_v1beta1.json#/properties/spec/required: missing properties: 'role'
```

**Expected Behavior**:

No validation errors (see reproduction steps)

**Reproduction Steps** (Please include YAML):

```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - id: subnet-123lkj
  securityGroupSelectorTerms:
    - id: sg-lkj3lkj
  instanceProfile: "instance-profile-name"
```

```
kubeconform -strict -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json <above yaml filename>
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
