### ISSUE TITLE
Support placement group feature.

### ISSUE THREAD

**Issue by gaussye** [aws/karpenter-provider-aws#5479]
### Description

**What problem are you trying to solve?**
If I created a placement group, can karpenter attach the placment group to it? So far i can not find any configurations for that.
**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by baznikin** [comment]
Worked around by
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  userData: |
      #!/bin/bash
      echo "$(jq .runtimeRequestTimeout=\"7m\" /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
```
