### ISSUE TITLE
Karpenter killing new nodes before pod can be deployed, causing infinite loop of node creation/destruction

### ISSUE THREAD

**Issue by ryanhockstad** [aws/karpenter-provider-aws#5497]
### Description

**Observed Behavior**:
I have configured Terraform to deploy an AWS EKS cluster, and I'm trying to move some default applications to Karpenter provisioned nodes.  All of this was working when I was deploying everything on an AWS node group that I manage, but after moving to Karpenter, my cluster gets stuck in an endless loop of spinning up and destroying nodes.

To use Karpenter, I have one node group that I manage, where I install Karpenter, Cilium, and a few other apps. Then I install the applications that are configured to run on Karpenter managed nodes, and the first few applications spin up successfully.  One of these apps is aws-ebs-csi-driver, which allows me to use EBS volumes in StatefulSets. 

The problem begins when I install my first application that is deployed as a StatefulSet. Up until this point, two Karpenter nodes automatically spin up with no problems, but this application requires 3 nodes, and they use the same ports on the hostNetwork, which requires a new Karpenter node. I can see this node spin up, and the node is tainted by the Cilium Operator until a cilium agent from a daemonset is running.  But I expect the pod should eventually be deployed to this node. Instead, Karpenter destroys the node before it is ready and retries forever.

Here are some event logs from the pod being destroyed:
```
  Warning  FailedScheduling        30m                 default-scheduler        running PreBind plugin "VolumeBinding": binding volumes: failed to get node "ip-10-155-5-42.ec2.internal": node "ip-10-155-5-42.ec2.internal" not found
  Normal   Nominated               30m                 karpenter                Pod should schedule on: nodeclaim/karp-node-pool-zjm4p
  Normal   Nominated               28m                 karpenter                Pod should schedule on: nodeclaim/karp-node-pool-5r887, node/ip-10-155-5-123.ec2.internal
  Normal   Nominated               26m                 karpenter                Pod should schedule on: nodeclaim/karp-node-pool-nqq26
  Warning  FailedScheduling        25m (x12 over 35m)  default-scheduler        0/4 nodes are available: 1 node(s) had untolerated taint {eks: control-plane}, 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }, 2 node(s) didn't have free ports for the requested pod ports. preemption: 0/4 nodes are available: 2 No preemption victims found for incoming pod, 2 Preemption is not helpful for scheduling..
  Normal   Nominated               23m                 karpenter                Pod should schedule on: nodeclaim/karp-node-pool-fjdg2
  Normal   Nominated               21m                 karpenter                Pod should schedule on: nodeclaim/karp-node-pool-xtlsb
  Normal   Nominated               19m                 karpenter                Pod should schedule on: nodeclaim/karp-node-pool-jrrqm
  Warning  FailedScheduling        16m (x21 over 29m)  default-scheduler        (combined from similar events): running PreBind plugin "VolumeBinding": binding volumes: failed to get node "ip-10-155-6-221.ec2.internal": node "ip-10-155-6-221.ec2.internal" not found
```

Karpenter logs repeat the following error:
```
{"level":"ERROR","time":"2024-01-20T00:09:30.944Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"karp-node-pool\", daemonset overhead={\"cpu\":\"550m\",\"memory\":\"768Mi\",\"pods\":\"3\"}, key kubernetes.io/hostname, kubernetes.io/hostname DoesNotExist not in kubernetes.io/hostname In [hostname-placeholder-0111]; incompatible with nodepool \"test-node-pool\", daemonset overhead={\"cpu\":\"550m\",\"memory\":\"768Mi\",\"pods\":\"3\"}, did not tolerate purpose=karpenter-test:NoSchedule","commit":"2dd7fdc","pod":"cilium/hubble-relay-5856fb7dc5-vswgg"}
```

This pod should be deployed in the `karp-node-pool` nodePool. I believe that Karpenter is preemptively destroying the nodeClaims that the pod should be deployed on before the node is ready.  If I kill the Karpenter deployment, what usually happens is the last 2 karpenter nodes that were spun up (about 1 minute apart from each other) join my cluster, and my Pod finally gets deployed. I can then resume Karpenter and everything works as expected.

**Expected Behavior**:
I expect the third pod from the statefulset should cause Karpenter to spin up a new node, and then all of the pods will be healthy.

**Reproduction Steps** (Please include YAML):
NodePool: 
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: karp-node-pool
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  template:
    metadata:
      labels:
        nodeGroupManagedBy: karpenter
    spec:
      nodeClassRef:
        name: karp-node-class
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
      - key: karpenter.k8s.aws/instance-cpu
        operator: Gt
        values:
        - "2"
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      taints:
      - effect: NoSchedule
        key: dedicated
        value: karp
```

EC2NodeClass:
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  annotations:
    kubernetes.io/description: "karp node class"
  finalizers:
  - karpenter.k8s.aws/termination
  name: karp-node-class
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - id: <ami-id>
  detailedMonitoring: true
  instanceProfile: <instance profile>
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  securityGroupSelectorTerms:
  - id: <sg-id>
  subnetSelectorTerms:
  - id: <subnet-id>
  tags:
    OwnerContact: me
```

The StatefulSet pods are configured with a nodeSelector that selects Karpenter nodes from the `karp-node-pool`, and they tolerate the 'dedicated karp' taint. I know this because everything finally spins up once I kill Karpenter to stop it from removing a node too early.  

**Versions**:
- Chart Version: v0.33.0
- Kubernetes Version (`kubectl version`): v1.27.9-eks-5e0fdde

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
