### ISSUE TITLE
Scheduling 2000 Pods takes more than an hour

### ISSUE THREAD

**Issue by gmdfalk** [aws/karpenter-provider-aws#5505]
### Description

**Observed Behavior**:
Hi folks,

we're having an issue where Karpenter is sometimes unable to schedule Pods for an hour or longer, causing deficits and user facing errors.

This only happens when a large amount of Pods have to be rescheduled e.g. 2000+ during a spot interruption of 20+ nodes.

This seems to be a regression in Karpenter v0.32.3 since we don't see this problem with v0.30.0 that we've now rolled back to. It also doesn't seem to be a problem in v0.31.3 but for that version we only have metrics/data for 5 days, so it's not 100% clear that version is safe.

Example log line:
```
{"level":"INFO","time":"2024-01-18T19:13:23.417Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"56aaec1","pods":"foo, bar, baz and 2086 other(s)","duration":"1h2m30.037086807s"}
```

The metric `karpenter_provisioner_scheduling_simulation_duration_seconds_bucket` shows many simulation loops slower than 600 seconds when spot interruptions occur.

This leads us to believe that there might be a performance problem running the scheduling simulation for thousands of Pods.

Additional context:
* We have one provisioner per AZ and usually 2 AZs
* Our pods usually have one nodeSelector,  two preferred topology spread constraints (one for host skew, one for zone skew)
* This is happening on a cluster with ~50k pods

**Expected Behavior**:
Making scheduling decisions for 2k pods should take a few minutes at most instead of 1+ hours.
As a side note, it would be great if the metric `karpenter_provisioner_scheduling_simulation_duration_seconds_{bucket,sum,count}` was documented because it's useful for alerting. And buckets larger than 10 minutes might also be useful.

**Reproduction Steps** (Please include YAML):
This happens for us during spot interruptions of 20+ large nodes in a large production environment which may be difficult to simulate/replicate. But maybe quickly (re-)scheduling 2000+ pods could induce this problem?

Example pod:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    pool: default
    instance: main
  name: foo
  namespace: bar
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 1800
        image: nginx
  nodeSelector:
    yelp.com/pool: default
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        instance: main
    maxSkew: 15
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
  - labelSelector:
      matchLabels:
        instance: main
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
```

Example provisioner:
```
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-uswest2a
spec:
  providerRef:
    name: default-uswest2a

  startupTaints:
    - key: key
      effect: NoSchedule

  labels:
    pool: default

  requirements:
    - key: "pool"
      operator: In
      values: ["default"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Gt
      values: ["31"]
    - key: node.kubernetes.io/instance-type
      operator: NotIn
      values: ["c6a.32xlarge"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Lt
      values: ["192"]
    - key: "karpenter.k8s.aws/instance-family"
      operator: In
      values:
        - "m5"
        - "m5d"
        - "m5dn"
        - "m5n"
        - "m5zn"
        - "m6a"
        - "m6i"
        - "m6id"
        - "m6idn"
        - "m6in"
        - "m7a"
        - "m7i"
        - "r5"
        - "r5b"
        - "r5dn"
        - "r5n"
        - "r6a"
        - "r6i"
        - "r6id"
        - "r6idn"
        - "r6in"
        - "r7a"
        - "r7i"
        - "i4i"  # Equivalent processors to r6i.
        - "c5"
        - "c5d"
        - "c5n"
        - "c6a"
        - "c6i"
        - "c6id"
        - "c6in"
        - "c7a"
        - "c7i"
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-west-2a"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]

  limits:
    resources:
      cpu: "20000"

  consolidation:
    enabled: true

  ttlSecondsUntilExpired: 86400
```

**Versions**:
- Chart Version: v0.32.3
- Kubernetes Version (`kubectl version`): 1.23

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> This seems to be a regression in Karpenter v0.32.3 since we don't see this problem with v0.30.0 that we've now rolled back to.

To be clear, you see instances of you trying to schedule 2000 pods on v0.30.0 in short amounts of time as well?

**Comment by jonathan-innis** [comment]
I didn't see a mention of the number of nodes that you have on your cluster. How big is this cluster in terms of nodes?

**Comment by gmdfalk** [comment]
> I didn't see a mention of the number of nodes that you have on your cluster. How big is this cluster in terms of nodes?

I think peak for this cluster is 50k pods across 3k nodes.
I also just noticed that I didn't post the log dump of the scheduler, I'll add that bit tomorrow.
Is there anything else I can collect while I'm at it?

Thanks!

**Comment by jonathan-innis** [comment]
> you can see that average karpenter scheduling simulation duration seconds was pretty flat and never exceeded 450 seconds before introduction of v0.32 on January 15th

I will note just from glancing at the chart, that the scheduling simulation that seems to have taken the longest also seems to be the biggest set of pods that scheduled at one time across the timeframe that you shared.

> Is there anything else I can collect while I'm at it

 I think at this point the log dump should be sufficient to at least know how quickly Karpenter was moving as it was trying to schedule pods here.

**Comment by ilkinmammadzada** [comment]
I wanted to share some details about the issue. I spotted that the issue mostly happens during one of our service (which has a few deployments and thousand(ish) pods) deployment. And those pods need a few minutes to be healthy. 

I haven't checked the code logic fully yet, But Is there any logic like "waiting for deployment completion" inside simulation (`karpenter_provisioner_scheduling_simulation_duration_seconds`) and scheduling (`karpenter_provisioner_scheduling_duration_seconds`) ? 

Just in case, our deployment strategy: 
```
strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 19%
    type: RollingUpdate
```
