### ISSUE TITLE
Karpenter not recognizing ready Bottlerocket nodes with bootstrap containers

### ISSUE THREAD

**Issue by blame19** [aws/karpenter-provider-aws#5506]
### Description

Bottlerocket allows users to define [bootstrap-containers](https://bottlerocket.dev/en/os/1.15.x/concepts/bootstrap-containers/) through userData. This is useful for a variety of reason.

**Observed Behavior**:
The AWSNodeTemplate passes validation:
```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: gpu
spec:
  amiFamily: Bottlerocket
  ...
  userData: "[settings.bootstrap-containers.mybootstrap] \n  source = \"oscarhealth/bottlerocket-bootstrap-public\"\n
    \ mode = \"always\" \n  essential = true"
```
New nodes are launched as needed:
```
2024-01-22T17:07:40.518Z	INFO	controller.machine.lifecycle	launched machine	{"commit": "322822a", "machine": "gpu-lt6ts", "provisioner": "gpu", "provider-id": "aws:///eu-central-1a/i-08a00fdfe4d51cee1", "instance-type": "g4dn.xlarge", "...
2024-01-22T17:07:40.518Z	INFO	controller.machine.lifecycle	launched machine	{"commit": "322822a", "machine": "gpu-l6k7n", "provisioner": "gpu", "provider-id": "aws:///eu-central-1a/i-0d84aeca2be1fe47b", "instance-type": "g4dn.xlarge", ...
```
The machines appear as Running in AWS:
![image](https://github.com/aws/karpenter-provider-aws/assets/11650257/57519e1e-e048-4174-a56f-98188fae4b7b)

However, said machines never join the cluster. The only thing Karpenter and K8S can see are the old nodes that have been cordoned for the exercise. As a result, the pods that had triggered Karpenter's node update stay in pending. 
```
k get no
NAME                                            STATUS                     ROLES    AGE     VERSION
ip-10-19-20-44.eu-central-1.compute.internal    Ready,SchedulingDisabled   <none>   3d19h   v1.27.8-eks-75169ff
ip-10-19-21-10.eu-central-1.compute.internal    Ready,SchedulingDisabled   <none>   3d6h    v1.27.8-eks-75169ff

```

**Expected Behavior**:
The bottlerocket machines should be joining the cluster.

**Reproduction Steps** (Please include YAML):

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: gpu
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      volumeSize: 4Gi
      volumeType: gp2
  userData: "[settings.bootstrap-containers.mybootstrap] \n  source = \"busybox:latest\"\n
    \ mode = \"always\" \n  essential = false"
```
Note: according to Bottlerocket's docs, if the container fails and `essential = true`, node boot stops. I tested this both with true and false with no difference.

**Versions**:
- Chart Version: 1.13.1
- Kubernetes Version (`kubectl version`): v1.27.8-eks-8cb36c9

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
