### ISSUE TITLE
Security groups are not associated with nodes network interfaces as per spec securityGroupSelector as well as issue with subnet selector

### ISSUE THREAD

**Issue by mangeishp** [aws/karpenter-provider-aws#5514]
### Description

**Observed Behavior**:
I have added two security groups IDs in the node template `spec securityGroupSelector` however the only primary network get associated with both security groups and secondary network interface get only one security group association.

**Expected Behavior**:
I am expecting that all network interfaces on Node should get associated with security group ids as specified in spec securityGroupSelector  
**Reproduction Steps** (Please include YAML):
```

resource "kubectl_manifest" "karpenter_node_template" {
  yaml_body = <<-YAML
    apiVersion: karpenter.k8s.aws/v1alpha1
    kind: AWSNodeTemplate
    metadata:
      name: default
    spec:
      blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          encrypted: true
          volumeSize: 400Gi
          volumeType: gp3
      subnetSelector:
        karpenter.sh/discovery: ${module.eks.cluster_name}
      securityGroupSelector:
        aws-ids: "${module.eks.node_security_group_id},${module.eks.cluster_primary_security_group_id}"
      instanceProfile: ${module.eks_blueprints_addons.karpenter.node_instance_profile_name}
      tags:
        karpenter.sh/discovery: ${module.eks.cluster_name}
  YAML
}

```

**Versions**: 1.29.0
- Chart Version: v0.29.2
- Kubernetes Version (`kubectl version`): 1.24 (1.29)

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
