### ISSUE TITLE
Consolidation of Spot nodes WhenUnderutilized doesn't appear to work properly

### ISSUE THREAD

**Issue by theothermike** [aws/karpenter-provider-aws#5529]
### Description

This might be considered a question too, maybe I'm not understanding the consolidation logic properly. 

**Observed Behavior**:
Very simple setup: 

3 helm charts, two are just single containers, the third starts a redis master/replica service as well, and has a housekeeping cronjob that runs daily.    No spreading affinities defined

I've created a single general purpose NodePool (with spot, on-demand enabled), and ensured the charts all use nodeselector and tolerations to run on the nodepool (including various system daemonsets of course).   I set the resource requests very low (25m, 128/256Mi) for all containers (including redis stuff) so that they might all fit on a single node using consolidationPolicy `WhenUnderutilized`

The helm charts are deployed by `argo-cd` (as 3 Applications) and I've tried freshly adding them to an empty cluster, so they get created and startup at the same time, with the first 2 simple helm charts pretty much starting right away, and the second one taking maybe 30s to come up because of the redis stuff.

Karpenter creates 2 nodeclaims for: `m5a.large` and `m6i.large` (each 2cpu/8gb).   They are both spot nodes currently

Inspecting `kubectl events` shows "Can't replace a spot node with a spot node" reported for the two nodes

Here's `kubectl describe `node` for the two nodes

```
Capacity:
  cpu:                2
  ephemeral-storage:  52416492Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             7982016Ki
  pods:               29
Allocatable:
  cpu:                1930m
  ephemeral-storage:  47233297124
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             7291840Ki
  pods:               29
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests          Limits
  --------           --------          ------
  cpu                556m (28%)        750m (38%)
  memory             1547210614 (20%)  2338Mi (32%)
  ephemeral-storage  0 (0%)            0 (0%)
  hugepages-1Gi      0 (0%)            0 (0%)
  hugepages-2Mi      0 (0%)            0 (0%)
```

and

```
Capacity:
  cpu:                2
  ephemeral-storage:  52416492Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             7869388Ki
  pods:               29
Allocatable:
  cpu:                1930m
  ephemeral-storage:  47233297124
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             7179212Ki
  pods:               29
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests      Limits
  --------           --------      ------
  cpu                541m (28%)    750m (38%)
  memory             1167Mi (16%)  2338Mi (33%)
  ephemeral-storage  0 (0%)        0 (0%)
  hugepages-1Gi      0 (0%)        0 (0%)
  hugepages-2Mi      0 (0%)        0 (0%)
```

`kubectl top nodes`

```
NAME                                            CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-10-70-10-255.ca-central-1.compute.internal   69m          3%     1303Mi          18% 
ip-10-70-34-10.ca-central-1.compute.internal    98m          5%     990Mi           14%       
```

**Expected Behavior**:

To consolidate the workloads onto a single node since there is plenty of space on a 2cpu/8gb node.    You can see the Requests/Limits and actual utilization shows that consolidating either on request or limit should still fit on a single node, especially if taking out the extra daemonsets used on the second node

**Reproduction Steps** (Please include YAML):

Nodepool yaml:

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: pool-name
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: pool-name
      requirements:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - ca-central-1a
        - ca-central-1b
        - ca-central-1d
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - m
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "4"
      taints:
      - effect: NoSchedule
        key: nodepool
        value: pool-name
```

**Versions**:
- Chart Version: 0.33.0
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
