### ISSUE TITLE
Karpenter created nodes for pods without a matching requirement key exists

### ISSUE THREAD

**Issue by InsomniaCoder** [aws/karpenter-provider-aws#5537]
### Description

**Observed Behavior**:

We are running Karpenter v0.33.1 alongside cluster autoscaler.

Recently we introduced a NodePool for GPU workload to our cluster with a requirement for specific keys

```
requirements:
      - key: node.x.io/gpu
        operator: Exists
```

as we understand that with this configuration, this NodePool will only create NodeClaim when there's a pod specifying `node.x.io/gpu` as part of the nodeSelector.

However, in reality, we saw that there were pods that do not have said selector triggered the nodeclaim creation.

```
{"level":"INFO","time":"2024-01-26T12:34:57.748Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"a70b39e","pods":"ns/pods-without-selector","duration":"198.30158ms"}
{"level":"INFO","time":"2024-01-26T12:34:57.748Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"a70b39e","nodeclaims":1,"pods":1}
{"level":"INFO","time":"2024-01-26T12:34:57.759Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"a70b39e","nodepool":"gpu-node-nodepool","nodeclaim":"gpu-node-nodepool-fxdxg","requests":{"cpu":"4220m","memory":"14352908289536m","pods":"17"},"instance-types":"g4dn.2xlarge, g4dn.4xlarge, g4dn.8xlarge, g5.2xlarge, g5.4xlarge and 1 other(s)"}
```

**Expected Behavior**:

Karpenter should ignore pods that do not specify the `node.x.io/gpu` as selector and let ClusterAutoscaler handles.

Maybe I misunderstood the meaning of the requirement key, please let me know If I'm wrong.

**Reproduction Steps** (Please include YAML):

This is our node pool definition

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: gpu-node-nodepool
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 250s
  template:
    metadata:
      labels:
        node.x.io/gpu: "true"
    spec:
      kubelet:
        maxPods: 110
      nodeClassRef:
        name: default
      requirements:
      - key: node.x.io/gpu
        operator: Exists
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - g
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "3"
      - key: karpenter.k8s.aws/instance-gpu-manufacturer
        operator: In
        values:
        - nvidia
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - xlarge
        - 2xlarge
        - 4xlarge
        - 8xlarge
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
```

**Versions**:
- Chart Version: v0.33.1 
- Kubernetes Version (`kubectl version`): 1.25

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
> as we understand that with this configuration, this NodePool will only create NodeClaim when there's a pod specifying node.x.io/gpu as part of the nodeSelector.

This is not correct. The pod selects the node, not the other way around. If a pod has a node selector for `node.x.io/gpu`, then the node pool must have that label, but not vise versa. I think you're looking for taints https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ to "repel" pods that don't have a matching toleration.

**Comment by InsomniaCoder** [comment]
Hi @ellistarn,

Thanks for answering, It seems I misunderstood this feature https://karpenter.sh/docs/concepts/scheduling/#exists-operator and I wonder what's the different between this and the normal template labels.

```
template:
    metadata:
      labels:
        node.x.io/gpu: "true"
```

Anyhow, taint is not an option for us as we don't want to force our users to add the tolerations.

```
 If a pod has a node selector for node.x.io/gpu, then the node pool must have that label, but not vise versa
```

Are there any ways for us to prevent Karpenter to generate nodes for pods that do not have the nodeSelector apart from taints/tolerations? because right now, it's generating nodes for pod that does not have a node selector.

Thank you.
