### ISSUE TITLE
cpuManagerPolicy doesn't support on nodepool

### ISSUE THREAD

**Issue by prashnttf** [aws/karpenter-provider-aws#5559]
### Description

**Observed Behavior**:
      kubelet:
        cpuManagerPolicy: "static"

Doesn't pop up when we apply over nodepool configuration

**Expected Behavior**:
--cpu-manager-policy=static 
**Reproduction Steps** (Please include YAML):

**Versions**: 0.33.1
- Chart Version:
- Kubernetes Version (`kubectl version`): 1.25

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> Doesn't pop up when we apply over nodepool configuration

This isn't part of the Kubelet schema today. Do you have validation running on your manifest applies? You should get a warning or rejection when you try to apply this against the apiserver.

**Comment by prashnttf** [comment]
so is there a way to apply cpumanagerpolicy ?

**Comment by jmdeal** [comment]
You can configure the field by updating the kubelet configuration file through some custom userdata. This is an example with AL2:
```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
spec:
  # ...
  userData: |
    #!/bin/bash
    echo "$(jq '.cpuManagerPolicy=static' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
```
