### ISSUE TITLE
Karpenter seems to ignore pods using volumeclaim to csi smb driver volume.

### ISSUE THREAD

**Issue by leynebe** [aws/karpenter-provider-aws#5560]
### Description

**Observed Behavior**:
Karpenter does not scale up a node for use by a pod with an smb csi driver mount. 

```
# events for the smb mount pod
default-scheduler: 0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
cluster-autoscaler: pod didn't trigger scale-up: 1 node(s) didn't match Pod's node affinity/selector
```

```
# events for any other pod
default-scheduler:   0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
karpenter: Pod should schedule on: nodeclaim/accelerated-computing-inf1-x2bns
cluster-autoscaler: pod didn't trigger scale-up: 1 node(s) didn't match Pod's node affinity/selector
default-scheduler: Successfully assigned dev-rate/karpenter-node-pools-inf1-example to ip-100-64-12-191.eu-west-1.compute.internal
kubelet: Pulling image "jady-docker.artifactrepo.jnj.com/pause:2.0"
...
```

**Expected Behavior**:
Karpenter should scale up a node for use by a pod with an smb csi driver mount. 

**Reproduction Steps** (Please include YAML):

```yaml
# 1; Pod with smb pv mount. Does NOT work. No pod events from karpenter, so ignored by karpenter for some reason.
#    No special logs from karpenter pods even though debug logs are enabled.
#    However, when another pod trigger karpenter, this pod can hijack the node since the resources.limits.aws.amazon.com/neuron prevents more than one pod per node currently.
#    This causes the original pod which triggered karpenter to trigger karpenter twice to create a node.
# csi-driver-smb source: https://github.com/kubernetes-csi/csi-driver-smb/tree/master/charts
apiVersion: v1
kind: Pod
metadata:
  name: example-vol-smb
  namespace: dev
spec:
  nodeSelector:
    some_company.com/instance_type_group: accelerated_computing
    some_company.com/instance_type_family: inf1
  imagePullSecrets:
  - name: image-pull-secret
  containers:
  - name: pod-name
    image: some_company.com/pause:2.0
    resources:
      limits:
        aws.amazon.com/neuron: 1
    volumeMounts:
    - mountPath: /mnt
      name: example-vol-smb
  volumes:
  - name: example-vol-smb
    persistentVolumeClaim:
      claimName: example-vol-smb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app.kubernetes.io/instance: dev
  name: example-vol-smb
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: smb.csi.k8s.io
    nodeStageSecretRef:
      name: cifs-secret
      namespace: dev
    volumeAttributes:
      source: //some_private_ip/share/vol
    volumeHandle: vol-fsx
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=2.1
  - sec=ntlmsspi
  - uid=1001
  - gid=1001
  - nodfs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  volumeMode: Filesystem
---
# 2; Pod without any mounts. Works.
apiVersion: v1
kind: Pod
metadata:
  name: example-bare
  namespace: dev
spec:
  nodeSelector:
    some_company.com/instance_type_group: accelerated_computing
    some_company.com/instance_type_family: inf1
  imagePullSecrets:
  - name: image-pull-secret
  containers:
  - name: pod-name
    image: some_company.com/pause:2.0
    resources:
      limits:
        aws.amazon.com/neuron: 1
---
# 3; Pod with emptydir pv mount. Works.
apiVersion: v1
kind: Pod
metadata:
  name: example-vol-emptydir
  namespace: dev
spec:
  nodeSelector:
    some_company.com/instance_type_group: accelerated_computing
    some_company.com/instance_type_family: inf1
  imagePullSecrets:
  - name: image-pull-secret
  containers:
  - name: pod-name
    image: some_company.com/pause:2.0
    resources:
      limits:
        aws.amazon.com/neuron: 1
    volumeMounts:
    - mountPath: /mnt
      name: vol
  volumes:
  - name: vol
    emptyDir: {} 
---
# 4; Pod with gp3 pv mount. Works.
apiVersion: v1
kind: Pod
metadata:
  name: example-vol-gp3
  namespace: dev
spec:
  nodeSelector:
    some_company.com/instance_type_group: accelerated_computing
    some_company.com/instance_type_family: inf1
  imagePullSecrets:
  - name: image-pull-secret
  containers:
  - name: pod-name
    image: some_company.com/pause:2.0
    resources:
      limits:
        aws.amazon.com/neuron: 1
    volumeMounts:
    - mountPath: /mnt
      name: vol
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: example-vol-gp3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-vol-gp3
  namespace: dev
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

**Versions**:
- Chart Version: karpenter-v0.33.1
- Kubernetes Version (`kubectl version`):  
```
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.11-eks-8cb36c9
WARNING: version difference between client (1.29) and server (1.26) exceeds the supported minor version skew of +/-1
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
