### ISSUE TITLE
Support Ubuntu 22.04 AMIs for EKS 1.29+

### ISSUE THREAD

**Issue by jmdeal** [aws/karpenter-provider-aws#5572]
### Description

**Update:**
Canonical has released 20.04 AMIs for Ubuntu 1.29 alongside the 22.04 AMIs. Users may continue to use the Ubuntu AMI family without pinning AMIs on 1.29 with 20.04. There is still ongoing discussion on how Karpenter should support 22.04.

**What problem are you trying to solve?**
Canonical has switched to Ubuntu 22.04 for their EKS optimized AMI for EKS 1.29+. Karpenter currently will only auto-discover 20.04 AMIs due to the new AMIs using a new SSM parameter. While it would be trivial to use the new SSM parameter for EKS 1.29+ and fallback to the 20.04 parameter for previous versions, this would force major Ubuntu version upgrades on users relying on Karpenter for AMI auto-discovery when they upgrade to EKS 1.29. 

Currently, users that rely on AMI auto-discovery with the Ubuntu AMIFamily that upgrade 1.29 will fail to create new nodes since AMIs can't be discovered. If you are one of these users and want to upgrade before Karpenter introduces a long term strategy, you can pin your current AMI using [amiSelectorTerms](https://karpenter.sh/docs/concepts/nodeclasses/#specamiselectorterms). 

Example:
```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
spec:
  amiFamily: Ubuntu
  # ...
  amiSelectorTerms:
    # The latest 20.04 amd64 and arm64 AMIs for EKS 1.28 in us-west-2 at time of writing
    - id: ami-04d00324ebf262399 
    - id: ami-03513159c48355642
```

**Open Questions**
- Are the changes between major versions minimal enough that an auto-upgrade can be considered safe? Or does a new AMIFamily and migration strategy need to be introduced?

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
