### ISSUE TITLE
Difference between oci and git repository on v0.33.2

### ISSUE THREAD

**Issue by cbid71** [aws/karpenter-provider-aws#5583]
Hello guys,

I can see that there is a difference between the git repository and the oci repository with the tag value for the controller for v0.33.2

On git : 
https://github.com/aws/karpenter-provider-aws/blob/v0.33.2/charts/karpenter/values.yaml#L95C1-L99C17

````
controller:
  image:
    # -- Repository path to the controller image.
    repository: public.ecr.aws/karpenter/controller
    # -- Tag of the controller image.
    tag: v0.32.3
````

By pulling the repository on the oci :

#> helm pull oci://public.ecr.aws/karpenter/karpenter --version v0.33.2

```
 controller:
  image:
    # -- Repository path to the controller image.
    repository: public.ecr.aws/karpenter/controller
    # -- Tag of the controller image.
    tag: v0.33.2
```

According to this post : https://github.com/aws/karpenter-provider-aws/issues/5410 it seems to be a known problem but since it has been switched as closed, is there a reason for such difference between sources ?
