### ISSUE TITLE
error after upgrading to k8s 1.29

### ISSUE THREAD

**Issue by pdeva** [aws/karpenter-provider-aws#5585]
### Description

**Observed Behavior**:
seeing these 2 errors in logs:

![Screenshot 2024-02-01 at 8 57 46 AM](https://github.com/aws/karpenter-provider-aws/assets/3190176/640f44d9-e436-4272-b4f6-a6233c113998)

![Screenshot 2024-02-01 at 8 59 57 AM](https://github.com/aws/karpenter-provider-aws/assets/3190176/96c06d63-8997-48f5-b20e-d794534fd7e9)

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):
```yaml
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: ubuntu
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  amiFamily: Ubuntu
  subnetSelector:
    karpenter.sh/discovery: "true"
  securityGroupSelector:
    karpenter.sh/discovery: k1
    Name: "k1-node"
  tags:
    karpenter.sh/discovery: k1
```

**Versions**:
- Chart Version: v0.32.4
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
