### ISSUE TITLE
Unable to schedule nodes when blockDeviceMappings is specified

### ISSUE THREAD

**Issue by rwe-dtroup** [aws/karpenter-provider-aws#5588]
### Description

I've deploying Karpenter for the first time, we are attempting to modify the blockDeviceMappings for a standard bottlerocket image. If we add the settings, even if it's just the volume sizes I get an error. If I remove the config for the blockDeviceMappings and take the defaults it all works fine and I'm able to deploy instances.

The error is: no instance type has enough resources

```
{"level":"ERROR","time":"2024-02-02T11:54:03.449Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"default\", daemonset overhead={\"cpu\":\"150m\",\"pods\":\"2\"}, no instance type satisfied resources {\"cpu\":\"150m\",\"pods\":\"3\"} and requirements karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-cpu In [16 32 4 8], karpenter.k8s.aws/instance-generation Exists >4, karpenter.k8s.aws/instance-hypervisor In [nitro], karpenter.sh/capacity-type In [on-demand spot], karpenter.sh/nodepool In [default], kubernetes.io/os In [linux], node.kubernetes.io/instance-type NotIn [c6g.16xlarge m6g.16xlarge m6gd.16xlarge r6g.16xlarge r6gd.16xlarge] (no instance type has enough resources)","commit":"8fb62bf","pod":"default/deployment-2048-6547c6b6cf-bl6v7"}
```

**Expected Behavior**:

The block devices are updated with the configuration specified

**Reproduction Steps** (Please include YAML):

```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
  - name: bottlerocket-aws-k8s-1.28-x86_64*
    tags:
      imageLaunchApproval: "true"
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 10
  - deviceName: /dev/xvdb
    ebs:
      volumeSize: 100
  role: KarpenterNodeRole-my-cluster
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: my-cluster
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: my-cluster
  tags:
    karpenter.sh/discovery: my-cluster
```
Deployment used
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: deployment-2048k
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048k
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048k
    spec:
      containers:
      - image: public.ecr.aws/kishorj/docker-2048:latest
        imagePullPolicy: Always
        name: app-2048k
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: karpenter.sh/nodepool
                  operator: Exists
                - key: karpenter.sh/capacity-type
                  operator: In
                  values:
                    - on-demand
                    - spot
```

**Versions**:
- Chart Version: v0.33.2, v0.33.1
- Kubernetes Version (`kubectl version`): v1.28.5-eks

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
