### ISSUE TITLE
Karpenter Nodes remain in NotReady state in GovCloud

### ISSUE THREAD

**Issue by vstthomas** [aws/karpenter-provider-aws#5593]
### Description

**Observed Behavior**

Karpenter can request a node and spin it up but it never completes the (whatever) process to enter a "Ready" state. 

This means it's not a Kubernetes object (yet) so `kubectl get nodes` displays the EKS/mng but not the Karpenter nodes. 

The Karpenter nodes are only observable from `eks-node-viewer`

```shell
% eks-node-viewer --node-selector="karpenter.sh/nodepool" --resources memory,cpu

1 nodes (0/14162Mi) 0.0% memory ░░ $0.037/hour | $26.864/month 
        0/7910m     0.0% cpu    ░░                             
11 pods (4 pending 7 running 7 bound)

i-0a87d1e060c6bb172 memory ░░   0% (0 pods) c5a.2xlarge/$0.0368 Spot - NotReady/6m58s 
                    cpu    ░░   0%                                                    
•
←/→ page • q: quit
```

Was contributing to issue #5570 but that one was closed out; finishing here. This may only apply to GovCloud anyway.

**Additional Context**:

It's unclear to me if this is a program issue or an implementation issue. Before [this fix](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/346) Karpenter deployed nodes and scheduled the pod as expected - but it couldn't kill a node that it had spun up in GovCloud. Worked fine in a commercial account.

Now, Karpenter can't seem to spin the nodes up correctly in GovCloud but it can kill them.

**Expected Behavior**:

The node is deployed by Karpenter, it goes to a ready state and the pod is scheduled according to the documentation. 

**Reproduction Steps** (Please include YAML):

1. Apply [TF config](https://github.com/VivSoftOrg/reproduction/tree/karpenter-iam)
2. get kubeconfig file (get-creds.sh)
3. uncomment/apply the blueprint tf file
4. send the [nodepool definition](https://github.com/VivSoftOrg/reproduction/blob/karpenter-iam/karpenter/node-pool-apps.yaml) to the cluster
5. send the [pause program](https://github.com/VivSoftOrg/reproduction/blob/karpenter-iam/karpenter/test/pause.yaml) to the cluster.
6. Scale up: `kubectl scale deployment inflate --replicas 5`

Fail: one `pause` pod is scheduled on to the single node in the managed node group; the others just sit there waiting for the karpenter node to become ready - it never does. 

After 15 minutes of non-use, the node is killed by Karpenter and replaced because the deployment still needs to schedule the 4 remaining pods. This becomes an infinite loop. 

**Additional Troubleshooting Steps**

I used Packer to copy an EKS worker node AMI and add my user account to it with an ssh key; then reconfigured the `EC2NodeClass` to use my AMI. Then opened up an ssh port to the VPC. After ssh'ing into the node and checking the logs I found that they looked relatively untouched:

```shell
$ journalctl -p 3 -xb
-- Logs begin at Thu 2024-02-01 23:36:30 UTC, end at Sat 2024-02-03 00:43:50 UTC. --
Feb 03 00:30:59 ip-172-31-43-231.us-gov-east-1.compute.internal kernel: SELinux:  Runtime disable is deprecated, use selinux=0 on the kernel cmdline.
```

Pretty standard 😂 

```shell
$ journalctl -u kubelet
-- No entries --
```

I would have expected something from the kubelet but it appears to have received nothing from the controller.

Everything else appeared to be normal, the boot process, init, et al.

```shell
$ pstree 
systemd─┬─2*[agetty]
        ├─amazon-ssm-agen───11*[{amazon-ssm-agen}]
        ├─auditd───{auditd}
        ├─chronyd
        ├─cloud-init─┬─part-001─┬─bash───bash───sleep
        │            │          └─part-001─┬─logger
        │            │                     └─tee
        │            └─sh───sh───tee
        ├─containerd───60*[{containerd}]
        ├─crond
        ├─dbus-daemon
        ├─2*[dhclient]
        ├─gssproxy───5*[{gssproxy}]
        ├─irqbalance───{irqbalance}
        ├─lvmetad
        ├─master─┬─pickup
        │        └─qmgr
        ├─rngd
        ├─rpcbind
        ├─rsyslogd───2*[{rsyslogd}]
        ├─sshd───sshd───sshd───bash───pstree
        ├─systemd-journal
        ├─systemd-logind
        └─systemd-udevd
```

From a networking perspective, I can hit anything in the VPC but there is no outbound path.

**Versions**:
- Chart Version:
- it appears the app and chart version are `0.32.1` (latest version of blueprints/addons)

- Kubernetes Version (`kubectl version`):
- Client Version: v1.29.1
- Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
- Server Version: v1.29.0-eks-c417bb3

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> I would have expected something from the kubelet but it appears to have received nothing from the controller

This sounds like an issue with something in the userData and in the node image that is causing the kubelet not to run. Since it looks like you using a custom AMI through the `amiSelectorTerms`, do you know if the AMI that Karpenter is selecting on has the `eks-bootstrap` script that Karpenter is expecting. 

The other thing that I will note from reading through the EC2NodeClass that you shared is that you may intend to be selecting on a combination of an image that has an id `ami-040d04b7b6b4ee64a` AND a name `eks-tester` AND a couple tags; however, terms are ORed together through the `amiSelectorTerms`, similar to `nodeSelectorTerms`, which means that you may be selecting on more images than you intend.

**Comment by vstthomas** [comment]
I'm only using the custom AMI to login and see what the kubelet is doing; the [modifications](https://github.com/todd-dsm/dev-linux-os/blob/main/aws-eks-node.pkr.hcl#L12-L25) are minimal:

1. update OS packages
2. install some diagnostic tools: lsof, bind-utils and tree
3. add a user account and ssh key

Can't imagine that would have any effect on OS/kubelet operations. 

---

> you may be selecting on more images than you intend

that's my first config for troubleshooting; I'm sure it could be improved. I'll review that bit to tighten it up. But, it does allow me to login to the node with the credentials configured into the AMI so I'm getting the intended AMI. Sounds like I'm getting the right one but probably too much criteria.

--- 

Even after all of that, I do see the same behavior with a standard AMI; the only difference is I can't login to it to verify anything. 

I've got a bit more investigation with SSM though; if I can get that working I can go back to the standard AMI AND see what it's doing.

**Comment by engedaam** [comment]
@vstthomas Can you share the NodeClaim that is created for a node that does not go ready?

**Comment by vstthomas** [comment]
@engedaam, good callout  😀  easiest answers first:

> _**what version of the eks-optimized AMI is the base for custom AMI?**_

`Base_AMI_ID` =  `ami-0e86a63ef91c7eb22`

I switched back to the AWS AMI today though (`ami-049ff3db30fd665c7`); it behaves the same. I should say that when I was using the custom one, it never never registered with SSM so I couldn't connect to it in session manager, as the troubleshooting docs suggest. That's specifically why I created the custom AMI with the user account/key; the assumption was that if anything was found in the logs using the custom one, it could have been true of both.

> _**Can you share the NodeClaim that is created for a node that does not go ready?**_

Looks like it all resolves to, "Message: Node not registered with cluster".

Based on how you asked the question, it seemed like there might be a objects (plural) listed; `default-9vdz7` is the only object under nodeclaims.

```yaml
# kubectl -n karpenter describe nodeclaims/default-9vdz7
Name:         default-9vdz7
Namespace:    
Labels:       karpenter.k8s.aws/instance-category=c
              karpenter.k8s.aws/instance-cpu=8
              karpenter.k8s.aws/instance-encryption-in-transit-supported=true
              karpenter.k8s.aws/instance-family=c5a
              karpenter.k8s.aws/instance-generation=5
              karpenter.k8s.aws/instance-hypervisor=nitro
              karpenter.k8s.aws/instance-memory=16384
              karpenter.k8s.aws/instance-network-bandwidth=2500
              karpenter.k8s.aws/instance-size=2xlarge
              karpenter.sh/capacity-type=spot
              karpenter.sh/nodepool=default
              kubernetes.io/arch=amd64
              kubernetes.io/os=linux
              node.kubernetes.io/instance-type=c5a.2xlarge
              topology.kubernetes.io/region=us-gov-east-1
              topology.kubernetes.io/zone=us-gov-east-1c
Annotations:  karpenter.k8s.aws/ec2nodeclass-hash: 6752849699453800551
              karpenter.sh/managed-by: reproduction
              karpenter.sh/nodepool-hash: 12393960163388511505
API Version:  karpenter.sh/v1beta1
Kind:         NodeClaim
Metadata:
  Creation Timestamp:  2024-02-06T01:56:16Z
  Finalizers:
    karpenter.sh/termination
  Generate Name:  default-
  Generation:     1
  Owner References:
    API Version:           karpenter.sh/v1beta1
    Block Owner Deletion:  true
    Kind:                  NodePool
    Name:                  default
    UID:                   c05b57b8-5a19-4cb3-9019-12e5bdf29301
  Resource Version:        1574827
  UID:                     1eba9fcb-3c63-499f-a2b9-ebf39a1fef6e
Spec:
  Node Class Ref:
    Name:  default
  Requirements:
    Key:       karpenter.sh/nodepool
    Operator:  In
    Values:
      default
    Key:       node.kubernetes.io/instance-type
    Operator:  In
    Values:
      c5.12xlarge
      ...
      r6i.8xlarge
    Key:       karpenter.sh/capacity-type
    Operator:  In
    Values:
      spot
    Key:       karpenter.k8s.aws/instance-category
    Operator:  In
    Values:
      c
      m
      r
    Key:       karpenter.k8s.aws/instance-generation
    Operator:  Gt
    Values:
      3
    Key:       kubernetes.io/arch
    Operator:  In
    Values:
      amd64
    Key:       kubernetes.io/os
    Operator:  In
    Values:
      linux
  Resources:
    Requests:
      Cpu:   4150m
      Pods:  6
Status:
  Allocatable:
    Cpu:                        7910m
    Ephemeral - Storage:        17Gi
    Memory:                     14162Mi
    Pods:                       58
    vpc.amazonaws.com/pod-eni:  38
  Capacity:
    Cpu:                        8
    Ephemeral - Storage:        20Gi
    Memory:                     15155Mi
    Pods:                       58
    vpc.amazonaws.com/pod-eni:  38
  Conditions:
    Last Transition Time:  2024-02-06T01:56:18Z
    Message:               Node not registered with cluster
    Reason:                NodeNotFound
    Status:                False
    Type:                  Initialized
    Last Transition Time:  2024-02-06T01:56:18Z
    Status:                True
    Type:                  Launched
    Last Transition Time:  2024-02-06T01:56:18Z
    Message:               Node not registered with cluster
    Reason:                NodeNotFound
    Status:                False
    Type:                  Ready
    Last Transition Time:  2024-02-06T01:56:18Z
    Message:               Node not registered with cluster
    Reason:                NodeNotFound
    Status:                False
    Type:                  Registered
  Image ID:                ami-049ff3db30fd665c7
  Provider ID:             aws:///us-gov-east-1c/i-00c1fe852a5503e95
Events:                    <none>
```

Some supporting logging:

```sh
% kubectl logs -n karpenter -c controller -l app.kubernetes.io/name=karpenter | grep -i nodeclaim                                                                                                                               <aws:vivsoft-gov>
{"level":"INFO","time":"2024-02-06T01:56:16.150Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"8fb62bf","nodeclaims":1,"pods":4}
{"level":"INFO","time":"2024-02-06T01:56:16.167Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"8fb62bf","nodepool":"default","nodeclaim":"default-9vdz7","requests":{"cpu":"4150m","pods":"6"},"instance-types":"c5.12xlarge, c5.18xlarge, c5.24xlarge, c5.2xlarge, c5.4xlarge and 95 other(s)"}
{"level":"INFO","time":"2024-02-06T01:56:18.775Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"8fb62bf","nodeclaim":"default-9vdz7","provider-id":"aws:///us-gov-east-1c/i-00c1fe852a5503e95","instance-type":"c5a.2xlarge","zone":"us-gov-east-1c","capacity-type":"spot","allocatable":{"cpu":"7910m","ephemeral-storage":"17Gi","memory":"14162Mi","pods":"58","vpc.amazonaws.com/pod-eni":"38"}}
{"level":"INFO","time":"2024-02-06T02:11:20.188Z","logger":"controller.nodeclaim.termination","message":"deleted nodeclaim","commit":"8fb62bf","nodeclaim":"default-9vdz7","node":"","provider-id":"aws:///us-gov-east-1c/i-00c1fe852a5503e95"}
{"level":"INFO","time":"2024-02-06T02:11:21.632Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"8fb62bf","nodeclaims":1,"pods":4}
{"level":"INFO","time":"2024-02-06T02:11:21.647Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"8fb62bf","nodepool":"default","nodeclaim":"default-vksc4","requests":{"cpu":"4150m","pods":"6"},"instance-types":"c5.12xlarge, c5.18xlarge, c5.24xlarge, c5.2xlarge, c5.4xlarge and 95 other(s)"}
{"level":"INFO","time":"2024-02-06T02:11:24.110Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"8fb62bf","nodeclaim":"default-vksc4","provider-id":"aws:///us-gov-east-1c/i-0190bbaa1bf33a56d","instance-type":"c5a.2xlarge","zone":"us-gov-east-1c","capacity-type":"spot","allocatable":{"cpu":"7910m","ephemeral-storage":"17Gi","memory":"14162Mi","pods":"58","vpc.amazonaws.com/pod-eni":"38"}}
```

_NOTE: the `instance-type` was truncated but it did reflect the requirements of the configuration_

I can put it back if it helps.

---

As a bonus, I did notice today that the docs mention the [deletion of launch-templates](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#9-delete-the-cluster) during tear-down. 

```sh
% aws ec2 describe-launch-templates --filters Name=tag:karpenter.k8s.aws/cluster,Values=reproduction
{
    "LaunchTemplates": []
}
```

Ne'er a one. So it didn't get as far as creating an LT; a few observations:

1. I do remember launch-templates scrolling by in the logs before before [the fix](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/346)
2. didn't realize until today that the logs no longer mention the creation of the LTs

**Comment by vstthomas** [comment]
Not sure if this is relevant but here's the first few `Node NotReady` [troubleshooting steps](https://karpenter.sh/preview/troubleshooting/#node-notready)

```sh
% kubectl get node -l "karpenter.sh/nodepool"

No resources found
% INSTANCE_ID=i-0ac7b3b5075a6effb
% aws ssm start-session --target $INSTANCE_ID

An error occurred (TargetNotConnected) when calling the StartSession operation: i-0ac7b3b5075a6effb is not connected.
```

**Comment by engedaam** [comment]
Can you provide your EC2NodeClass and NodePool? Since the node is not registering, it can be a problem with the subnets or security groups

**Comment by vstthomas** [comment]
I left everything in the Apply [TF config](https://github.com/VivSoftOrg/reproduction/tree/karpenter-iam) in the original post. 

Since it's been problematic most of the [karpenter config] is the same as what's in the Getting Started docs

[karpenter config]:https://github.com/VivSoftOrg/reproduction/blob/karpenter-iam/karpenter/node-pool-apps.yaml

**Comment by engedaam** [comment]
I should have clarified, I was hoping to the see the status section of the EC2NodeClass. That can give us information on the resolved values for the Subnet and Security Groups

**Comment by vstthomas** [comment]
Here's the EC2NodeClass: 

```yaml
# kubectl describe EC2NodeClass
Name:         default
Namespace:    
Labels:       <none>
Annotations:  karpenter.k8s.aws/ec2nodeclass-hash: 6752849699453800551
API Version:  karpenter.k8s.aws/v1beta1
Kind:         EC2NodeClass
Metadata:
  Creation Timestamp:  2024-02-05T18:15:03Z
  Finalizers:
    karpenter.k8s.aws/termination
  Generation:        1
  Resource Version:  1980319
  UID:               358eac7a-0e39-48c1-ac90-14edebb6866d
Spec:
  Ami Family:  AL2
  Metadata Options:
    Http Endpoint:                enabled
    httpProtocolIPv6:             disabled
    Http Put Response Hop Limit:  2
    Http Tokens:                  required
  Role:                           karpenter-reproduction-2024013019241487490000000e
  Security Group Selector Terms:
    Tags:
      karpenter.sh/discovery:  reproduction
  Subnet Selector Terms:
    Tags:
      karpenter.sh/discovery:  reproduction
Status:
  Amis:
    Id:    ami-075367bf3e511472f
    Name:  amazon-eks-arm64-node-1.29-v20240202
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        arm64
      Key:       karpenter.k8s.aws/instance-gpu-count
      Operator:  DoesNotExist
      Key:       karpenter.k8s.aws/instance-accelerator-count
      Operator:  DoesNotExist
    Id:          ami-0872d1704843e9a30
    Name:        amazon-eks-gpu-node-1.29-v20240202
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        amd64
      Key:       karpenter.k8s.aws/instance-gpu-count
      Operator:  Exists
    Id:          ami-0872d1704843e9a30
    Name:        amazon-eks-gpu-node-1.29-v20240202
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        amd64
      Key:       karpenter.k8s.aws/instance-accelerator-count
      Operator:  Exists
    Id:          ami-049ff3db30fd665c7
    Name:        amazon-eks-node-1.29-v20240202
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        amd64
      Key:           karpenter.k8s.aws/instance-gpu-count
      Operator:      DoesNotExist
      Key:           karpenter.k8s.aws/instance-accelerator-count
      Operator:      DoesNotExist
  Instance Profile:  reproduction_1945827343076045061
  Security Groups:
    Id:    sg-050d80bb6de1e87ca
    Name:  default
  Subnets:
    Id:    subnet-023c235748b66dad0
    Zone:  us-gov-east-1b
    Id:    subnet-01f2835e4171201b1
    Zone:  us-gov-east-1c
    Id:    subnet-05044360e84c56610
    Zone:  us-gov-east-1a
Events:    <none>
```

If there's a specific command(s) that you would like to see the out of then please let me know.

**Comment by engedaam** [comment]
Everything with the EC2NodeClass seems to be in order. Can you validate that your node authentication is set up correctly? Can check that the KarpenterNodeRole can join nodes to your cluster? When you describe your aws-auth configmap you should a section as such.
```
apiVersion: v1
kind: ConfigMap
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/KarpenterNodeRole-${${CLUSTER_NAME}}
      username: system:node:{{EC2PrivateDNSName}}
```
