### ISSUE TITLE
[Developing Locally]EC2MetadataRequestError: failed to get EC2 instance identity document

### ISSUE THREAD

**Issue by francis-jjk** [aws/karpenter-provider-aws#5607]
### Description

**Observed Behavior**:
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.xxx/latest/dynamic/instance-identity/document": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

- Ran `make run` got this error
- K8s: EKS on AWS
- Finsihed [Environment specific setup](https://karpenter.sh/docs/contributing/development-guide/#environment-specific-setup)

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Do you a Kubernetes cluster specified in your `~/.kube/config`?

**Comment by francis-jjk** [comment]
> Do you a Kubernetes cluster specified in your `~/.kube/config`?

Hi @engedaam , here is my ` ~/.kube/config`

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: QCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWE9vMTBKTXhjUzJsSTZFR3k4QUZqNUtSY2JEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3NPOW54dldLZApEWDZsUFRZR20vNlJ3L2tzV0dDbTVEbnFybVRyVngvL0x5VXd2eFBsNVJXbnVHa3pYQ1JqRUdQbnIwdnlTTWhFCkJMTTlZV0RxcWlST2NQa2Mvc1FpdzlIcFk4aFFlT05iZhfsjdhfuheuhfuehufheuhufheuhfuFhVUN5VEhYMll2STVLM1R0eU82OWViRzErbGplWndxZnhXSE9sdVVpRnQKRFdmam1jR2ZKQkZTCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://2FDD7F738AE61ABC42655D43DEF11EC1.gr7.us-west-2.eks.amazonaws.com
  name: francis-karpenter-demo.us-west-2.eksctl.io
contexts:
- context:
    cluster: francis-karpenter-demo.us-west-2.eksctl.io
    user: francis.jjk@francis-karpenter-demo.us-west-2.eksctl.io
  name: francis.jjk@francis-karpenter-demo.us-west-2.eksctl.io
current-context: francis.jjk@francis-karpenter-demo.us-west-2.eksctl.io
kind: Config
preferences: {}
users:
- name: francis.jjk@francis-karpenter-demo.us-west-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - francis-karpenter-demo
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: us-west-2
      provideClusterInfo: false


```
