### ISSUE TITLE
v0.34.0 throwing dial tcp 172.20.0.1:443: i/o timeout (Fargate / EKS 1.29)

### ISSUE THREAD

**Issue by sidick** [aws/karpenter-provider-aws#5631]
### Description

**Observed Behavior**:

I have a working 0.33.2 Karpenter install on EKS 1.29 with Karpenter on Fargate which is installed using Flux. When I attempt to upgrade to 0.34.0 I get the following error:

```
panic: failed to setup manager: failed to determine if *v1.Lease is namespaced: failed to get restmapping: failed to get server groups: Get "https://172.20.0.1:443/api": dial tcp 172.20.0.1:443: i/o timeout

goroutine 1 [running]:
github.com/samber/lo.must({0x263e8e0, 0xc0002e8300}, {0xc00099f740, 0x1, 0x1})
	github.com/samber/lo@v1.39.0/errors.go:51 +0x1c5
github.com/samber/lo.Must[...](...)
	github.com/samber/lo@v1.39.0/errors.go:65
sigs.k8s.io/karpenter/pkg/operator.NewOperator()
	sigs.k8s.io/karpenter@v0.34.0/pkg/operator/operator.go:183 +0x13d8
main.main()
	github.com/aws/karpenter-provider-aws/cmd/controller/main.go:33 +0x25
{"level":"FATAL","time":"2024-02-08T11:05:38.146Z","logger":"controller","message":"Checking EC2 API connectivity, WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.eu-west-1.amazonaws.com/\": dial tcp: lookup sts.eu-west-1.amazonaws.com: i/o timeout","commit":"17d6c05"}
```

**Expected Behavior**:

I would expect it to work as the previous installation did, the only change I made was the chart version number. Rolling back to 0.33.2 works fine even though the EKS is on 1.29.

**Reproduction Steps** (Please include YAML):

I update the version number in Flux and it upgrades first the CRD chart and then the main chart. After the deploy finishes the pod is created and runs but never becomes healthy, instead eventually showing the above error and restarting itself.

I did try setting `dnsPolicy=Default` in the chart but it didn't fix the issue

Edit: I forgot to add the helm chart values
```yaml
controller:
  resources:
    limits:
      cpu: 0.8
      memory: 1Gi
    requests:
      cpu: 0.5
      memory: 1Gi
logLevel: info
logConfig:
  logEncoding: json
replicas: 2
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: ${karpenter_role_arn}
settings:
  clusterName: ${cluster_name}
  interruptionQueue: ${karpenter_interruptionQueueName}
  featureGates:
    drift: 'true'
```

**Versions**:
- Chart Version: 0.34.0 (karpenter and karpenter-crd)
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
