### ISSUE TITLE
v0.34.0 nodepool creation is blocked when webhook is enabled due to validation.webhook.karpenter.sh 

### ISSUE THREAD

**Issue by shivendra-sharma-git** [aws/karpenter-provider-aws#5671]
### Description

**Observed Behavior**:
I am using v0.34.0 version of karpenter in 1.27 eks after enabling webhook for webhook metrics. i am not able to create nodepool its getting blocked

```
# node pool config
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: test-node-pool
spec:
  template:
    spec:
      taints:
        - key: "test-node-pool"
          effect: "NoSchedule"
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["eu-west-1a", "eu-west-1b","eu-west-1c"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["4xlarge","2xlarge","xlarge","large"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
      nodeClassRef:
        name: test-node-class
  limits:
    cpu: 100
    memory: 200Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h

# Error
Error from server (BadRequest): error when creating "nodePool.yaml": admission webhook "validation.webhook.karpenter.sh" denied the request: decoding request failed: cannot decode incoming new object: json: unknown field "budgets"

```

**Expected Behavior**:
Nodepool should be created. When i am disabling webhook it just works.

**Reproduction Steps** (Please include YAML):
- Apply above nodepool manifest 

**Versions**:
- Chart Version: v0.34.0
- Kubernetes Version (`kubectl version`): v1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> after enabling webhook for webhook metrics

How did you enable the webhook?

**Comment by shivendra-sharma-git** [comment]
@jonathan-innis : thanks for the response. my karpenter instance is managed by argocd. and below are its values i pass. 

```
      serviceAccount:
        create: true
        name: aws-karpenter
        annotations:

          eks.amazonaws.com/role-arn: "<iam-role>"

      controller:
        resources:
          limits:
            cpu: 1
            memory: 1Gi

      settings:
        clusterName: <cluster-name>
```

to enable webhook i have passed. 

```
      webhook:
        enabled: true

      # Had to add this cause i am using custom CNI (Calico). 
      hostNetwork: true

```

**Comment by jonathan-innis** [comment]
Can you share the deployment that Argo deployed to your cluster and the service that Karpenter is provisioning?

**Comment by shivendra-sharma-git** [comment]
sure below is the manifest. 

karpenter argo app 

```
---
project: k8s-infrastructure
source:
  repoURL: 'https://github.com/aws/karpenter.git'
  path: charts/karpenter
  targetRevision: v0.34.0
  helm:
    releaseName: aws-karpenter
    values: |
      serviceAccount:
        create: true
        name: aws-karpenter
        annotations:
          eks.amazonaws.com/role-arn: "<iam-role>"
      controller:
        resources:
          limits:
            cpu: 1
            memory: 1Gi
      settings:
        clusterName: <cluster-name>
      webhook:
        enabled: true
      hostNetwork: true
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
      tolerations: 
      - key: CriticalAddonsOnly
        operator: Exists
destination:
  server: 'https://kubernetes.default.svc'
  namespace: cluster
syncPolicy:
  syncOptions:
    - CreateNamespace=true
  retry:
    limit: 3
    backoff:
      duration: 30s
      factor: 2
      maxDuration: 3m
```


karpenter deployment 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: aws-karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.33.0
    argocd.argoproj.io/instance: karpenter
    helm.sh/chart: karpenter-0.33.0
  name: aws-karpenter
  namespace: cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: aws-karpenter
      app.kubernetes.io/name: karpenter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: aws-karpenter
        app.kubernetes.io/name: karpenter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: DoesNotExist
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: aws-karpenter
                app.kubernetes.io/name: karpenter
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: KUBERNETES_MIN_VERSION
          value: 1.19.0-0
        - name: KARPENTER_SERVICE
          value: aws-karpenter
        - name: WEBHOOK_PORT
          value: "8443"
        - name: WEBHOOK_METRICS_PORT
          value: "8001"
        - name: DISABLE_WEBHOOK
          value: "false"
        - name: LOG_LEVEL
          value: info
        - name: METRICS_PORT
          value: "8000"
        - name: HEALTH_PROBE_PORT
          value: "8081"
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: controller
              divisor: "0"
              resource: limits.memory
        - name: FEATURE_GATES
          value: Drift=true,SpotToSpotConsolidation=false
        - name: BATCH_MAX_DURATION
          value: 10s
        - name: BATCH_IDLE_DURATION
          value: 1s
        - name: ASSUME_ROLE_DURATION
          value: 15m
        - name: CLUSTER_NAME
          value: cluster1-main-euw1-0-dev
        - name: VM_MEMORY_OVERHEAD_PERCENT
          value: "0.075"
        - name: RESERVED_ENIS
          value: "0"
        image: public.ecr.aws/karpenter/controller:v0.33.0@sha256:5e5f59f74d86ff7f13d7d80b89afff8c661cb4e3265f2fdda95b76dd9c838cc1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: controller
        ports:
        - containerPort: 8000
          hostPort: 8000
          name: http-metrics
          protocol: TCP
        - containerPort: 8001
          hostPort: 8001
          name: webhook-metrics
          protocol: TCP
        - containerPort: 8443
          hostPort: 8443
          name: https-webhook
          protocol: TCP
        - containerPort: 8081
          hostPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65536
          runAsNonRoot: true
          runAsUser: 65536
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      priorityClassName: system-cluster-critical
      securityContext:
        fsGroup: 65536
      serviceAccount: aws-karpenter
      serviceAccountName: aws-karpenter
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: aws-karpenter
            app.kubernetes.io/name: karpenter
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
```

Service 

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: aws-karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.33.0
    argocd.argoproj.io/instance: karpenter
    helm.sh/chart: karpenter-0.33.0
  name: aws-karpenter
  namespace: cluster
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 8000
    protocol: TCP
    targetPort: http-metrics
  - name: webhook-metrics
    port: 8001
    protocol: TCP
    targetPort: webhook-metrics
  - name: https-webhook
    port: 8443
    protocol: TCP
    targetPort: https-webhook
  selector:
    app.kubernetes.io/instance: aws-karpenter
    app.kubernetes.io/name: karpenter
  type: ClusterIP

```

**Comment by jonathan-innis** [comment]
Ah, I misread what you originally posted in the description. Looks like this is the problem

> decoding request failed: cannot decode incoming new object: json: unknown field "budgets"

You need to make sure that you upgrade to the latest CRD when you are upgrading your controller version of Karpenter. Further detail can be found here: https://karpenter.sh/docs/upgrading/upgrade-guide/#crd-upgrades

**Comment by shivendra-sharma-git** [comment]
Sorry @jonathan-innis for delay in response. I try to sync CDRs but i don't see any changes.

```
kubectl apply -f https://raw.githubusercontent.com/aws/karpenter/v0.34.0/pkg/apis/crds/karpenter.sh_nodepools.yaml
customresourcedefinition.apiextensions.k8s.io/nodepools.karpenter.sh unchanged
kubectl apply -f https://raw.githubusercontent.com/aws/karpenter/v0.34.0/pkg/apis/crds/karpenter.sh_nodeclaims.yaml
customresourcedefinition.apiextensions.k8s.io/nodeclaims.karpenter.sh unchanged
kubectl apply -f https://raw.githubusercontent.com/aws/karpenter/v0.34.0/pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
customresourcedefinition.apiextensions.k8s.io/ec2nodeclasses.karpenter.k8s.aws unchanged
```

**Comment by jonathan-innis** [comment]
The Karpenter deployment that you are sharing above shows that it's on v0.33.0. Are you sure that both the CRDs AND the controller are running on the v0.34.0 version that contains the budgets?

**Comment by shivendra-sharma-git** [comment]
yep it seems like using github as source for application in argocd was not a good idea. this is what i tried. 
- removed karpenter from argocd 
- install a fresh instance using helm (which works as expected) 
- try to let argocd overtake it by create a karpenter argocd app 
```
spec:
  source:
    repoURL: "https://github.com/aws/karpenter.git"
    targetRevision: v0.34.1
```
the result was it tries to downgrade to v0.33.0 not sure why this specific version.
![image](https://github.com/aws/karpenter-provider-aws/assets/53882197/0f8d1bc4-0a79-4707-a830-eea306274e80)


after switching to oci helm repo it seems to work
```
source:
  repoURL: public.ecr.aws/karpenter
  targetRevision: v0.34.1
```

Thanks for all the help @jonathan-innis
