### ISSUE TITLE
Karpenter cannot provision node with same instance type previously used by cluster-autoscaler

### ISSUE THREAD

**Issue by dgdevops** [aws/karpenter-provider-aws#5676]
### Description

**Observed Behavior**:
After the migration from cluster-autoscaler to Karpenter, Karpenter cannot provision worker node with the exact same instance type (`m6a.2xlarge`) cluster-autoscaler was configured for due to `no instance type which had enough resources and the required offering met the scheduling requirements`.

**Scenario 1)**
When removing the `instance-family` requirement (m6a) from the NodePool configuration and setting the `instance-memory` requirement (`32768`) Karpenter manages to provision node from the `d` & `g` instance categories with the instance type `d3en.2xlarge` (Karpenter also considers `g4ad.2xlarge`, `g4dn.2xlarge` based on the logs) that has the exact same amount of vCPU & Memory the `m6a.2xlarge` instance type has. 

**Scenario 2)**
When removing the `instance-family` requirement (m6a) from the NodePool configuration and keeping the `instance-cpu` requirement (`8`) Karpenter manages to provision node from the `r` instance category with the instance type `r6a.2xlarge` that has the exact same amount of vCPU but double Memory (`64GB`) than the `m6a.2xlarge` instance type.

In case there is a worker node with instance type `m6a.2xlarge` already provisioned &  available in the cluster the default-scheduler manages to allocate the workload to this worker node, this also confirms that the `m6a.2xlarge` instance has the capacity to allocate our workload.

The [1306](https://github.com/aws/karpenter-provider-aws/issues/1306) GitHub issue mentions similar behaviour, the same setup was tested with the `vmMemoryOverheadPercent` set to `0.01` (from the `0.075` default) with no improvements.

**Temporary workarounds**:
1. Decrease the memory request of our workload by `2Gi` to `26Gi` and wait for Karpenter to provision a worker node with `m6a.2xlarge` instance type then revert back the memory request change
2. Extend the `karpenter.k8s.aws/instance-cpu` requirement list with `"16"` to give Karpenter the possibility to (over)provision a worker node with `m6a.4xlarge` instance type

**Expected Behavior**:
Karpenter should be able to use the same instance type that was allocated to our workload when cluster-autoscaler was used. As the default scheduler of Kubernetes can allocate the workload to a worker node with `m6a.2xlarge` instance type Karpenter should not block the provisioning of the worker node.

**Reproduction Steps** (Please include YAML):
1) Configure a NodePool with the details shared below
2) Create a workload with the resource specifications shared below (toleration is required)
3) Observe the Karpenter logs
4) Extend the instance-cpu list with `"16"`
5) Observe Karpenter provisioning a worker node with `m6a.4xlarge` instance type instead of `m6a.2xlarge` where the workload could previously fit when cluster-autoscaler was in use

NodePool configuration:
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: <omitted>-master
spec:
  disruption:
    consolidateAfter: 60s
    consolidationPolicy: WhenEmpty
    expireAfter: Never
  template:
    metadata:
      labels:
        <omitted>: <omitted>
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - m6a
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            - '8'
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values:
            - nitro
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - eu-west-1a
            - eu-west-1b
            - eu-west-1c
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
      taints:
        - effect: NoSchedule
          key: dedicated
          value: <omitted>-master
```

**Versions**:
- Chart Version: `v0.32.1`
- Kubernetes Version (`kubectl version`): `EKS 1.25`

**Further information**:
- AWS Region: `eu-west-1`
- OS: `BottleRocket OS` (also tested AL2, no improvements)
- Every minor version from `v0.32.1` to `v0.32.7` was tested, same behaviour was observed
- We do not hit Insufficient instance capacity issues as at the time of the error EC2 instances with `m6a.2xlarge` instance type can be successfully provisioned manually
- Workload resource specifications:
```
resources:
  limits:
    memory: 28Gi
  requests:
    cpu: '6'
    memory: 28Gi
```
- Karpenter global configuration:
```
  aws.assumeRoleARN: ''
  aws.assumeRoleDuration: 15m
  aws.clusterCABundle: ''
  aws.clusterEndpoint: https://<omitted>
  aws.clusterName: <omitted>
  aws.enableENILimitedPodDensity: 'true'
  aws.enablePodENI: 'false'
  aws.interruptionQueueName: ''
  aws.isolatedVPC: 'true'
  aws.vmMemoryOverheadPercent: '0.075'
  batchIdleDuration: 1s
  batchMaxDuration: 10s
  featureGates.driftEnabled: 'false'
```

If we summarise the findings it is clearly visible that some instance types cannot allocate our workload based on Karpenter while others can despite the fact they have same vCPU & Memory specifications.
Can you please help us understand Karpenter's logic behind the instance choice?

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Could you provide logs, your pod spec, and your EC2NodeClass? Using the provided nodepool and a pod with the same resource requests (the original 28, not 26) Karpenter successfully provisions a `m6a.2xlarge`.

**Comment by dgdevops** [comment]
Hello @jmdeal,
Thank you for your quick response.
Please find the requested outputs shared below:

Logs:
`{"level":"ERROR","time":"2024-02-15T11:10:12.564Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"<omitted>-master\", daemonset overhead={\"cpu\":\"480m\",\"memory\":\"812700032\",\"pods\":\"5\"}, no instance type satisfied resources {\"cpu\":\"6480m\",\"memory\":\"30877471104\",\"pods\":\"6\"} and requirements <omitted>-server-role In [<omitted>], karpenter.k8s.aws/instance-cpu In [8], karpenter.k8s.aws/instance-family In [m6a], karpenter.k8s.aws/instance-hypervisor In [nitro], karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [<omitted>-master], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], topology.kubernetes.io/zone In [eu-west-1a] (no instance type which had enough resources and the required offering met the scheduling requirements); incompatible with nodepool \"<omitted>-slave\", daemonset overhead={\"cpu\":\"480m\",\"memory\":\"812700032\",\"pods\":\"5\"}, did not tolerate dedicated=<omitted>slaves:NoSchedule; incompatible with nodepool \"on-demand\", daemonset overhead={\"cpu\":\"480m\",\"memory\":\"812700032\",\"pods\":\"5\"}, did not tolerate lifecycle=OnDemand:NoSchedule; incompatible with nodepool \"spot\", daemonset overhead={\"cpu\":\"480m\",\"memory\":\"812700032\",\"pods\":\"5\"}, incompatible requirements, label \"<omitted>-server-role\" does not have known values","commit":"1072d3b","pod":"<omitted>/<omitted>-master-1"}`

Pod specifications:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: <omitted>-master
  namespace: <omitted>
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: <omitted>-master
      app.kubernetes.io/name: <omitted>-master
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: <omitted>-master
        app.kubernetes.io/name: <omitted>-master
        <omitted>-role: master
      annotations:
    spec:
      initContainers:
        - name: volume
          image: <omitted>
          command:
            - <omitted>
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
      containers:
        - name: <omitted>
          image: <omitted>
          resources:
            limits:
              memory: 28Gi
            requests:
              cpu: '6'
              memory: 28Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - eu-west-1a
                      - eu-west-1b
                      - eu-west-1c
                  - key: <omitted>-server-role
                    operator: In
                    values:
                      - <omitted>master
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: <omitted>-master
                  app.kubernetes.io/name: <omitted>-master
              topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
      tolerations:
        - key: dedicated
          operator: Equal
          value: <omitted>master
          effect: NoSchedule
```

EC2NodeClass:         
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  instanceProfile: <omitted>
  securityGroups:
    - id: <omitted>
      name: <omitted>
    - id: <omitted>
      name: <omitted>
    - id: <omitted>
      name: <omitted>
  subnets:
    - id: <omitted>
      zone: eu-west-1c
    - id: <omitted>
      zone: eu-west-1a
    - id: <omitted>
      zone: eu-west-1b
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
    - id: ami-0c93c9f434e3d1c5e
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        kmsKeyID: >-
          arn:aws:kms:eu-west-1:<omitted>:key/<omitted>
        volumeSize: 20Gi
        volumeType: gp3
    - deviceName: /dev/xvdb
      ebs:
        deleteOnTermination: true
        encrypted: true
        kmsKeyID: >-
          arn:aws:kms:eu-west-1:<omitted>:key/<omitted>
        volumeSize: 50Gi
        volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: optional
  role: <omitted>
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: <omitted>
    - id: <omitted>
  subnetSelectorTerms:
    - id: <omitted>
    - id: <omitted>
    - id: <omitted>
```
