### ISSUE TITLE
v0.34.0 Disruption Budgets not accepted in Nodepool manifest

### ISSUE THREAD

**Issue by rsavage-nozominetworks** [aws/karpenter-provider-aws#5682]
### Description

**Observed Behavior**:
When trying to add disruption budgets to either an new nodepool or an existing nodepool, I am seeing that the `budgets` field is rejected.

```yaml
# nodepools.karpenter.sh "default" was not valid:
# * <nil>: Invalid value: "The edited file failed validation": ValidationError(NodePool.spec.disruption): unknown field "budgets" in sh.karpenter.v1beta1.NodePool.spec.disruption
#
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "16443692865225363756"
  name: default
spec:
  disruption:
    budgets:
    - nodes: "10%"
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: Never
    
... truncated
```
Error
```
ValidationError(NodePool.spec.disruption): unknown field "budgets" in sh.karpenter.v1beta1.NodePool.spec.disruption
```

**Expected Behavior**:
Budgets fields work

**Reproduction Steps** (Please include YAML):
I tested this in two separate EKS clusters.

**Versions**:
- Chart Version: v0.34.0
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
