### ISSUE TITLE
Facing issues while using topologySpreadConstraints

### ISSUE THREAD

**Issue by aashish-fiftyfive** [aws/karpenter-provider-aws#5685]
I recently faced an issue while using karpenter version 0.22.1 that as I included `topologySpreadConstraints` into my application deployment to spread pods across different nodes, consolidation stopped working, I have a eks managed node group and rest scaling is being managed by karpenter, I want maximum 3 nodes for the application including managed group one but now the nodes are 4 where 3 are of karpenter provisioned, everything was working fine before adding `topologySpreadConstraints` in my deployment.

I am using on-demand instances for both eks managed group and karpenter provisioner

Has anyone faced similar issue before?

**Comment by jmdeal** [comment]
Could you share your pod spec, provisioner, and logs? There are a couple caveats to using topologySpreadConstraints with consolidation, particularly that consolidation will always respect preferences. This may result in consolidation not taking place when you believe it should.

**Comment by aashish-fiftyfive** [comment]
> Could you share your pod spec, provisioner, and logs? There are a couple caveats to using topologySpreadConstraints with consolidation, particularly that consolidation will always respect preferences. This may result in consolidation not taking place when you believe it should.

Pod Spec -
```
topologySpreadConstraints:
  - maxSkew: 5
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
```

Provisioner -

```
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: app-template
spec:
  subnetSelector:
    aws-ids: (subnet id's)    
  launchTemplate: (launch template id)

---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: app-provisioner
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.xlarge"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
  labels: (custom labels)
  providerRef:
    name: app-template
  consolidation:
    enabled: true
```
