### ISSUE TITLE
Karpenter override wrong the Bottlerocket userData

### ISSUE THREAD

**Issue by lteixeira-dock** [aws/karpenter-provider-aws#5702]
### Description

**Observed Behavior**:

I have a Karpenter controller deployed in EKS Cluster 1.26. After the Karpenter deploy, I just created a NodeClass and NodePool to provision the Nodes.

NodeClass: 

```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Bottlerocket # Bottlerocket
  role: "<MY_IAM_ROLE>"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "true" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/karpenter-eks: "owned" # replace with your cluster name
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required        
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 30Gi
        volumeType: gp3
        deleteOnTermination: true
```

NodePool:

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec: 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["medium", "large"]
        - key: karpenter.k8s.aws/instance-generation
          operator: In
          values: ["3"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-2a", "us-east-2b", "us-east-2c"]
      nodeClassRef:
        name: default
  limits:
    cpu: 30
    memory: 60Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 12h # 30 * 24h = 720h
```

So When the Karpenter provisioned the EC2 Node, the field settings.kubernetes.api-server in the EC2 UserData is wrong. The correct value should be API Server Endpoint, but The karpeneter added the OIDC URL of EKS Cluster.

This form the EC2 Node (Worker) could't join in the EKS Cluster.

I did the change manually via api-client changing the api-server directly in EC2 via AWS Session Manager and after changed the EC2 works fine.

**Expected Behavior**: The Karpenter override the field correctly.

**Reproduction Steps** (Please include YAML):
- Deploy the Karpenter 0.34.0
- Create NodeClass and NodePool
- Failed the join of EC2 in the EKS Cluster

**Versions**: 0.34.0
- Chart Version: 0.34.0
- Kubernetes Version (`kubectl version`): 1.26

Docs referrence: https://karpenter.sh/docs/concepts/nodeclasses/#bottlerocket-2
