### ISSUE TITLE
Bug with scheduling multi gpu for a pod with a single gpu request?

### ISSUE THREAD

**Issue by drawnwren** [aws/karpenter-provider-aws#5703]
### Description
I have two issues.
When I apply the following yamls with a single gpu instance (i.e. p2.xlarge)  the pod provisions fine. However, the nodeclaim gets stuck with nvidia.com/gpu resource not available. However, karpenter fails to schedule a node at all when I increase the instance to i.e. p2.16xlarge. 

```
  Warning  FailedScheduling  47s   karpenter          Failed to schedule pod, incompatible with nodepool "rag-nodepool", daemonset overhead={"cpu":"210m","memory":"240Mi","pods":"7"}, no instance type satisfied resources {"cpu":"210m","ephemeral-storage":"20Gi","memory":"240Mi","nvidia.com/gpu":"1","pods":"8"} and requirements karpenter.sh/capacity-type In [on-demand spot], karpenter.sh/nodepool In [rag-nodepool]
```
The pod spec: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summarizer-container
  template:
    metadata:
      labels:
        app: summarizer-container
    spec:
      containers:
        - name: summarizer-container
          image: vllm/vllm-openai
          ports:
            - containerPort: 8000
              name: http-web-svc
          args: ['--model', '{{ .Values.summarizer.model_name }}']
          resources:
            requests:
              ephemeral-storage: '20Gi'
              nvidia.com/gpu: 1
            limits:
              ephemeral-storage: '30Gi'
              nvidia.com/gpu: 1

      nodeSelector:
        node.kubernetes.io/instance-type:
          {{ .Values.summarizer.instanceType }}
    tolerations:
      - key: nvidia.com/gpu
        operator: "Equals"
        value: "true"
        effect: "NoSchedule"
```

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: rag-nodepool
spec:
  template:
    spec:
      nodeClassRef:
        name: {{ .Values.summarizer.nodeClass }}
      # Define your provisioner spec here
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ['spot', 'on-demand']
        - key: node.kubernetes.io/instance-type
          operator: In
          values: [{{ .Values.summarizer.instanceType }}]
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: 'NoSchedule'
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .Values.summarizer.nodeClass }}
  annotations:
    kubernetes.io/description: 'Small, single GPU instance for running background 7B models'
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 120Gi
        volumeType: gp3
        encrypted: true
  role: 'KarpenterNodeRole-{{ .Values.settings.clusterName }}' # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.settings.clusterName }} # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.settings.clusterName }} # replace with your cluster name
```

**Comment by jmdeal** [comment]
I don't see the instance type requirement in the error log, could you describe the NodePool and verify that it was applied correctly?

**Comment by drawnwren** [comment]
sorry, I missed this response. I don't have the original nodepool/pod but I'm still getting the same error. Here are my current deployment + nodepool:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scifighter-13b-vllm-app-v1
  namespace: xoul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scifighter-13b-vllm-app-v1
  template:
    metadata:
      labels:
        app: scifighter-13b-vllm-app-v1
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: scifighter-13b-vllm-container-v1
          image: vllm/vllm-openai
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          ports:
            - containerPort: 8000
              name: http-web-svc
          args:
            [
              '--model',
              'KoboldAI/LLaMA2-13B-Psyfighter2',
            ]
          resources:
            requests:
              ephemeral-storage: '50Gi'
              nvidia.com/gpu: 1
            limits:
              ephemeral-storage: '100Gi'
              nvidia.com/gpu: 1
      nodeSelector:
        xoul-ai: single-medium-gpu 
      tolerations:
        - key: 'nvidia.com/gpu'
          operator: 'Equal'
          value: 'true'
          effect: 'NoSchedule'

---
apiVersion: v1
kind: Service
metadata:
  name: scifighter-13b-vllm-v1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: 'external'
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: 'ip'
    service.beta.kubernetes.io/aws-load-balancer-scheme: 'internal'
  namespace: xoul
spec:
  type: LoadBalancer
  selector:
    app: scifighter-13b-vllm-app-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-web-svc
```

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: g5-family
spec:
  template:
    metadata:
      labels:
        xoul-ai: single-medium-gpu
    spec:
      nodeClassRef:
        name: g5-family
      # Define your provisioner spec here
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ['spot', 'on-demand']
        - key: karpenter.k8s.aws/instance-family 
          operator: In
          values: [ "g"] 
        - key: karpenter.k8s.aws/instance-generation 
          operator: In
          values: ["5"] # == 24GB VRAM / gpu
      taints:
        - key: nvidia.com/gpu
          value: 'true'
          effect: 'NoSchedule'
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: g5-family
  annotations:
    kubernetes.io/description: 'Medium, single GPU instance for running background models'
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
        encrypted: true
  role: 'KarpenterNodeRole-{{ .Values.settings.clusterName }}'
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.settings.clusterName }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.settings.clusterName }}
```

here's the failing line from karpenter's logs:

```
 incompatible with nodepool \"g5-family\", daemonset overhead={\"cpu\":\"210m\",\"memory\":\"240Mi\",\"pods\":\"7\"}, no instance type satisfied resources {\"cpu\":\"210m\",\"ephemeral-storage\":\"50Gi\",\"memory\":\"240Mi\",\"nvidia.com/gpu\":\"1\",\"pods\":\"8\"} and requirements karpenter.k8s.aws/instance-family In [g], karpenter.k8s.aws/instance-generation In [5], karpenter.sh/capacity-type In [on-demand spot], karpenter.sh/nodepool In [g5-family], xoul-ai In [single-medium-gpu] (no instance type met all requirements); 
```

here's the description of the nodepool:
```
Name:         g5-family
Namespace:
Labels:       app.kubernetes.io/managed-by=Helm
              helm.toolkit.fluxcd.io/name=llm
              helm.toolkit.fluxcd.io/namespace=xoul
Annotations:  karpenter.sh/nodepool-hash: 7448491163432494300
              meta.helm.sh/release-name: llm-llm
              meta.helm.sh/release-namespace: llm
API Version:  karpenter.sh/v1beta1
Kind:         NodePool
Metadata:
  Creation Timestamp:  2024-03-06T23:31:56Z
  Generation:          4
  Resource Version:    9315867
  UID:                 281f5b9d-934f-4b3c-9c6c-4983fa2a4618
Spec:
  Disruption:
    Budgets:
      Nodes:               10%
    Consolidate After:     1m
    Consolidation Policy:  WhenEmpty
    Expire After:          720h
  Template:
    Metadata:
      Labels:
        Xoul - Ai:  single-medium-gpu
    Spec:
      Node Class Ref:
        Name:  g5-family
      Requirements:
        Key:       karpenter.sh/capacity-type
        Operator:  In
        Values:
          spot
          on-demand
        Key:       karpenter.k8s.aws/instance-family
        Operator:  In
        Values:
          g
        Key:       karpenter.k8s.aws/instance-generation
        Operator:  In
        Values:
          5
      Taints:
        Effect:  NoSchedule
        Key:     nvidia.com/gpu
        Value:   true
Events:
  Type    Reason             Age                From       Message
  ----    ------             ----               ----       -------
  Normal  DisruptionBlocked  2s (x81 over 80m)  karpenter  No allowed disruptions due to blocking budget
```
