### ISSUE TITLE
Karpenter does not disrupt/consolidate nodes that are underutilised

### ISSUE THREAD

**Issue by epetrovski-endava** [aws/karpenter-provider-aws#5707]
### Description

**Observed Behavior**:

Karpenter does not terminate nodes that are underutilised

**Expected Behavior**:

Karpenter should terminate underutilised nodes when the consolidation policy has been set to `WhenUnderutilized`

**Reproduction Steps** (Please include YAML):
These are the NodePool and EC2NodeClass resources. I'm using version 0.34.0

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        scope: "application"
    spec:
      requirements:
          - key: kubernetes.io/arch
            operator: In
            values: ["amd64"]
          - key: kubernetes.io/os
            operator: In
            values: ["linux"]
          - key: karpenter.sh/capacity-type
            operator: In
            values: ["on-demand"]
          - key: karpenter.k8s.aws/instance-category
            operator: In
            values: ["c", "m", "r"]
          - key: karpenter.k8s.aws/instance-generation
            operator: Gt
            values: ["2"]
      startupTaints:
      - key: node.cilium.io/agent-not-ready
        value: "true"
        effect: NoExecute
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      limits:
        cpu: 100
  disruption:
    consolidationPolicy: WhenUnderutilized
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 40Gi
        volumeType: gp3
        encrypted: true
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "cluster-name"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: "cluster-name"
  role: "KarpenterNodeRole"
```
**Versions**:
- Chart Version: 0.34.0
- Kubernetes Version (`kubectl version`): 1.28

The nodes in the cluster have less than 10% CPU and around 30-50% Memory usage. How can I make sure the cluster uses less nodes? My goal is to have as few nodes provisioned from Karpenter as possible, with a large pod density per node and making sure at least 80% of the CPU/Memory/Disk are used.
