### ISSUE TITLE
Karpenter not respecting topologySpreadConstraints

### ISSUE THREAD

**Issue by agelosnm** [aws/karpenter-provider-aws#5709]
### Description

**Observed Behavior**: Incoming pods being scheduled on existing nodes

**Expected Behavior**: Karpenter should spawn a new node each time the existing node groups cannot fullfill the number of requested pods

**Reproduction Steps** (Please include YAML):

I have an EKS cluster of 10 worker nodes (2 node groups of 5 nodes each). According to this setup, each of the pods are running on each node. The 11th one, should be scheduled on a new node that Karpenter will spawn but it is being scheduled on one of the existing nodes. The same behaviour occurs when icreasing the number of the `replicas`.

I've also included a new k/v of `topologyKey: "karpenter.sh/capacity-type"` but nothing different was observed.

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 11
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx
```

**Versions**:
- Chart Version: 0.34.1
- Kubernetes Version (`kubectl version`): 1.29.0
