### ISSUE TITLE
Pod with ephemeral-storage request not scaling NodePool from 0 on v0.34.1

### ISSUE THREAD

**Issue by cniessigma** [aws/karpenter-provider-aws#5715]
### Description

**Observed Behavior**:

```
Failed to schedule pod, incompatible with nodepool "devrunners-intel-xlarge-pool", daemonset overhead={"cpu":"685m","memory":"340Mi","pods":"9"}, no instance type satisfied resources {"cpu":"30685m","ephemeral-storage":"180G","memory":"112980Mi","pods":"10"}
```

**Expected Behavior**:

When setting the `blockDeviceMappings` in the `EC2NodeClass` resource has been set to have a large disk, I expect Karpenter to be able to ascertain the available ephemeral-storage ahead of a scale out, but it seems to be unable to. Removing the ephemeral-storage request fixes it and the NodePool can suddenly scale from 0

**Reproduction Steps** (Please include YAML):

Made essentially the following resources, removing some more specific bits like labels, ensuring that the NodePool can't be scaled up by any other node (as once the NodePool has an example node, it can be scheduled)

```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: devrunners-intel-xlarge-class
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 250G
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: <role arn>
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: <cluster_name>
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: <cluster_name>

---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: devrunners-intel-xlarge-pool
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: devrunners-intel-xlarge-class
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - m5n
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - 8xlarge
      taints:
        - effect: NoSchedule
          key: xlarge-box
```

Scheduling a pod with a 180 GiB ephemeral storage request spits an error that the NodePool cannot accomodate  the resources.

```
Failed to schedule pod, incompatible with nodepool "devrunners-intel-xlarge-pool", daemonset overhead={"cpu":"685m","memory":"340Mi","pods":"9"}, no instance type satisfied resources {"cpu":"30685m","ephemeral-storage":"180G","memory":"112980Mi","pods":"10"}
```

Removing the ephemeral storage requests fixes it, and were a node to come online it would schedule. Is there some way to annotate to Karpenter that a NodePool will have a certain ephemeral storage upon startup? Like ClusterAutoscaler's ASG tags.

**Versions**:
- Chart Version:
  v0.34.1

- Kubernetes Version (`kubectl version`):
```
Client Version: v1.28.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
