### ISSUE TITLE
Consolidation not working

### ISSUE THREAD

**Issue by kwarunek** [aws/karpenter-provider-aws#5733]
### Description

**Observed Behavior**:
We are in a migration process from `Provisioners` to `NodePools`. 

We have observed that Karpenter do not consolidate nodes either underutilized as well as the empty ones (left only daemonsets). The only changed made is PRovisioner>NodePool using `karpenter-convert`

As you can see from the 22th Feb number of nodes raises - the date of start of migration process.
![Screenshot 2024-02-26 at 23-53-36 Karpenter rotator - Karpenter - Dashboards - Grafana](https://github.com/aws/karpenter-provider-aws/assets/670887/ed7e9317-ffac-41b9-bedd-0212f51a0170)

Example definitions of the provisioner and corresponding nodepool:

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: monitoring-arm-d29kn3pvdw-spot-on-demand
spec:
  consolidation:
    enabled: true
  labels:
    rasp.nodegroup/name: arm
    rasp.nodegroup/namespace: monitoring
  limits:
    resources: {}
  providerRef:
    name: monitoring-arm-d29kn3pvdw
  requirements:
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - c7g.large
    - c7g.xlarge
    - c6g.large
    - c6g.xlarge
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - eu-central-1a
    - eu-central-1b
    - eu-central-1c
  taints:
  - effect: NoSchedule
    key: karpenter
    value: legacy
  - effect: NoSchedule
    key: dedicated
    value: monitoring
  - effect: NoSchedule
    key: special
    value: arm
  ttlSecondsUntilExpired: 2592000
  weight: 30
```

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: monitoring-arm-d29kn3pvdw-spot-on-demand
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h0m0s
  template:
    metadata:
      labels:
        rasp.nodegroup/name: arm
        rasp.nodegroup/namespace: monitoring
    spec:
      nodeClassRef:
        name: monitoring-arm-d29kn3pvdw
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c7g.large
        - c7g.xlarge
        - c6g.large
        - c6g.xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      taints:
      - effect: NoSchedule
        key: dedicated
        value: monitoring
      - effect: NoSchedule
        key: special
        value: arm
  weight: 30

```

**Expected Behavior**:
Empty nodes should be terminated, underutilized nodes also after reschedluing workload on other nodes.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 0.32.7
- Kubernetes Version (`kubectl version`): 1.25.16

**Stats**
- Number of nodepools: 188
- Number of provisioners: 188

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kwarunek** [comment]
Maybe related https://github.com/aws/karpenter-provider-aws/issues/5707

**Comment by kwarunek** [comment]
![Screenshot 2024-02-27 at 00-22-04 Edit panel - Karpenter overall - Karpenter - Dashboards - Grafana](https://github.com/aws/karpenter-provider-aws/assets/670887/27559f82-2b5a-4bd4-944d-96449233ceb5)
![Screenshot 2024-02-27 at 00-23-06 Edit panel - Karpenter overall - Karpenter - Dashboards - Grafana](https://github.com/aws/karpenter-provider-aws/assets/670887/1ca5ea62-437e-4b96-aa60-1be7a1c22c76)

Termination stats of nodeclaims/machines

**Comment by kwarunek** [comment]
On the smaller: cluster (~176 nodes, 74 nodepools, where the migration finished (0 machnies) we do not observe such a problem. But frankly I do not know if it's due the scale or the migration.

**Comment by jigisha620** [comment]
@kwarunek I was looking at the example Provisioner definition that you have used. Assuming that you have used periodic rolling with expiration to roll over your nodes, the value of `ttlSecondsUntilExpired` that you have set is almost 7 days. Wondering if that could be the reason why the existing nodes did not terminate?

**Comment by jonathan-innis** [comment]
There should be events that are associated with nodes that Karpenter will not remove that should give you more information about why Karpenter is not operating against them. Can you look at the `describe node` output of these nodes and see if there are any `DeprovisioningBlocked` or `Unconsolidatable` events attached?

**Comment by kwarunek** [comment]
Currently the mentioned nodepool have:
```
kwarunek@ws:~$ k top node -l karpenter.sh/nodepool=monitoring-arm-d29kn3pvdw-spot-on-demand
NAME                                              CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-10-228-109-148.eu-central-1.compute.internal   450m         23%    1089Mi          34%       
ip-10-228-127-102.eu-central-1.compute.internal   373m         19%    1315Mi          41%       
ip-10-228-169-193.eu-central-1.compute.internal   268m         13%    1178Mi          37%       
ip-10-228-223-118.eu-central-1.compute.internal   510m         26%    1090Mi          34%       
ip-10-228-250-4.eu-central-1.compute.internal     540m         27%    1156Mi          36%       
ip-10-228-254-49.eu-central-1.compute.internal    402m         20%    810Mi           25%       
ip-10-228-26-174.eu-central-1.compute.internal    255m         13%    1187Mi          37%       
ip-10-228-30-30.eu-central-1.compute.internal     294m         15%    1182Mi          37%       
ip-10-228-6-110.eu-central-1.compute.internal     424m         21%    1209Mi          38%       
ip-10-228-75-213.eu-central-1.compute.internal    244m         12%    1112Mi          35%       
ip-10-228-89-97.eu-central-1.compute.internal     297m         15%    1067Mi          33%       
ip-10-228-91-235.eu-central-1.compute.internal    404m         20%    1166Mi          37%       
ip-10-229-106-53.eu-central-1.compute.internal    349m         18%    1351Mi          43%       
ip-10-229-141-103.eu-central-1.compute.internal   515m         26%    1116Mi          35%       
ip-10-229-211-42.eu-central-1.compute.internal    557m         28%    1093Mi          34%       
ip-10-229-213-2.eu-central-1.compute.internal     383m         19%    1366Mi          43%       
ip-10-229-216-119.eu-central-1.compute.internal   580m         30%    1107Mi          35%       
ip-10-229-24-165.eu-central-1.compute.internal    507m         26%    1062Mi          33%       
ip-10-229-249-10.eu-central-1.compute.internal    609m         31%    1090Mi          34%       
ip-10-229-50-41.eu-central-1.compute.internal     451m         23%    1118Mi          35%       
ip-10-229-80-226.eu-central-1.compute.internal    595m         30%    1093Mi          34%       
ip-10-229-84-92.eu-central-1.compute.internal     414m         21%    1308Mi          41%       
ip-10-230-122-29.eu-central-1.compute.internal    412m         21%    1204Mi          38%       
ip-10-230-124-116.eu-central-1.compute.internal   327m         16%    1133Mi          36%       
ip-10-230-126-4.eu-central-1.compute.internal     346m         17%    1273Mi          40%       
ip-10-230-127-247.eu-central-1.compute.internal   504m         26%    1223Mi          38%       
ip-10-230-155-13.eu-central-1.compute.internal    346m         17%    1118Mi          35%       
ip-10-230-168-117.eu-central-1.compute.internal   327m         16%    952Mi           30%       
ip-10-230-19-221.eu-central-1.compute.internal    274m         14%    1117Mi          35%       
ip-10-230-22-132.eu-central-1.compute.internal    354m         18%    1263Mi          40%       
ip-10-230-232-94.eu-central-1.compute.internal    363m         18%    947Mi           30%       
ip-10-230-246-214.eu-central-1.compute.internal   398m         20%    1214Mi          38%       
ip-10-230-54-231.eu-central-1.compute.internal    379m         19%    808Mi           25%       
ip-10-230-82-146.eu-central-1.compute.internal    512m         26%    1009Mi          32%       
ip-10-230-96-147.eu-central-1.compute.internal    408m         21%    1136Mi          36%       
ip-10-230-97-217.eu-central-1.compute.internal    264m         13%    1116Mi          35%  
```
And there is no events for any of these. On these node there is only one workload (2 replicas) that requires specific  topologyConstraint, but still no info in the events.

@jigisha620 Possible, I presume that many things changed with nodepools - what is the priority of the conditions - emptiness/underutilized/ttl? But still that nodepool was created using `karpenter-convert` as such I presumed that I should get similar experience as the origin provisioner. Before further adjustments I will try to get rid of legacy provisioners.

**Comment by jonathan-innis** [comment]
> And there is no events for any of these. On these node there is only one workload (2 replicas) that requires specific topologyConstraint, but still no info in the events

Do you have the log output from Karpenter that you can share? It's surprising to me that we aren't logging events when nodes are down so low, I'm wondering if there's something that's going on here that might be seen in the logs.

**Comment by kwarunek** [comment]
[karpenter_logs_encrypted.zip](https://github.com/aws/karpenter-provider-aws/files/14416886/karpenter_logs_encrypted.zip)

@jonathan-innis In the zip arichive is a encrypted (with yours gpg key 7E54A797912EBA687EFA8A605046BA5825A72350) log files

**Comment by kwarunek** [comment]
Ok, after further debugging it's seems to be releated to the migration process itself - rescheduling all the pods allow to take into effect loose topologyConstraints (ScheduleAnyway) for the host and zone forced. I will work on it and tune replicasets.

The other thing that we're facing is that cordoned or empty nodes are not terminated by Karpenter - as from the snippet above we use `consolidationPolicy: WhenUnderutilized`. Is that also triggers emptiness? Karpenter 0.31. didn't have such a issue.

**Comment by kwarunek** [comment]
Update: I don't want to jinx it, but it seems that after forcing a faster migration of machines, the situation is starting to stabilize - as if Karpenter didn't "want" to operate efficiently alongside provisioners and node pools.

The issue of emptiness not functioning and the absence of logs regarding these actions, or why they are missing, still remains.

**Comment by kwarunek** [comment]
Emptiness issue example:

node desc
```
spec:
  providerID: aws:///eu-central-1a/i-0e9fd66b01f12bbe8
  taints:
  - effect: NoSchedule
    key: dedicated
    value: widgets-platform
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    timeAdded: "2024-02-27T22:32:12Z"
  unschedulable: true
status:
  addresses:
  - address: 10.228.60.106
    type: InternalIP
  - address: ip-10-228-60-106.eu-central-1.compute.internal
    type: Hostname
  - address: ip-10-228-60-106.eu-central-1.compute.internal
    type: InternalDNS
  allocatable:
    attachable-volumes-aws-ebs: "39"
    cpu: 1930m
    ephemeral-storage: "18233774458"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    hugepages-32Mi: "0"
    hugepages-64Ki: "0"
    memory: 1408568Ki
    pods: "11"
  capacity:
    attachable-volumes-aws-ebs: "39"
    cpu: "2"
    ephemeral-storage: 20949996Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    hugepages-32Mi: "0"
    hugepages-64Ki: "0"
    memory: 1895992Ki
    pods: "11"
  conditions:
  - lastHeartbeatTime: "2024-02-27T22:59:07Z"
    lastTransitionTime: "2024-02-22T22:30:43Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2024-02-27T22:59:07Z"
    lastTransitionTime: "2024-02-22T22:30:43Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2024-02-27T22:59:07Z"
    lastTransitionTime: "2024-02-22T22:30:43Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2024-02-27T22:59:07Z"
    lastTransitionTime: "2024-02-22T22:30:55Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
```
nodeclaim desc
```
status:
  allocatable:
    cpu: 1930m
    ephemeral-storage: 17Gi
    memory: 1359Mi
    pods: "11"
  capacity:
    cpu: "2"
    ephemeral-storage: 20Gi
    memory: 1835Mi
    pods: "11"
  conditions:
  - lastTransitionTime: "2024-02-22T22:30:56Z"
    status: "True"
    type: Initialized
  - lastTransitionTime: "2024-02-22T22:30:16Z"
    status: "True"
    type: Launched
  - lastTransitionTime: "2024-02-22T22:30:56Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-02-22T22:30:44Z"
    status: "True"
    type: Registered
  imageID: ami-0f53d22d949a2e99a
  nodeName: ip-10-228-60-106.eu-central-1.compute.internal
  providerID: aws:///eu-central-1a/i-0e9fd66b01f12bbe8
```
nodepool desc
```
Status:
  Resources:
    Attachable - Volumes - Aws - Ebs:  117
    Cpu:                               6
    Ephemeral - Storage:               62849988Ki
    Memory:                            5687976Ki
    Pods:                              33
Events:                                <none>
```
