### ISSUE TITLE
Karpenter launches on-demand instances instead of spot 

### ISSUE THREAD

**Issue by ilkinmammadzada** [aws/karpenter-provider-aws#5743]
### Description

**Observed Behavior**:

Karpenter launches on-demand instances even thought spot market has quite enough ec2 to respond our requirements 

   message: {"level":"INFO","time":"2024-02-27T17:43:27.399Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"17d6c05","nodepool":"default-uswest2bprod","nodeclaim":"default-uswest2bprod-xbxdw","requests":{"cpu":"120","ephemeral-storage":"45Gi","memory":"194860Mi","pods":"22"},"instance-types":"c6i.32xlarge, c6i.metal, c6id.32xlarge, c6id.metal, c6in.32xlarge and 23 other(s)"}
   
   
   
   message: {"level":"WARN","time":"2024-02-27T17:43:30.235Z","logger":"controller.nodeclaim.lifecycle","message":"at least 5 instance types are recommended when flexible to spot but requesting on-demand, the current provisioning request only has 1 instance type options","commit":"17d6c05","nodeclaim":"default-uswest2bprod-xbxdw"}
   
   
   
   message: {"level":"INFO","time":"2024-02-27T17:43:31.886Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"17d6c05","nodeclaim":"default-uswest2bprod-xbxdw","provider-id":"aws:///us-west-2b/i-xxxx","instance-type":"c6i.32xlarge","zone":"us-west-2b","capacity-type":"on-demand","allocatable":{"cpu":"125610m","ephemeral-storage":"206336Mi","memory":"235731254Ki","pods":"200","vpc.amazonaws.com/pod-eni":"107"}}
   
   
   
   message: {"level":"INFO","time":"2024-02-27T17:47:05.891Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"17d6c05","nodeclaim":"default-uswest2bprod-xbxdw","provider-id":"aws:///us-west-2b/i-xxxx","node":"yyyy"}

**Expected Behavior**:

I would expect launching on-demand only if there is no spot instances with given requirements. 
([Karpenter prioritizes Spot offerings if the NodePool allows Spot and on-demand instances](https://karpenter.sh/docs/concepts/nodepools/#capacity-type))

**Reproduction Steps** (Please include YAML):
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default-uswest2bprod
spec:
  template:
    metadata:
      labels:
        x.com/pool: default
    spec:
      nodeClassRef:
        name: default-uswest2bprod
      requirements:
      - key: x.com/pool
        operator: In
        values:
        - default
      - key: karpenter.k8s.aws/instance-cpu
        operator: Gt
        values:
        - "31"
      - key: karpenter.k8s.aws/instance-cpu
        operator: Lt
        values:
        - "192"
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - m5
        - m5d
        - m5dn
        - m5n
        - m5zn
        - m6i
        - m6id
        - m6idn
        - m6in
        - m7i
        - r5
        - r5b
        - r5dn
        - r5n
        - r6i
        - r6id
        - r6idn
        - r6in
        - r7i
        - i4i
        - c5
        - c5d
        - c5n
        - c6i
        - c6id
        - c6in
        - c7i
        - x2idn
        - x2iedn
        - x2iezn
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-west-2b
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      startupTaints:
      - effect: NoSchedule
        key: key
```

**Versions**:
- Chart Version: v0.34
- Kubernetes Version (`kubectl version`): v1.23.17

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
