### ISSUE TITLE
 WebIdentityErr: failed to retrieve credentials when upgrading from 0.33 to 0.34

### ISSUE THREAD

**Issue by ami-descope** [aws/karpenter-provider-aws#5761]
### Description

**Observed Behavior**:
using pulumi to spin up chart 0.33.2 => working no issues
using same code with only change of 0.34.1 and applied CRD's fails on getting credentials due to timeout

Karpenter env is fargate

error is

```console
karpenter-83f78451-b7c756fbc-zjlwr controller {"level":"FATAL","time":"2024-03-01T16:09:11.828Z","logger":"controller","message":"Checking EC2 API connectivity, WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.us-east-1.amazonaws.com/\": dial tcp: lookup sts.us-east-1.amazonaws.com: i/o timeout","commit":"596ea97"}
```

chart.yaml

```yaml
apiVersion: v2
version: 0.1.0
appVersion: 0.1.0
name: aws-eks
description: chart manifest 
dependencies:
  - name: karpenter
    repository: oci://public.ecr.aws/karpenter/karpenter
    version: "v0.33.2"
  - name: node-local-dns
    repository: https://charts.deliveryhero.io
    version: "2.0.4"
  - name: aws-vpc-cni
    version: 1.15.4
    repository: https://aws.github.io/eks-charts
```

Although this looks like networking issue its not since the same configuration works on 0.33.2 but not on 0.34 or 0.35

**Expected Behavior**:
Should upgrade smoothly from 0.33 to 0.34 or 0.35
 
**Reproduction Steps** (Please include YAML):
install 0.33.2 upgrade to 0.34.1 fails
revert to 0.33.2 using pulumi works as expected

seems like the networking is blocked once deployed the new version of the chart
 curl google.com
curl: (6) Could not resolve host: google.com

**Versions**:
- Chart Version: 0.34.1 / 0.35.0
- Kubernetes Version (`kubectl version`): 1.27 EKS

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
