### ISSUE TITLE
Node provisioning fails with `the body of the request is too large.`.

### ISSUE THREAD

**Issue by hivectl-cf** [aws/karpenter-provider-aws#5776]
### Description

**Observed Behavior**:

No new nodes are being added to the cluster, `nodeClaims` are stuck on node creation with the following error:
```
creating instance, creating fleet InvalidInput: The request failed because the payload for the body of the request is too large.
                           status code: 400, request id: 80085587-de7c-4659-8c5a-456e93b168e5 (80085587-de7c-4659-8c5a-456e93b168e5)
```
Prior to upgrade to `0.35.0` the nodes of the `EC2NodeClass` were being provisioned just fine.

**Expected Behavior**:
Nodes are created and added to the cluster.

**Reproduction Steps** (Please include YAML):
```yaml
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  annotations:
    kubernetes.io/description: EC2NodeClass for running Bottlerocket nodes
  name: bottlerocket-cpu
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      volumeSize: 4Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      volumeSize: 20Gi
      volumeType: gp3
  role: kprnd-cluster_name-2024030410563613600000000e # role_name_length = 60
  securityGroupSelectorTerms:
  - id: sg-id
  subnetSelectorTerms:
  - id: subnet-id1
  - id: subnet-id2
  - id: subnet-id3
  - id: subnet-id4
  - id: subnet-id5
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
    kubernetes.io/description: General purpose NodePool for generic workloads
  name: cpu
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
  template:
    spec:
      kubelet:
        maxPods: 200
      nodeClassRef:
        name: bottlerocket-cpu
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
        - arm64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
        - t
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
  weight: 100
```
**Versions**:
- Chart Version: `0.35.0`
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0-eks-c417bb3
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
