### ISSUE TITLE
Karpenter disrupting pods with `karpenter.sh/do-not-disrupt: "true"` annotation

### ISSUE THREAD

**Issue by AleksaC** [aws/karpenter-provider-aws#5786]
### Description

**Observed Behavior**:

Karpenter provisioned a node (`ip-10-3-166-58.eu-central-1.compute.internal`) to schedule two pending pods (`runner-6fvcfnjvw-project-335-concurrent-0-jnhl2u9b` and `runner-6fvcfnjvw-project-335-concurrent-1-1zfg6jd5`) only to consolidate the node and evict the pods ~20s later. The pods were annotated with `karpenter.sh/do-not-disrupt: "true"`.

Here are excerpts from karpenter logs and k8s events.

```console
2024-03-05 10:29:54	 {"level":"INFO","time":"2024-03-05T09:29:54.109Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"596ea97","nodeclaim":"gitlab-runner-overflow-sbdgm","provider-id":"aws:///eu-central-1b/i-026f428dc48c7d1e1","node":"ip-10-3-166-58.eu-central-1.compute.internal"}
2024-03-05 10:30:14	 {"level":"INFO","time":"2024-03-05T09:30:14.357Z","logger":"controller.disruption","message":"disrupting via consolidation delete, terminating 1 candidates ip-10-3-166-58.eu-central-1.compute.internal/t3.large/spot","commit":"596ea97","command-id":"296e8d57-8002-4e62-99fe-951d4bd3bb77"}
2024-03-05 10:30:14	 {"level":"INFO","time":"2024-03-05T09:30:14.823Z","logger":"controller.disruption.queue","message":"command succeeded","commit":"596ea97","command-id":"296e8d57-8002-4e62-99fe-951d4bd3bb77"}
2024-03-05 10:30:14	 {"level":"INFO","time":"2024-03-05T09:30:14.869Z","logger":"controller.node.termination","message":"tainted node","commit":"596ea97","node":"ip-10-3-166-58.eu-central-1.compute.internal"}
2024-03-05 10:30:16	 {"level":"INFO","time":"2024-03-05T09:30:16.489Z","logger":"controller.node.termination","message":"deleted node","commit":"596ea97","node":"ip-10-3-166-58.eu-central-1.compute.internal"}
2024-03-05 10:30:16	 {"level":"INFO","time":"2024-03-05T09:30:16.812Z","logger":"controller.nodeclaim.termination","message":"deleted nodeclaim","commit":"596ea97","nodeclaim":"gitlab-runner-overflow-sbdgm","node":"ip-10-3-166-58.eu-central-1.compute.internal","provider-id":"aws:///eu-central-1b/i-026f428dc48c7d1e1"}
```

```console
45m         Normal    Scheduled              pod/runner-6fvcfnjvw-project-335-concurrent-0-jnhl2u9b   Successfully assigned gitlab-runner/runner-6fvcfnjvw-project-335-concurrent-0-jnhl2u9b to ip-10-3-166-58.eu-central-1.compute.internal
45m         Normal    Pulling                pod/runner-6fvcfnjvw-project-335-concurrent-0-jnhl2u9b   Pulling image "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-f5da3c5a"
45m         Normal    Created                pod/runner-6fvcfnjvw-project-335-concurrent-0-jnhl2u9b   Created container init-permissions
45m         Normal    Pulled                 pod/runner-6fvcfnjvw-project-335-concurrent-0-jnhl2u9b   Successfully pulled image "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-f5da3c5a" in 4.204s (4.204s including waiting)
45m         Normal    Started                pod/runner-6fvcfnjvw-project-335-concurrent-0-jnhl2u9b   Started container init-permissions
45m         Normal    Pulling                pod/runner-6fvcfnjvw-project-335-concurrent-0-jnhl2u9b   Pulling image "node:18-alpine"
45m         Normal    Evicted                pod/runner-6fvcfnjvw-project-335-concurrent-0-jnhl2u9b   Evicted pod

45m         Normal    Scheduled              pod/runner-6fvcfnjvw-project-335-concurrent-1-1zfg6jd5   Successfully assigned gitlab-runner/runner-6fvcfnjvw-project-335-concurrent-1-1zfg6jd5 to ip-10-3-166-58.eu-central-1.compute.internal
45m         Normal    Pulling                pod/runner-6fvcfnjvw-project-335-concurrent-1-1zfg6jd5   Pulling image "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-f5da3c5a"
45m         Normal    Pulled                 pod/runner-6fvcfnjvw-project-335-concurrent-1-1zfg6jd5   Successfully pulled image "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-f5da3c5a" in 3.579s (3.579s including waiting)
45m         Normal    Created                pod/runner-6fvcfnjvw-project-335-concurrent-1-1zfg6jd5   Created container init-permissions
45m         Normal    Started                pod/runner-6fvcfnjvw-project-335-concurrent-1-1zfg6jd5   Started container init-permissions
45m         Normal    Pulling                pod/runner-6fvcfnjvw-project-335-concurrent-1-1zfg6jd5   Pulling image "node:18-alpine"
45m         Normal    Evicted                pod/runner-6fvcfnjvw-project-335-concurrent-1-1zfg6jd5   Evicted pod
```

The two pods were the only thing scheduled on the node other than daemonsets. 

I have no reason to believe that the pods got evicted by some other process and karpenter just cleaned up the node afterwards. Because prometheus only got a single scrape of the node metrics I cannot guarantee that there was no node pressure based on that, but it's very unlikely since the pods that were scheduled on the node consume next to no resources and the timespan was very short. 

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

I cannot really provide a set of manifests that would reproduce this deterministically as it's the first time this happened in a couple of weeks that this setup has been active.

Here is the `NodePool` manifest if it helps with anything:
```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
    meta.helm.sh/release-name: gitlab-runner
    meta.helm.sh/release-namespace: gitlab-runner
  labels:
    app.kubernetes.io/managed-by: Helm
  name: gitlab-runner-overflow
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  limits:
    cpu: "12"
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - t3
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - medium
        - large
        - xlarge
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      taints:
      - effect: NoSchedule
        key: gitlab-runner
  weight: 98
```

It would be helpful if karpenter provided more information in its logs. I glanced at the code to see if maybe there is more useful info if I changed the log level to debug, but couldn't find anything to support that.

**Versions**:
- Chart Version: `v0.34.1`
- Kubernetes Version (`kubectl version`): `1.28`

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by AleksaC** [comment]
Based on the events above only the `init-permissions` init container started. I'm not sure if that counts as running or is it still waiting state.

**Comment by engedaam** [comment]
@AleksaC Can you share the pods spec?

**Comment by AleksaC** [comment]
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    karpenter.sh/do-not-disrupt: "true"
  labels:
    pod: runner-6fvcfnjvw-project-335-concurrent-0
  name: runner-6fvcfnjvw-project-335-concurrent-0-tufgrs7o
  namespace: gitlab-runner
spec:
  activeDeadlineSeconds: 3601
  affinity: {}
  containers:
  - command:
    - sh
    - -c
    - "if [ -x /usr/local/bin/bash ]; then\n\texec /usr/local/bin/bash \nelif [ -x
      /usr/bin/bash ]; then\n\texec /usr/bin/bash \nelif [ -x /bin/bash ]; then\n\texec
      /bin/bash \nelif [ -x /usr/local/bin/sh ]; then\n\texec /usr/local/bin/sh \nelif
      [ -x /usr/bin/sh ]; then\n\texec /usr/bin/sh \nelif [ -x /bin/sh ]; then\n\texec
      /bin/sh \nelif [ -x /busybox/sh ]; then\n\texec /busybox/sh \nelse\n\techo shell
      not found\n\texit 1\nfi\n\n"
    image: node:18-alpine
    imagePullPolicy: IfNotPresent
    name: build
    resources:
      limits:
        memory: 3Gi
      requests:
        cpu: 250m
        memory: 3Gi
    securityContext:
      capabilities:
        drop:
        - NET_RAW
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /scripts-335-102274
      name: scripts
    - mountPath: /logs-335-102274
      name: logs
    - mountPath: /builds
      name: repo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lv878
      readOnly: true
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
  - command:
    - sh
    - -c
    - "if [ -x /usr/local/bin/bash ]; then\n\texec /usr/local/bin/bash \nelif [ -x
      /usr/bin/bash ]; then\n\texec /usr/bin/bash \nelif [ -x /bin/bash ]; then\n\texec
      /bin/bash \nelif [ -x /usr/local/bin/sh ]; then\n\texec /usr/local/bin/sh \nelif
      [ -x /usr/bin/sh ]; then\n\texec /usr/bin/sh \nelif [ -x /bin/sh ]; then\n\texec
      /bin/sh \nelif [ -x /busybox/sh ]; then\n\texec /busybox/sh \nelse\n\techo shell
      not found\n\texit 1\nfi\n\n"
    image: registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-f5da3c5a
    imagePullPolicy: IfNotPresent
    name: helper
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      capabilities:
        drop:
        - NET_RAW
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /scripts-335-102274
      name: scripts
    - mountPath: /logs-335-102274
      name: logs
    - mountPath: /builds
      name: repo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lv878
      readOnly: true
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: runner-6fvcfnjvw-project-335-concurrent-0-v3o8xgoq
  initContainers:
  - command:
    - sh
    - -c
    - touch /logs-335-102274/output.log && (chmod 777 /logs-335-102274/output.log
      || exit 0)
    image: registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-f5da3c5a
    imagePullPolicy: IfNotPresent
    name: init-permissions
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      capabilities:
        drop:
        - NET_RAW
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /scripts-335-102274
      name: scripts
    - mountPath: /logs-335-102274
      name: logs
    - mountPath: /builds
      name: repo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lv878
      readOnly: true
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: gitlab-runner
  serviceAccountName: gitlab-runner
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoSchedule
    key: gitlab-runner
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
  - emptyDir: {}
    name: repo
  - emptyDir: {}
    name: scripts
  - emptyDir: {}
    name: logs
  - name: kube-api-access-lv878
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

**Comment by engedaam** [comment]
> Based on the events above only the `init-permissions` init container started. I'm not sure if that counts as running or is it still waiting state.

From doing a little bit of research, I found that for a pod to be in a running state on a cluster the init container must have fully completed https://devopscube.com/kubernetes-pod-lifecycle/. Since the node was in a ready state and healthy, Karpenter considered that pod to be unschedulable as that pod did not immediately  go into a running state on the node. Therefore, Karpenter considered that node to be empty. How long does the `init-permissions` container take to fully complete? This issue will be solved once `consolidateAfter` is able to be used for `consolidationPolicy: WhenUnderutilized`. We currently have an open issue for the `consolidateAfter` feature  https://github.com/kubernetes-sigs/karpenter/issues/735

**Comment by edsonmarquezani** [comment]
I'm experiencing this issue. My pods are annotated with `karpenter.sh/do-not-disrupt: "true"` but still, their nodes are disrupted due to consolidation.

**Comment by engedaam** [comment]
@AleksaC Can you provide the pod describe to show what could be the reason the pod was evicted? Can share the events with timestamps, so we can compare when the eviction event was fired and when karpenter started terminating the node? Also are you seeing this happen regularly?

**Comment by edsonmarquezani** [comment]
@AleksaC I'm still investing, but it seems like I was just looking at the wrong place. The annotation actually shows up in nodes events (I was expecting to see it in Karpenter's logs). Regarding the eviction behavior, I'm still investigating but might not be triggered by Karpenter, after all.

**Comment by AleksaC** [comment]
@engedaam I cannot describe the original pods as they were gone by the time I was originally notified of the issue. It seems that naked pods get deleted upon eviction. Also the events aren't exported anywhere so they are gone now as well.

This is the first and only time it happened so far that I noticed. However this node pool isn't used often, as it's purpose is to handle spikes in CI jobs that node pool that doesn't have consolidation enabled cannot handle. As far as other node pools are concerned their workloads don't have pods that use this annotation. 

I had an issue with a misbehaving HPA that would quickly scale up and down leading karpenter to provision a new node and then consolidate both the original and the new node leaving the pods from the original node in Pending state waiting for a new node to be spun up.

I only noticed this because one of the pods was from a Statefulset so it was pending a little longer than other pods, triggering our alerts. In this case I used the `do-not-disrupt` annotation on the pods for that statefulset to prevent the unnecessary consolidation until I fixed the HPA and it worked correctly AFAIK.

**Comment by AleksaC** [comment]
I did some more testing.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: testing
spec:
  shareProcessNamespace: true
  containers:
  - command:
    - sh
    - -c
    - sleep inf
    image: busybox
    name: test
  restartPolicy: Never
  tolerations:
  - effect: NoSchedule
    key: gitlab-runner
    operator: Exists

---

apiVersion: v1
kind: Pod
metadata:
  name: testing1
spec:
  shareProcessNamespace: true
  containers:
  - command:
    - sh
    - -c
    - sleep inf
    image: busybox
    name: test
    resources:
      requests:
        cpu: 2 
  restartPolicy: Never
  tolerations:
  - effect: NoSchedule
    key: gitlab-runner
    operator: Exists

---

apiVersion: v1
kind: Pod
metadata:
  name: testing2
spec:
  shareProcessNamespace: true
  containers:
  - command:
    - sh
    - -c
    - sleep inf
    image: busybox
    name: test
    resources:
      requests:
        cpu: 2 
  restartPolicy: Never
  tolerations:
  - effect: NoSchedule
    key: gitlab-runner
    operator: Exists
```

When this is applied with the `NodePool` from the first comment in the issue it creates 3 pods on 2 nodes. Deleting the pod that shares the same node with `testing` pod leads to consolidation. 

I noticed that there is a `Nominated` event by karpenter before the pod is evicted which isn't present in my example. This goes in favor of karpenter not being one that evicted the pods, but it's also possible that I omitted these events by mistake or that it's expected for them not to be there in case there is indeed a bug in this process.
```
2m34s       Normal    Killing                pod/testing1   Stopping container test
2m10s       Normal    Nominated              pod/testing2   Pod should schedule on: nodeclaim/gitlab-runner-overflow-h5rmm, node/ip-10-1-70-12.eu-central-1.compute.internal
2m9s        Normal    Killing                pod/testing2   Stopping container test
2m9s        Normal    Evicted                pod/testing2   Evicted pod
```

I also checked the events with yaml output and it turns out that they contain the source of event. If I checked that when the issue occured I would have known for sure if karpenter evicted the pods. I guess I didn't do that because I though that if this information was available it would have been shown in table format. 

```yaml
- apiVersion: v1
  count: 2
  eventTime: null
  firstTimestamp: "2024-03-13T20:35:11Z"
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: testing2
    namespace: gitlab-runner
  kind: Event
  lastTimestamp: "2024-03-13T21:01:15Z"
  message: Evicted pod
  metadata:
    creationTimestamp: "2024-03-13T20:35:11Z"
    name: testing2.17bc6d4756d59486
    namespace: gitlab-runner
    resourceVersion: "107777692"
    uid: 87d12ea1-611b-403e-a5cf-a056ef7d9356
  reason: Evicted
  reportingComponent: karpenter
  reportingInstance: ""
  source:
    component: karpenter
  type: Normal
```

I noticed that the event message matches the one in the first comment of this issue, but that isn't enough evidence to conclude that it was karpener that evicted the pods.

I also tried the same test with `do-not-disrupt` annotation everything works correctly, i.e. no consolidation occurs. However this test isn't a good reproduction of the environment the issue occured in, and I didn't try it many times nor did I wait for long to see if a consolidation would occur.

---

After all this I don't know if we can safely conclude that the issue wasn't caused by karpenter, but as far as I'm concerned I think that setting up event exporter will be enough for me to easily investigate this issue if it were to happen again.

**Comment by gnuletik** [comment]
I've seen the same pattern occurs multiple times too.

I use the following `NodePool` config:
```
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
    expireAfter: Never
```

### What happened?

- 15:52: 2.5K pods were created in the cluster (pods are manually created, they are not part of Deployment or ReplicaSet)
- 15:52 - 15:56: many nodes were provisioned in the cluster
- 16:06: Karpenter disrupted some nodes and had to evict some pods (these pods had the `karpenter.sh/do-not-disrupt: "true"` annotation).

If I understand correctly, Karpenter should not have evicted the running pods with this configuration.

I found interesting stuff while trying to understand why Karpenter evicted the node.

### Evicted node is not displayed in controller.disruption's logger
 
When filtering Karpenter logs with `@logger:controller.disruption`, I see that some nodes are being disrupted for legitimate reason (and why they are being disrupted).

When searching by using the `node` attribute in logs I can see the following messages:
```
Date,@commit,@logger,Message
"2024-03-25T15:53:29.730Z","""8b2d1d7""","""controller.nodeclaim.lifecycle""","registered nodeclaim"
"2024-03-25T15:54:50.790Z","""8b2d1d7""","""controller.nodeclaim.lifecycle""","initialized nodeclaim"
"2024-03-25T16:05:07.215Z","""8b2d1d7""","""controller.node.termination""","tainted node"
"2024-03-25T16:06:41.273Z","""8b2d1d7""","""controller.node.termination""","deleted node"
"2024-03-25T16:06:41.273Z","""8b2d1d7""","""controller.nodeclaim.termination""","deleted nodeclaim"
```

However, when pods got evicted by Karpenter, there was no logs entry for the node where the pod was running in `@logger:controller.disruption`.

### Kubernetes events shows that the pod was started just before the disruption

- 16:04:22: Containerd event: `Container [id] started, running the image [image]`
- 16:04:26: Disruption Blocked: `Cannot disrupt Node: Pod [name] has "karpenter.sh/do-not-disrupt" annotation` (Events emitted by karpenter)
- 16:05:03: NodeNotReady: `Node [name] status is now: NodeNotReady` (events emitted by node-controller)
- 16:05:06: FailedDraining: Failed to drain node, 52 pods are waiting to be evicted (events emitted by karpenter)
- 16:05:11: Evicted pod (events emitted by karpenter)
- 16:06:45: RemovingNode: Removing [name] from Controller (events emitted by node-controller)
- 16:07:47: Our logs shows that the pod has failed

### Solutions

Is it possible that Karpenter has some kind of race condition where it doesn't see the newly created pod and disrupt the node? (maybe linked to https://github.com/aws/karpenter-provider-aws/issues/5778 ?)

Thanks!
