### ISSUE TITLE
Karpenter provisioning an additional nodeclaim for single Nginx job

### ISSUE THREAD

**Issue by dky** [aws/karpenter-provider-aws#5790]
### Description

**Observed Behavior**:

We observe `two` nodeclaims occur. 

After submitting the job to k8s we will see the first nodeclaim for a node get triggered with the job eventually landing on the 1st node then a 2nd nodeclaim gets deployed causing another EC2 instance to spawn. 

The 1st node that was provisioned gets the job scheduled on it by kube-scheduler and the 2nd node is cleaned up by disruption as there are zero pods deployed on it. 

We notice it takes about 2 minutes for the 1st node to come up followed by the 2nd, they do not run in parallel. It's almost as if the 1st nodeclaim took too long and Karpenter decided to schedule a 2nd. 

This is seen in the logging attached below. 

The only thing I could see being close to this behavior was:

https://karpenter.sh/docs/faq/#why-do-i-sometimes-see-an-extra-node-get-launched-when-updating-a-deployment-that-remains-empty-and-is-later-removed

**Expected Behavior**:

A single nodeclaim is provisioned for a job and kube-scheduler schedules job on it.

**Reproduction Steps** (Please include YAML):

### Pod Spec

```
apiVersion: v1
kind: Pod
metadata:
  name: node-toleration
spec:
  tolerations:
  - key: "nodepool"
    operator: "Equal"
    value: "default"
    effect: "NoSchedule"
  containers:
  - name: nginx-tolerates
    image: nginx
    resources:
      requests:
        memory: "3096Mi"
        cpu: "500m"
```
                                                                 
### Logs

```
{"level":"INFO","time":"2024-03-05T19:15:52.287Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"43.010182ms"}

{"level":"INFO","time":"2024-03-05T19:15:52.287Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"2c8f2a5","nodeclaims":1,"pods":1}

{"level":"INFO","time":"2024-03-05T19:15:52.309Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"2c8f2a5","nodepool":"default","nodeclaim":"default-5b9h6","requests":{"cpu":"840m","memory":"3747Mi","pods":"9"},"instance-types":"c6i.2xlarge, c6i.4xlarge, c6i.8xlarge, c6i.xlarge, c6id.2xlarge and 54 other(s)"}

{"level":"INFO","time":"2024-03-05T19:15:54.708Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"2c8f2a5","nodeclaim":"default-5b9h6","provider-id":"aws:///us-east-1a/i-abc","instance-type":"m6i.large","zone":"us-east-1a","capacity-type":"spot","allocatable":{"cpu":"1930m","ephemeral-storage":"35Gi","memory":"6903Mi","pods":"29","[vpc.amazonaws.com/pod-eni](http://vpc.amazonaws.com/pod-eni)":"9"}}

{"level":"INFO","time":"2024-03-05T19:16:02.281Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"33.656873ms"}

{"level":"INFO","time":"2024-03-05T19:16:12.268Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"19.505593ms"}

{"level":"INFO","time":"2024-03-05T19:16:22.267Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"18.183944ms"}

{"level":"INFO","time":"2024-03-05T19:16:32.279Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"29.320836ms"}

{"level":"INFO","time":"2024-03-05T19:16:42.269Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"18.515257ms"}

{"level":"INFO","time":"2024-03-05T19:16:52.270Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"18.200953ms"}

{"level":"INFO","time":"2024-03-05T19:17:02.270Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"17.512294ms"}

{"level":"INFO","time":"2024-03-05T19:17:12.272Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"19.001982ms"}

{"level":"INFO","time":"2024-03-05T19:17:22.286Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"33.087589ms"}

{"level":"INFO","time":"2024-03-05T19:17:32.274Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"20.168498ms"}

{"level":"INFO","time":"2024-03-05T19:17:42.273Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"18.881018ms"}

{"level":"INFO","time":"2024-03-05T19:17:44.731Z","logger":"controller.nodeclaim.lifecycle","message":"registered nodeclaim","commit":"2c8f2a5","nodeclaim":"default-5b9h6","provider-id":"aws:///us-east-1a/i-abc","node":"ip-127.0.0.1.ec2.internal"}

{"level":"INFO","time":"2024-03-05T19:17:52.392Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"135.777953ms"}

{"level":"INFO","time":"2024-03-05T19:17:52.392Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"2c8f2a5","nodeclaims":1,"pods":1}

{"level":"INFO","time":"2024-03-05T19:17:52.414Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"2c8f2a5","nodepool":"default","nodeclaim":"default-7kjhr","requests":{"cpu":"840m","memory":"3747Mi","pods":"9"},"instance-types":"c6i.2xlarge, c6i.4xlarge, c6i.8xlarge, c6i.xlarge, c6id.2xlarge and 54 other(s)"}

{"level":"INFO","time":"2024-03-05T19:17:55.087Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"2c8f2a5","nodeclaim":"default-7kjhr","provider-id":"aws:///us-east-1a/i-abc","instance-type":"m6i.large","zone":"us-east-1a","capacity-type":"spot","allocatable":{"cpu":"1930m","ephemeral-storage":"35Gi","memory":"6903Mi","pods":"29","[vpc.amazonaws.com/pod-eni](http://vpc.amazonaws.com/pod-eni)":"9"}}

{"level":"INFO","time":"2024-03-05T19:18:02.276Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"18.889369ms"}

{"level":"INFO","time":"2024-03-05T19:18:15.316Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"3.058642562s"}

{"level":"INFO","time":"2024-03-05T19:18:19.017Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"2c8f2a5","nodeclaim":"default-5b9h6","provider-id":"aws:///us-east-1a/i-abc","node":"ip-127.0.0.1.ec2.internal","allocatable":{"cpu":"1930m","ephemeral-storage":"1234","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"7291832Ki","pods":"29"}}

{"level":"INFO","time":"2024-03-05T19:18:22.277Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2c8f2a5","pods":"default/node-toleration","duration":"18.645421ms"}

{"level":"INFO","time":"2024-03-05T19:19:45.795Z","logger":"controller.nodeclaim.lifecycle","message":"registered nodeclaim","commit":"2c8f2a5","nodeclaim":"default-7kjhr","provider-id":"aws:///us-east-1a/i-abc","node":"ip-127.0.0.1.ec2.internal"}

{"level":"INFO","time":"2024-03-05T19:20:10.006Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"2c8f2a5","nodeclaim":"default-7kjhr","provider-id":"aws:///us-east-1a/i-abc","node":"ip-127.0.0.1.ec2.internal","allocatable":{"cpu":"1930m","ephemeral-storage":"1234","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"7291840Ki","pods":"29"}}

{"level":"INFO","time":"2024-03-05T19:20:31.608Z","logger":"controller.disruption","message":"disrupting via consolidation delete, terminating 1 nodes (0 pods) ip-127.0.0.1.ec2.internal/m6i.large/spot","commit":"2c8f2a5","command-id":"5b89c6f7-9f16-4f0e-9ab0-e89a440d1c20"}

{"level":"INFO","time":"2024-03-05T19:20:31.930Z","logger":"controller.disruption.queue","message":"command succeeded","commit":"2c8f2a5","command-id":"5b89c6f7-9f16-4f0e-9ab0-e89a440d1c20"}

{"level":"INFO","time":"2024-03-05T19:20:32.017Z","logger":"controller.node.termination","message":"tainted node","commit":"2c8f2a5","node":"ip-127.0.0.1.ec2.internal"}

{"level":"INFO","time":"2024-03-05T19:20:32.426Z","logger":"controller.node.termination","message":"deleted node","commit":"2c8f2a5","node":"ip-127.0.0.1.ec2.internal"}

{"level":"INFO","time":"2024-03-05T19:20:32.817Z","logger":"controller.nodeclaim.termination","message":"deleted nodeclaim","commit":"2c8f2a5","nodeclaim":"default-7kjhr","node":"ip-127.0.0.1.ec2.internal","provider-id":"aws:///us-east-1a/i-abc"}
```
 
### Nodepool

 ```
apiVersion: [karpenter.sh/v1beta1](http://karpenter.sh/v1beta1)
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      taints:
        - key: nodepool
          value: default
          effect: NoSchedule
      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - m6i
            - m6id
            - m6idn
            - m6in
            - c6i
            - c6id
            - c6in
            - r6i
            - r6id
            - r6idn
            - r6in
            - x2iezn
            - x2iedn
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - large
            - xlarge
            - 2xlarge
            - 4xlarge
            - 8xlarge
        - key: "[kubernetes.io/arch](http://kubernetes.io/arch)"
          operator: In
          values: ["amd64"]
        - key: "[karpenter.sh/capacity-type](http://karpenter.sh/capacity-type)"
          operator: In
          values: ["spot", "on-demand"]
```

### EC2NodeClass

```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        Type: workload
  securityGroupSelectorTerms:
    - tags:
        [karpenter.sh/discovery](http://karpenter.sh/discovery): ${var.cluster_id}
    - tags:
        Name: ${var.cluster_id}-node
  instanceProfile: "KarpenterNodeInstanceProfile-${var.cluster_id}"
  # Override the default /dev/sda so we can resize + delete it on termination
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 40Gi
        volumeType: gp3
        iops: 6000
        encrypted: false
        deleteOnTermination: true
        throughput: 500
  tags:
    [karpenter.sh/discovery](http://karpenter.sh/discovery): ${var.cluster_id}
    KarpenterProvisionerName: "default"
    NodeType: "apps-worker"
    IntentLabel: "apps"
    Backup: "false"

  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional

  userData: |
    #!/bin/bash
    set -e
    cat >> ~ec2-user/.ssh/authorized_keys <<EOF
    ssh-rsa
                abc1234
    EOF
    chmod -R go-w ~ec2-user/.ssh/authorized_keys
    chown -R ec2-user ~ec2-user/.ssh
```

**Versions**:
- Chart Version:

0.35.0 - karpenter helm chart
0.35.0 - karpenter crd 

- Kubernetes Version (`kubectl version`):

v1.27.2 for kubectl. EKS Cluster is running 1.28 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
