### ISSUE TITLE
Karpenter's node is conflict AZ with original node.

### ISSUE THREAD

**Issue by laiminhtrung1997** [aws/karpenter-provider-aws#5792]
### Description

**Observed Behavior**:
The pods are pending because they violated the topologySpreadConstraints configuration.

---

**Expected Behavior**:
The pods are running within not violate the topologySpreadConstraints configuration.

---

**Reproduction Steps** (Please include YAML):
AWS EKS Cluster with 3 worker nodes separate on 3 AZs, 2 original nodes and 1 Karpenter's node.
The original nodes type are spot. So at somepoint, 1 node is terminated and replaced by a new node. For somehow, It is placed at the AZ that already contained the Karpenter's node.
There is a deployment within 3 replicas and topologySpreadConstraints configuration below.
```
topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/name: pod-name
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
```
When the scenario above happened, 1 pod will be at state pending and cannot running.

---

**Versions**:
- Chart Version: v0.32.2
- Kubernetes Version (`kubectl version`): v1.28

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
