### ISSUE TITLE
Can't launch AL2023 nodes

### ISSUE THREAD

**Issue by bribroder** [aws/karpenter-provider-aws#5793]
### Description

**Observed Behavior**:

When my node class specifies `amiFamily: AL2023`, nodes never launch. I see demand on the provisioner and schedulable pods waiting, but I never get any new nodes.

If I change the amiFamily to `Ubuntu` or remove it so it defaults to `AL2`, nodes start up as usual

Changing it to a nonsense value gets the edit rejected by the cluster and I see AL2023 in the error message's list of valid options

**Reproduction Steps** (Please include YAML):

```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default

spec:
  amiFamily: AL2023
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 512Gi
        volumeType: gp3
        deleteOnTermination: true
```

**Versions**:
- Chart Version: karpenter-0.35.0
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Are any `NodeClaims` created? If so, could you check the providerID in the `NodeClaim` status, check that a matching instance exists in the EC2 console, and share the UserData for the EC2 instance? Could you also share Karpenter logs and your pod / nodepool specs?

**Comment by bribroder** [comment]
My EC2 Node Class shows status:                                                                                                                                                                                   ```
│   amis:
│   - id: ami-0552b3e5085247f36
│     name: amazon-eks-node-al2023-x86_64-standard-1.29-v20240227
│     requirements:
│     - key: kubernetes.io/arch
│       operator: In
│       values:
│       - amd64
│   - id: ami-0e3a77bda9dcc7add│
│     name: amazon-eks-node-al2023-arm64-standard-1.29-v20240227
│     requirements:
│     - key: kubernetes.io/arch
│       operator: In
│       values:
│       - arm64
```
(the nodeclaim uses the first one, ami-0552b3e5085247f36)

**Comment by jmdeal** [comment]
Everything here looks correct to me. Are you able to ssh / ssm into the EC2 instance? Would you be able to check the output from the nodeadm and kubelet logs?

```
sudo journalctl -u nodeadm-run
```
and 
```
sudo journalctl -u kubelet
```

**Comment by bribroder** [comment]
Some interesting stuff in the kubelet logs!
```
"Attempting to register node" node="ip-172-16-0-100.domain.com"
"Unable to register node with API server" err="nodes \"ip-172-16-0-100.domain.com\" is forbidden: node \"ip-172-16-0-100.ec2.internal\" is not allowed to modify node \"ip-172-16-0-100.domain.com\"" node="ip-172-16-0-100.domain.com"
"Eviction manager: failed to get summary stats" err="failed to get node info: node \"ip-172-16-0-100.domain.com\" not found"
Failed to contact API server when waiting for CSINode publishing: csinodes.storage.k8s.io "ip-172-16-0-100.domain.com" is forbidden: User "system:node:ip-172-16-0-100.ec2.internal" cannot getresource "csinodes" in API group "storage.k8s.io" at the cluster scope: can only access CSINode with the same name as the requesting node
```

We have a DHCP options set which specifies a custom domain name, which is where domain.com comes from

**Comment by bribroder** [comment]
Similar reports:
https://github.com/awslabs/amazon-eks-ami/issues/1263
https://github.com/awslabs/amazon-eks-ami/issues/1376
https://github.com/awslabs/amazon-eks-ami/issues/1457

**Comment by njtran** [comment]
Will close in favor of the other issue in amazon-eks-ami. Feel free to re-open if I've misunderstood.

**Comment by voltagebots** [comment]
sorry guys, i know this issue is closed.. but a quick one.. do we really need to specify a NodeConfig to use AL2023 with karpenter.. the docs says a cidr must be spcified

`An EC2NodeClass that uses AL2023 requires the cluster CIDR for launching nodes. Cluster CIDR will not be resolved for EC2NodeClass that doesn’t use AL2023.`

**Comment by jmdeal** [comment]
Cluster CIDR is resolved automatically for AL2023 NodeClasses. You don't need to supply this via UserData. That note just indicates cluster CIDR is only resolved as part of NodeClass readiness for AL2023 NodeClasses.

**Comment by george-zubrienko** [comment]
For all those like me who had this when changing node role... remember you must have node role in `aws-auth` configmap:

```
- rolearn: <node role arn>
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes
```

**Comment by alexandru-iacob** [comment]
> For all those like me who had this when changing node role... remember you must have node role in `aws-auth` configmap:
> 
> ```
> - rolearn: <node role arn>
>   username: system:node:{{EC2PrivateDNSName}}
>   groups:
>   - system:bootstrappers
>   - system:nodes
> ```

Is there. Still failing to add the node.

```
- groups:
  - system:bootstrappers
  - system:nodes
  rolearn: arn:aws-cn:iam::xxxxxxxxxx:role/xxxxxxxxx-node-role
  username: system:node:{{EC2PrivateDNSName}}
```
