### ISSUE TITLE
when using spec.instanceProfile, spec.role required error

### ISSUE THREAD

**Issue by ArturZurawski** [aws/karpenter-provider-aws#5796]
### Description

**Observed Behavior**:

When specifying `spec.instanceProfile` in EC2NodeClass got error about missing `spec.role`. 

Documentation says that:
> Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes

Error:
```
EC2NodeClass.karpenter.k8s.aws "default" is invalid: [spec.role: Required value, <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]
```

**Expected Behavior**: 

Be able to use `spec.instanceProfile`

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 0.35.0
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you show the manifests that you are trying to apply when you hit this error?

**Comment by renan-silva-bx** [comment]
Same error here. 

`cluster xxx: manifest update: failed to create resource: EC2NodeClass.karpenter.k8s.aws "m-linux-karpenter-nodepool" is invalid: [spec.role: Required value, <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]`

_apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: m-linux-karpenter-nodepool
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["m"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["medium", "large", "xlarge"]
      nodeClassRef:
        name: default
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: m-linux-karpenter-nodepool
spec:
  tags:
    managed-by-karpenter: "true"
  amiFamily: AL2 # Amazon Linux 2
  instanceProfile: "eks-xxx"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "xxx"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "xxx"_

**Comment by emilhdiaz** [comment]
I'm seeing this same error. 

NodeClass Manifest (PLACEHOLDER used for deployment specific info): 

```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "PLACEHOLDER"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "PLACEHOLDER"

  # Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  # role: "PLACEHOLDER"

  # Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  instanceProfile: "PLACEHOLDER"

  userData: |
    sudo systemctl enable amazon-ssm-agent
    sudo systemctl start amazon-ssm-agent

  tags:
    Name: "PLACEHOLDER"

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
        iops: 5000
        throughput: 125
  detailedMonitoring: true
```
