### ISSUE TITLE
Support for selecting instance types based on processor features like AMX, QAT, DSA, etc

### ISSUE THREAD

**Issue by ecerulm** [aws/karpenter-provider-aws#5797]
### Description

**What problem are you trying to solve?**

I know that my workload (PyTorch) can benefit from processors that support  [AMX (Advanced Matric Extensions)](https://en.wikipedia.org/wiki/Advanced_Matrix_Extensions). In order to do that with karpenter 0.35.0 (AFAIK) I need to manually specify all the  instance-families that I know support AMX like this

```
spec:
  template:
    spec:
      requirements:
      - key:  karpenter.k8s.aws/instance-family
        operator: In
        values:
        - m7i-flex 
        - r7i
        - xxx
        - xxx
        - xxx
 
```

I want to be able to specify something like this instead

      - key:  karpenter.k8s.aws/processor-features
        operator: In
        values: ["amx"]

I'm not sure this information is exposed via AWS API today (at least I can't find it in [InstanceType](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_InstanceTypeInfo.html), [ProcessorInfo](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ProcessorInfo.html) )  but probably people on this project know better, and there maybe other apis that expose this information. 

**How important is this feature to you?**

Eventually the manually compiled list of instance-families supporting AMX will become obsolete, so if Karpenter can compile the list itself that frees me from having to maintain that list

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
