### ISSUE TITLE
One Karpenter Node Not Upgrading to EKS Cluster Version 1.29 Automatically

### ISSUE THREAD

**Issue by assiakhateeb** [aws/karpenter-provider-aws#5899]
### Issue Description:

I'm using Karpenter version v0.33.0. When I upgraded the EKS cluster version from version 1.28 to version 1.29, nodes spawned by Karpenter upgraded to version 1.29 automatically, except for one node. This behavior is unexpected.

### Details:

- Karpenter Version: v0.33.0
- EKS Cluster Version: 1.28 (Upgraded to 1.29)
- Nodepool: 
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: nodepool-spots
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: [ "c", "m", "r", "t", "x", "a" ]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        name: ec2-node-class
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: nodepool-ondemand
spec:
  template:
    metadata:
      labels:
        nodepool: karpenter-ondemand
    spec:
      taints:
        - key: karpenter-ondemand
          value: "true"
          effect: NoSchedule    
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: [ "c", "m", "r", "t", "x", "a" ]    
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        name: ec2-node-class
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h    
```

### Steps to Reproduce:

1. Upgrade EKS cluster version from 1.28 to 1.29.
2. Observe the behavior of Karpenter-managed nodes during the upgrade process.
3. Identify any nodes that do not upgrade to the expected version.

### Expected Behavior:

All nodes managed by Karpenter should upgrade to version 1.29 after upgrading the EKS cluster from version 1.28 to 1.29.

### Actual Behavior:

One node in the nodepool did not upgrade to version 1.29 after upgrading the EKS cluster version.

**Comment by engedaam** [comment]
Can you provide the node spec?

**Comment by assiakhateeb** [comment]
@engedaam 
```
spec:
  providerID: aws:///eu-central-1a/i-01794dcb317834a12
nodeInfo:
  architecture: amd64
  bootID: 7e724296-d78e-4739-8d5b-6ef8e716b5f3
  containerRuntimeVersion: containerd://1.7.11
  kernelVersion: 5.10.210-201.852.amzn2.x86_64
  kubeProxyVersion: v1.28.5-eks-5e0fdde
  kubeletVersion: v1.28.5-eks-5e0fdde
  machineID: ec2d5a53ec9590b45b79dfd5d2e68681
  operatingSystem: linux
  osImage: Amazon Linux 2
  systemUUID: ec2d5a53-ec95-90b4-5b79-dfd5d2e68681


```
