### ISSUE TITLE
Smallest Nodepool chosen regardless of pending Pods scale

### ISSUE THREAD

**Issue by kfirsch** [aws/karpenter-provider-aws#5908]
### Description

**Observed Behavior**:
After upgrading to Karpenter 0.32 (also in 0.35) and migrating from provisioners to nodepools, we observed that our on-demand pods are not being scheduled on the most suitable node size with the lowest price. Instead, Karpenter always provision from the smallest nodepool possible, regardless of the pending pods scale, leading to suboptimal node utilization.

We use to split our provisioners into different sizes with identical weights but varying CPU and EBS sizes to accommodate the ephemeral storage requests of our pods.

**Expected Behavior**:
The scheduler should evaluate all nodepools with the same weight and select the most cost-effective node size that can accommodate all pending pods, thereby optimizing node utilization.

**Reproduction Steps** (Please include YAML):
1. Create the following nodepools with identical weights:
   - NodePool with "karpenter.k8s.aws/instance-cpu" requirements of "2" (small) with 100GB storage  
   - NodePool with "karpenter.k8s.aws/instance-cpu" requirements of "4" (medium) with 150GB storage
   - NodePool with "karpenter.k8s.aws/instance-cpu" requirements of "8" (large) with 200GB storage
2. Deploy a simple deployment with a single core request.
3. Scale the deployment to various sizes (e.g., from 1 to 10 or 40 replicas).
4. Observe that all pods are scheduled on the 'smalll' nodepool, regardless of the number of replicas.

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: small
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  template:
    spec:
      nodeClassRef:
        name: default-ec2-node-class-100gb
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - c6i
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            - '2'
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
  weight: 100
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: medium
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  template:
    spec:
      nodeClassRef:
        name: default-ec2-node-class-150gb
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - c6i
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            - '2'
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
  weight: 100
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: large
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  template:
    spec:
      nodeClassRef:
        name: default-ec2-node-class-200gb
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - c6i
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            - '8'
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
  weight: 100
```

**Versions**:
- Chart Version: 0.35.2
- Kubernetes Version:  1.26.13

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
