### ISSUE TITLE
Disruption Duration validation regex is wrong

### ISSUE THREAD

**Issue by thangle-grabtaxi** [aws/karpenter-provider-aws#5913]
### Description

**Observed Behavior**:
Unable to set Disruption Duration of value 23h55m

The validation regex set in NodePool CRD does not allow the value ([Ref](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/apis/crds/karpenter.sh_nodepools.yaml#L83))

**Expected Behavior**:
In the documentation of Karpenter, it is mentioned that Disruption Duration can be in the format 10h5m or 30m or 160h ([Ref](https://karpenter.sh/v0.35/concepts/disruption/#duration))

**Reproduction Steps** (Please include YAML):
```yaml
      disruption:
        consolidationPolicy: WhenUnderutilized
        expireAfter: Never
        budgets:
          - nodes: "0"
            schedule: "5 7 * * *"
            duration: "23h55m"
          - nodes: "1"
```

**Versions**:
- Chart Version: 0.35.2
- Kubernetes Version (`kubectl version`): 1.25.15

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
