### ISSUE TITLE
Support m -> n consolidation actions

### ISSUE THREAD

**Issue by michaelswierszcz** [aws/karpenter-provider-aws#5944]
### Description

**Observed Behavior**:
Karpenter does not seem to make very intellegent choices on how to provision node classes. It seems to just select the cheapest choice without understanding cluster wide imbalances. In my case, Karpenter selects many c7i.24xlarge, occasionaly choosing c7i.48large. It has no interest in the r7i's and m7i's because they are more expensive? As my cluster scales, the imbalance between cluster cpu utilization (70%~) and memory utilization (95%) grows larger. This means im wasting almost 30% of my cluster cpu which is actually the more expensive component of ec2's vs the memory.

**Expected Behavior**:

Karpenter to scale intelligently, using all available instance-family types to maintain a healthy cpu vs memory utilization ratio.

For example it may realize it should scale 3 c7i's down to 2 r7i's, saving $

**Reproduction Steps** (Please include YAML):

```
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: dev-48s
spec:
  providerRef:
    name: eks129
  consolidation:
    enabled: true
  weight: 9
  labels:
    provisioner: m7is
  requirements:
    - key: "karpenter.k8s.aws/instance-family"
      operator: In
      values: ["c7i", "r7i", "m7i",]
    - key: "karpenter.k8s.aws/instance-size"
      operator: In
      values: ["24xlarge", "48xlarge",]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d", "us-east-1f",]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
  kubeletConfiguration:
    maxPods: 250
  limits:
    resources:
      cpu: "17280"
```

**Versions**:
- Chart Version: 0.32.4
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
