### ISSUE TITLE
AMI selector across architectures and GPUs

### ISSUE THREAD

**Issue by cep21** [aws/karpenter-provider-aws#5959]
### Description

**What problem are you trying to solve?**

I want karpenter to pick the AMI my nodepool should use.  We have lots of node types (arm, x86, GPUs, etc) so we cannot just hard code the AMI to use.

Karpenter does a good job finding which AMI to use based upon the node details, but we recently ran into issue https://github.com/awslabs/amazon-eks-ami/issues/1744 which completely broke our GPU nodes.

We now understand how important it is to pin AMIs, but the problem is not trivial because we have no way of saying "Pin to this if a GPU node, pin to this if a x86 CPU node, pin to this if a ARM node, Pin to this if a Linux node, etc etc"

The alternative is to use a different nodeclass and nodepool for each AMI type we need to spin up, but this is a very large set.

The ideal situation is for me to "snapshot" the logic karpenter would use to pick the AMI it wants, and then promote that list.  That way I can continue to leverage the karpenter team's work of picking the correct AMI, but also promote and test AMI updates.

**How important is this feature to you?**

It would have prevented a p0 site outage.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by cep21** [comment]
As an alternative to this ticket, if there was an AMI selector for "AMI must be created before date X", then we could select on that and promote that date "X" across our clusters, testing fully in staging before production.

**Comment by engedaam** [comment]
cc: @njtran

**Comment by njtran** [comment]
We've heard about selecting by AMI age. There's a bit of hidden problems within this, particularly with roll-forward patches and time-bombs. Giving a time knob to know when to upgrade requires being aware of when AMIs are released. If you need more time, such as for holidays or days where you can't release changes, you have to continually change this knob.

Realistically, the optimal way to handle AMI rollouts is to test changes in your lowest environments, automatically upgrading there, and pin/promote AMIs in your production environments when you're ready.

What is the way you were hoping to promote AMIs if not through Tags or setting the AMI ID in the EC2NodeClass?

**Comment by cep21** [comment]
> We've heard about selecting by AMI age. 

I'm not proposing promoting by age.  I'm proposing promoting by creation date.  Can you describe how this becomes a time bomb?

**Comment by cep21** [comment]
> pin/promote AMIs in your production environments when you're ready

Karpenter does not have a way to pin gpu Ami's to one thing and cpu Ami's to another without 4xing the number of node pool x instance class combinations I have.

**Comment by njtran** [comment]
> I'm not proposing promoting by age. I'm proposing promoting by creation date. Can you describe how this becomes a time bomb?

Ah my apologies, I misread. I thought you meant you'd expose this as a duration from the current time as a sliding window. So would you be hoping to use the oldest image that was created after the given creation timestamp? We'd have to change our AMISelection logic for this, as we currently just use the newest AMI out of the AMIs that match the constraints given.

**Comment by cep21** [comment]
> So would you be hoping to use the oldest image that was created after the given creation timestamp? 

Yes.  I'm unsure if the SSM API you use will allow you to search by creation date.

The code may look like this, and I would maybe do a weekly promotion of the `after` date.
```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - after: 1712594365
```

This is also a good alternative (Notice I just moved the "status" fields into the spec itself)

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amis:
    - id: ami-01234567890123456
      name: custom-ami-amd64
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
    - id: ami-01234567890123456
      name: custom-ami-arm64
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64
```
