### ISSUE TITLE
Containerd nondeterministic misconfiguration on a GPU nodes

### ISSUE THREAD

**Issue by jan-skarupa** [aws/karpenter-provider-aws#5974]
### Description

**Observed Behavior**:

Hi. Our team has an EKS cluster and uses Karpenter to provision GPU nodes (g4dn type) to process some ML workloads. One pod always requests a full GPU unit. Sometimes, the pod gets stuck in a pending state because the provisioned node has the `nvidia-device-plugin` pod in a CrashLoopBackOff and never receives GPU labels. It happens randomly, and when we manually delete the bad node, Karpenter provisions a new one (which usually works), the pod gets scheduled, and all is fine.

Here is the device plugin log:
```
[main.go:154] Starting FS watcher.
[main.go:123] error starting plugins: error creating plugin manager: unable to create plugin manager: platform detection failed
[factory.go:119] If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
[factory.go:118] You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
[factory.go:117] You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
[factory.go:116] If this is a GPU node, did you configure the NVIDIA Container Toolkit?
[factory.go:115] Incompatible platform detected
[factory.go:107] Detected non-Tegra platform: /sys/devices/soc0/family file not found
[factory.go:107] Detected non-NVML platform: could not load NVML library: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
[factory.go:31] No valid resources detected, creating a null CDI handler
```

I sshed into the node and verified an NVIDIA GPU with working drivers is available. I looked for the `libnvidia-ml.so` and found it only on the host filesystem. All working GPU nodes have it in the hosted containers, too.

I checked the containerd config at `/etc/containerd/config.toml` and found that the bad node does not use nvidida runtime plugin. Despite using the same AMI `ami-0893c31d2e4091165`, it was configured like this:

```
version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
imports = ["/etc/containerd/config.d/*.toml"]


[grpc]
address = "/run/containerd/containerd.sock"

[plugins."io.containerd.grpc.v1.cri".containerd]
default_runtime_name = "runc"
discard_unpacked_layers = true

[plugins."io.containerd.grpc.v1.cri"]
sandbox_image = "602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.5"

[plugins."io.containerd.grpc.v1.cri".registry]
config_path = "/etc/containerd/certs.d:/etc/docker/certs.d"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
SystemdCgroup = true

[plugins."io.containerd.grpc.v1.cri".cni]
bin_dir = "/opt/cni/bin"
conf_dir = "/etc/cni/net.d"
```

All working nodes have `default_runtime_name = "nvidia"`. I will post the full config below.

When I copied the config from the working node to the bad one and restarted the containerd service, the node started behaving as expected and was able to process our ML workload.

I assume the Karpenter does some additional configuration, but I am unable to explore this as the launch templates seem to get deleted once the provisioning is done. So my question is, how can it happen, that the node gets a different containerd config? How can I debug or fix this? 

**Expected Behavior**:

All GPU nodes use Nvidia container runtime, and `nvidia-device-plugin` runs successfully on them.

**Reproduction Steps** (Please include YAML):

I cannot reproduce the problem at this time. I estimate it happens once for every 200 nodes that are successfully provisioned.

**Versions**:
- Chart Version: public.ecr.aws/karpenter/karpenter:v0.33.1
- Kubernetes Version: v1.28.6-eks-508b6b3
- Nvidia Device Plugin Chart Version: 0.14.3
- AMI used on all nodes: ami-0893c31d2e4091165

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jan-skarupa** [comment]
Here are some more details.

Containerd config in our working nodes looks like this:
```
imports = ["/etc/containerd/config.d/*.toml"]
root = "/var/lib/containerd"
state = "/run/containerd"
version = 2

[grpc]
  address = "/run/containerd/containerd.sock"

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.5"

    [plugins."io.containerd.grpc.v1.cri".cni]
      bin_dir = "/opt/cni/bin"
      conf_dir = "/etc/cni/net.d"

    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "nvidia"
      discard_unpacked_layers = true

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/bin/nvidia-container-runtime"
            SystemdCgroup = true

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true

    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d:/etc/docker/certs.d"
```


NVIDIA device plugin is installed with Terraform:
```
resource "helm_release" "this" {
  name             = "${var.name}-${var.env}"
  repository       = "https://nvidia.github.io/k8s-device-plugin"
  chart            = "nvidia-device-plugin"
  version          = "0.14.3"
  namespace        = "nvidia-device-plugin"
  create_namespace = true

  atomic  = true
  timeout = 900

  set {
    name  = "gfd.enabled"
    value = "true"
  }
}
```


Karpenter node config:
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{ .Values.name }}-*--eks-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{ .Values.name }}-*--eks-cluster"
  role: "KarpenterNodeRole-{{ .Values.name }}-{{ .Values.env }}--eks-cluster"
  tags:
    Application: {{ .Values.app }}
    Environment: "{{ .Values.env }}"
    Owner: AI
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        volumeSize: 85Gi
        volumeType: gp3
  detailedMonitoring: false
```

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: spot
spec:
  template:
    metadata:
      labels:
      	<internal labels only>
    spec:
      nodeClassRef:
        name: gpu
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["g4dn.xlarge", "g4dn.2xlarge", "g4dn.4xlarge"]
      taints:
        - key: "nvidia.com/gpu"
          value: "present"
          effect: NoSchedule
  weight: 70
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1m
    expireAfter: Never
```

Karpenter itself has a default configuration.
