### ISSUE TITLE
no instance type satisfied resources

### ISSUE THREAD

**Issue by galshmil** [aws/karpenter-provider-aws#5975]
### Description

**Observed Behavior**:

On "rush hours", pods are stuck on pending waiting on a specific provisioner with the following error:

`ERROR controller.provisioner Could not schedule pod, incompatible with provisioner "main", daemonset overhead={"cpu":"990m","memory":"1016Mi","pods":"7"}, incompatible requirements, label "provisioner" does not have known values (typo of "karpenter.sh/provisioner-name"?); incompatible with provisioner "spark", daemonset overhead={"cpu":"840m","memory":"1072Mi","pods":"7"}, did not tolerate spark=yes:NoSchedule; incompatible with provisioner "cron", daemonset overhead={"cpu":"790m","memory":"816Mi","pods":"6"}, no instance type satisfied resources {"cpu":"5790m","memory":"46691Mi","pods":"7"} and requirements karpenter.k8s.aws/instance-category In [c d g i m and 4 others], karpenter.k8s.aws/instance-generation Exists >2, karpenter.sh/capacity-type In [on-demand spot], karpenter.sh/provisioner-name In [cron], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], provisioner In [cron] (no instance type has enough resources); incompatible with provisioner "DEDUCTED", daemonset overhead={"cpu":"790m","memory":"816Mi","pods":"6"}, did not tolerate provisioner=DEDUCTED:NoSchedule {"commit": "709030d", "pod": "DEDUCTED"}`

Specifically assigning them to `cron` provisioner, resulting in `no instance type has enough resources` at times where the provisioner is working the most.
Important to say, throughout the day the provisioner works as intended.

**Expected Behavior**:

Pods to be successfully assigned to `cron` provisioner.

**Reproduction Steps** (Please include YAML):

Currently problematic for me to reproduce, as this happens at night-time, which is the time the cluster is most busiest.
Seems like the provisioner is working as intended throughout the day though.

Attaching provisioner manifest:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: cron
spec:
  providerRef:
    name: main
  labels:
    provisioner: "cron"
  taints:
    - key: provisioner
      value: "cron"
      effect: NoSchedule
  requirements:
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["c", "d", "g", "i", "m", "p", "r", "x", "z"]
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ["2"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand", "spot"]
  limits:
    resources:
      cpu: 1500
      memory: 4300Gi
      nvidia.com/gpu: 16
  ttlSecondsAfterEmpty: 300
```

And NodeTemplate manifest:
```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: main
spec:
  subnetSelector:
    karpenter.sh/discovery: DEDUCTED
  securityGroupSelector:
    karpenter.sh/discovery: DEDUCTED
  userData: |
    #!/bin/bash
    # adding update to netfilter to not limit connections
    sysctl -w net.netfilter.nf_conntrack_tcp_be_liberal=1
  tags:
    Name: DEDUCTED
    Type: karpenter_compute
  blockDeviceMappings:
    # Root device
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 80Gi
        volumeType: gp3
        encrypted: true
status:
  subnets:
    - id: DEDUCTED
      zone: ca-central-1a
  securityGroups:
    - id: DEDUCTED
      name: DEDUCTED
  amis:
    - id: ami-00030d0aa2a4cc544
      name: amazon-eks-node-1.26-v20240117
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-gpu-count
          operator: DoesNotExist
        - key: karpenter.k8s.aws/instance-accelerator-count
          operator: DoesNotExist

```

**Versions**:
- Chart Version: v0.31.2
- Kubernetes Version (`kubectl version`): 1.26

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
We've made this log better in more recent versions. Can you share more info about the pod you're trying to schedule?

**Comment by galshmil** [comment]
> We've made this log better in more recent versions. Can you share more info about the pod you're trying to schedule?

So basically it's SparkApplications, both controllers and execs.
They do seem to work after the period of the "rush hour", as well as normally throughout the day.
I've also opened a ticket to AWS to check if it might be some limitations/quotas from their side.

Here's an example for one:
```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  generateName: DEDUCTED
  labels:
    repo: DEDUCTED
    spark_job: DEDUCTED
    team: DEDUCTED
  namespace: DEDUCTED
spec:
  arguments:
    - DEDUCTED
    - DEDUCTED
    - DEDUCTED
    - DEDUCTED
  driver:
    annotations:
      karpenter.sh/do-not-evict: "true"
    env:
      - name: DEDUCTED
        valueFrom:
          secretKeyRef:
            key: DEDUCTED
            name: DEDUCTED
      - name: DEDUCTED
        valueFrom:
          secretKeyRef:
            key: DEDUCTED
            name: DEDUCTED
      - name: PYSPARK_MAJOR_PYTHON_VERSION
        value: "3"
      - name: SPARK_CLASSPATH
        value: /opt/spark/jars/*:/opt/spark/jars
      - name: DEDUCTED
        value: DEDUCTED
      - name: EXECUTORS
        value: "2"
      - name: CORES_PER_EXECUTOR
        value: "5"
      - name: EXECUTOR_TASKS
        value: "5"
    javaOptions: -Dlog4j.configuration=file:///opt/spark/work-dir/log4j.properties
    labels:
      is_test: "true"
      version: 3.0.0
    memory: 8g
    nodeSelector:
      karpenter.sh/capacity-type: on-demand
      provisioner: cron
    podSecurityContext:
      fsGroup: 185
    serviceAccount: spark-operator
    tolerations:
      - effect: NoSchedule
        key: provisioner
        operator: Equal
        value: cron
  executor:
    annotations:
      karpenter.sh/do-not-evict: "true"
    cores: 5
    envVars:
      PYSPARK_MAJOR_PYTHON_VERSION: "3"
      DEDUCTED: DEDUCTED
      SPARK_CLASSPATH: /opt/spark/jars/*:/opt/spark/jars
    instances: 2
    javaOptions: -Dlog4j.configuration=file:///opt/spark/work-dir/log4j.properties
    labels:
      is_test: "true"
      version: 3.0.0
    memory: 32g
    nodeSelector:
      provisioner: cron
    podSecurityContext:
      fsGroup: 185
    tolerations:
      - effect: NoSchedule
        key: provisioner
        operator: Equal
        value: cron
  hadoopConf:
    fs.s3a.committer.magic.enabled: "true"
    fs.s3a.committer.name: magic
    fs.s3a.committer.staging.abort.pending.uploads: "true"
    mapreduce.outputcommitter.factory.scheme.s3a: org.apache.hadoop.fs.s3a.commit.S3ACommitterFactory
  image: DEDUCTED
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/work-dir/src/jobs/split_raw_by_org.py
  mode: cluster
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    metricsPropertiesFile: /etc/metrics/conf/metrics.properties
    prometheus:
      configFile: /etc/metrics/conf/prometheus.yaml
      jmxExporterJar: /opt/spark/jars/jmx_prometheus_javaagent-0.20.0.jar
      port: 8090
  pythonVersion: "3"
  restartPolicy:
    onFailureRetries: 0
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
    type: OnFailure
  sparkConf:
    spark.app.name: split-raw-by-org
    spark.default.parallelism: "400"
    spark.delta.logStore.class: org.apache.spark.sql.delta.storage.S3SingleDriverLogStore
    spark.driver.extraJavaOptions: -Duser.timezone=UTC
    spark.executor.extraJavaOptions: -Duser.timezone=UTC
    spark.hadoop.fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
    spark.hadoop.fs.s3a.fast.upload: "true"
    spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.kubernetes.authenticate.driver.serviceAccountName: spark-operator
    spark.kubernetes.driver.service.deleteOnTermination: "true"
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-1.mount.path: /scratch
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-1.mount.readOnly: "false"
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-1.options.claimName: OnDemand
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-1.options.sizeLimit: 100Gi
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-1.options.storageClass: ebs-sc
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.mount.path: /scratch
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.mount.readOnly: "false"
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.claimName: OnDemand
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.sizeLimit: 150Gi
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.storageClass: ebs-sc
    spark.local.dir: /scratch
    spark.scheduler.allocation.file: /opt/spark/fair-scheduler.xml
    spark.scheduler.mode: fair
    spark.sql.broadcastTimeout: "900"
    spark.sql.catalog.spark_catalog: org.apache.spark.sql.delta.catalog.DeltaCatalog
    spark.sql.extensions: io.delta.sql.DeltaSparkSessionExtension
    spark.sql.files.maxPartitionBytes: "67108864"
    spark.sql.parquet.output.committer.class: org.apache.spark.internal.io.cloud.BindingParquetOutputCommitter
    spark.sql.shuffle.partitions: "400"
    spark.sql.sources.commitProtocolClass: org.apache.spark.internal.io.cloud.PathOutputCommitProtocol
    spark.sql.sources.partitionOverwriteMode: dynamic
  sparkVersion: 3.0.0
  timeToLiveSeconds: 3600
  type: Python
```

**Comment by jonathan-innis** [comment]
> Important to say, throughout the day the provisioner works as intended

Do you know if you are anywhere near your Provisioner limits when Karpenter is scaling up nodes for these pods. I see you have these limits listed so it'd be important to track-down what the active count of resources is while we are doing the scale-up behavior

```yaml
  limits:
    resources:
      cpu: 1500
      memory: 4300Gi
      nvidia.com/gpu: 16
```

The other thing that would be good to see would be logs that occurred just before you are seeing these errors. The biggest question is: Are you seeing any ICE (Insufficient Capacity Errors) right before you are seeing this message that might restrict the number of available instance types that Karpenter is aware of.
