### ISSUE TITLE
Priority of instanceStorePolicy: RAID0 on AL2023

### ISSUE THREAD

**Issue by dntosas** [aws/karpenter-provider-aws#5981]
### Description

Hello team!

Started testing AL2023 with the option `instanceStorePolicy: RAID0`. While this option creates as expected the mount `/mnt/k8s-disks/0/` , this seems to be create after running the provided `userData`. As a result, we can't run commands against this path until created. Any ideas how to overcome this or merge it in appropriate order?

Example config with storePolicy + userData:
```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: test
spec:
  amiFamily: AL2023
  instanceProfile: XXX
  instanceStorePolicy: RAID0
  userData: >
    MIME-Version: 1.0

    Content-Type: multipart/mixed; boundary="==EC2INIT=="

    --==EC2INIT==

    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    NVM_PATH="/mnt/k8s-disks/0"
    if [[ -d "$NVM_PATH" ]]; then
      mkdir $NVM_PATH/test_directory
    fi
    --==EC2INIT==
 ```

**Observed Behavior**:
mount `/mnt/k8s-disks/0/` is created after the userData script is running thus we can't utilize it for running arbitrary commands.

**Expected Behavior**:
userData script to create directory on the new mounted RAID0 volume

**Reproduction Steps** (Please include YAML):
attached above ^

**Versions**:
- Chart Version: 0.35.4
- Kubernetes Version (`kubectl version`): 1.28
