### ISSUE TITLE
Karpenter metrics drop with prometheus scraper

### ISSUE THREAD

**Issue by victor-smg** [aws/karpenter-provider-aws#6013]
### Description

**Observed Behavior**:
I observed drop of metrics without any clear reason, it seems to only be for some metrics but not all.
For example `karpenter_nodes_allocatable` will just not be available anymore, while other like `karpenter_build_info` are still present.
It seems to be at metric production level, as prometheus scraping metrics is otherwise working fine.

**Expected Behavior**:
Metrics should be stable.

**Reproduction Steps** (Please include YAML):
EKS is on 1.29
Karpenter is on 0.35.4
Prometheus is on 22.7.0, it is scraping with a static configuration:
```
- job_name: karpenter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - karpenter.karpenter.svc.cluster.local:8000
```

I can also try to query the metrics url manually, and I see Karpenter is not producing some metrics but working for some:
```
wget karpenter.karpenter.svc.cluster.local:8000/metrics
cat metrics | grep karpenter_node_allocation | wc -l
0
cat metrics | grep karpenter_pods_state | wc -l
327
```
We can also see that the sync witht he cluster is fine: `karpenter_cluster_state_synced 1`

**Versions**:
- Chart Version: 0.35.4
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
