### ISSUE TITLE
On-Demand/Spot Ratio Split Behaviour

### ISSUE THREAD

**Issue by hitsub2** [aws/karpenter-provider-aws#6023]
### Description

**What problem are you trying to solve?**
Followed [this doc](https://karpenter.sh/docs/concepts/scheduling/#on-demandspot-ratio-split), we can acheive the desired ratio. But we have a question, what if we configure the two nodepool as follows with both refer to spot or demand, what's the behaviour of Karpenter?

In our own testing, it seems the ratio nearly equal to 1:1. So wants to know what's the behaviour for this scenario.

node-pool.yaml
```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: spot
spec:
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      - key: capacity-spread
        operator: In
        values:
        - "1"
        - "2"
        - "3"
        - "4"
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: on-demand
spec:
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["arm64"]
      - key: capacity-spread
        operator: In
        values:
        - "5"
```

application.yaml
```yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mars-app
  name: deployment-mars-api-m
  labels:
    app: mars-api-m
    version: v1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-mars-api-m
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-mars-api-m
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              #app.kubernetes.io/name: app-gaianet-portal-hub-beat
              app.kubernetes.io/name: app-mars-api-m
          minDomains: 1
        - maxSkew: 1
          topologyKey: capacity-spread
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              #app.kubernetes.io/name: app-gaianet-portal-hub-beat
              app.kubernetes.io/name: app-mars-api-m
          minDomains: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - app-mars-api-m
            topologyKey: kubernetes.io/hostname
      containers:
      - name: web-app
        image: nginx:latest

```

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
