### ISSUE TITLE
ERROR: Karpenter not authorized to perform: iam:PassRole

### ISSUE THREAD

**Issue by ricardorqr** [aws/karpenter-provider-aws#6036]
### Description

Hi everyone,

For some reason, I'm having the **ERROR** below after deploy KArpenter 0.36.0. I have deployed it using Heml and provisioned the EKS using Terraform.
```json
{"level":"ERROR","time":"2024-04-13T19:32:06.637Z","logger":"controller","message":"Reconciler error","commit":"6b868db","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"57ebead8-6c58-4b09-9258-a71d1e8eff32","error":"creating instance profile, adding role \"eks-devopsv2-rico-karpeter-role\" to instance profile \"eks-devopsv2-rico_4067990795380418201\", AccessDenied: User: arn:aws:sts::495633144232:assumed-role/eks-devopsv2-rico-karpeter-controller-role/1713036559589181010 is not authorized to perform: iam:PassRole on resource: arn:aws:iam::495633144232:role/eks-devopsv2-rico-karpeter-role because no identity-based policy allows the iam:PassRole action\n\tstatus code: 403, request id: 9d87922d-b025-47f1-a0ad-6972c5ddfd8f"}
```
This is my Karpenter controller node Trusted Relationship. I added it using this [Karpenter Terraform module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/karpenter).

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "pods.eks.amazonaws.com"
            },
            "Action": [
                "sts:TagSession",
                "sts:AssumeRole"
            ]
        },
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::99999:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/90B602A5431QWEC2B5C23B12AE76BDB2"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-west-2.amazonaws.com/id/90B602A5431QWEC2B5C23B12AE76BDB2:sub": "system:serviceaccount:karpenter:karpenter",
                    "oidc.eks.us-west-2.amazonaws.com/id/90B602A5431QWEC2B5C23B12AE76BDB2:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```
And here is the policy. It has the action `iam:PassRole`. 
```json
...
"Action": "iam:PassRole",
"Condition": {
    "StringEquals": {
        "iam:PassedToService": "ec2.amazonaws.com"
    }
},
"Effect": "Allow",
"Resource": "arn:aws:iam::99999:role/eks-devopsv2-rico-karpeter-node-role",
"Sid": "AllowPassingInstanceRole"
...
```
The [documentation](https://karpenter.sh/docs/getting-started/migrating-from-cas/#create-iam-roles) says to use the following. The condition added by the TF would not be the problem. I tested removing this condition from the policy, but it didn't work.
```json
...
{
    "Effect": "Allow",
    "Action": "iam:PassRole",
    "Resource": "arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/KarpenterNodeRole-${CLUSTER_NAME}",
    "Sid": "PassNodeIAMRole"
},
...
```
What am I missing?

**Versions**:
- Chart Version: 0.36.0
- Kubernetes Version (`kubectl version`): 
```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8-eks-adc7111
```

**Comment by jigisha620** [comment]
The permissions look right to me. Would you mind sharing your EC2NodeClass configuration?

**Comment by ricardorqr** [comment]
Yeah, here are both configurations.
```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: '13281206547058169321'
    karpenter.k8s.aws/ec2nodeclass-hash-version: v2
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"karpenter.k8s.aws/v1beta1","kind":"EC2NodeClass","metadata":{"annotations":{},"name":"default"},"spec":{"amiFamily":"AL2","role":"eks-devopsv2-rico-karpeter-role","securityGroupSelectorTerms":[{"tags":{"karpenter.sh/discovery":"eks-devopsv2-rico"}}],"subnetSelectorTerms":[{"tags":{"karpenter.sh/discovery":"eks-devopsv2-rico"}}]}}
  creationTimestamp: '2024-04-13T19:21:55Z'
  finalizers:
    - karpenter.k8s.aws/termination
  generation: 1
status:
  amis:
    - id: ami-026becccb3631b25c
      name: amazon-eks-arm64-node-1.28-v20240409
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64
        - key: karpenter.k8s.aws/instance-gpu-count
          operator: DoesNotExist
        - key: karpenter.k8s.aws/instance-accelerator-count
          operator: DoesNotExist
    - id: ami-0b3811b92199f18d0
      name: amazon-eks-gpu-node-1.28-v20240409
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-gpu-count
          operator: Exists
    - id: ami-0b3811b92199f18d0
      name: amazon-eks-gpu-node-1.28-v20240409
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-accelerator-count
          operator: Exists
    - id: ami-0ada1450d8fc74d61
      name: amazon-eks-node-1.28-v20240409
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-gpu-count
          operator: DoesNotExist
        - key: karpenter.k8s.aws/instance-accelerator-count
          operator: DoesNotExist
  securityGroups:
    - id: sg-026e88ac735ce968c
      name: eks-cluster-sg-eks-devopsv2-rico-810130231
    - id: sg-05593f971b4ea27bc
      name: eks-devopsv2-rico-cluster
    - id: sg-0fee4b852fc218a80
      name: eks-devopsv2-rico-node
  subnets:
    - id: subnet-074c1a5c1108988c8
      zone: us-west-2b
    - id: subnet-0b5b47cc16bc5e440
      zone: us-west-2c
    - id: subnet-0875530f4d38387b0
      zone: us-west-2a
spec:
  amiFamily: AL2
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: eks-devopsv2-rico-karpeter-role
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-devopsv2-rico
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-devopsv2-rico

  YAML
```
```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: '15093649574832938182'
    karpenter.sh/nodepool-hash-version: v2
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"karpenter.sh/v1beta1","kind":"NodePool","metadata":{"annotations":{},"name":"default"},"spec":{"disruption":{"consolidationPolicy":"WhenUnderutilized","expireAfter":"720h"},"limits":{"cpu":1000},"template":{"spec":{"nodeClassRef":{"apiVersion":"karpenter.k8s.aws/v1beta1","kind":"EC2NodeClass","name":"default"},"requirements":[{"key":"kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"kubernetes.io/os","operator":"In","values":["linux"]},{"key":"karpenter.sh/capacity-type","operator":"In","values":["spot"]},{"key":"karpenter.k8s.aws/instance-category","operator":"In","values":["c","m","r"]},{"key":"karpenter.k8s.aws/instance-generation","operator":"Gt","values":["2"]}]}}}}
  creationTimestamp: '2024-04-13T19:21:55Z'
  generation: 1
  name: default
  resourceVersion: '2188'
  uid: 98aabfb1-8e40-4a9d-9737-8045dfbdc000
  selfLink: /apis/karpenter.sh/v1beta1/nodepools/default
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  limits:
    cpu: 1000
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - c
            - m
            - r
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - '2'

```
