### ISSUE TITLE
What is the best way to upgrade EKS versions when pinning AMIs?

### ISSUE THREAD

**Issue by mrparkers** [aws/karpenter-provider-aws#6050]
### Description

**Context**:
In the past, our Karpenter configuration utilized `EC2NodeClass` objects that set `.spec.amiFamily` to `AL2`, which allowed Karpenter to automatically select the latest appropriate AMI for our Kubernetes nodes.  Since we're currently on EKS 1.27, this would select `amazon-eks-gpu-node-1.27-v20240409` for GPU nodes, `amazon-eks-arm64-node-1.27-v20240409` for ARM nodes, and `amazon-eks-node-1.27-v20240409` for everything else.

However, recently the EKS team published a bad AMI that was affected by a bug that caused GPU nodes to not start correctly (https://github.com/awslabs/amazon-eks-ami/issues/1744).  Karpenter automatically upgraded all of our clusters to use this AMI, causing a production outage for GPU workloads.  So we have decided that this behavior of automatically upgrading AMIs is no longer acceptable for a production environment.

Now, we have a specific `EC2NodeClass` that is referenced by a `NodePool` that provisions GPU nodes within the `g4` and `g5` instance families.  It looks something like this:

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu-pinned-ami
spec:
  amiSelectorTerms:
    - name: "amazon-eks-gpu-node-1.27-v20240315"
  instanceStorePolicy: RAID0
  role: staging-node-instance-role
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  tags:
    datadog: monitored
    karpenter.sh/discovery: staging
```

This works for now, but we are starting to upgrade to EKS 1.28, and we don't understand how to correctly do this when we're pinning AMI versions.

**Observed Behavior**:
We have tried two different configurations, both of which behaved differently than I expected.

First, we tried using a wildcard to represent the EKS version:

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu-pinned-ami
spec:
  amiSelectorTerms:
    - name: "amazon-eks-gpu-node-*-v20240315"
  instanceStorePolicy: RAID0
  role: staging-node-instance-role
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  tags:
    datadog: monitored
    karpenter.sh/discovery: staging
```

I expected Karpenter to understand that its running within a 1.27 cluster, and thus to prefer AMIs that use that version.  The idea here being that, after upgrading to 1.28, Karpenter would see this and start selecting the 1.28 AMIs instead.  However, this configuration resulted in nodes using a 1.26 AMI within a 1.27 cluster.

In the second attempt, we tried to explicitly list the two acceptable AMIs:

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu-pinned-ami
spec:
  amiSelectorTerms:
    - name: "amazon-eks-gpu-node-1.27-v20240315"
    - name: "amazon-eks-gpu-node-1.28-v20240315"
  instanceStorePolicy: RAID0
  role: staging-node-instance-role
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  tags:
    datadog: monitored
    karpenter.sh/discovery: staging
```

In this case, I expected Karpenter again to understand that it is currently running within a 1.27 cluster, and to select the 1.27 AMI, then switch to the 1.28 AMI after the EKS control plane upgrade is complete.  But in this case, Karpented selected a 1.28 AMI even though we were running a 1.27 cluster.

**Expected Behavior**:
In both cases, Karpenter seems to prefer selecting AMIs that are using Kubernetes versions that are different than the version we're actually running.  It's possible that this is truly random and I'm just getting unlucky with this configuration, but I expected a little bit more intelligence here when the `amiSelectorTerms` results in multiple matches.

**Reproduction Steps** (Please include YAML): See the observed behavior section

**Questions**:
How are users expected to perform an EKS upgrade when they're pinning AMI versions?  Should we be creating multiple `EC2NodeClass` objects, and thus duplicate this configuration plus the configuration of every `NodePool` that references it?

Are there some controls that I'm missing here?

Could we perhaps have some sort of variable that we could use within `amiSelectorTerms` that can be substituted for the EKS version at runtime?

**Versions**:
- Chart Version: 0.36.0
- Kubernetes Version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:48Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.11-eks-b9c9ed7", GitCommit:"f19f83c16ca534237fbfb65bc580d51752b98c91", GitTreeState:"clean", BuildDate:"2024-03-02T03:46:53Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/amd64"}
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
