### ISSUE TITLE
EC2NodeClass Validation Doesn't detect malformed blockDeviceMappings.ebs.volumeSize value

### ISSUE THREAD

**Issue by vitaly-dt** [aws/karpenter-provider-aws#6055]
### Description

**Observed Behavior**:
Please notice the below `EC2NodeClass` is invalid.
The issue is: `blockDeviceMappings.ebs.volumeSize` is `80` Instead of `80Gi`
I got the following VERY NOT INFORMATIVE error in Karpenter logs, with debug flag turned on:
```
{"level":"ERROR","time":"2024-04-18T07:53:19.935Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool...(no instance type has enough resources)
```
Applying the following EC2NodeClass is successful:
``` yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  annotations:
    kubernetes.io/description: "General purpose EC2NodeClass for running Amazon Linux 2 nodes"
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "KarpenterNodeRole-${CLUSTER_NAME}" # replace with your cluster name
  blockDeviceMappings: # Disk size
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 80
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
```

**Expected Behavior**:
Karpenter CRD will throw an error on the blockDeviceMappings.ebs.volumeSize value.

**Reproduction Steps** (Please include YAML):
Apply the above `EC2NodeClass`

**Versions**:
- Chart Version: 0.36.0
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
