### ISSUE TITLE
Better documentation for NodePool "Exists" operator

### ISSUE THREAD

**Issue by Nuru** [aws/karpenter-provider-aws#6058]
The Scheduling documentation [for v0.36.0](https://github.com/aws/karpenter-provider-aws/blob/main/website/content/en/v0.36/concepts/scheduling.md) says in part:

> The Exists operator can be used on a NodePool to provide workload segregation across nodes.
> 
> With the requirement on the NodePool, workloads can optionally specify a custom value as a required node affinity or node selector. Karpenter will then label the nodes it launches for these pods which prevents `kube-scheduler` from scheduling conflicting pods to those nodes. This provides a way to more dynamically isolate workloads without requiring a unique NodePool for each workload subset.

I would like elaboration on this topic. 

First, marking a NodePool with a requirement that a certain label key exists suggests that it will *only* launch nodes with that label. That puts it in conflict with the statement "...without requiring a unique NodePool for each workload subset" because I would need to create a unique NodePool for each label. I guess it doesn't actually work this way, but it is non-obvious that a "requirement" for a node label would merely be an option to allow such a node label, and if this is the case, it should be explicitly explained.

Second, how does having a label on a node "prevent `kube-scheduler` from scheduling conflicting pods to those nodes"? AFAIK a node label is not any kind of taint that would prevent pods without a node selector from being deployed to the node. 

Third, what is a "conflicting pod"?

**Comment by jonathan-innis** [comment]
> I would like elaboration on this topic

Agree that this could be clarified a bit and we'd happily accept a contribution to add to this part of the scheduling docs if you think that this could be improved. 

> AFAIK a node label is not any kind of taint that would prevent pods without a node selector from being deployed to the node

You're correct on this. I think the statement is implying that all of your application pods have a label with a given key and you can use Karpenter to isolate pods based on the _value_ of that key. For instance, if you had a key `team` and you enforced that every pod that ever ran on your cluster had that key, then you would know that for each different value for that key, you would have isolated nodes. Another example is the `kubernetes.io/role` label.

**Comment by Nuru** [comment]
> > I would like elaboration on this topic
> 
> Agree that this could be clarified a bit and we'd happily accept a contribution to add to this part of the scheduling docs if you think that this could be improved.

@jonathan-innis I'd consider contributing documentation if I understood what was going on, but I don't. My request here is because I don't understand how this feature works.

> 
> > AFAIK a node label is not any kind of taint that would prevent pods without a node selector from being deployed to the node
> 
> You're correct on this. I think the statement is implying that all of your application pods have a label with a given key and you can use Karpenter to isolate pods based on the _value_ of that key. For instance, if you had a key `team` and you enforced that every pod that ever ran on your cluster had that key, then you would know that for each different value for that key, you would have isolated nodes. Another example is the `kubernetes.io/role` label.

I would not have guessed this at all. In fact, I had to read what you wrote a few times to even begin to think I understood it. Restating:

- Configure "key exists" in a NodePool
- The NodePool will only consider pods that have a value of that key set in node affinity or node selector
- Furthermore, NodePool will set the value of that key on each node, such that different pods having the same key but different values for the key will be placed on separate nodes


> 
> > marking a NodePool with a requirement that a certain label key exists suggests that it will only launch nodes with that label
> 
> This is true. If you have an `Exists` requirement on your NodePool, Karpenter will either: 1) Use the label if it exists on the workload pod that you are trying to schedule or 2) Auto-generate the label if there is no label provided by the workload pod and it needs to generate a value for the required key in the `Exists` statement.

Do the pods need to be labeled, or is `nodeSelector` sufficient?

If the pod has no label or affinity or node selector, what prevents it from being scheduled on a node with a label other pods have specified? 

If 10 pods have no label or affinity, but the `Exists` requirement is in effect, does that mean each pod will get its own node?

**Comment by jonathan-innis** [comment]
> The NodePool will only consider pods that have a value of that key set in node affinity or node selector

You have everything right except for this statement above. If the application pod doesn't have a value for the key that you specify with the `Exists` operator, Karpenter will generate one for you. You can see this if you specify the following configuration:

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        apiVersion: "karpenter.k8s.aws"
        kind: "EC2NodeClass"
        name: default
      requirements:
        - key: app
          operator: Exists
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: KarpenterNodeRole-${CLUSTER_NAME}
  amiFamily: AL2023
  subnetSelectorTerms:                             
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
  securityGroupSelectorTerms:                      
    - tags: 
        karpenter.sh/discovery: ${CLUSTER_NAME}
```

If I then try and deploy the following deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
              memory: 100Mi
```

The output of a Node that Karpenter generates for me contains the `app` label but has a randomly generated value, since the pod didn't specify one

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "8427593205629377792"
    karpenter.k8s.aws/ec2nodeclass-hash-version: v2
    karpenter.sh/nodepool-hash: "17611978632695636306"
    karpenter.sh/nodepool-hash-version: v2
    node.alpha.kubernetes.io/ttl: "0"
  creationTimestamp: "2024-04-21T21:20:25Z"
  finalizers:
  - karpenter.sh/termination
  labels:
    app: "4724084926046977451"
   ...
```

> Do the pods need to be labeled, or is nodeSelector sufficient?

Pod labels don't do anything when being scheduled against nodes; it's only nodeSelectors and node affinities that are going to have any bearing here.

> If the pod has no label or affinity or node selector, what prevents it from being scheduled on a node with a label other pods have specified

The answer: nothing. Karpenter will schedule this pod with either a generated label or a label that was generated from a previous pod in the scheduling loop that had the key. In the same way that the kube-scheduler would allow these pods to schedule unless they had an affinity/selector or taint that prevented it from doing so, so does Karpenter. 

> If 10 pods have no label or affinity, but the Exists requirement is in effect, does that mean each pod will get its own node

You should be able to check this behavior, but the answer from my testing is that you will get a single node with a karpenter-generated label and the rest of the pods can all schedule to that same node -- so you get 10 pods on a single node.
