### ISSUE TITLE
Karpenter fails to register nodes even after successful nodeclaim launch

### ISSUE THREAD

**Issue by tomjohnburton** [aws/karpenter-provider-aws#6084]
### Description

**Observed Behavior**:
When running Karpenter, we get the following logs
```
karpenter-7cc9675fd5-t8bqp controller {"level":"INFO","time":"2024-04-22T10:39:04.903Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"6b868db","nodeclaims":1,"pods":1}
karpenter-7cc9675fd5-t8bqp controller {"level":"INFO","time":"2024-04-22T10:39:04.917Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"6b868db","nodepool":"default","nodeclaim":"default-p6rvq","requests":{"cpu":"675m","memory":"5625Mi","pods":"8"},"instance-types":"a1.xlarge, c5.xlarge, c5a.xlarge, c5ad.xlarge, c6a.xlarge and 55 other(s)"}
karpenter-7cc9675fd5-t8bqp controller {"level":"INFO","time":"2024-04-22T10:39:07.498Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"6b868db","nodeclaim":"default-p6rvq","provider-id":"aws:///eu-central-1a/i-0589d5ed2ba16204d","instance-type":"t3a.large","zone":"eu-central-1a","capacity-type":"on-demand","allocatable":{"cpu":"1930m","ephemeral-storage":"17Gi","memory":"6837Mi","pods":"35"}}
karpenter-7cc9675fd5-t8bqp controller {"level":"INFO","time":"2024-04-22T10:39:14.892Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"6b868db","pods":"monitoring/prometheus-server-0","duration":"19.201578ms"}
karpenter-7cc9675fd5-t8bqp controller {"level":"INFO","time":"2024-04-22T10:39:24.883Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"6b868db","pods":"monitoring/prometheus-server-0","duration":"9.782341ms"}
...
...
ad infinitum
```
One would now expect the node to spin up in the cluster. In fact we see that a node is successfully created in EC2 but it is not registered into the cluster. 
<img width="1083" alt="Screenshot 2024-04-22 at 12 44 59" src="https://github.com/aws/karpenter-provider-aws/assets/39559415/4cb6d71c-1d04-4ab7-88ca-f54b1a893703">

**Expected Behavior**:
Karpenter should register the node to the cluster

**Reproduction Steps** (Please include YAML):
This is our config. 
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
  namespace: kube-system
spec:
  disruption:
    consolidateAfter: 2m
    consolidationPolicy: WhenEmpty
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: "In"
          values: ["on-demand"]
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  namespace: kube-system
spec:
  amiFamily: AL2023
  role: *****
  amiSelectorTerms:
    - name: amazon-eks-node-1.29-v20240415 # https://github.com/awslabs/amazon-eks-ami/releases
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: tag-main
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: tag-main
  tags:
    karpenter.sh/discovery: tag-main
```

**Versions**:
- Chart Version: 0.36.0
- Kubernetes Version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15", GitCommit:"1d79bc3bcccfba7466c44cc2055d6e7442e140ea", GitTreeState:"clean", BuildDate:"2022-09-21T12:11:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"29+", GitVersion:"v1.29.3-eks-adc7111", GitCommit:"c8f33fb3fdd7ee39809c260233424fb73ce1893b", GitTreeState:"clean", BuildDate:"2024-04-01T19:25:15Z", GoVersion:"go1.21.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
