### ISSUE TITLE
Node taking time to join EKS cluster

### ISSUE THREAD

**Issue by Deepak-Arjariya** [aws/karpenter-provider-aws#6128]
### Description
When using awsnodetemplate and provisioner (v1alpha5 apis), node joins the eks cluster in 40-55 seconds, but when using nodepool and ec2nodeclass (v1beta1 apis) node is taking 100 - 120 seconds to join eks cluster and become ready.

Can anyone help if I am missing something ?

**Comment by arijitamin** [comment]
faced the same issue as well. @lamdor @javier @DWSR @asimshankar FYI.

**Comment by jmdeal** [comment]
What do your nodepool / nodeclass and provisioner / nodetemplate pairs look like? There are a lot of factors that can impact node join time, e.g. instance type, AMI, etc.  One of the notable changes in v1beta1 is that requirements are no longer defaulted onto the NodePool like they were on the provisioner. For example, the provisioner had a `karpenter.sh/instance-category IN ["c", "m", "r"]` requirement by default. This opens up the instance types available to a default NodePool and could result if you're getting slower instance types (e.g. t3.small).

**Comment by Deepak-Arjariya** [comment]
Hi @jmdeal thanks for replying. Below are my configurations. I am not using default configurations. we are using instance types as ["c", "m", "r"] types only. AMI created by few additional installations on top of Amazon linux 2. Kubernetes version is 1.29

### NodeClass
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: '${eks_cluster_name}'
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - id: '${ami_name}'
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      volumeSize: 200Gi
      volumeType: gp3
  role: '${eks_cluster_name}-mng'
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: '${eks_cluster_name}'
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: '${eks_cluster_name}'
  tags:
    karpenter.sh/discovery: '${eks_cluster_name}'
```
    
    
   ### NodePool
```
   apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: '${eks_cluster_name}'
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  limits:
    cpu: 1k
    memory: 1000Gi
  template:
    metadata: {}
    spec:
      nodeClassRef:
        name: '${eks_cluster_name}'
      requirements:
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - c6a
        - c6i
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "4"
        - "8"
        - "16"
        - "32"
        - "48"
        - "64"
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - ap-south-1a
        - ap-south-1b
        - ap-south-1c
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
```
