### ISSUE TITLE
StatefulSet unsatisfiable topology constraint for topology spread 

### ISSUE THREAD

**Issue by edblake00** [aws/karpenter-provider-aws#6141]
### Description

**Observed Behavior**:

During draining of nodes, or scaling StatefulSet replicas down and back up again, StatefulSet pods get stuck in pending. 
Karpenter logs show:

> {"level":"DEBUG","time":"2024-05-03T06:48:06.528Z","logger":"controller.provisioner","message":"adding requirements derived from pod volumes, [{topology.ebs.csi.aws.com/zone In [eu-central-1c]}]","commit":"17d6c05","pod":"sre/test-5"}

> incompatible with nodepool \"sre-amd64\", daemonset overhead={\"cpu\":\"273m\",\"memory\":\"1047Mi\",\"pods\":\"7\"}, unsatisfiable topology constraint for topology spread, key=topology.kubernetes.io/zone (counts = eu-central-1c: 1 and 12 other(s), podDomains = topology.kubernetes.io/zone In [eu-central-1c], nodeDomains = topology.kubernetes.io/zone In [eu-central-1c];

**Expected Behavior**:

When draining nodes, Karpenter should provision new nodes and schedule statefulSet pods on them.
When scaling down StatefulSet replicas and then scaling back up again, pods should again be scheduled successfully.

**Reproduction Steps** (Please include YAML):

1. Create resources using below YAML, wait for 5 replicas to be ready.
2. Decrease the statefulSet replicas to 3. 
3. Wait for Karpenter to consolidate the empty nodes down from 5 > 3.

Note, test-data-test-3 and test-data-test-4 PVCs remain bound to non-existing nodes after pods and nodes removed.

<img width="580" alt="image" src="https://github.com/aws/karpenter-provider-aws/assets/150042190/55c7d288-ef0e-40c9-b4d7-e27eda1c0a68">

4. Increase replica count to 5 again.

Pods test-3 is stuck in pending state and cannot schedule. Events on the pod and logs from karpenter show:

> {"level":"DEBUG","time":"2024-05-03T06:48:06.528Z","logger":"controller.provisioner","message":"adding requirements derived from pod volumes, [{topology.ebs.csi.aws.com/zone In [eu-central-1c]}]","commit":"17d6c05","pod":"sre/test-5"}

> incompatible with nodepool \"sre-amd64\", daemonset overhead={\"cpu\":\"273m\",\"memory\":\"1047Mi\",\"pods\":\"7\"}, unsatisfiable topology constraint for topology spread, key=topology.kubernetes.io/zone (counts = eu-central-1c: 1 and 12 other(s), podDomains = topology.kubernetes.io/zone In [eu-central-1c], nodeDomains = topology.kubernetes.io/zone In [eu-central-1c];

5. Scale down the replicas back to 3, and then manually delete test-data-test-3 and test-data-test-4 PVCs, 
6. Scale back up to 5 replicas

Karpenter successfully to creates new nodes and schedules the pods. 

The same issue can also be seen by draining any of the nodes. The replacement pod gets stuck in a pending state, with Karpenter logs showing the same unsatisfiable topology constraint for topology spread.

If we use a separate deployment to force Karpenter to scale up to 5 nodes, the pending StatefulSet pods are then able to schedule. 

```
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: test-pdb
  namespace: sre
spec:
  maxUnavailable: 10%
  selector:
    matchLabels:
      app: test
  unhealthyPodEvictionPolicy: AlwaysAllow
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
  namespace: sre
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 5
  selector:
      matchLabels:
        app: test
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
        labels:
          app: test
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: test-data
      volumes:
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
      tolerations:
        - key: Workload
          operator: Equal
          value: SRE
          effect: NoSchedule
      nodeSelector:
        Workload: SRE
        kubernetes.io/arch: amd64
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          minDomains: 3
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          minDomains: 60
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule

  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: class1
      volumeMode: Filesystem
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: kubernetes-main
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: sre-amd64
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 5m0s
    consolidationPolicy: WhenEmpty
    expireAfter: Never
  limits:
    cpu: "300"
  template:
    metadata:
      labels:
        Workload: SRE
    spec:
      nodeClassRef:
        name: eng
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - m5n
        - c5n
        - r5n
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - large
        - xlarge
        - 2xlarge
        - 4xlarge
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      taints:
      - effect: NoSchedule
        key: Workload
        value: SRE
  weight: 50
```

**Versions**:
- Chart Version: v0.34.0
- Kubernetes Version (`kubectl version`): v1.28.7-eks-b9c9ed7

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
