### ISSUE TITLE
Update NodePool.Status with node drift information.

### ISSUE THREAD

**Issue by shreyas-badiger** [aws/karpenter-provider-aws#6166]
### Description

**What problem are you trying to solve?**
Currently, there is no clear way to identify how many nodes have drifted from the current hash (nodepool hash and ec2nodeclass hash). To determine the node rotation progress, we will have to look into individual node objects, nodeclaims, nodepool and nodeclass. 

Since Karpenter controller identifies and rotates the drifted nodes, I am assuming the controller already maintains the list of drifted nodes (if not, identifies the drifted nodes in every reconciliation.)  It will be helpful to surface this information in the NodePool status.

**for ex:**
```
status:
  resources:
    cpu: "64"
    ephemeral-storage: 134205420Ki
    memory: 258565188Ki
    pods: "640"
    nodes:
      totalNodes: 10
      driftedNodes: 2
```

**How important is this feature to you?**
This feature will be very useful to identify the progress of node rotation whenever we change AMIs or trigger any other form of upgrades by updating the nodepool or ec2nodeclass.

**If you are interested in working on this issue or have submitted a pull request, please leave a comment**
I am interested to work on this issue.
