### ISSUE TITLE
Unable to pass array to Bottlerocket`[kubernetes.setting]` `cluster-dns-ip`

### ISSUE THREAD

**Issue by z0rc** [aws/karpenter-provider-aws#6212]
### Description

**Observed Behavior**:

Instance user data:
```
...
[settings.kubernetes]
cluster-dns-ip = '169.254.20.25'
...
```

**Expected Behavior**:

```
...
[settings.kubernetes]
cluster-dns-ip = ['169.254.20.25', '10.100.0.10']
...
```

**Reproduction Steps** (Please include YAML):

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: foo
spec:
  template:
    spec:
      kubelet:
        clusterDNS:
        - 169.254.20.25
        - 10.100.0.10
```

**Versions**:
- Chart Version: 0.36.1
- Kubernetes Version (`kubectl version`): irrelevant

See https://bottlerocket.dev/en/os/1.19.x/api/settings/kubernetes/#cluster-dns-ip

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
