### ISSUE TITLE
EC2 Nodeclass using Bottlerocket image won't provision larger root volume

### ISSUE THREAD

**Issue by seanpascual** [aws/karpenter-provider-aws#6214]
### Description

**Observed Behavior**:
We are running Karpenter with AWS Bottlerocket nodes, but have seen that since moving to Bottlerocket AMIs from AL2 that the /dev/root volume is always >80% full.

The documentation states that a 4Gi EBS volume should be provisioned by default for /dev/root and a 20Gi EBS volume for data.

We are seeing, however, that only a 1Gi /dev/root volume is provisioned.

Doc link: https://karpenter.sh/v0.34/concepts/nodeclasses/#bottlerocket-1

We have therefore tried overriding the blockDeviceMapping both for root and data. This appears to work for the data volume, but not for root.

Checking mounted volume sizes on the instance one can see that /dev/nvme1n1p1 is at the expected 50Gi, however the /dev/root volume is still at 1Gi.

<img width="634" alt="Screenshot 2024-05-16 at 11 04 56" src="https://github.com/aws/karpenter-provider-aws/assets/31441595/0607442e-a6a8-4fd6-ba9d-ca4330056439">

This only appears to be happening with Bottlerocket nodes as it is not affecting our AL2 nodes / EC2NodeClass.

**Expected Behavior**:

We are expecting that the root volume should be overridden to 5Gi and the data volume be overridden to 50Gi.

**Reproduction Steps** (Please include YAML):

Provisioning the EC2NodeClass:
```
defaults:
  ec2NodeClass:
    spec:
      securityGroupSelectorTerms:
      - tags:
          Name: xxx-node
      tags:
        # Matches the tag in the IRSA policy
        karpenter.k8s.aws/cluster: xxx
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            volumeSize: 5Gi
            volumeType: gp3
            encrypted: true
            deleteOnTermination: true
        - deviceName: /dev/xvdb
          ebs:
            volumeSize: 50Gi
            volumeType: gp3
            iops: 3000
            encrypted: true
            deleteOnTermination: true
            throughput: 125
```

Describing the EC2NodeClass after deploying the above config:
```
> k describe ec2nodeclass default
Name:         default
Namespace:    
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  karpenter.k8s.aws/ec2nodeclass-hash: xxx
              karpenter.k8s.aws/ec2nodeclass-hash-version: v2
              meta.helm.sh/release-name: karpenter-provisioning
              meta.helm.sh/release-namespace: karpenter
API Version:  karpenter.k8s.aws/v1beta1
Kind:         EC2NodeClass
Metadata:
  Creation Timestamp:  2024-02-27T11:57:06Z
  Finalizers:
    karpenter.k8s.aws/termination
  Generation:        6
  Resource Version:  748924897
  UID:               22b5f79e-a4aa-4903-8b9f-4aabc1d4c012
Spec:
  Ami Family:  Bottlerocket
  Block Device Mappings:
    Device Name:  /dev/xvda
    Ebs:
      Delete On Termination:  true
      Encrypted:              true
      Volume Size:            5Gi
      Volume Type:            gp3
    Device Name:              /dev/xvdb
    Ebs:
      Delete On Termination:  true
      Encrypted:              true
      Iops:                   3000
      Throughput:             125
      Volume Size:            50Gi
      Volume Type:            gp3
```

Checking the volume sizes on the instance shows that the /dev/root volume hasn't increased in size, while the "data" volume has increased as expected:
```
/dev/nvme1n1p1   50G  7.5G   43G  15% /.bottlerocket/support
/dev/root       904M  676M  166M  81% /usr/local/bin/apiclient
```

**Versions**:
- Chart Version: 0.36.1
- Kubernetes Version (`kubectl version`): v1.29.3-eks-adc7111

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
