### ISSUE TITLE
Karpenter creates on-demand instance even though it is only configured for spot instances

### ISSUE THREAD

**Issue by waihong** [aws/karpenter-provider-aws#6244]
### Description

**Observed Behavior**:

We have a NodePool with only `spot` as `karpenter.sh/capacity-type` defined. Karpenter created spot instances as expected however once in a while it also created an on-demand instance with contradicting labels. The on-demand node had the labels `eks.amazonaws.com/capacityType: ON_DEMAND` and `karpenter.sh/capacity-type: spot`

Node labels:

```
 labels:                                                               
    beta.kubernetes.io/arch: amd64                                      
    beta.kubernetes.io/instance-type: t3.large                          
    beta.kubernetes.io/os: linux                                        
    eks.amazonaws.com/capacityType: ON_DEMAND                           
    failure-domain.beta.kubernetes.io/region: ap-east-1                 
    failure-domain.beta.kubernetes.io/zone: ap-east-1b                  
    k8s.io/cloud-provider-aws: xxxxx         
    karpenter.k8s.aws/instance-category: t                              
    karpenter.k8s.aws/instance-cpu: "2"                                 
    karpenter.k8s.aws/instance-cpu-manufacturer: intel                  
    karpenter.k8s.aws/instance-encryption-in-transit-supported: "false" 
    karpenter.k8s.aws/instance-family: t3                               
    karpenter.k8s.aws/instance-generation: "3"                          
    karpenter.k8s.aws/instance-hypervisor: nitro                        
    karpenter.k8s.aws/instance-memory: "8192"                           
    karpenter.k8s.aws/instance-network-bandwidth: "512"                 
    karpenter.k8s.aws/instance-size: large                              
    karpenter.sh/capacity-type: spot                                    
    karpenter.sh/initialized: "true"                                    
    karpenter.sh/nodepool: spot-workload                                
    karpenter.sh/registered: "true"                                     
    kubernetes.io/arch: amd64                                           
    kubernetes.io/hostname: ip-10-12-67-82.ap-east-1.compute.internal   
    kubernetes.io/os: linux                                             
    node.kubernetes.io/instance-type: t3.large                          
    topology.ebs.csi.aws.com/zone: ap-east-1b                           
    topology.kubernetes.io/region: ap-east-1                            
    topology.kubernetes.io/zone: ap-east-1b 
```

**Expected Behavior**:
According to https://karpenter.sh/docs/faq/#what-if-there-is-no-spot-capacity-will-karpenter-use-on-demand, Karpenter should only be able to create on-demand instances when on-demand is configured in `karpenter.sh/capacity-type`.

**Reproduction Steps** (Please include YAML):
NodePool requirements:

```
requirements:                          
  - key: node.kubernetes.io/instance-type
    operator: In                         
    values:                              
    - m5d.large                          
    - m5d.xlarge                         
    - m6i.large                          
    - m6i.xlarge                         
    - m6i.2xlarge                        
    - m5.large                           
    - t3.small                           
    - t3.medium                          
    - t3.large                           
    - t3a.small                          
    - t3a.medium                         
    - t3a.large                          
    - t3a.xlarge                         
    - t3a.2xlarge                        
    - r6i.large                          
    - r6i.xlarge                         
    - r5.large                           
    - r5.xlarge                          
    - r5n.large                          
    - r5n.xlarge                         
  - key: karpenter.sh/capacity-type      
    operator: In                         
    values:                              
    - spot                               
  - key: topology.kubernetes.io/zone     
    operator: In                         
    values:                              
    - ap-east-1a                         
    - ap-east-1b                         
    - ap-east-1c  
```

**Versions**:
- Chart Version: 0.36.2
- Kubernetes Version (`kubectl version`): 1.26

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
