### ISSUE TITLE
AL2023: cannot configure kubelet-config.json as it is not existing

### ISSUE THREAD

**Issue by universam1** [aws/karpenter-provider-aws#6251]
### Description

**Observed Behavior**:

in AL2023 it is impossible to set custom settings in the _/etc/kubernetes/kubelet/kubelet-config.json_ as it is not existing!
Even `find / -name kubelet-config.json` does not reveal another location.

Note system logs:
```
2024/05/21 09:08:11Z: Amazon SSM Agent v3.3.380.0 is running
2024/05/21 09:08:11Z: OsProductName: Amazon Linux
2024/05/21 09:08:11Z: OsVersion: 2023
[   16.836584] cloud-init[1911]: jq: error: Could not open file /etc/kubernetes/kubelet/kubelet-config.json: No such file or directory
```

**Expected Behavior**:

kubelet-config.json to be existing and possible to extend via userdata.

**Reproduction Steps** (Please include YAML):

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: kubelet-config-example
spec:
  ...
  amiFamily: AL2023
  userData: |
    #!/bin/bash
    find / -name kubelet-config.json
    echo "$(jq '.kubeAPIQPS=50' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json    
```

This renders into a userdata script:

```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: application/node.eks.aws

# Karpenter Generated NodeConfig
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
metadata:
  creationTimestamp: null
spec:
...
  kubelet:
    config:
      clusterDNS:
      - 10.100.0.10
      maxPods: 58
    flags:
    - --node-labels="karpenter.sh/capacity-type=spot,karpenter.sh/nodepool=al2023"

--//
Content-Type: text/x-shellscript; charset="us-ascii"

#!/bin/sh
find / -name kubelet-config.json
echo "$(jq '.registryPullQPS=50' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json

--//--

```

**Versions**:
- Chart Version: 0.36.2
- Kubernetes Version (`kubectl version`): 1.28

relates to https://github.com/aws/karpenter-provider-aws/issues/6250

**Comment by jmdeal** [comment]
The AL2023 AMI uses the [drop-in directory for kubelet configuration files](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#kubelet-conf-d) which is why the expected file doesn't exist. The recommended way to configure kubelet options on AL2023 is to use the `NodeConfig` resource. For example, you could use the following user data:
```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: kubelet-config-example
spec:
  ...
  amiFamily: AL2023
  userData: |
    kind: NodeConfig
    spec:
      kubelet:
        config:
          registryPullQPS: 50
```
This node config object will be added to Karpenter's generated userdata and the AL2023 AMI handles merging the two nodeconfig objects.

**Comment by universam1** [comment]
Thank you @jmdeal for that insights, appreciated!

That config option registryPullQPS is not supported according to the Karpenter docs. Is that missing?

**Comment by jmdeal** [comment]
We don't document the full set of options for `NodeConfig`, but we do link out to the relevant docs in the [AL2023 UserData docs](https://karpenter.sh/docs/concepts/nodeclasses/#al2023-3). Technically `spec.kubelet.config` is not typed so they don't enumerate all of the fields in their docs, but it's just an embeded [KubeletConfiguration](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) object.

**Comment by bruno-espino** [comment]
Try with /etc/kubernetes/kubelet/config.json instead.
In my case, when changing to AL2023, the config filename changed.

**Comment by universam1** [comment]
@bruno-espino Indeed, this file exists  - after a KubeletConfiguration is applied. Don't know if it would work without it.

@jmdeal Great information - I wasn't aware of this generics. It gets applied and works as you suggested. Sounds like it would be worth adding this information to the docs?

Anyways, closing this issue as resolved
/close

**Comment by ecloud-team-ferroamp-se** [comment]
Note: The userData needs to include apiVersion, or the node won't start.

Correcting the example above:

```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: kubelet-config-example
spec:
  ...
  amiFamily: AL2023
  userData: |
    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      kubelet:
        config:
          registryPullQPS: 50
```
