### ISSUE TITLE
Karpenter provisions too large machine

### ISSUE THREAD

**Issue by ahmetozer** [aws/karpenter-provider-aws#6287]
### Description

**Observed Behavior**:
Today we have noticed that karpenter provisioned too large machine types which fit our playground deployments many times.

![image](https://github.com/aws/karpenter-provider-aws/assets/10574489/5b5f9296-db8f-4cb3-855e-8dfa59cc821e)

**Expected Behavior**:
Smaller machine types

Temporary solution:
Setting instance type condition.

```yaml
kind: NodePool
.....
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - a1.large
        - a1.medium
        - a1.xlarge
        - c3.large
        - ....
```

**Reproduction Steps** (Please include YAML):
Deleting EC2NodeClass and re provision 

**Versions**:
- Chart Version: 0.36
- Kubernetes Version (`kubectl version`): 1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
