### ISSUE TITLE
ERROR: Karpenter not authorized to perform: iam:PassRole

### ISSUE THREAD

**Issue by vipul0805** [aws/karpenter-provider-aws#6298]
Hi everyone,

For some reason, I'm getting the ERROR below after updating the karpenter to v0.32.10 following the [v1beta1 migration guide](https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#upgrade-procedure).

Error:

<pre class="notranslate">
{
  "level": "ERROR",
  "time": "2024-05-30T14:40:34.966Z",
  "logger": "controller",
  "message": "Reconciler error",
  "commit": "f0eb822",
  "controller": "nodeclaim.lifecycle",
  "controllerGroup": "karpenter.sh",
  "controllerKind": "NodeClaim",
  "NodeClaim": {
    "name": "bottlerocket-wts6g"
  },
  "namespace": "",
  "name": "bottlerocket-wts6g",
  "reconcileID": "666566d1-fc82-47b4-beb8-72aeefa2dbab",
  "error": "launching nodeclaim, creating instance, with fleet error(s), UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::111111:assumed-role/${CLUSTER_NAME}-karpenter/1717079343811266923 is not authorized to perform: iam:PassRole on resource: arn:aws:iam::111111:role/KarpenterNodeRole-${CLUSTER_NAME} because no identity-based policy allows the iam:PassRole action. Encoded Failure: <encoded-message>"
}
</pre>

On digging down further I found that its not working for the resource provided in  the IAM policy `iam:PassRole` action

```
      {
        "Sid": "AllowPassingInstanceRole",
        "Effect": "Allow",
        "Resource": "arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/KarpenterNodeRole-${CLUSTER_NAME}",
        "Action": "iam:PassRole",
        "Condition": {
          "StringEquals": {
            "iam:PassedToService": "ec2.amazonaws.com"
          }
        }
      }
```

It starts working If I allow the above action for all the resources. Can someone please help  in understanding what I am doing wrong here.

**Comment by engedaam** [comment]
The permission you shared above seem correct to me? Can you share your EC2NodeClass?

**Comment by vipul0805** [comment]
Sure, here it is.
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  labels:
    release: bottlerocket-nodepool-with-consolidation
  name: bottlerocket
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      volumeSize: 4Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      volumeSize: 20Gi
      volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: KarpenterNodeRole-${CLUSTER_NAME}
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${CLUSTER_NAME}
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${CLUSTER_NAME}
```
