### ISSUE TITLE
Health Probe Timeout and Node Claiming Issues Following Upgrade to Karpenter v0.36.1

### ISSUE THREAD

**Issue by unitmatrix** [aws/karpenter-provider-aws#6300]
**Observed Behavior**:
We recently upgraded Karpenter from v0.35.5 to v0.36.1 in our EKS 1.29 environment within an isolated VPC. Post upgrade, Karpenter ceased to create new node claims and schedule new nodes. This was accompanied by a non-responsive health probe, causing Karpenter to enter a continuous cycle of shutdown and restart. 

An error related to the pricing API was observed:

> {"level":"ERROR","time":"2024-05-30T09:35:18.886Z","logger":"controller.pricing","message":"updating pricing, retreiving on-demand pricing data, RequestCanceled: request context canceled\ncaused by: context canceled; RequestCanceled: request context canceled\ncaused by: context canceled","commit":"fb4d75f"}

However, please note that this error was present even before the upgrade and it did not affect the health probe timeout or Karpenter's ability to claim new nodes.

Additionally, the following warning messages were captured from the pod events, showing that the liveness probe failed continuously:

> Warning Unhealthy 92s (x6 over 13m) kubelet Liveness probe failed: Get "http://192.168.1.244:8081/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
Normal Killing 92s (x2 over 12m) kubelet Container controller failed liveness probe, will be restarted 
Normal Created 61s (x3 over 14m) kubelet Created container controller Normal Started 61s (x3 over 14m) kubelet Started container controller

**Expected Behavior**:
Karpenter should continue to create new node claims and schedule new nodes without any disruptions, even after the upgrade. The health probe should respond in time, preventing any unnecessary cycling of shutdown and restart.

**Reproduction Steps**:
1. Upgrade Karpenter to v0.36.1 in an EKS 1.29 environment within an isolated VPC.
2. Observe that Karpenter stops creating new node claims and scheduling new nodes.
3. Investigate and find that Karpenter's health probe isn't responding in time, causing a continuous cycle of shutdown and restart.

**Versions**:

* Karpenter Version: 0.36.1
* Kubernetes Version (`kubectl version`): 1.29
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Are you running Karpenter in EKS Fargate or MNG? Can you share the size of the nodes that are running Karpenter? Can you share the Karpenter deployment that you are running in the cluster?

**Comment by unitmatrix** [comment]
Thank you for your response. 

Karpenter is running on a self-managed node group on `t3a.medium` size instances. 

The deployment used for testing involves 10 replicas of an 'inflate' pod. Here is the YAML configuration for the same:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 10
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 1
```
As a workaround, setting the isolatedVPC value to true in the Karpenter settings has resolved the issue: `isolatedVPC: true`
However, it's worth noting that this configuration was not required prior to the upgrade to v0.36.1. We're trying to understand why this change has become necessary and whether this is the intended behavior moving forward.
