### ISSUE TITLE
karpenter.k8s.aws/instance-size will not work with `xlarge`

### ISSUE THREAD

**Issue by ernievd** [aws/karpenter-provider-aws#6301]
### Description

**Observed Behavior**:
If you set the `karpenter.k8s.aws/instance-size`to try and use `xlarge` karpenter will not bring up an instance

If I have this configuration in my NodePool it will not bring up an EC2 instance -

```
      requirements:
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - c6a
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - xlarge
 ```

If I have this in my NodePool it will bring up a `c6a.2xlarge` instance - 

```
      requirements:
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - c6a
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - 2xlarge
  ```

I also tried using `4xlarge` and kapenter did spin up an EC2 instance of `c6a.4xlarge`.

**Expected Behavior**:

Using the following should have karpenter bring up an EC2 instance of `c6a.xlarge`. 

```
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - c6a
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - xlarge
```
**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:  0.36.1
- Kubernetes Version (`kubectl version`): v1.23.1

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
