### ISSUE TITLE
Nodes are created but are not being registered to the cluster

### ISSUE THREAD

**Issue by nalshamaajc** [aws/karpenter-provider-aws#6303]
### Description

**Observed Behavior**: Nodes are created but are not being registered to the cluster

**Expected Behavior**: Nodes are created and are registered to the cluster

**Reproduction Steps** (Please include YAML):
Try upgrade from v0.31.5 to v0.32.0 and follow the [upgrade guide](https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#upgrade-procedure) I skipped some steps because I use a helm chart.

I was also using the role parameter and not the instanceProfile in the ec2NodeClass.

The nodepool creates a nodeClaim but does not create the node.

I got the below in the nodeClaim status section.

```
status:
  allocatable:
    cpu: 7910m
    ephemeral-storage: 107Gi
    memory: 14162Mi
    pods: '58'
    vpc.amazonaws.com/pod-eni: '38'
  capacity:
    cpu: '8'
    ephemeral-storage: 120Gi
    memory: 15155Mi
    pods: '58'
    vpc.amazonaws.com/pod-eni: '38'
  conditions:
    - lastTransitionTime: '2024-05-30T13:31:00Z'
      message: Node not registered with cluster
      reason: NodeNotFound
      status: 'False'
      type: Initialized
    - lastTransitionTime: '2024-05-30T13:31:00Z'
      status: 'True'
      type: Launched
    - lastTransitionTime: '2024-05-30T13:31:00Z'
      message: Node not registered with cluster
      reason: NodeNotFound
      status: 'False'
      type: Ready
    - lastTransitionTime: '2024-05-30T13:31:00Z'
      message: Node not registered with cluster
      reason: NodeNotFound
      status: 'False'
      type: Registered
  imageID: ami-0fe93db2c62573b1a
  providerID: 'aws:///us-west-2c/i-0f84d19de2821fd6c'
```
In the logs I noticed the below entry
```
"level":"DEBUG","time":"2024-05-30T13:46:01.646Z","logger":"controller.nodeclaim.lifecycle","message":"terminating due to registration ttl","commit":"f0eb822","nodeclaim":"default-hbgnd","nodepool":"default","ttl":"15m0s"}
```

The docs state that when using a role it should be able to create/manage an instance profile, but it seems that it doesn't add  the role/service account mapping to the aws-auth configmap when using IRSA.

[Migration guide](https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#upgrade-procedure) 
```
For each EC2NodeClass, specify the $KARPENTER_NODE_ROLE you will use for nodes launched with this node class. Karpenter v1beta1 drops the need for managing your own instance profile and uses node roles directly. The example below shows how to migrate your AWSNodeTemplate to an EC2NodeClass if your node role is the same role that was used when creating your cluster with the Getting Started Guide.
```

[changelog](https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#awsnodetemplate---ec2nodeclass) 
```
Karpenter will now auto-generate the instance profile in your EC2NodeClass, given the role that you specify.
```

*Solution*

The problem was solved when I used the instanceProfile instead of role for  the ec2NodeClass, the instanceProfile was already configured in the aws-auth configMap which made it work.

**Versions**: v0.32.10
- Chart Version: v0.32.10
- Kubernetes Version (`kubectl version`): EKS v1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
