### ISSUE TITLE
Persistent Issue with Karpenter v0.36.0: Node Creation and Scheduling Failure Despite Resource Adjustments

### ISSUE THREAD

**Issue by unitmatrix** [aws/karpenter-provider-aws#6304]
### Description

**Observed Behavior**:
We recently upgraded Karpenter from v0.35.5 to v0.36.0 in our EKS 1.29 environment within an isolated VPC. Post upgrade, Karpenter ceased to create new node claims and schedule new nodes. This was accompanied by a delay in the response from the health probe, causing Karpenter to enter a continuous cycle of shutdown and restart. 

The issue persisted even after applying the recommended resource requests and limits to the Karpenter deployment in #6300. The health probe kept timing out (timeout=30s) and Karpenter could not claim and schedule new nodes.

**Expected Behavior**:
Karpenter should continue to create new node claims and schedule new nodes, and the health probe should respond within the timeout period, preventing any unnecessary cycling of shutdown and restart, even after resource adjustments.

**Reproduction Steps**:
1. Upgrade Karpenter to v0.36.0 in an EKS 1.29 environment within an isolated VPC.
2. Apply recommended resource requests and limits to the Karpenter deployment.
3. Observe that Karpenter continues to fail in creating new node claims and scheduling new nodes.
4. Notice that Karpenter's health probe isn't responding within the timeout period, causing a continuous cycle of shutdown and restart.

**Versions**:
* Karpenter Version: 0.36.0
* Kubernetes Version (`kubectl version`): 1.29

The helm chart values used in our setup are as follows:

```yaml
controller:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: redacted
settings:
  clusterEndpoint: redacted
  clusterName: redacted
  isolatedVPC: false

**Comment by engedaam** [comment]
Can you share your full Karpenter deployment spec?

**Comment by unitmatrix** [comment]
Sure, here's the full Karpenter deployment spec in our environment:
<details>
<summary>Click to expand!</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: karpenter
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.36.0
    helm.sh/chart: karpenter-0.36.0
  name: karpenter
  namespace: karpenter
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: karpenter
      app.kubernetes.io/name: karpenter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: karpenter
        app.kubernetes.io/name: karpenter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: DoesNotExist
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: karpenter
                app.kubernetes.io/name: karpenter
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: KUBERNETES_MIN_VERSION
          value: 1.19.0-0
        - name: KARPENTER_SERVICE
          value: karpenter
        - name: LOG_LEVEL
          value: info
        - name: METRICS_PORT
          value: "8000"
        - name: HEALTH_PROBE_PORT
          value: "8081"
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: controller
              divisor: "0"
              resource: limits.memory
        - name: FEATURE_GATES
          value: Drift=true,SpotToSpotConsolidation=false
        - name: BATCH_MAX_DURATION
          value: 10s
        - name: BATCH_IDLE_DURATION
          value: 1s
        - name: ASSUME_ROLE_DURATION
          value: 15m
        - name: CLUSTER_NAME
          value: eks-test
        - name: CLUSTER_ENDPOINT
          value: redacted
        - name: VM_MEMORY_OVERHEAD_PERCENT
          value: "0.075"
        - name: RESERVED_ENIS
          value: "0"
        image: redacted/karpenter/controller:0.36.0@sha256:90adaba9e8e9f66244324ca64408a5abbfe063f8c41fbbfebf226bdda4fadd58
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: controller
        ports:
        - containerPort: 8000
          name: http-metrics
          protocol: TCP
        - containerPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65532
      serviceAccount: karpenter
      serviceAccountName: karpenter
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: karpenter
            app.kubernetes.io/name: karpenter
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2024-05-31T11:33:00Z"
    lastUpdateTime: "2024-05-31T11:33:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-30T07:40:07Z"
    lastUpdateTime: "2024-06-04T05:24:44Z"
    message: ReplicaSet "karpenter-8645888649" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
```

</details>

Let me know if you need any more information.

**Comment by engedaam** [comment]
It would seem that you have your setting to false for isolated VPC?
```
settings:
  clusterEndpoint: redacted
  clusterName: redacted
  isolatedVPC: false
```

Can you validate that first?
