### ISSUE TITLE
When spot is not available, karpenter fails to create an on-demand (within the 45 seconds documented time)

### ISSUE THREAD

**Issue by guido-muscioni-anthem** [aws/karpenter-provider-aws#6324]
### Description

**Observed Behavior**:

Based on what I understand, when a node claim is created on a nodepool with both `on-demand` and `spot` support:
1. `karpenter` will try for `spot`
2. if `spot` fails, `karpenter` will eventually move to `on-demand` (which I think it is what is happening based on logs). Please correct me here if my understanding is not correct.
3. EXPECTED: a new `on-demand` instance joins the cluster
4. ACTUAL: `karpenter` loops with the following:
```
{"level":"ERROR","time":"2024-06-05T21:47:37.588Z","logger":"controller","message":"Reconciler error","commit":"a70b39e","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"REDACTED"},"namespace":"","name":"REDACTED","reconcileID":"88900728-9f75-4694-a9bb-3eee435e9c4f","error":"launching nodeclaim, creating instance, with fleet error(s), InvalidParameterValue: You cannot specify tags for Spot instances requests if there are no Spot instances requests being created by the request.; InsufficientInstanceCapacity: We currently do not have sufficient g5.2xlarge capacity in zones with support for 'gp3' volumes. Our system will be working on provisioning additional capacity."}
{"level":"WARN","time":"2024-06-5T21:47:38.665Z","logger":"controller.nodeclaim.lifecycle","message":"at least 5 instance types are recommended when flexible to spot but requesting on-demand, the current provisioning request only has 1 instance type options","commit":"a70b39e","nodeclaim":"REDACTED"}
{"level":"ERROR","time":"2024-06-05T21:47:40.674Z","logger":"controller","message":"Reconciler error","commit":"a70b39e","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"REDACTED"},"namespace":"","name":"REDACTED","reconcileID":"a4777a3c-c0f5-45d8-96ca-138bb3b5f3d7","error":"launching nodeclaim, creating instance, with fleet error(s), InvalidParameterValue: You cannot specify tags for Spot instances requests if there are no Spot instances requests being created by the request."}
```

I checked `CloudTrail` and the error of the first log line are actually 2 separate errors, one refers to the no availability, the second to the tagging.

checking the doc, there should be a 45seconds interval for fallback from `spot` to `on-demand`. It takes a lot more (7 minutes) for the provisioner to actually generate the right node-claim with `on-demand` only ([https://karpenter.sh/docs/concepts/nodepools/#capacity-type]).

**Expected Behavior**:

`karpenter` should request an `on-demand` EC2 after a while.

**Reproduction Steps** (Please include YAML):

Here is my yaml for the NodePool, everything works fine if the NodePool is set to only `on-demand`.
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels:
    app.kubernetes.io/instance: REDACTED
  name: default-gpu-node-pool-g5-1
spec:
  disruption:
    consolidateAfter: 100s
    consolidationPolicy: WhenEmpty
  template:
    metadata:
      labels:
        k8s.amazonaws.com/accelerator: nvidia-a10g
    spec:
      nodeClassRef:
        name: default-gpu-nc
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - g5
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - xlarge
            - 2xlarge
            - 4xlarge
            - 8xlarge
            - 16xlarge
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - spot
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      taints:
        - effect: NoSchedule
          key: nvidia.com/gpu
          value: 'true'
```
**Versions**:
- Chart Version: tested with 0.33.1, 0.33.5, 0.34.6 (happy to move versions if this was a known bug).
- Kubernetes Version (`kubectl version`): 1.29

--------------------------
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
