### ISSUE TITLE
Validation errors occur due to CRD changes in the Karpenter 0.37 upgrade

### ISSUE THREAD

**Issue by st-cyrill** [aws/karpenter-provider-aws#6326]
### Description

**Observed Behavior**:

An error message is being logged `Reconciler error`

**Expected Behavior**:
No Error

**Reproduction Steps** (Please include YAML):

1. CRD Upgrade 0.37.0
2. Upgrade 0.37.0

I have noticed the following error message during the Karpenter 0.37 upgrade:

```
{"level":"ERROR","time":"2024-06-06T02:29:28.197Z","logger":"controller","message":"Reconciler error","commit":"490ef94","controller":"n
odeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"NODECLAIM_NAME"},"nam
espace":"","name":"NODECLAIM_NAME","reconcileID":"1a9d0bf6-e8b7-40c7-aadd-ec256c2b25bd","error":"NodeClaim.karpenter.sh \"<NODECLAIM_NAME>\" is invalid: [conditions[1].reason: Invalid value: \"\": conditions[1].reason in body should match '^[A-Za-z]([A
-Za-z0-9_,:]*[A-Za-z0-9_])?$', conditions[2].reason: Invalid value: \"\": conditions[2].reason in body should match '^[A-Za-z]([A-Za-z0-
9_,:]*[A-Za-z0-9_])?$', conditions[4].reason: Invalid value: \"\": conditions[4].reason in body should match '^[A-Za-z]([A-Za-z0-9_,:]*[
A-Za-z0-9_])?$']"}
```

I believe this is a validation error because the conditions.[*].reason does not exist in NodeClaims created by versions prior to 0.36. Could you relax the regular expression rules so that this error message does not appear after the 0.37 upgrade? (I think this discrepancy will occur until all NodeClaims switch to 0.37)

NodeClaim(0.36)
```
apiVersion: karpenter.sh/v1beta1
kind: NodeClaim
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "9205900624094331973"
    karpenter.k8s.aws/ec2nodeclass-hash-version: v2
    karpenter.k8s.aws/tagged: "true"
    karpenter.sh/nodepool-hash: "55912135702836999"
    karpenter.sh/nodepool-hash-version: v2
  creationTimestamp: "2024-06-04T19:32:55Z"
  finalizers:
  - karpenter.sh/termination
# ....
status:
  conditions:
  - lastTransitionTime: "2024-06-04T19:33:42Z"
    status: "True"
    type: Initialized
  - lastTransitionTime: "2024-06-04T19:32:57Z"
    status: "True"
    type: Launched
  - lastTransitionTime: "2024-06-04T19:33:42Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-06-04T19:33:29Z"
    status: "True"
    type: Registered
```

NodeClaim(0.37)

```
apiVersion: karpenter.sh/v1beta1
kind: NodeClaim
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "11409843810880919442"
    karpenter.k8s.aws/ec2nodeclass-hash-version: v2
    karpenter.k8s.aws/tagged: "true"
    karpenter.sh/nodepool-hash: "13293967534339224649"
    karpenter.sh/nodepool-hash-version: v2
  creationTimestamp: "2024-06-06T02:35:41Z"
  finalizers:
  - karpenter.sh/termination
# ...
status:
  conditions:
  - lastTransitionTime: "2024-06-06T02:36:18Z"
    message: ""
    reason: Initialized
    status: "True"
    type: Initialized
  - lastTransitionTime: "2024-06-06T02:35:44Z"
    message: ""
    reason: Launched
    status: "True"
    type: Launched
  - lastTransitionTime: "2024-06-06T02:36:18Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-06-06T02:36:07Z"
    message: ""
    reason: Registered
    status: "True"
    type: Registered
```

**Versions**:
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): 1.30.1

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
