### ISSUE TITLE
ta3.small instance type seems to be missing

### ISSUE THREAD

**Issue by ahollmann** [aws/karpenter-provider-aws#6327]
### Description

**Observed Behavior**: Instance type restricted to ta3. Karpenter started t3a.medium or t3a.large

**Expected Behavior**: Expected ta3.small instance, as resource requests are low enough. Adding t3 instance type made Karpenter to use t3.small.

Changing capacity-type to "on-demand" only resulted in the same behavior, as if t3a.small is completely missing.

**Reproduction Steps** (Please include YAML):
```
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
        - spot
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - t3a
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "2"
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
```

**Versions**:
- Chart Version: 0.36
- Kubernetes Version (`kubectl version`): 1.29
