### ISSUE TITLE
karpenter unable to launch windows instances with custom AMI gives no instance type satisfied resources

### ISSUE THREAD

**Issue by nujragan93** [aws/karpenter-provider-aws#6333]
### Description

**Observed Behavior**:
Ec2NodeClass
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: karpenter-windows2022
spec:
  amiFamily: Custom
  amiSelectorTerms:
    - id: ami-0***** 
  blockDeviceMappings:
    - deviceName: /dev/sda1
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 100Gi
        volumeType: gp3
  instanceProfile: *
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional
  securityGroupSelectorTerms: *
  subnetSelectorTerms: *
  userData: >-
    <powershell>

    [string]$EKSBootstrapScriptFile =
    "$env:ProgramFiles\Amazon\EKS\Start-EKSBootstrap.ps1"

    & $EKSBootstrapScriptFile -EKSClusterName 'test-cluster'
    -APIServerEndpoint
    'https://**********sk1.us-east-1.eks.amazonaws.com'
    -Base64ClusterCA
    '****'
    -KubeletExtraArgs
    '--node-labels="karpenter.sh/capacity-type=on-demand,tatenda.dev/custom-ami=ami-testami,karpenter.sh/nodepool=karpenter-windows2022,purpose=windows2022"
    --max-pods=110' -DNSClusterIP '172.20.0.10'

    </powershell>
   ```
Nodepool
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: karpenter-windows2022
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 4h0m0s
    consolidationPolicy: WhenEmpty
    expireAfter: Never
  template:
    metadata:
      labels:
        kubernetes.io/os: windows
        purpose: windows2022
    spec:
      nodeClassRef:
        name: karpenter-windows2022
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
        - key: kubernetes.io/os
          operator: In
          values:
            - windows
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-cpu
          operator: Lt
          values:
            - '50'
      taints:
        - effect: NoSchedule
          key: purpose
          value: windows2022
```
Observed Error:
```
 pod/windows-server-iis-ltsc2022-5fb755b6fb-78vw9    Failed to schedule pod, incompatible with nodepool "platform-test", daemonset overhead={"cpu":"298m","memory":"578452663","pods":"7"}, did not tolerate test-delegate=:NoSchedule; incompatible with nodepool "karpenter-windows2022", daemonset overhead={"pods":"0"}, no instance type satisfied resources {"cpu":"400m","memory":"512Mi","pods":"1","vpc.amazonaws.com/PrivateIPv4Address":"1"} and requirements karpenter.k8s.aws/instance-cpu Exists <50, karpenter.sh/capacity-type In [on-demand spot], karpenter.sh/nodepool In [karpenter-windows2022], kubernetes.io/arch In [amd64], kubernetes.io/os In [windows], purpose In [windows2022] (no instance type met the scheduling requirements or had enough resources); incompatible with nodepool "karpenter-upgrade-test", daemonset overhead={"cpu":"298m","memory":"578452663","pods":"7"}, did not tolerate purpose=test:NoSchedule; incompatible with nodepool "karpenter-default", daemonset overhead={"cpu":"308m","memory":"630881463","pods":"9"}, incompatible requirements, key kubernetes.io/os, kubernetes.io/os In [windows] not in kubernetes.io/os In [linux]
```
**Expected Behavior**:
Bring up windows instances and deploy windows pods

**Reproduction Steps** (Please include YAML):
deploy ec2nodeclass, nodepool and a test windows deployment

**Versions**:
- Chart Version: karpenter-0.35.2
- Kubernetes Version (`kubectl version`):  v1.29.1

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
