### ISSUE TITLE
Disruption not pre-spinning?

### ISSUE THREAD

**Issue by drawnwren** [aws/karpenter-provider-aws#6362]
### Description

**Observed Behavior**:
We have a nodepool of gpu nodes that has only one pod and expireAfter: 3h (to try and get put back onto spot if we are on an on-demand node). We're seeing karpenter take the node down every 3 hours and then schedule a new pod afterwards. So the first node fully terminates and then the new node is started. We're also having trouble reliably documenting this behavior. We can see it when we're watching the pods w/ `watch -n 5 kubectl get all`. Is there an easier way to double check what we're seeing?
**Expected Behavior**:
We expect karpenter to "Pre-spin any replacement nodes needed as calculated in Step (2), and wait for them to become ready." every 3 hours.
**Reproduction Steps** (Please include YAML):
```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: g5-family
spec:
  template:
    metadata:
      labels:
        xoul-ai: single-medium-gpu
    spec:
      nodeClassRef:
        name: g5-family
      # Define your provisioner spec here
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ['spot', 'on-demand']
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ['g5.xlarge']
      taints:
        - key: nvidia.com/gpu
          value: 'true'
          effect: 'NoSchedule'
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 3h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: g5-family
  annotations:
    kubernetes.io/description: 'Medium, single GPU instance for running background models'
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 150Gi
        volumeType: gp3
        encrypted: true
  role: 'KarpenterNodeRole-{{ .Values.settings.clusterName }}'
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: '{{ .Values.settings.clusterName }}'
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: '{{ .Values.settings.clusterName }}'
```
**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`):
