### ISSUE TITLE
Labels applied to nodes via NodePool generate requirements and subsequent errors

### ISSUE THREAD

**Issue by fullykubed** [aws/karpenter-provider-aws#6387]
### Description

**Observed Behavior**:

Labels added to `spec.template.metadata` of `NodePool` resources are added to the requirements array of generated `NodeClaim` resources.

If the number of labels exceeds 30, the following errors are generated:

```shell
NodeClaim.karpenter.sh \"spot-arm-tqsgl\" is invalid: [spec.requirements: Too many: 53: must have at most 30 items, <nil>: Invalid value: \"null\": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]"
```

*In practice, the error occurs with much fewer than 30 as you would likely have other requirements.*

**Expected Behavior**:

I imagine there is some intended purpose for propagating labels as requirements, but I am not sure what it might be.

I think that this should be opt-in behavior rather than the default (or it might be an outright bug). I do not know what benefit this would provide in the majority of circumstances, but it hinders the ability to apply labels that should not impact scheduling nodes (for example, for ownership and billing purposes).

At the very least, I think this behavior should be documented.

**Reproduction Steps** (Please include YAML):

This NodePool

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
spec:
  template:
    metadata:
      labels:
        foo: bar
```

would generated this `NodeClaim`

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodeClaim
spec:
  requirements:
  - key: foo
    operator: In
    values:
    - bar
```

**Versions**:
- Chart Version: `0.37.0`
- Kubernetes Version (`kubectl version`): `v1.29.4-eks-036c24b`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
