### ISSUE TITLE
Admission controller reject "app.kubernetes.io/managed-by" labels on Provisioner

### ISSUE THREAD

**Issue by loganmzz** [aws/karpenter-provider-aws#6399]
### Description

**Observed Behavior**:

When wanting to add ["standard" labels `app.kubernetes.io/*`](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) resource creation is rejected by adminission controller

**Expected Behavior**:

Being able to use any `app.kubernetes.io/*` labels.

**Reproduction Steps** (Please include YAML):

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: demo
  labels:
    "app.kubernetes.io/name": "demo" # OK
    "app.kubernetes.io/managed-from": "Git" # OK
    "app.kubernetes.io/managed-by: "Self" # FAILED
```

**Versions**:
- Chart Version: `0.31.5`
- Kubernetes Version (`kubectl version`): 

```plain
Client Version: v1.28.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9-eks-036c24b
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
