### ISSUE TITLE
Disruption via drift results in 4x the nodes being provisioned which aren't consolidated afterwards

### ISSUE THREAD

**Issue by AleksaC** [aws/karpenter-provider-aws#6426]
### Description

**Observed Behavior**:

The nodepool managed by karpenter is sitting at <20% utilization in terms of both CPU and memory requests. When I looked into the logs I came accross the following lines:

```
{"level":"INFO","time":"2024-06-27T19:38:01.744Z","logger":"controller","message":"disrupting via drift replace, terminating 1 nodes (33 pods) ip-10-3-157-84.eu-central-1.compute.internal/t3.xlarge/on-demand and replacing with 0 spot and 4 on-demand, from types t3.xlarge","commit":"490ef94","controller":"disruption","command-id":"1a2a64c0-2cef-4649-a0d7-014db1ff2409"}
...
{"level":"INFO","time":"2024-06-27T19:41:48.006Z","logger":"controller","message":"disrupting via drift replace, terminating 1 nodes (29 pods) ip-10-3-98-245.eu-central-1.compute.internal/t3.xlarge/on-demand and replacing with 0 spot and 3 on-demand, from types t3.xlarge","commit":"490ef94","controller":"disruption","command-id":"326df360-67ed-499b-b335-aa9a7bde2c54"}
...
{"level":"INFO","time":"2024-06-27T19:44:49.537Z","logger":"controller","message":"disrupting via drift replace, terminating 1 nodes (28 pods) ip-10-3-235-126.eu-central-1.compute.internal/t3.xlarge/on-demand and replacing with 0 spot and 3 on-demand, from types t3.xlarge","commit":"490ef94","controller":"disruption","command-id":"c86a04a9-c3d5-45b5-bb90-9c565ad7ba62"}
```
So karpenter replaced 3 nodes with 10 nodes of the same type after drift disruption. While I understand that the initial calculation may have been wrong, I'd expect consolidation to occur afterwards however for every node karpenter kept emitting the `Unconsolidatable` event:
```
Normal  Unconsolidatable   10m (x73 over 20h)  karpenter  Can't replace with a cheaper node
```

When I manually drained 3/4 nodes in one zone everything fit on the one remaining node.

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: general
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  limits:
    cpu: 1k
    memory: 1000Gi
  template:
    metadata: {}
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - t3
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - xlarge
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      taints:
        - effect: NoSchedule
          key: general
  weight: 100
```

In this particular case the limits are way too high as there will never be a need for even 10% of that, but even after fixing that the node pool would still be overprovisioned.

**Versions**: 
- Chart Version: `0.37.0`
- Kubernetes Version (`kubectl version`): `1.30`

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> The nodepool managed by karpenter is sitting at <20% utilization in terms of both CPU and memory requests

Can you share the deployment specs that you are using here?

**Comment by AleksaC** [comment]
There are probably >50 manifests. It would take a lot of time to redact potentially sensitive information and clean them up. I'll see if I can come up with an easier way to reproduce the issue. If I don't come up with anything I'll include them all.

**Comment by tm-nadavsh** [comment]
i have exactly the same issue, after changing the EC2nodeClass so that my nodes will have larger amount of disk, karpenter removed 4 nodes ( i have a default budget of 10%) created  maybe 6 or 7 nodes and i would assume it will consolidate as they are clearly underutilized. looking at the node events i get:
_Can't replace with a cheaper node_

clearly the nodes are underutilized and all of them or showing the _Can't replace with a cheaper node_

![Screenshot 2024-07-15 at 16 07 24](https://github.com/user-attachments/assets/b0d1bb12-d953-4aa7-9c54-ea91ee6bd479)

**Comment by AleksaC** [comment]
@jonathan-innis The issue occurred again for me, and I was able to up with a simple reproduction by cordoning one of the extra nodes and deleting the pods on it one by one until I was left with one and the daemonsets. Karpenter still wouldn't consolidate the node until I deleted the final pod.

I took the deployment of the pod (it was coredns) and managed to reproduce the issue on a separate node pool.

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: testing
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  limits:
    cpu: 20
    memory: 80Gi
  template:
    metadata: {}
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - t3
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - xlarge
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      taints:
        - effect: NoSchedule
          key: testing
  weight: 97
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testing
  name: testing
spec:
  replicas: 6
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - testing
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - image: k8s.gcr.io/pause 
        imagePullPolicy: IfNotPresent
        name: testing
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
      priorityClassName: system-cluster-critical
      tolerations:
      - effect: NoSchedule
        key: testing
        operator: Exists
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: testing
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
```

When I apply this karpenter tries creating 5 nodes for the 6 pods specified:

```console
$ k get nodes --selector=karpenter.sh/nodepool=testing

NAME                                            STATUS     ROLES    AGE   VERSION
ip-10-1-126-151.eu-central-1.compute.internal   NotReady   <none>   18s   v1.30.0-eks-036c24b
ip-10-1-178-129.eu-central-1.compute.internal   NotReady   <none>   17s   v1.30.0-eks-036c24b
ip-10-1-184-59.eu-central-1.compute.internal    NotReady   <none>   17s   v1.30.0-eks-036c24b
ip-10-1-196-117.eu-central-1.compute.internal   NotReady   <none>   17s   v1.30.0-eks-036c24b
ip-10-1-229-93.eu-central-1.compute.internal    NotReady   <none>   16s   v1.30.0-eks-036c24b
```

```console
$ k get pods -o wide

NAME                       READY   STATUS              RESTARTS   AGE   IP       NODE                                            NOMINATED NODE   READINESS GATES
testing-669988444c-9q4b2   0/1     ContainerCreating   0          55s   <none>   ip-10-1-178-129.eu-central-1.compute.internal   <none>           <none>
testing-669988444c-j4vd9   0/1     ContainerCreating   0          55s   <none>   ip-10-1-178-129.eu-central-1.compute.internal   <none>           <none>
testing-669988444c-ncqkr   0/1     ContainerCreating   0          55s   <none>   ip-10-1-178-129.eu-central-1.compute.internal   <none>           <none>
testing-669988444c-p4pd4   0/1     ContainerCreating   0          55s   <none>   ip-10-1-178-129.eu-central-1.compute.internal   <none>           <none>
testing-669988444c-qkmwl   0/1     ContainerCreating   0          55s   <none>   ip-10-1-178-129.eu-central-1.compute.internal   <none>           <none>
testing-669988444c-zpd9p   0/1     ContainerCreating   0          55s   <none>   ip-10-1-178-129.eu-central-1.compute.internal   <none>           <none>
```

One node becomes ready before the others and all pods get scheduled on it. If I let it stay like this karpenter would consolidate the remaining 4 nodes as they become ready. To prevent this I deleted one of the pods so it gets scheduled on another node. After I do this the two nodes karpenter keeps both nodes:

```console
$ k get pods -o wide

NAME                       READY   STATUS    RESTARTS   AGE   IP             NODE                                            NOMINATED NODE   READINESS GATES
testing-669988444c-9q4b2   1/1     Running   0          17m   10.1.157.17    ip-10-1-178-129.eu-central-1.compute.internal   <none>           <none>
testing-669988444c-ltwqp   1/1     Running   0          16m   10.1.193.174   ip-10-1-196-117.eu-central-1.compute.internal   <none>           <none>
testing-669988444c-ncqkr   1/1     Running   0          17m   10.1.160.85    ip-10-1-178-129.eu-central-1.compute.internal   <none>           <none>
testing-669988444c-p4pd4   1/1     Running   0          17m   10.1.177.198   ip-10-1-178-129.eu-central-1.compute.internal   <none>           <none>
testing-669988444c-qkmwl   1/1     Running   0          17m   10.1.144.6     ip-10-1-178-129.eu-central-1.compute.internal   <none>           <none>
testing-669988444c-zpd9p   1/1     Running   0          17m   10.1.166.136   ip-10-1-178-129.eu-central-1.compute.internal   <none>           <none>
```

Karpenter is unable to consolidate either of the nodes:

```console
k describe nodes --selector=karpenter.sh/nodepool=testing
Name:               ip-10-1-178-129.eu-central-1.compute.internal
...
Events:
  Type     Reason                   Age                 From                   Message
  ----     ------                   ----                ----                   -------
  ...
  Normal   Unconsolidatable         2m1s (x2 over 18m)  karpenter              Can't remove without creating 4 candidates

Name:               ip-10-1-196-117.eu-central-1.compute.internal
...
Events:
  Type     Reason                   Age                 From                   Message
  ----     ------                   ----                ----                   -------
  ...
  Normal   Unconsolidatable         2m2s (x2 over 18m)  karpenter              Can't replace with a cheaper node
```

Based on this it seems karpenter doesn't handle properly either the `preferredDuringSchedulingIgnoredDuringExecution` anti affinity or `ScheduleAnyway` topology spread constraint.
