### ISSUE TITLE
Consolidation deletes busy node instead of emptier one

### ISSUE THREAD

**Issue by offzale** [aws/karpenter-provider-aws#6452]
### Description

**Observed Behavior**:
Our clusters scale up every 30 minutes to be able to host all cronjobs. Consolidation usually works as expected and removes the node with fewer/no pods, which is the one that got created to run the cronjobs. However, after the cronjobs run, sometimes a node full of pods is deleted instead of the one empty or with very few pods running. 

At the time most cronjobs finish the cluster can run on fewer nodes. Therefore, the consolidation triggers the deletion of a node, but this less busy node (a couple pods left running maximum) is not picked up for deletion, instead a very busy node with around 50 pods is deleted.

I did not see anything on karpenter debug logs. However, running a node describe on the surviving node I found this:
```
Events:
  Type    Reason             Age                  From       Message
  ----    ------             ----                 ----       -------
  Normal  DisruptionBlocked  42m (x2 over 72m)    karpenter  Cannot disrupt Node: Nominated for a pending pod
```

- karpenter's chart is deployed with no custom values affecting its behaviour
- EC2NodeClass has no relevant values that affect consolidation decisions
- NodePools are configured as shown below

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: spot-general-purpose-burstable
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.large"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: kubernetes.io/os	
          operator: In	
          values:	
            - linux	
        - key: kubernetes.io/arch	
          operator: In	
          values:	
            - amd64
      kubelet:
        kubeReserved:
          cpu: 100m
          ephemeral-storage: 1Gi
          memory: 200Mi
        maxPods: 110
        systemReserved:
          cpu: 100m
          ephemeral-storage: 1Gi
          memory: 200Mi
  weight: 50
```

**Expected Behavior**:
I would expect karpenter takes that less busy node for deletion, although it has a pod nominated to run, instead of deleting a far less busy node, to cause the least disruption.

**Versions**:
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): v1.30.0-eks-036c24b

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
