### ISSUE TITLE
Scheduling issue for g5 instance

### ISSUE THREAD

**Issue by WxFang** [aws/karpenter-provider-aws#6475]
### Description

**Observed Behavior**:
Pod cannot be scheduled to g5.xlarge instance hence unable to scale up. The requested cpu and memory are both lower than the spec of g5.xlarge instance. Am I missing anything? 
```
incompatible with nodepool "gpu-g5", daemonset overhead={"cpu":"250m","memory":"2198Mi","pods":"6"}, no instance type satisfied resources {"cpu":"3250m","memory":"15510Mi","nvidia.com/gpu":"1","pods":"7"} and requirements karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [gpu-g5], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node.kubernetes.io/instance-type In [g5.xlarge], nodepool In [gpu-g5], nvidia.com/gpu In [true] (no instance type which had enough resources and the required offering met the scheduling requirements)
```
**Expected Behavior**:

**Reproduction Steps** (Please include YAML):
nodepool:
```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: gpu-g5
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  limits:
    cpu: 4k
    nvidia.com/gpu: 1k
  template:
    spec:
      nodeClassRef:
        name: gpu-g5
      requirements:
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - g5.xlarge
      - key: nvidia.com/gpu
        operator: In
        values:
        - "true"
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: nodepool
        operator: In
        values:
        - gpu-g5
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      taints:
      - effect: NoSchedule
        key: gpu-g5
        value: "true"
      - effect: NoSchedule
        key: nvidia.com/gpu
        value: "true"
```
pod spec:
```yaml
    resources:
      limits:
        cpu: "3"
        memory: 13Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "3"
        memory: 13Gi
        nvidia.com/gpu: "1"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nodepool
            operator: In
            values:
            - gpu-g5
  tolerations:
  - effect: NoSchedule
    key: gpu-g5
    operator: Equal
    value: "true"
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Equal
    value: "true"
```
**Versions**:
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): v1.29.4-eks-036c24b

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
