### ISSUE TITLE
Migrating pods from One NodePool to Another

### ISSUE THREAD

**Issue by bittracer** [aws/karpenter-provider-aws#6498]
### Description

**Observed Behavior**:

When migrating pods from one NodePool (al2) to another (al2023), all the new replica end up in a single EC2 instance in one az.

Here’s what I have in my manifest:

```
tolerations:
 - key: node-pool
   operator: “Equal"
   value: al2-pool -> During next redeployment I modify this to al2023-pool. Both these labels are present on the respective NodePool 

affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-pool
                  operator: In
                  values:
                      - al2-pool -> During next redeployment I modify this to al2023-pool. Both these labels are present on the respective NodePool 
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/app-name
                operator: In
                values:
                  - dev-hello-world
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/app-name
                operator: In
                values:
                  - dev-hello-world
```

 
 NodePool is standard with following label and toleration
 
 al2023
 
```
 labels:
   node-pool: al2023-pool

taints:
  - key: node-pool
    value: “al2023-pool”
    effect: NoSchedule
```
    
al2

```
 labels:
   node-pool: al2-pool

taints:
  - key: node-pool
    value: “al2-pool”
    effect: NoSchedule    
```

**Expected Behavior**:

When I have 3 replicas already deployed multi-az (3 az), I would expect that when migrating the same app from al2 to al2023 node pool, the apps are re-deployed across multiple az.  

I’ve also tried `matchLabelKeys` with `pod-template-hash` and that did not help either. 

Looking for any recommendations.

**Versions**:
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
