### ISSUE TITLE
Manage CRDs with Kustomize

### ISSUE THREAD

**Issue by KqLLL** [aws/karpenter-provider-aws#6542]
### Description

**What problem are you trying to solve?**
Want an easier way to manage CRDs updates.

**How important is this feature to you?**
You can use apply -k to directly select the directory where crd is deployed, without writing multiple files specified by apply -f.

Add the `kustomization.yaml` file to api/crds folder.
Example:
```yaml
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - karpenter.k8s.aws_ec2nodeclasses.yaml
  - karpenter.sh_nodeclaims.yaml
  - karpenter.sh_nodepools.yaml

```
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
