### ISSUE TITLE
Drift based on AMI not working 0.37.0

### ISSUE THREAD

**Issue by Rez0k** [aws/karpenter-provider-aws#6562]
### Description

**Observed Behavior**:
Karpenter version 0.37.0 - Changing the AMI won't replace nodes even though the status of the nodeclaim is:
```
- lastTransitionTime: "2024-07-21T08:59:41Z"
    message: AMIDrift
    reason: AMIDrift
    status: "True"
    type: Drifted
```
Karpenter not printing related logs

**Expected Behavior**:
The nodes should be drifted based on the budget policy.

**Reproduction Steps** (Please include YAML):
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: <gp-name>
spec:
  disruption:
    budgets:
    - nodes: 1
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  limits:
    memory: 150Gi
  template:
    metadata:
      labels:
        nodeGroup: <gp-name>
    spec:
      nodeClassRef:
        name: <gp-name>
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - r5.xlarge
        - r5a.xlarge
        - m5.xlarge
        - m5a.xlarge
        - c5.xlarge
        - c4.xlarge
        - c4a.xlarge
        - m4.xlarge
        - r4a.xlarge
        - m5a.large
        - m5.large
        - m6a.large
        - m6i.large
        - m6a.xlarge
        - m6i.xlarge
        - c6a.xlarge
        - c6i.xlarge
      taints:
      - effect: NoSchedule
        key: nodeGroup
        value: <gp-name>
```

I tried to change the budgets - to 100% or even delete it completly.
The nodeclaim has a status of:
```
- lastTransitionTime: "2024-07-21T08:59:41Z"
    message: AMIDrift
    reason: AMIDrift
    status: "True"
    type: Drifted
```

But nothing is getting updated.
note: karpenter is working great and creating new nodes with the new AMI but the old ones not getting replaced.

**Versions**: 0.37.0
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): 1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
