### ISSUE TITLE
Karpenter replacement for Autoscaler absolute failure

### ISSUE THREAD

**Issue by JakubSima** [aws/karpenter-provider-aws#6573]
### Description

**Observed Behavior**:
I have recently replaced Autoscaler with Karpenter as it is allegedly a smarter solution that can even save some costs. I use it in an EKS cluster. However, the costs are actually double compared to when I was using Autoscaler, and stateful sets like Prometheus are often down in a Terminating state. The nodes are in a NoSchedule state, and nothing is happening. As a result, the cluster runs with double the nodes and services are down. I wonder what the cause could be, especially since I have read so many good things about Karpenter.

Gitlab pipelines are the worst with Karpeneter. The pipeline failure increased by 70% and does not matter if I use SPOT or ON DEMAND._

**Expected Behavior**:

Costs should be at least the same as with Autoscaler, GitLab jobs should not be interrupted, and pods should not be stuck in a Terminating state.

**Reproduction Steps** (Please include YAML):

```
 apiVersion: karpenter.sh/v1beta1
    kind: NodePool
    metadata:
      name: gitlab-runner
    spec:
      template:
        metadata:
          labels:
            type: gitlab-runner
        spec:
          nodeClassRef:
            apiVersion: karpenter.k8s.aws/v1beta1
            kind: EC2NodeClass
            name: default
          requirements:
            - key: "kubernetes.io/arch"
              operator: In
              values: ["amd64"]
            - key: "karpenter.sh/capacity-type"
              operator: In
              values: ["on-demand"]
          taints:
            - effect: NoSchedule
              key: gitlab-runner
      limits:
        cpu: 100
      disruption:
        consolidationPolicy: WhenUnderutilized
        expireAfter: 12h
        budgets:
        - duration: 45m
          nodes: "0"
          schedule: '@hourly'
```
```
    apiVersion: karpenter.sh/v1beta1
    kind: NodePool
    metadata:
      name: infrastructure
    spec:
      template:
        metadata:
          labels:
            kubernetes.node_type: infrastructure
        spec:
          nodeClassRef:
            apiVersion: karpenter.k8s.aws/v1beta1
            kind: EC2NodeClass
            name: default
          requirements:
            - key: "karpenter.k8s.aws/instance-category"
              operator: In
              values: ["m", "t"]
            - key: "karpenter.k8s.aws/instance-family"
              operator: In
              values: ["t3", "m5"]
            - key: "karpenter.k8s.aws/instance-memory"
              operator: Gt
              values: ["2048"]
            - key: "karpenter.k8s.aws/instance-hypervisor" 
              operator: In
              values: ["nitro"]
            - key: "kubernetes.io/arch"
              operator: In
              values: ["amd64"]
            - key: "karpenter.sh/capacity-type"
              operator: In
              values: ["on-demand"]
      limits:
        cpu: 10
      disruption:
        consolidationPolicy: WhenUnderutilized
        expireAfter: 720h
        budgets:
        - duration: 14h
          nodes: "0"
          schedule: 0 6 * * mon-fri

```

**Versions**:
- Chart Version: "0.37.0"
- Kubernetes Version (`kubectl version`): 1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
