### ISSUE TITLE
What would happen if I set it up the disruption policy like this?

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter-provider-aws#6579]
Are the results of both cases that nodes are not recycled even if they are empty?

- case1:

```
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: Never
    expireAfter: Never
    budgets:
    - nodes: 10%
```

- case2:

```
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: Never
    budgets:
    - schedule: "0 1 * * mon-sun"
      duration: 24h
      nodes: "0"
```
