### ISSUE TITLE
Question about Drift behavior when wildcard in the name of amiSelectorTerms

### ISSUE THREAD

**Issue by kyleli666** [aws/karpenter-provider-aws#6632]
I'd like to upgrade node just by changing the name of amiSelectorTerms. I do like this:
```
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
    - name: 'bottlerocket-aws-k8s-1.30-x86_64*'
```
I'm just wondering about the wildcard '*' part.
There can be some version upgrade of the ami, like from _bottlerocket-aws-k8s-1.29-x86_64-**v1.20.0-fcf71a47**_ to _bottlerocket-aws-k8s-1.29-x86_64-**v1.20.1-7c3e9198**_, will a drift automatically happen in this case? 
I'd like to avoid this drift.
Thank you!
