### ISSUE TITLE
Unexpectectly high number of node replacements when using the WhenUnderutilized consolidation policy

### ISSUE THREAD

**Issue by 617m4rc** [aws/karpenter-provider-aws#6642]
### Description

**Observed Behavior**:

We are experimenting with the consolidation policy in our clusters and see that the amount of node replacement increases drastically and remains permanently high after switching to the WhenUnderutilized policy. More specifically, Karpenter permanently trades M6a instances to C6a and vice-versa, which seems pointless and which we would like to avoid. 

The workloads in our clusters are mostly stable, so no pods are added or removed, which could encourage this behavior. I'm attaching a log excerpt of a random affected cluster with 17 worker nodes. All worker nodes are replaced by Karpenter within a single week.

Is this caused by a misconfiguration on our end or is it the expected behavior? Can we do anything to get a better understanding of the reason for the disruptions?

```
{"level":"INFO","time":"2024-07-31T20:01:11.558Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 2 nodes (9 pods) ip-10-0-137-165.eu-central-1.compute.internal/c6a.4xlarge/on-demand, ip-10-0-139-10.eu-central-1.compute.internal/c6a.4xlarge/on-demand and replacing with on-demand node from types m6a.4xlarge","commit":"e719109","command-id":"f44014e9-2569-4398-8a9f-26879d321172"}
{"level":"INFO","time":"2024-07-31T20:03:50.904Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 2 nodes (12 pods) ip-10-0-147-118.eu-central-1.compute.internal/c6a.4xlarge/on-demand, ip-10-0-147-38.eu-central-1.compute.internal/c6a.4xlarge/on-demand and replacing with on-demand node from types m6a.4xlarge, m7a.4xlarge","commit":"e719109","command-id":"c831772e-90c1-4cf1-b742-942d31903760"}
{"level":"INFO","time":"2024-07-31T21:15:58.034Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 2 nodes (15 pods) ip-10-0-136-19.eu-central-1.compute.internal/c6a.4xlarge/on-demand, ip-10-0-139-139.eu-central-1.compute.internal/m6a.4xlarge/on-demand and replacing with on-demand node from types c6a.8xlarge","commit":"e719109","command-id":"c7063eaf-7e6d-4383-a295-c944dc4d7b8b"}
{"level":"INFO","time":"2024-08-01T19:01:03.539Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 1 nodes (20 pods) ip-10-0-138-9.eu-central-1.compute.internal/c6a.8xlarge/on-demand and replacing with on-demand node from types m6a.4xlarge","commit":"e719109","command-id":"95b93dda-bc69-4f6e-9b49-a43b1173759e"}
{"level":"INFO","time":"2024-08-01T19:02:28.854Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 2 nodes (17 pods) ip-10-0-141-64.eu-central-1.compute.internal/c6a.4xlarge/on-demand, ip-10-0-143-17.eu-central-1.compute.internal/c6a.4xlarge/on-demand and replacing with on-demand node from types m6a.4xlarge, m7a.4xlarge","commit":"e719109","command-id":"8b7e8770-3012-42ad-8afe-a4b53b19ed8e"}
{"level":"INFO","time":"2024-08-01T19:04:08.045Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 2 nodes (23 pods) ip-10-0-147-163.eu-central-1.compute.internal/c6a.4xlarge/on-demand, ip-10-0-147-199.eu-central-1.compute.internal/c6a.4xlarge/on-demand and replacing with on-demand node from types m6a.4xlarge, m7a.4xlarge","commit":"e719109","command-id":"033b06b6-9d4d-4711-bfcf-66d98ce04d58"}
{"level":"INFO","time":"2024-08-01T21:15:52.265Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 1 nodes (20 pods) ip-10-0-136-101.eu-central-1.compute.internal/m6a.4xlarge/on-demand and replacing with on-demand node from types c6a.4xlarge","commit":"e719109","command-id":"8b2a09e5-e9dd-4aa0-8212-84c281d599f4"}
{"level":"INFO","time":"2024-08-01T21:17:21.188Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 1 nodes (23 pods) ip-10-0-138-178.eu-central-1.compute.internal/m6a.4xlarge/on-demand and replacing with on-demand node from types c6a.4xlarge","commit":"e719109","command-id":"ab5dfbc6-307f-4e23-a145-294d4d9adc99"}
{"level":"INFO","time":"2024-08-01T21:18:14.797Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 1 nodes (23 pods) ip-10-0-147-173.eu-central-1.compute.internal/m6a.4xlarge/on-demand and replacing with on-demand node from types c6a.4xlarge","commit":"e719109","command-id":"698848bb-ed43-4c09-8574-dfe705b5dd0d"}
{"level":"INFO","time":"2024-08-01T21:21:08.395Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 2 nodes (9 pods) ip-10-0-139-203.eu-central-1.compute.internal/c6a.4xlarge/on-demand, ip-10-0-137-132.eu-central-1.compute.internal/c6a.4xlarge/on-demand and replacing with on-demand node from types m6a.4xlarge","commit":"e719109","command-id":"02f2a929-138c-4122-8aaa-43c6540cde3e"}
{"level":"INFO","time":"2024-08-01T21:23:56.583Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 2 nodes (17 pods) ip-10-0-138-20.eu-central-1.compute.internal/c6a.4xlarge/on-demand, ip-10-0-139-16.eu-central-1.compute.internal/c6a.4xlarge/on-demand and replacing with on-demand node from types m6a.4xlarge","commit":"e719109","command-id":"e2d9535c-f82c-4df7-a60a-a94bcb35f76c"}
{"level":"INFO","time":"2024-08-01T21:28:40.402Z","logger":"controller.disruption","message":"disrupting via consolidation replace, terminating 2 nodes (9 pods) ip-10-0-147-17.eu-central-1.compute.internal/c6a.4xlarge/on-demand, ip-10-0-144-14.eu-central-1.compute.internal/c6a.4xlarge/on-demand and replacing with on-demand node from types m6a.4xlarge, m7a.4xlarge","commit":"e719109","command-id":"7d1e8486-c8b4-4fc8-a34c-af4974c72691"}
```

**Expected Behavior**:

The number of node replacements increases only temporarily and settles at a low level.

**Reproduction Steps** (Please include YAML):

Have an EKS cluster with Karpenter and the below described node pool. Observe cluster behavior over time.

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  disruption:
    budgets:
    - nodes: 10%
    - duration: 12h
      nodes: "0"
      schedule: 0 7 * * mon-fri
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  template:
    metadata:
      labels:
        nodetype: regular
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - m7a
        - c7a
        - m6a
        - c6a
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "16"
        - "24"
        - "32"
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-encryption-in-transit-supported
        operator: In
        values:
        - "true"
  weight: 30
```

**Versions**:
- Chart Version: 0.36.2
- Kubernetes Version (`kubectl version`): v1.29.5-eks-1de2ab1

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
