### ISSUE TITLE
launching nodeclaim, resolving ec2nodeclass, Failed to resolve security groups"

### ISSUE THREAD

**Issue by davidt-gh** [aws/karpenter-provider-aws#6650]
### Description

**Observed Behavior**:
Got this error:
```
{"level":"ERROR","time":"2024-08-05T12:02:06.478Z","logger":"controller","message":"Reconciler error","commit":"490ef94","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-gz4qh"},"namespace":"","name":"default-gz4qh","reconcileID":"bd28f5c0-44e3-4b7a-a540-d9ccd8b827ba","error":"launching nodeclaim, resolving ec2nodeclass, Failed to resolve security groups"}

```

**Expected Behavior**:
Not getting errors

**Reproduction Steps** (Please include YAML):
Apply karpenter 0.37.0
Values.yaml
```
  settings:
    clusterName: "<cluster-name>"
    interruptionQueue: "<cluster-name>"
  serviceAccount:
    annotations:
      "eks.amazonaws.com/role-arn": "arn:aws:iam::<account-number>:role/<cluster-name>-karpenter"
  controller:
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
```
templates:
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role:  "arn:aws:iam::<account-number>:role/<cluster-name>-karpenter"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.settings.clusterName }}
    - id: subnet-****************
    - id: subnet-****************
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.settings.clusterName }}
  amiSelectorTerms:
    - id: "ami-07a876f98b5bdf972"
```
AND
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "us-east-1a","us-east-1b" ]
      nodeClassRef:
        name: default
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h

```  

**Versions**:
- Chart Version:  0.37.0
- Kubernetes Version (`kubectl version`): 
```
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2-eks-db838b0
```
