### ISSUE TITLE
Karpenter Consolidation Not Gracefully Draining Nodes, Resulting in Pod Termination and Recreation

### ISSUE THREAD

**Issue by Shreyank031** [aws/karpenter-provider-aws#6660]
### Description

**Observed Behavior**: When using Karpenter with consolidation: WhenUnderutilized, nodes are not gracefully draining pods. Instead, the pods are terminated and then redeployed to new nodes. The pods' age starts from 0, indicating they are being recreated rather than being gracefully evicted and rescheduled.

**Expected Behavior**: Karpenter should gracefully drain the nodes by evicting the pods and rescheduling them on new nodes without terminating the pods. The pods should maintain their state and not restart from scratch.

**Reproduction Steps** (Please include YAML):
1. Create a NodePool with the following configuration:
```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: karpenter-beta
spec:
  template:
    metadata:
      labels:
        team: devops
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: [linux]
        - key: karpenter.sh/capacity-type
          operator: In
          values: [spot]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-south-1a", "ap-south-1b", "ap-south-1c"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["c6g","c7g"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: [2]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
  limits:
    cpu: 1000
disruption:
  consolidationPolicy: WhenUnderutilized
  expireAfter: 720h # 30 * 24h = 720h
```

2. Observe the behavior when Karpenter consolidates underutilized nodes.

**Versions**:
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
