### ISSUE TITLE
Feature request: More flexible requirements for NodePools

### ISSUE THREAD

**Issue by mrparkers** [aws/karpenter-provider-aws#6676]
### Description

**What problem are you trying to solve?**

I have a generic `NodePool` that's used by a majority of my workloads, which has pretty lose requirements, except that it puts a floor on the number of CPUs so that my cluster is comprised of fewer, larger nodes (instead of more nodes that are smaller):

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: arm
spec:
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
        - key: "kubernetes.io/os"
          operator: In
          values: ["linux"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: Gt
          values: ["15"]
  weight: 90
```

However, I want to make an exception to this idea of preferring larger nodes for memory-optimized instances:  I'd like to allow for a minimum of 7 CPUs specifically for the `r` instance category, such that a `r6g.2xlarge` could be used.  There does not seem to be a good way to fit this exception in my existing `NodePool`, which would require me to make another one, and update specific workloads to select that `NodePool` instead.

While this works, it would be nice if I could have more flexible node requirements, so I could say something like: "The `c` and `m` instance categories should have a minimum of 15 CPUs, but the `r` instance category can have a minimum of 7 CPUs"

**How important is this feature to you?**

It would be nice to have so I didn't have to manage more nodepools and specific requirements for some workloads.

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
