### ISSUE TITLE
Helm chart: Allow overriding container image url for post-install-job

### ISSUE THREAD

**Issue by rubel-ahammad** [aws/karpenter-provider-aws#6701]
### Description

I am trying to install Karpenter in AWS Gov Cloud. Since we do not have access to public.ecr.aws registry there, Karpenter isn't able to start post-install-job because it cannot download the container image from public.ecr.aws.

Allowing to override the image url is absolutely necessary for those who do not have access to public.ecr.aws registry. 

We can add a new property in the helm chart as given below.
```
webhook:
  image: 
    repository: <image-repository>
    tag: <image-tag>
```

Please let us know your thoughts. If you agree to this change, I can submit a PR.
