### ISSUE TITLE
Karpenter Provisioned Node Does Not Reflect Configuration

### ISSUE THREAD

**Issue by thenithishrajan** [aws/karpenter-provider-aws#6702]
### Description

**Observed Behavior**:
I have configured Karpenter to provision an EC2(fargate) instance of type g6.2xlarge, but the provisioned node only shows 2 vCPUs and does not have a GPU(maybe it didn't even use my provided config?). Despite changing the instance type and other parameters, the issue persists.

**Expected Behavior**:
The node provisioned by Karpenter should match the specified configuration, including all the resources indicated by the g6 instance type.

**Reproduction Steps** (Please include YAML):

**EC2NodeClass:**
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: nvidia-gpu
spec:
  amiFamily: AL2 
  role: karpenter-${cluster_name}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
  tags:
    karpenter.sh/discovery: ${cluster_name}
  instanceStorePolicy: RAID0
```

**NodePool:**
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: nvidia-gpu
spec:
  template:
    metadata:
      labels:
        nvidia.com/gpu.present: "true"
    spec:
      nodeClassRef:
        name: nvidia-gpu
      taints:
        - key: nvidia.com/gpu
          effect: NoSchedule
          operator: Exists
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["g6"]
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values: ["2xlarge"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
  limits:
    cpu: 100
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
```

Terraform configuration:
```
resource "kubectl_manifest" "karpenter" {
  for_each = fileset("${path.module}/karpenter", "*.yaml")

  yaml_body = templatefile("${path.module}/karpenter/${each.key}", {
    cluster_name = module.eks.cluster_name
  })

  depends_on = [module.core_addons]
}
```

**Additional Information**:

```
Name:               fargate-ip-10-10-25-116.us-west-1.compute.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    eks.amazonaws.com/compute-type=fargate
                    failure-domain.beta.kubernetes.io/region=us-west-1
                    failure-domain.beta.kubernetes.io/zone=us-west-1c
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=fargate-ip-10-10-25-116.us-west-1.compute.internal
                    kubernetes.io/os=linux
                    topology.kubernetes.io/region=us-west-1
                    topology.kubernetes.io/zone=us-west-1c
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Mon, 12 Aug 2024 00:36:42 +0530
Taints:             eks.amazonaws.com/compute-type=fargate:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  fargate-ip-10-10-25-116.us-west-1.compute.internal
  AcquireTime:     <unset>
  RenewTime:       Mon, 12 Aug 2024 02:14:23 +0530
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Mon, 12 Aug 2024 02:14:10 +0530   Mon, 12 Aug 2024 00:36:42 +0530   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Mon, 12 Aug 2024 02:14:10 +0530   Mon, 12 Aug 2024 00:36:42 +0530   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Mon, 12 Aug 2024 02:14:10 +0530   Mon, 12 Aug 2024 00:36:42 +0530   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Mon, 12 Aug 2024 02:14:10 +0530   Mon, 12 Aug 2024 00:36:42 +0530   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:   10.10.25.116
  InternalDNS:  ip-10-10-25-116.us-west-1.compute.internal
Capacity:
  cpu:                2
  ephemeral-storage:  30787492Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             3943308Ki
  pods:               1
Allocatable:
  cpu:                2
  ephemeral-storage:  17308964Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             3840908Ki
  pods:               1
System Info:
  Machine ID:                 
  System UUID:                ec27c460-fcc2-c300-d0f6-da959d101acd
  Boot ID:                    b30a224f-3a33-4fb2-884d-d819e80d7a4b
  Kernel Version:             5.10.220-209.869.amzn2.x86_64
  OS Image:                   Amazon Linux 2
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.7.11
  Kubelet Version:            v1.29.0-eks-680e576
  Kube-Proxy Version:         v1.29.0-eks-680e576
ProviderID:                   aws:///us-west-1c/ca02c4924e-fad93f7d19744701aece2f9d6c4f1f9f/fargate-ip-10-10-25-116.us-west-1.compute.internal
Non-terminated Pods:          (1 in total)
  Namespace                   Name                          CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                          ------------  ----------  ---------------  -------------  ---
  karpenter                   karpenter-6b95785dd7-sbzr2    0 (0%)        0 (0%)      0 (0%)           0 (0%)         98m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
  hugepages-1Gi      0 (0%)    0 (0%)
  hugepages-2Mi      0 (0%)    0 (0%)
Events:              <none>
```

**Versions:**
```
terraform {
  required_version = ">= 1.3"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.59"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.14"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.31"
    }
    kubectl = {
      source  = "alekc/kubectl"
      version = ">= 2.0"
    }
  }
}
```
