### ISSUE TITLE
Karpenter Node Claims Stalled by EC2 Launch Failures

### ISSUE THREAD

**Issue by JacobAmar** [aws/karpenter-provider-aws#6723]
### Description

**Observed Behavior**:

We experienced prolonged (~15 minute) delays in node provisioning due to AWS experiencing internal issues launching c6 instances in us-east-1f (and intermittently us-east-1b). The problem was visible in the EC2 console and not related to capacity constraints.

Currently, Karpenter takes an extended time to react and recover from such failures. 

**Expected Behavior**:

- **Faster Failure Detection and Response:** Quicker retries or fallback mechanisms (e.g., different instance types, AZs) when launch failures occur.
- **Improved Communication:** Clearer logs/events to distinguish launch failures from capacity issues and communicate Karpenter's response.
- **Potential Configuration Options:** Allow users to fine-tune timeouts or thresholds for handling consecutive launch failures.

**Reproduction Steps**:
1. create the node pool
2. create the pod using the deploy.yaml
### nodepool.yaml

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels:
    argocd.argoproj.io/instance: karpenter-resources
  name: test-node-pool
spec:
  disruption:
    expireAfter: Never
  template:
    metadata:
      labels:
        project: test-node-pool
    spec:
      requirements:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - us-east-1c
            - us-east-1f
            - us-east-1b
            - us-east-1d
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values:
            - nano
            - micro
            - small
            - large
            - 12xlarge
            - 16xlarge
            - 18xlarge
            - 24xlarge
            - 32xlarge
            - 36xlarge
            - 48xlarge
            - metal
            - metal-48xl
            - metal-24xl
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - c6i
            - c6in
            - m6i
            - m6in
            - m6id
            - r6i
            - r6id
            - c7i
            - m7i
            - r7i
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux

```

### Deploy.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 20
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector:
         topology.k8s.aws/zone-id: use1-az5
         node.kubernetes.io/instance-type: c6i.8xlarge
         project: test-node-pool
      containers:
      - name: my-app
        image: nginx:latest
        resources:
          requests:
            cpu: "28"
            memory: "40Gi"
          limits:
            memory: "40Gi"

```
**Explenation**:
- The provisioner is configured to use only spot instances.
- It explicitly targets the use1-az5 zone using a node affinity rule.
- If spot capacity for this instance type is low in use1-az5, the observed issue may occur.

**Versions**:
- Chart Version: `0.37.0`
- Kubernetes Version (`kubectl version`):
```bash
  Client Version: v1.28.4
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.29.6-eks-db838b0
```
