### ISSUE TITLE
Post Install Hook doesn't ever sync via ArgoCD

### ISSUE THREAD

**Issue by danielloader** [aws/karpenter-provider-aws#6765]
### Description

**Observed Behavior**:

Due to https://github.com/aws/karpenter-provider-aws/blob/a70356ac2224e93d09372994a790fbdcad9cbc0f/charts/karpenter/templates/post-install-hook.yaml#L15 in conjunction with this issue https://github.com/argoproj/argo-cd/issues/6880#issuecomment-2274495939 means the hook never syncs and installation via ArgoCD isn't possible.

**Expected Behavior**:

Chart syncs via ArgoCD installation.

**Reproduction Steps** (Please include YAML):

Install the karpenter chart via ArgoCD and default values.

**Versions**:
- Chart Version: 1.0.0
- Kubernetes Version (`kubectl version`): 1.30.0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Vinaum8** [comment]
I installed karpenter in a separate namespace and with a different service name than the default.

**I can't configure the values ​​for the webhook** and it returns the error:

`service: karpenter not found.`

However, **it is obvious** that I did not create the service with this name in the kube-system namespace.

`I am using version 0.37.1 and I installed karpenter with ArgoCD.`

**Comment by inclemenstv** [comment]
I had the same bug when I tried to install Karpenter using Argo cd
Chart Version: 1.0.0

**Comment by snieg** [comment]
> I had the same bug when I tried to install Karpenter using Argo cd Chart Version: 1.0.0

Same here. As a temporary solution, I had to edit each CRD and change the namespace to the proper one.

![image](https://github.com/user-attachments/assets/503abfd8-cd73-4220-8f2a-4b187361d14d)

**Comment by inclemenstv** [comment]
> > I had the same bug when I tried to install Karpenter using Argo cd Chart Version: 1.0.0
> 
> Same here. As a temporary solution, I had to edit each CRD and change the namespace to the proper one.
> 
> ![image](https://private-user-images.githubusercontent.com/35065344/358571775-503abfd8-cd73-4220-8f2a-4b187361d14d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDkwNDgsIm5iZiI6MTcyMzgwODc0OCwicGF0aCI6Ii8zNTA2NTM0NC8zNTg1NzE3NzUtNTAzYWJmZDgtY2Q3My00MjIwLThmMmEtNGIxODczNjFkMTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDExNDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYjQyNGJmMTNkZmZkZmNiMWY1YTVmODY0OGUyNjQ3M2EzNTI2NGFmNzEzNTFhOWY0NjAyNzZkNWE3NThlMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._TqVPbOZOdijx7exK_dCGwVoxpnzMqDeyG3P9-ZTjmc)

yes I have same DIFF did you install Karpenter-crd chart separatly from karpenter main chart?  and did you edit CRD manually?

**Comment by snieg** [comment]
> yes I have same DIFF did you install Karpenter-crd chart separatly from karpenter main chart? and you edited CRD manually?

I installed it from the [main](https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/Chart.yaml) chart and edited manually.

**Comment by Vinaum8** [comment]
> > yes I have same DIFF did you install Karpenter-crd chart separatly from karpenter main chart? and you edited CRD manually?
> 
> I installed it from the [main](https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/Chart.yaml) chart and edited manually.

@snieg has your argocd gone out of sync?

**Comment by snieg** [comment]
> > > yes I have same DIFF did you install Karpenter-crd chart separatly from karpenter main chart? and you edited CRD manually?
> > 
> > 
> > I installed it from the [main](https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/Chart.yaml) chart and edited manually.
> 
> @snieg has your argocd gone out of sync?

Yes, after editing CRDs, ArgoCD shows "out of sync" now.

Luckily, I only updated one cluster, I'll hold off on updating until the stable version is actually stable. ;)

**Comment by virtualdom** [comment]
I'm seeing the same behavior when upgrading to v0.35.6 (prerequisite to upgrading to v1.0.0)

**Comment by engedaam** [comment]
Can you relay on the `karpenter-crd` helm chart as the mechanism to maintain the CRDs? https://karpenter.sh/v1.0/upgrading/upgrade-guide/#crd-upgrades We have values there that allows you to edit the conversion block. https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter-crd/values.yaml

**Comment by inclemenstv** [comment]
> Can you relay on the `karpenter-crd` helm chart as the mechanism to maintain the CRDs? https://karpenter.sh/v1.0/upgrading/upgrade-guide/#crd-upgrades We have values there that allows you to edit the conversion block. https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter-crd/values.yaml

I tried to install Karpenter-crd using ArgoCD but when I install main karpenter I had diff 
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/38f3c972-4ed2-43d1-ac86-fa65be7c4d2b">
 because I can't to change service:
          name: karpenter	          name: karpenter
          namespace: karpenter-fargate	          namespace: kube-system

**Comment by engedaam** [comment]
What namespace are you intending to run the Karpenter controller? In `karpenter-fargate`? If so, did you include `--set webhook.serviceNamespace` as part of the `karpenter-crd` helm upgrade?

**Comment by inclemenstv** [comment]
> What namespace are you intending to run the Karpenter controller? In `karpenter-fargate`? If so, did you include `--set webhook.serviceNamespace` as part of the `karpenter-crd` helm upgrade?

yes I had following values.yaml
`  webhook:
    # -- Whether to enable the webhooks and webhook permissions.
    enabled: true
    serviceName: karpenter
    serviceNamespace: karpenter-fargate
    # -- The container port to use for the webhook.
    port: 8443
`

But when I install karpenter it tries to change the namespace to cube-system

**Comment by inclemenstv** [comment]
also argocd is waiting for completion of hook batch/Job/karpenter-post-install-hook
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/d5a4f21c-485e-42de-96ae-caecdd7d64d0">
but I checked karpenter-post-install-hook job and it finished 
`customresourcedefinition.apiextensions.k8s.io/nodepools.karpenter.sh patched
customresourcedefinition.apiextensions.k8s.io/nodeclaims.karpenter.sh patched
customresourcedefinition.apiextensions.k8s.io/ec2nodeclasses.karpenter.k8s.aws patched`

**Comment by engedaam** [comment]
Yes, the post install hook will run and patch the CRDs to make the karpenter service consistent with the helm chart in the Karpenter controller. You can disable the post install hook by setting `--no-hooks` as part of the karpenter helm chart, but keep in mind that the service could be different then what is specified for the karpenter controller.

**Comment by inclemenstv** [comment]
> Yes, the post install hook will run and patch the CRDs to make the karpenter service consistent with the helm chart in the Karpenter controller. You can disable the post install hook by setting `--no-hooks` as part of the karpenter helm chart, but keep in mind that the service could be different then what is specified for the karpenter controller.

But I deploying Karpenter-crd and karpenter using ArgoCD and I can't use --no-hooks

**Comment by danielloader** [comment]
It's worth interjecting here, as far as I can tell _without making ttlSecondsAfterFinished value larger than 0_ ArgoCD can never install this chart, no matter how you fiddle it. 

The only other option available to me is to use a tool like kyervno to put a mutation webhook on the job and enforce this change in the cluster, but that's a lot of moving parts and things that can go wrong to be able to change an integer in a manifest.

**Comment by snieg** [comment]
> Yes, the post install hook will run and patch the CRDs to make the karpenter service consistent with the helm chart in the Karpenter controller. (...)
I'm using the [main](https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/Chart.yaml) Chart (because it contains both CRD and controller deployment).

And ArgoCD never reaches the post-hook moment (as described in the main message). 

Because the newly installed CRDs have a [hardcoded](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml#L1342) namespace `kube-system` so everything stops, because ArgoCD gets stuck because it is unable to list the current resources (because it's looking for a service in the wrong namespace) and therefore it never reaches the post-hook part.

**Comment by danielloader** [comment]
Guess if there's a desire to force this into kube-system namespace, might be pertinent to swap all the `namespace: {{ .Release.Namespace }}` on the objects to `namespace: kube-system` and take the choice away formally.

**Comment by Vinaum8** [comment]
> Guess if there's a desire to force this into kube-system namespace, might be pertinent to swap all the `namespace: {{ .Release.Namespace }}` on the objects to `namespace: kube-system` and take the choice away formally.

@danielloader  The ideal is to leave it dynamic for the user to choose.

**Comment by snieg** [comment]
> Can you relay on the `karpenter-crd` helm chart as the mechanism to maintain the CRDs? https://karpenter.sh/v1.0/upgrading/upgrade-guide/#crd-upgrades We have values there that allows you to edit the conversion block. https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter-crd/values.yaml

Even if I install CRDs using helm chart's karpenter-crds. The helm chart with the controller will also try to install CRDs and they will overlap so it will try to restore the namespace to `kube-system`.

An optional solution would be the ability to parameterize in the values whether to install or not install CRDs via the controller helm chart and disable the post-hook from the helm template.

... or put the CRDs into the template and the ability to set the namespace from values.

**Comment by Vinaum8** [comment]
@snieg @engedaam Some helm charts have the option to install or not the CRDs, I think it would be interesting to add karpenter/karpenter to the helm chart, this would help to have an alternative.

example:
```
crds:
  # This option decides if the CRDs should be installed
  # as part of the Helm installation.
  enabled: false
```

**Comment by tico24** [comment]
You have the option to do this with Argo CD by passing in the skip-crd flag even if the values file doesn't offer it (assuming you are using the `helm` feature of Argo CD directly.. which I unfortunately am not.

https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-skip-crds

**Comment by thomasgouveia** [comment]
Is there any reason why the `karpenter` chart doesn't declare a dependency on `karpenter-crd`?

If it did, it would be straightforward to control whether to deploy the CRDs (as mentioned above by [@Vinaum8](https://github.com/aws/karpenter-provider-aws/issues/6765#issuecomment-2294993359)) as part of the release. Additionally, it would allow the ability to customize the values passed to the `karpenter-crd`, without needing to install it in a dedicated release. For example:

```yaml
crds:
  enabled: false

  # Custom values to be passed to karpenter-crd dependency
  serviceNamespace: my-custom-namespace
```

**If anyone here struggles with CRDs that are out of sync using ArgoCD** (caused by the namespace that is updated by the post-install hook job), you can **temporarily** work around this issue by using the `ignoreDifferences` block in your application template:

```yaml
ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: nodepools.karpenter.sh
    jsonPointers:
      - /spec/conversion/webhook/clientConfig/service/namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: ec2nodeclasses.karpenter.k8s.aws
    jsonPointers:
      - /spec/conversion/webhook/clientConfig/service/namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: nodeclaims.karpenter.sh
    jsonPointers:
      - /spec/conversion/webhook/clientConfig/service/namespace
```

**Comment by snieg** [comment]
> You have the option to do this with Argo CD by passing in the `skipCrds` flag even if the values file doesn't offer it (assuming you are using the `helm` feature of Argo CD directly.. which I unfortunately am not).
> 
> https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-skip-crds

This worked, but we are still back to the first point where ArgoCD cannot complete the post-hook (even though it has been completed)

```
15m         Normal    SuccessfulCreate    job/karpenter-post-install-hook                    Created pod: karpenter-post-install-hook-gdx8c
15m         Normal    Completed           job/karpenter-post-install-hook                    Job completed
9m42s       Normal    SuccessfulCreate    job/karpenter-post-install-hook                    Created pod: karpenter-post-install-hook-qmg6m
9m38s       Normal    Completed           job/karpenter-post-install-hook                    Job completed
```

<img width="1408" alt="image" src="https://github.com/user-attachments/assets/47fd4160-5b04-4be6-b845-e9160981773b">

**Comment by jetersen** [comment]
As a workaround / permanent fix, I used argo cd and kustomize + helm. To patch it.

To enable kustomize + helm, add the following:
```yaml
kustomize.buildOptions: "--enable-helm"
```

Either via the argocd-cm configmap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  kustomize.buildOptions: "--enable-helm"
```

or adding to helm values

```yaml
configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
```
If you want to test it locally beware you need to use a recent kustomize. The embedded kubectl kustomize does not support OCI repo because of how it is invoking helm pull.

kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: karpenter
    repo: oci://public.ecr.aws/karpenter
    version: 1.0.0
    releaseName: karpenter
    namespace: kube-system
    valuesFile: values.yaml

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      name: karpenter-post-install-hook
    patch: |-
      - op: replace
        path: /spec/ttlSecondsAfterFinished
        value: 30
```

**Comment by snieg** [comment]
> As a workaround / permanent fix, I used argo cd and kustomize + helm. To patch it.
> 
> To enable kustomize + helm, add the following:
> 
> ```yaml
> kustomize.buildOptions: "--enable-helm"
> ```
> 
> Either via the argocd-cm configmap:
> 
> ```yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: argocd-cm
>   namespace: argocd
> data:
>   kustomize.buildOptions: "--enable-helm"
> ```
> 
> or adding to helm values
> 
> ```yaml
> configs:
>   cm:
>     kustomize.buildOptions: "--enable-helm"
> ```
> 
> If you want to test it locally beware you need to use a recent kustomize. The embedded kubectl kustomize does not support OCI repo because of how it is invoking helm pull.
> 
> kustomization.yaml:
> 
> ```yaml
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> 
> helmCharts:
>   - name: karpenter
>     repo: oci://public.ecr.aws/karpenter
>     version: 1.0.0
>     releaseName: karpenter
>     namespace: kube-system
>     valuesFile: values.yaml
> 
> patches:
>   - target:
>       group: batch
>       version: v1
>       kind: Job
>       name: karpenter-post-install-hook
>     patch: |-
>       - op: replace
>         path: /spec/ttlSecondsAfterFinished
>         value: 30
> ```

This trick worked for me too.

Added below to `ApplicationSet`:


```
    spec:
      sources:
        - chart: karpenter
          repoURL: public.ecr.aws/karpenter
          targetRevision: "{{values.version}}"
          helm:
            releaseName: karpenter
(...)
          kustomize:
            patches:
              - target:
                  group: batch
                  version: v1
                  kind: Job
                  name: karpenter-post-install-hook
                patch: |-
                  - op: replace
                    path: /spec/ttlSecondsAfterFinished
                    value: 30
```

**Comment by jetersen** [comment]
I was not aware that you could mix helm and kustomize in one application 🤯

**Comment by danielloader** [comment]
The real wins are deep in the comments, this is new to me also and might have made me considerably happier outside of this problem. Thanks @snieg

**Comment by danielloader** [comment]
I've got to the point where I just don't want this post install hook, I have a handful of custom objects I'm capable of migrating myself I just want the option to not have to deal with this any more. I get the good intention but this has totally broken my production environment from being able to configure karpenter and that's not ideal.

**Comment by danielloader** [comment]
I've just forked the chart code into a repo with my PR in it and pulling from there until it's done. If it ever gets merged or resolved so I don't need to use it I can revert back to the upstream.

**Comment by jetersen** [comment]
Be careful upgrading with argocd...
I just spent all day fixing karpenter issues...

The missing link for me was karpenter was downgrading my v1 nodepools to v1beta because I missed the CRDs for production clusters because I did helm upgrade found issues and converted to kustomize  without the new CRDs (missing includeCRDs in kustomization.yaml) and now I got a dead cluster... Because conflicts and old webhook validations leftovers.

I had to delete all webhook validation and mutation for karpenter.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: karpenter
    repo: oci://public.ecr.aws/karpenter
    version: 1.0.0
    releaseName: karpenter
    namespace: kube-system
    valuesFile: values.yaml
    includeCRDs: true
```
