### ISSUE TITLE
karpenter controller cannot pass health check because of lack of authorization in EKS

### ISSUE THREAD

**Issue by joosangkim** [aws/karpenter-provider-aws#6860]
### Description

**Observed Behavior**:

karpenter controller cannot pass the health check because of below error.
```
{"level":"INFO","time":"2024-08-23T01:04:47.011Z","logger":"controller.controller-runtime.healthz","message":"healthz check failed","commit":"490ef94","statuses":[{},{},{}]}
{"level":"INFO","time":"2024-08-23T01:04:47.749Z","logger":"controller","message":"k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: failed to list *v1beta1.NodeClaim: conversion webhook for karpenter.sh/v1, Kind=NodeClaim failed: Post \"https://karpenter.kube-system.svc:8443/?timeout=30s\": service \"karpenter\" not found","commit":"490ef94"}
{"level":"ERROR","time":"2024-08-23T01:04:47.749Z","logger":"controller","message":"k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch *v1beta1.NodeClaim: failed to list *v1beta1.NodeClaim: conversion webhook for karpenter.sh/v1, Kind=NodeClaim failed: Post \"https://karpenter.kube-system.svc:8443/?timeout=30s\": service \"karpenter\" not found","commit":"490ef94"}
{"level":"INFO","time":"2024-08-23T01:04:52.187Z","logger":"controller","message":"k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: failed to list *v1.ValidatingWebhookConfiguration: validatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User \"system:serviceaccount:karpenter:karpenter\" cannot list resource \"validatingwebhookconfigurations\" in API group \"admissionregistration.k8s.io\" at the cluster scope","commit":"490ef94"}
{"level":"ERROR","time":"2024-08-23T01:04:52.187Z","logger":"controller","message":"k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch *v1.ValidatingWebhookConfiguration: failed to list *v1.ValidatingWebhookConfiguration: validatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User \"system:serviceaccount:karpenter:karpenter\" cannot list resource \"validatingwebhookconfigurations\" in API group \"admissionregistration.k8s.io\" at the cluster scope","commit":"490ef94"}
``` 

**Expected Behavior**:
karpenter controller should pass the health check

**Reproduction Steps** (Please include YAML):
Install using helm v1.0.0 and v1.0.1 with below `values.yaml`. 
* values.yml
```
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::MYACCOUNT:role/ROLE_NAME
replicas: 2
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: karpenter.sh/nodepool
              operator: DoesNotExist
controller:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
webhook:
  enabled: true
settings:
  clusterName: my-cluster
  interruptionQueue: my-cluster-queue
nodeSelector:
  eks.amazonaws.com/capacityType: ON_DEMAND
  eks.amazonaws.com/nodegroup: on-demand-x86-4vcpu-8gb
```

**Versions**:
- Chart Version: `0.37.0` 
- Kubernetes Version (`kubectl version`): `v1.30.0`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
