### ISSUE TITLE
Nodes with do-not-evict:true pods get consolidated after setting consolidateAfter

### ISSUE THREAD

**Issue by schniedergers** [aws/karpenter-provider-aws#6861]
### Description

**Observed Behavior**:
I updated our clusters to Karpenter 1.0.0, and started to set the `consolidateAfter` to 15 minutes to slow down the node churn.
However - we have some pods with `do-not-evict: true` annotations on the nodes.

It seems that those node get consolidated and thus the do-not-evict pods get terminated.
Before 1.0.0 and `consolidateAfter`, the pod annotations were preventing node consolidations as expected.

**Expected Behavior**:
Do not consolidate nodes when it has pods with `do-not-evict: true` annotations even when `consolidateAfter` is set.

**Reproduction Steps** (Please include YAML):
Nodepool
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    compatibility.karpenter.sh/v1beta1-nodeclass-reference: '{"name":"default"}'
    meta.helm.sh/release-name: karpenter-nodes
    meta.helm.sh/release-namespace: karpenter
  generation: 5
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 15m
    consolidationPolicy: WhenEmptyOrUnderutilized
```

Pod
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    karpenter.sh/do-not-evict: "true"
```

**Versions**:
- Chart Version: 1.0.0
- Kubernetes Version (`kubectl version`):
```
Server Version: v1.30.2-eks-db838b0
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
