### ISSUE TITLE
Karpenter ignoring nodepool weights?

### ISSUE THREAD

**Issue by drawnwren** [aws/karpenter-provider-aws#6883]
### Description

I have two nodepools:

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: milvus
  labels:
    xoul.ai/grouping: milvus
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 5m
  weight: 5
  template:
    metadata:
        labels:
          xoul.ai/grouping: milvus
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: milvus
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["m6i.xlarge"]
  limits:
    cpu: 75
---
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  weight: 99
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 5m
  template:
    metadata:
        labels:
          node-type: basis-karpenter
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.small", "t3.medium", "t3a.small", "t3a.medium"]
  limits:
    cpu: 100
```
My expectation is that karpenter will always schedule the default nodepool unless a pod doesn't match it (because weight 99 > 5). However, the observed behavior is that karpenter spawns only m6is and fills them up.
