### ISSUE TITLE
CRDs in git release differ from CRDs rendered by karpenter-crd helm chart

### ISSUE THREAD

**Issue by raidlman** [aws/karpenter-provider-aws#6889]
### Description

**Observed Behavior**:

Rendering the CRDs via kustomize results in a different manifest than rendering with helm.

The CRDs installed via the helm chart remove the post-install webhook (cf. #6837).
The CRDs in the Karpenter release still contain the webhook.

**Expected Behavior**:

CRDs should be the same for both within the same release.

**Reproduction Steps** (Please include YAML):

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/aws/karpenter-provider-aws/v0.37.2/pkg/apis/crds/karpenter.sh_nodepools.yaml
  - https://raw.githubusercontent.com/aws/karpenter-provider-aws/v0.37.2/pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  - https://raw.githubusercontent.com/aws/karpenter-provider-aws/v0.37.2/pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
```

```bash
helm template karpenter-crd oci://public.ecr.aws/karpenter/karpenter-crd --version 0.37.2
```

**Versions**:
- Chart Version: 0.37.2
- Kubernetes Version (`kubectl version`): v1.30.2-eks-db838b0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
