### ISSUE TITLE
Incorrect Number of maxPods / Node Pods Capacity

### ISSUE THREAD

**Issue by msvechla** [aws/karpenter-provider-aws#6890]
### Description

**Observed Behavior**:

Since we upgraded to Karpenter v1 we observed incorrect kubelet `maxPods` settings for multiple nodes. We initially only noticed the issue with `m7a.medium` instances, however today we also had a case with an `r7a.medium` instance.

The issue becomes visible when multiple pods on a node in the cluster are stuck in initializing with:

> Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "850cdbed09a9f986b2370c7409fb9e5ee782846056ec7466fb13e863f6e225ad": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container 

Checking the node, it immediately becomes obvious that too many pods have been scheduled on it, and the node is running out of IP addresses.

In the example with `m7a.medium` we observed multiple nodes in the same cluster (all `m7a.medium`) with a different `status.capacity.pods` specified.

We observed nodes with `8`, `58` and `29` `maxPods` in the cluster.

According to https://github.com/awslabs/amazon-eks-ami/blob/main/templates/shared/runtime/eni-max-pods.txt#L518 the correct number should be `8`. So the nodes which had a higher number specified ran into the issue mentioned above.

Logging into the nodes and checking the kubelet config revealed the following:

```
[root@ip]# cat /etc/kubernetes/kubelet/config.json.d/00-nodeadm.conf |grep maxPods
    "maxPods": 29,
```

```
[root@ip]# cat /etc/kubernetes/kubelet/config.json |grep maxPods
  "maxPods": 8,
```

So it appears that the correct value is specified in `/etc/kubernetes/kubelet/config.json` but overwritten in `/etc/kubernetes/kubelet/config.json.d/00-nodeadm.conf`.

We use AL2023 and we do not specify any value for `podsPerCore` in our karpenter resources or similar.

As we had different nodes of the same instance type with varying values, this could also be some kind of race condition or similar.

**Expected Behavior**:

Calculated `maxPods` matches value in https://github.com/awslabs/amazon-eks-ami/blob/main/templates/shared/runtime/eni-max-pods.txt

**Reproduction Steps** (Please include YAML):

Used `EC2NodeClass`

```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
  - alias: al2023@v20240807
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 30Gi
      volumeType: gp3
  detailedMonitoring: true
  instanceProfile: karpenter
  kubelet:
    kubeReserved:
      cpu: 200m
      ephemeral-storage: 1Gi
      memory: 200Mi
    systemReserved:
      cpu: 100m
      ephemeral-storage: 1Gi
      memory: 200Mi
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  securityGroupSelectorTerms:
  - name: karpenter
  subnetSelectorTerms:
  - tags:
      Name: private
  userData: |
    #!/bin/bash

    # https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/faq.md#6-minute-delays-in-attaching-volumes
    # https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1955
    echo -e "InhibitDelayMaxSec=45\n" >> /etc/systemd/logind.conf
    systemctl restart systemd-logind
    echo "$(jq ".shutdownGracePeriod=\"400s\"" /etc/kubernetes/kubelet/config.json)" > /etc/kubernetes/kubelet/config.json
    echo "$(jq ".shutdownGracePeriodCriticalPods=\"100s\"" /etc/kubernetes/kubelet/config.json)" > /etc/kubernetes/kubelet/config.json
    systemctl restart kubelet
```

**Versions**:
- Chart Version: v1.0.1
- Kubernetes Version (`kubectl version`): v1.29.6-eks-db838b0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rschalo** [comment]
It looks like this problem is related to https://karpenter.sh/v1.0/troubleshooting/#maxpods-is-greater-than-the-nodes-supported-pod-density. 

I'll point out that some of the language there needs to be updated, for example I believe `NodePods` in Solution 2 was meant to point to `NodePools` and the pod density section now directs to the EC2NodeClass kubelet config section since it was moved there from NodePools in v1.

**Comment by msvechla** [comment]
I'm not quite sure what you mean. I posted my kubelet spec / the entire `EC2NodeClass` in the original post above. We are not specifying any maxPods as als mentioned in the troubleshooting guide, so it must mean karpenter is setting an incorrect amount.

Or did I misunderstand something?

**Comment by waihong** [comment]
We are encountering a similar problem that began with the upgrade to v1.0.0. We have noticed an excessive number of pods being scheduled on t3.small/t3a.small instances. Our kubelet configuration does not specify any maxPods settings as well.

**Comment by iharris-luno** [comment]
We're also seeing this issue after upgrading to v1.0.0.  Around 10% of new nodes have wildly high allocatable pods (eg 205 for a c6a.2xlarge), whereas mostly the calculations are correct (ie 42 for a c6a.2xlarge, as we have RESERVED_ENIS=1 in the karpenter controller).

**Comment by iharris-luno** [comment]
I can confirm that the affected nodes have an incorrect `maxPods` value in the `# Karpenter Generated NodeConfig` of the instance user-data.  (So AL2023 / kubelet is doing what it's told, and the problem is in karpenter's maxPods calculations)

**Comment by iharris-luno** [comment]
It appears to be related to the presence or absence of a `kubelet` stanza in the EC2NodeClass...

**Reproduction Steps:**
Create a deployment with 50 replicas, with node anti-affinity, in a nodepool which uses the following EC2NodeClass...
```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: iharris
spec:
  amiSelectorTerms:
  - alias: al2023@latest
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      kmsKeyID: <redacted>
      volumeSize: 150Gi
      volumeType: gp3
  role: karpenter-node-role.<redacted>
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
```
All 50 nodes have the correct `.status.allocatable.pods` - yay!

Change the EC2NodeClass to...
```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: iharris
spec:
  amiSelectorTerms:
  - alias: al2023@latest
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      kmsKeyID: <redacted>
      volumeSize: 150Gi
      volumeType: gp3
  kubelet:
    imageGCLowThresholdPercent: 65
  role: karpenter-node-role.<redacted>
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
 ```
 Around 5-10% of the 50 nodes have an incorrect `.status.allocatable.pods` - boo!
 (Nothing special about `imageGCLowThresholdPercent`, it seems to be the presence of `spec.kubelet` that triggers the behaviour.)
 
 I think we need that `bug` label back, sorry!
