### ISSUE TITLE
Karpenter not respecting NodeClaim budget

### ISSUE THREAD

**Issue by tm-nadavsh** [aws/karpenter-provider-aws#6911]
### Description

**Observed Behavior**:
Karpenter is disrupting more then 1 node every hour against whats defined in the budget.
Karpenter logs:
creates 2 nodeClaims for from nodepool workflow:
```
{"level":"INFO","time":"2024-09-02T01:46:09.681Z","logger":"controller","message":"initialized nodeclaim","commit":"490ef94","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"workflow-w7ngd"},"namespace":"","name":"workflow-w7ngd","reconcileID":"c3b51cad-1b76-4ad2-9f09-3a684d6522db","provider-id":"aws:///us-east-1f/i-09e572ad03bf8d181","Node":{"name":"ip-10-11-26-207.ec2.internal"},"allocatable":{"cpu":"3920m","ephemeral-storage":"37569620724","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"6919588Ki","pods":"58"}}
{"level":"INFO","time":"2024-09-02T02:02:43.808Z","logger":"controller","message":"initialized nodeclaim","commit":"490ef94","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"workflow-gkq4x"},"namespace":"","name":"workflow-gkq4x","reconcileID":"d9df987c-3eec-4646-8d7f-e736836e0a79","provider-id":"aws:///us-east-1f/i-066ad917e86b943b4","Node":{"name":"ip-10-11-19-239.ec2.internal"},"allocatable":{"cpu":"7910m","ephemeral-storage":"37569620724","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"14991808Ki","pods":"58"}}
```
in the same minute, has 2 distruptions against what is defined in the budget:

`{"level":"INFO","time":"2024-09-02T02:45:57.718Z","logger":"controller","message":"disrupting via consolidation delete, terminating 1 nodes (1 pods) ip-10-11-26-207.ec2.internal/c6a.xlarge/on-demand","commit":"490ef94","controller":"disruption","command-id":"f4a19dc5-8c29-4b4e-9bc0-391773a5c353"}
`

`{"level":"INFO","time":"2024-09-02T02:45:19.046Z","logger":"controller","message":"disrupting via consolidation delete, terminating 1 nodes (1 pods) ip-10-11-19-239.ec2.internal/c6a.2xlarge/on-demand","commit":"490ef94","controller":"disruption","command-id":"e5ae3d34-db70-487a-9751-9325de3528f2"}
`

**Expected Behavior**:
Karpenter would only distrupt 1 node every hour.
**Reproduction Steps** (Please include YAML):
I have the next Nodepool:
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels:
    argocd.argoproj/appname: karpenter-config--karpenter--prod-us
  name: workflow
spec:
  disruption:
    budgets:
      - duration: 45m
        nodes: '0'
        schedule: '@hourly'
      - nodes: '1'
    consolidationPolicy: WhenUnderutilized
  limits:
    cpu: '100'
    memory: 400Gi
  template:
    metadata:
      labels:
        role: workflow
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - c
            - m
            - r
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - '4'
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values:
            - nano
            - micro
            - small
            - medium
            - large
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - spot
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      taints:
        - effect: NoSchedule
          key: role
          value: workflow

```
Note that this nodepool has a taint on it so it is a dedicated nodepool for workflows.
Note that i added a budget that should only distrupt max of 1 node in the last 15 minutes of every hour based on [this comment](https://github.com/kubernetes-sigs/karpenter/issues/735#issuecomment-2214243702)
```
spec:
  disruption:
    budgets:
      - duration: 45m
        nodes: '0'
        schedule: '@hourly'
      - nodes: '1'
``` 

Karpenter chart:
```
name: karpenter
apiVersion: v2
version: 0.0.0
dependencies:
  - name: karpenter
    version: 0.37.0
    repository: oci://public.ecr.aws/karpenter

```
karpenter values:
```
karpenter:
  logLevel: debug
  controller:
    resources:
      requests:
        cpu: "0.3"
        memory: 512Mi

  serviceMonitor:
    enabled: true
  settings:
    featureGates:
      GRPCContainerProbe: true
    batchMaxDuration: 10s
    batchIdleDuration: 5s
  webhook:
    enabled: true

```
Ec2NodeClass:
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        encrypted: true
        volumeSize: 40Gi
        volumeType: gp3
  instanceProfile: eks-XXX-XXX-XXX
  securityGroupSelectorTerms:
    - tags:
        'aws:eks:cluster-name': XXX
        kubernetes.io/cluster/XXX: owned
  subnetSelectorTerms:
    - tags:
        Name: XXX-XXX-XXX
  tags:
    Business Unit: RND
    Compliance: SOC2 Type2
    Confidentiality: None
    Customer: DevOps
    Owner: Devops Team
  userData: >
    MIME-Version: 1.0

    Content-Type: multipart/mixed; boundary="BOUNDARY"


    --BOUNDARY

    Content-Type: text/x-shellscript; charset="us-ascii"


    #!/bin/bash

    mkdir -p ~ec2-user/.ssh/

    touch ~ec2-user/.ssh/authorized_keys

    cat >> ~ec2-user/.ssh/authorized_keys <<EOF

    ssh-rsa
    XXXXXXXXXXXXXXX
    EOF

    chmod -R go-w ~ec2-user/.ssh/authorized_keys

    chown -R ec2-user ~ec2-user/.ssh


    --BOUNDARY--

```
**Versions**:
- Chart Version:
- 0.37.0
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.11-eks-db838b0
```
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Do you have any other nodepools in your cluster?

**Comment by tm-nadavsh** [comment]
@engedaam  sure i will share them, but as far as i know one nodepool should not impact a different nodepool no matter the configuration, am i wrong?

nodepools:
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels:
    argocd.argoproj/appname: karpenter-config--karpenter--prod-us
  name: arangodb
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
  limits:
    cpu: '100'
    memory: 400Gi
  template:
    metadata:
      labels:
        role: arangodb-standalone
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - m
        - key: karpenter.k8s.aws/instance-generation
          operator: In
          values:
            - '5'
            - '6'
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values:
            - nano
            - micro
            - small
            - medium
            - large
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      taints:
        - effect: NoSchedule
          key: role
          value: arangodb-standalone

```
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels:
    argocd.argoproj/appname: karpenter-config--karpenter--prod-us
  name: debug
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  limits:
    cpu: '100'
    memory: 400Gi
  template:
    metadata:
      labels:
        role: debug
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - r
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - '5'
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - 2xlarge
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      taints:
        - effect: NoSchedule
          key: role
          value: debug

```
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels:
    argocd.argoproj/appname: karpenter-config--karpenter--prod-us
  name: default
spec:
  disruption:
    budgets:
      - duration: 45m
        nodes: '0'
        schedule: '@hourly'
      - nodes: '2'
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  limits:
    cpu: '100'
    memory: 400Gi
  template:
    metadata: null
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - c
            - m
            - r
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - '5'
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values:
            - nano
            - micro
            - small
            - medium
            - large
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux

```

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels:
    argocd.argoproj/appname: karpenter-config--karpenter--prod-us
  name: psmdb
spec:
  disruption:
    budgets:
      - duration: 45m
        nodes: '0'
        schedule: '@hourly'
      - nodes: '1'
    consolidationPolicy: WhenUnderutilized
  limits:
    cpu: '100'
    memory: 400Gi
  template:
    metadata:
      labels:
        role: psmdb
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - r
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - '5'
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values:
            - nano
            - micro
            - small
            - medium
            - large
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      taints:
        - effect: NoSchedule
          key: role
          value: psmdb

```
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels:
    argocd.argoproj/appname: karpenter-config--karpenter--prod-us
  name: testkube
spec:
  disruption:
    budgets:
      - duration: 45m
        nodes: '0'
        schedule: '@hourly'
      - nodes: '1'
    consolidateAfter: 30m
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  limits:
    cpu: '100'
    memory: 400Gi
  template:
    metadata:
      labels:
        role: testkube
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - c
            - m
            - r
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - '4'
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values:
            - nano
            - micro
            - small
            - medium
            - large
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - spot
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      taints:
        - effect: NoSchedule
          key: role
          value: testkube

```
