### ISSUE TITLE
ENI are not tagged correctly

### ISSUE THREAD

**Issue by pmorelli92** [aws/karpenter-provider-aws#6912]
### Description

**Observed Behavior**:

When a new EC2 is created it might have several ENI assigned. I observed that only one of those ENI will have the custom tags that I added meanwhile the others will not.

**EC2 attached ENI:**

<img width="723" alt="Screenshot 2024-09-02 at 11 24 39" src="https://github.com/user-attachments/assets/e95d2ba7-535d-49bd-90f1-739ce0c648af">

**ENI number one tags:**

<img width="450" alt="Screenshot 2024-09-02 at 11 24 28" src="https://github.com/user-attachments/assets/00e45d7d-d675-43e8-a8b5-3557adcf6019">

**ENI number two tags:**

<img width="554" alt="Screenshot 2024-09-02 at 11 24 52" src="https://github.com/user-attachments/assets/7cfc4a5b-200b-4256-b629-61fa65c89228">

**Expected Behavior**:

All the ENI are tagged with the custom tagging.

**Reproduction Steps** (Please include YAML):

Given the `aws-node` created by the `vpc-cni` plugin having `ADDITIONAL_ENI_TAGS`

```
      containers:
      - env:
        - name: ADDITIONAL_ENI_TAGS
          value: assetuuid=3cdf0543-11d4-49ec-be1f-75fa50ab4cf9,environment=Non production
```

Given the EC2 Node Class having the tags:

```
      tags:
        assetuuid: 3cdf0543-11d4-49ec-be1f-75fa50ab4cf9
        environment: Non production
        karpenter.sh/discovery: dev-0908
```

Any time a new EC2 machine is created, not all the attached ENI will have the required tags.

**Versions**:
- Chart Version: 1.0.1
- Kubernetes Version (`kubectl version`):

```
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.3-eks-2f46c53
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
