### ISSUE TITLE
Kubelet configuration not applied after v1 upgrade

### ISSUE THREAD

**Issue by InsomniaCoder** [aws/karpenter-provider-aws#6987]
### Description

**Observed Behavior**:

After upgrading to v1 from 0.37.0, I've noticed that our kubelet configuration specified in the NodePools is not applied anymore.

These are some of the example:

```
kubelet:
    maxPods: 110
    podsPerCore: 6
    evictionHard:
      memory.available: 300Mi
      nodefs.available: 10%
      nodefs.inodesFree: 5%
      imagefs.inodesFree: 5%
    evictionSoft:
      memory.available: 500Mi
      nodefs.available: 15%
    evictionSoftGracePeriod:
      memory.available: 1m0s
      nodefs.available: 1m0s
```

in the nodepool of 0.37.0 when inspecting kubelet's log in the machine I'd see

```
--eviction-hard="imagefs.inodesFree<5%,memory.available<300Mi,nodefs.available<10%,nodefs.inodesFree<5%"
FLAG: --eviction-max-pod-grace-period="0"
FLAG: --eviction-minimum-reclaim=""
FLAG: --eviction-pressure-transition-period="5m0s"
FLAG: --eviction-soft="memory.available<500Mi,nodefs.available<15%"
FLAG: --eviction-soft-grace-period="memory.available=1m0s,nodefs.available=1m0s"
```

However, after v1 upgrade, they are gone.

I do see conversion annotation added to the nodepool

```
compatibility.karpenter.sh/v1beta1-kubelet-conversion:
                {"maxPods":110,"podsPerCore":6,"evictionHard":{"imagefs.inodesFree":"5%","memory.available":"300Mi","nodefs.available":"10%","nodefs.inode...
              compatibility.karpenter.sh/v1beta1-nodeclass-reference: {"name":"schip-default"}
```

**Expected Behavior**:

> Once upgraded, you won't need to roll your nodes to be compatible with v1.1, except if you have multiple NodePools with different kubelets that are referencing the same EC2NodeClass. Karpenter has moved the kubelet to the EC2NodeClass in v1. NodePools with different kubelet referencing the same EC2NodeClass will be compatible with v1.0, but will not be in v1.1.

Using different kubelet config per NodePool is still compatible in v1.

**Reproduction Steps** (Please include YAML):
- create a nodepool with custom kubelet configuration on Karpenter 0.37.0
- Upgrade Karpenter from 0.37.0 to 1.0.1
- Check kubelet configuration of a new node

**Versions**:
- Chart Version: 1.0.1
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
