### ISSUE TITLE
Karpenter deployment - one pod have "Insufficient cpu" while other one goes well

### ISSUE THREAD

**Issue by davidt-gh** [aws/karpenter-provider-aws#6988]
### Description

**Observed Behavior**:
I've deployed 0.37 on my EKS using ArgoCD
After deployment is done, one pod is working OK, and one pod events say not CPU
```
0/2 nodes are available: 1 Insufficient cpu, 1 Too many pods, 1 node(s) didn't match Pod's node affinity/selector. preemption: 0/2 nodes are available: 1 Insufficient cpu, 1 Preemption is not helpful for scheduling.
```
EKS: 1.30
While using "inflate" for testing, I see a new node came up. so all good by karpenter. But it's driving me crazy.

**Expected Behavior**:
All pods will be up and good.

**Reproduction Steps** (Please include YAML):
**Versions**:
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): 1.30
My values:
```
  roleName: "xyz-node-group-20240801082441731100000005"
#  logLevel: debug
  settings:
    clusterName: "xyz-eks"
    interruptionQueue: "xyz-eks"
  serviceAccount:
    annotations:
      "eks.amazonaws.com/role-arn": "arn:aws:iam::****:role/xyz-karpenter"
  controller:
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
```
