### ISSUE TITLE
Karpenter not respecting nodepool budget

### ISSUE THREAD

**Issue by agarbato** [aws/karpenter-provider-aws#7026]
### Description

**Observed Behavior**:

I've the following disruption budget configured on one nodepool.

```spec:
  disruption:
    budgets:
    - duration: 20h
      nodes: 20%
      reasons:
      - Empty
      schedule: 0 6 * * *
    - duration: 4h
      nodes: 20%
      reasons:
      - Underutilized
      - Empty
      schedule: 0 2 * * *
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized`
```
**Expected Behavior**:

On day time (from 6am to 2am next day for a duration of 20hrs) I would expect that nodes are disrupted only if they're empty however I can see on logs and metrics that nodes are disrupted even when Underutilized.

Maybe I'm not understanding the doc properly or is not possible to have multiple schedules?
 
**Reproduction Steps** (Please include YAML):

Set budget above and check Karpenter logs/metrics.

**Versions**:
- Chart Version: 1.0.1
- Kubernetes Version 1.30

**Comment by njtran** [comment]
A budget is purely restrictive, respecting the most restrictive budget that's currently active (schedule + duration). If there's no budget defined, then there is no limit to the concurrency of disruption. In your case, there is no budget for Underutilized between 6 am to 2 am, equivalent to 100% at that time. The following is probably what you want
```
  disruption:
    budgets:
    - duration: 20h
      nodes: 0
      reasons:
      - Underutilized
    - duration: 20h
      nodes: 20%
      reasons:
      - Empty
      schedule: 0 6 * * *
    - duration: 4h
      nodes: 20%
      reasons:
      - Underutilized
      - Empty
      schedule: 0 2 * * *
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized`
```

Going to close this as solved. Feel free to cut a docs pr if you want the adjust the language used in the docs.
