### ISSUE TITLE
Can't access IMDS in bottlerocket nodes provisioned by Karpenter 1.0.2 (despite changing metadataOptions)

### ISSUE THREAD

**Issue by kletosl** [aws/karpenter-provider-aws#7048]
### Description

Hello,

I'm on EKS 1.28

**Observed Behavior**:
I've set in my EC2NodeClass
  metadataOptions:
    httpPutResponseHopLimit: 2
    httpTokens: optional

And when I in a pod, running the curl below just times out:
curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"

Additionally, I have webhooks set to disabled. 

Am I missing something?

**Expected Behavior**:
Should provide a response.

**Reproduction Steps** (Please include YAML):
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: cpu-br-np
spec:
  template:
    metadata:
      labels:
        noderole: cpu-br
    spec:
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["r6idn"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["xlarge", "2xlarge"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-1c", "us-east-1f"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: cpu-br-nc
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 90s
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: cpu-br-nc
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
    - alias: bottlerocket@latest
  role: "${node_role}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${cluster_name}"
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: "${cluster_name}"
  metadataOptions:
    httpPutResponseHopLimit: 2
  blockDeviceMappings:
    # Root device
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 4Gi
        volumeType: gp3
        encrypted: true
    # Data device: Container resources such as images and logs
    # Can be small as we flip over to ephemeral
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 2Gi
        volumeType: gp3
        encrypted: true
  userData: |
    [settings.bootstrap-containers.setup-ephemeral-disks]
    source = "<redacted - just a script to use ephemeral disks>"
    mode = "always"
    essential = true

```

**Versions**:
- Chart Version: 1.0.2
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
