### ISSUE TITLE
Karpenter is always disrupting node via drift after upgrading to 0.37.3 from

### ISSUE THREAD

**Issue by ariretiarno** [aws/karpenter-provider-aws#7049]
### Description

**Observed Behavior**:
Karpenter is always disrupting node via drift, even consolidate configuration is `expireAfter: Never` and `consolidateAfter: Never`.
This issue is happen after i've upgrade from 0.32.10 to 0.37.3.

And it's happen to whole nodes in the cluster.

Logs
```

{"level":"INFO","time":"2024-09-20T09:31:25.580Z","logger":"controller","message":"disrupting via drift replace, terminating 1 nodes (1 pods) ip-172-31-125-79.ap-southeast-1.compute.internal/t3a.xlarge/on-demand and replacing with on-demand node from types t3a.xlarge","commit":"378e8b1","controller":"disruption","command-id":"a49138f2-51e9-4bb1-95b1-1973aa9d694f"}
--



```

**Expected Behavior**:
Karpenter should not disrupt node when i defined 
```
disruption:
    expireAfter: Never
    consolidateAfter: Never
```

**Reproduction Steps** (Please include YAML):
Nodepoool
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: jenkins-master
spec:
  disruption:
    expireAfter: Never
    consolidateAfter: Never
  template:
    metadata: {}
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - t
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - t3a.xlarge
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      - key: evermos.com/serviceClass
        operator: In
        values:
        - jenkins-master
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "2"
        - "4"
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      startupTaints:
      - effect: NoExecute
        key: node.cilium.io/agent-not-ready
        value: "true"
      taints:
      - effect: NoSchedule
        key: jenkins-master
        value: "true"
```

NodeClass
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 50Gi
      volumeType: gp3
  role: KarpenterNodeRole-evermos-dev
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: evermos-dev
  subnetSelectorTerms:
  - tags:
      Name: private-a-dev
```

**Versions**:
- Chart Version: 0.37.3
- Kubernetes Version (`kubectl version`): v1.28.12-eks-a18cd3a

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rschalo** [comment]
How often are you seeing drift occur?

**Comment by ariretiarno** [comment]
The drift event is happened every 24h and it's affected in whole nodes, even i don’t make any changes on nodepool/ec2nodeclass..
I'm using Loki and here is my query `{app="karpenter"} |~ "disrupting" |~ "drift"`
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/a57bdf5d-8e53-4e57-ae20-c7a1dc8b54c2">

Anyway i didn’t found any related logs from this https://github.com/kubernetes-sigs/karpenter/blob/v0.37.3/pkg/controllers/nodeclaim/disruption/drift.go#L82

Is there any possibilities the logs is from this code? https://github.com/kubernetes-sigs/karpenter/blob/04a921c00ad837c5c82fe190f4b6c39f4dffe6fa/pkg/controllers/disruption/controller.go#L151
If so, from where the drift is coming from?

**Comment by ariretiarno** [comment]
anyway, on version 0.37.3 the drift is can be modified to disable/enable, but when i plan to upgrade to 1.0.0 the feature was dropped and cannot be disabled, so this is my concern when i upgrade karpenter to 1.0.0

**Comment by lucasfnds** [comment]
This problem is also occurring here. 
This problem occurred on all my nodes, different nodeclasses and nodepools, in spot and on-demand nodes.

Chart Version: 0.37.0
Kubernetes Version (kubectl version): v1.30.3-eks-a18cd3a

[karpenter-logs.log](https://github.com/user-attachments/files/17155977/karpenter-logs.log)

**Comment by ariretiarno** [comment]
any updates @rschalo

**Comment by jmdeal** [comment]
The logs @rschalo was looking for are only available if you had debug logging enabled, it doesn't look like either of you did. Given both of your examples happened within close proximity to an eks-optimized AMI release, I suspect Nodes were drifted due to that. To know for sure we would either need to see debug logs, the status conditions on the drifted NodeClaims, or the reason from the [`karpenter_nodeclaims_drifted` metric](https://karpenter.sh/v0.37/reference/metrics/#karpenter_nodeclaims_drifted).

>Karpenter should not disrupt node when i defined
>```
>disruption:
>    expireAfter: Never
>    consolidateAfter: Never
>```
I would also like to clarify that this isn't accurate. Drift is a separate disruption mechanism from consolidation and expiration, these fields are not intended to have any affect on it. As you found, you can disable drift globally through the feature gate pre-v1, and post v1 you can effectively disable it per NodePool via [disruption budgets](https://karpenter.sh/docs/concepts/disruption/#nodepool-disruption-budgets).

**Comment by Cruuncher** [comment]
Drift is still disruption though right? 

We've had this happen on nodes with pods that have the do-not-disrupt annotation on them, and drift just doesn't care and yanks it anyway. 

We're in the process of disabling the feature gate, but this is extremely dangerous default behaviour for critical infrastructure to have. I can't imagine too many people want their entire clusters to spontaneously restart on them.

**Comment by lgg42** [comment]
Same here... 

We have a critical long-running service with the following:

```yaml
    annotations:
      karpenter.sh/do-not-disrupt: "true"
    nodeSelector:
      karpenter.sh/capacity-type: "on-demand"
      karpenter.k8s.aws/instance-family: "c7a"
```

To ensure this pod never gets recreated from Spot termination (by running in on-demand always) or Consolidation. 

But it happened to us today that Karpenter Disrupted the node where this pod was running due to Drift. The reason was new AMI being discovered in SSM as I have the following spec in the EC2NodeClass

```yaml
    spec:
      amiFamily: AL2023
      amiSelectorTerms:
        - alias: al2023@latest
```

I would expect Karpenter to respect the `do-not-disrupt` annotation and only disrupt the Nodes when able due to a Drift instead of forcefully terminating them.

I second @Cruuncher 's affirmation
> but this is extremely dangerous default behaviour for critical infrastructure to have. I can't imagine too many people want their entire clusters to spontaneously restart on them.

For now as a workaround I'll set a fixed AMI in `amiSelectorTerms`, but I'd still this this as a bug.

Also, in the [documentation](https://karpenter.sh/docs/concepts/disruption/#pod-level-controls), it says _"Nodes with karpenter.sh/do-not-disrupt pods will be excluded from [Consolidation](https://karpenter.sh/docs/concepts/disruption/#consolidation), and **conditionally excluded** from [Drift](https://karpenter.sh/docs/concepts/disruption/#drift)."_

Which are these conditions? I wan't able to find them. Could we at least configure these conditions for Drift disruption?
