### ISSUE TITLE
Allow configuring defaultConstraints at the karpenter spec level

### ISSUE THREAD

**Issue by softcane** [aws/karpenter-provider-aws#7062]
### Description

**What problem are you trying to solve?**

The issue arises when Karpenter bypasses the logic of the kube scheduler. For instance, the Cluster Autoscaler typically depends on the kube scheduler and adheres to the default topology constraints.

 I suggest considering it as a feature request for Karpenter to honour the default topology constraints set at the cluster level or allowing the system administrator to inject topology constraints they deem optimal for the cluster's use case.
 
 Karpenter should prioritize the topology constraints specified at the deployment level, falling back to default constraints if none are provided.

Example
```
defaultConstraints:
  - maxSkew: 3
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: ScheduleAnyway
  - maxSkew: 5
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: ScheduleAnyway
```
 
**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
