### ISSUE TITLE
v0.32.7 Failing MetadataOptions for IPv6 in ISO regions

### ISSUE THREAD

**Issue by jlplasce** [aws/karpenter-provider-aws#7081]
### Description

**Observed Behavior**:
When using Chart/App version 0.32.7 of Karpenter in ISO AWS regions , the metadataOptions on NodePools is resulting in an error of:
`NodeClaim creating instance with errors: UnsupportedOperation specifying HttpProtocol Metadata Options for an instnace is not support in this region`

We typically provide metadataOptions as
```
{
    http_endpoint = "enabled"
    http_tokens  = "optional"
    httpProtocolIPv6 = "disabled"
    http_put_response_hop_limit = 2         
    instance_metadata_tags  = "disabled"
}  
```
**AWS Communication**
AWS Support verified that IPv6 Metadata is disabled by default in one ISO region, but is not yet a property available in other regions, and therefor, even setting the property to "disabled" or "false" will result in errors as the endpoint/properties do not exist 

**Attempted Troubleshooting**
The following attempted changes were made but none were successful:
- Completely remove any override metadataOptions and allow the chart defaults
```
metadataOptions = {}
```
- Set `httpProtocolIPv6` to `disabled`
```
{
    http_endpoint = "enabled"
    http_tokens  = "optional"
    httpProtocolIPv6 = "disabled"
    http_put_response_hop_limit = 2         
    instance_metadata_tags  = "disabled"
} 
```
- Provide the above standard metadataOptions for all other settings, but remove any setting of `httpProtocolIPv6`
```
{
    http_endpoint = "enabled"
    http_tokens  = "optional"
    ## httpProtocolIPv6 = "disabled"
    http_put_response_hop_limit = 2         
    instance_metadata_tags  = "disabled"
} 
```
- Set `httpProtocolIPv6` to `null`
```
{
    http_endpoint = "enabled"
    http_tokens  = "optional"
    httpProtocolIPv6 = null
    http_put_response_hop_limit = 2         
    instance_metadata_tags  = "disabled"
} 
```

**Workaround**
Reverting all the way back to v0.18.1 works successfully

**Versions**:
- Chart Version: 0.32.7
- Kubernetes Version (`kubectl version`): 1.26.10+rke2r2

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment]
Can you  please share your nodePool spec? I would also recommend updating to v0.33 and above as with the release of Karpenter v1.0, we have dropped support for karpenter versions v0.32 and below.

**Comment by go0ty** [comment]
I am having the same issue with v0.33 and v0.36. In these ISO regions, any specification of the MetadataOptions will cause a failure, as these properties are not available. Is there any way to omit the specification of these properties when the software makes the RunInstances call?

**Comment by Jokester761** [comment]
I encountered this issue in karpenter 1.0.8 using the following node pool:
```
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: core
  namespace: karpenter
spec:
  template:
    metadata:
      labels:
        component: core
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: core
      requirements:
        - key: "karperter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "t"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
  disruption:
    consolidationPolicy: WhenUnderutilized
    # This forces a node to be terminated every 30 days
    expireAfter: 720h # 30 * 24 = 720h
    # the budget reduces node churn
    budgets:
      # only replace nodes the last 15 minutes of every hour
      - duration: 45m
        nodes: "0"
        schedule: "@hourly"
      # replace 50% of the nodes
      - nodes: "50%"
```

This was was my `EC2NodeClass`:

```
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: core
  namespace: karpenter
spec:
  amiFamily: Custom
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "shared"
        kubernetes.io/cluster/${CLUSTER_NAME}: shared
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
        kubernetes.io/cluster/${CLUSTER_NAME}: owned
  amiSelectorTerms:
    - name: "${KARPENTER_AMI_PREFIX}"
  role: "${KARPENTER_NODE_IAM_ROLE}"
  # Optional, configures IMDS for the instance
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  tags:
    Name: "${NAME_PREFIX}-ec2-${CLUSTER_NAME}-core-ng"

  userData: |
    ${KARPENTER_NODE_USER_DATA}
```
