### ISSUE TITLE
v1: how to expire nodes only during certain times?

### ISSUE THREAD

**Issue by mikkoc** [aws/karpenter-provider-aws#7122]
In 0.37 this config allows us to expire nodes only during weekdays/working hours:

```
 disruption:
  consolidationPolicy: WhenUnderutilized
  expireAfter: 48h
  # Number of nodes: disrupt 1 node at a time, only during weekdays, from 10 to 18 UTC.
  # Schedule: zero disruptions (0) are allowed starting at 8am UTC on Friday, lasting 3 days + 2hrs.
  budgets:
  - nodes: "1"
   schedule: "0 10 * * mon-thu"
   duration: 8h
  - nodes: "0"
   schedule: "0 8 * * fri"
   duration: 74h
```

After migrating to v1 the config looks more like this:

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
 name: generic
spec:
 template:
  spec:
   nodeClassRef:
    apiVersion: karpenter.k8s.aws/v1
    kind: EC2NodeClass
    name: generic
   expireAfter: 48h   ### I don't want this to take effect during nights and weekends.

 disruption:
  consolidationPolicy: WhenEmptyOrUnderutilized
  consolidateAfter: 30m
  budgets:
  - nodes: "1"
   schedule: "0 10 * * mon-thu"
   duration: 8h
  - nodes: "0"
   schedule: "0 8 * * fri"
   duration: 74h
```

And nodes are expired also during weekends. How can I keep the behaviour of karpenter 0.37 in v1? From the documentation, it is unclear to me how to achieve this.

Thanks
