### ISSUE TITLE
Feature Request: Specify an parameter store as amiSelectorTerms for EC2NodeClass

### ISSUE THREAD

**Issue by msfidelis** [aws/karpenter-provider-aws#7152]
### Description

**What problem are you trying to solve?**

I want to enable Karpenter to dynamically retrieve the latest AMI ID from AWS  Parameter Store during reconciliation loops. 

The idea is to allow Karpenter to accept an amiSelectorTerms parameter (which contains the Parameter Store ID) and periodically fetch the value of this parameter to keep the AMI up-to-date. This would ensure that Karpenter always uses the most recent AMI as long as it is updated in the Parameter Store, without requiring manual intervention or configuration changes.

Example: 

```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
spec:
  amiFamily: bottlerocket
  amiSelectorTerms:
    - SSMParameterId: /aws/service/bottlerocket/aws-k8s-1.31/x86_64/latest/image_id
      Query: Parameter.Value
```

Or

```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
spec:
  amiFamily: AL2
  amiSelectorTerms:
    - SSMParameterId: /mycompany/amis/internal/eks/1.31/latest
```

[Reference](https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id-bottlerocket.html)

This feature would help in automating the process of keeping the infrastructure updated with the latest AMI versions in enterprise environments, especially for cases where AMIs are frequently updated for security patches, performance improvements, or other maintenance reasons.

**How important is this feature to you?**

This feature is critical for environments where maintaining up-to-date and secure AMIs is important and a hard task to multiple clusters on enterprise environments. Automating this process would reduce the need for manual updates or custom automation scripts, today we use an AWS Lambda to Patch a `spec.amiSelectorTerms[0].id` value.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
