### ISSUE TITLE
Can a nodepool simultaneously support both spot and demand types?

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter-provider-aws#7190]
### Description

For example, the following configurations are supported:
```
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot: 50%
        - on-demand: 50%
```

There are some important applications that want to be preferentially scheduled to on-demand type nodes using Kubernetes scheduling strategies.
