### ISSUE TITLE
Kubelet spec doesn't take effect

### ISSUE THREAD

**Issue by mdesouky** [aws/karpenter-provider-aws#7194]
### Description

**Observed Behavior**:
Changing the kubelet spec under nodeClass doesn't cause drift and doesn't trigger node replacement.
```bash
[root@ip-10-20-72-17 ~]# cat /etc/kubernetes/kubelet/kubelet-config.json
{
  "kind": "KubeletConfiguration",
  "apiVersion": "kubelet.config.k8s.io/v1beta1",
  "address": "0.0.0.0",
  "authentication": {
    "anonymous": {
      "enabled": false
    },
    "webhook": {
      "cacheTTL": "2m0s",
      "enabled": true
    },
    "x509": {
      "clientCAFile": "/etc/kubernetes/pki/ca.crt"
    }
  },
  "authorization": {
    "mode": "Webhook",
    "webhook": {
      "cacheAuthorizedTTL": "5m0s",
      "cacheUnauthorizedTTL": "30s"
    }
  },
  "clusterDomain": "cluster.local",
  "hairpinMode": "hairpin-veth",
  "readOnlyPort": 0,
  "cgroupDriver": "systemd",
  "cgroupRoot": "/",
  "featureGates": {
    "RotateKubeletServerCertificate": true
  },
  "protectKernelDefaults": true,
  "serializeImagePulls": false,
  "serverTLSBootstrap": true,
  "tlsCipherSuites": [
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_RSA_WITH_AES_128_GCM_SHA256"
  ],
  "clusterDNS": [
    "172.20.0.10"
  ],
  "evictionHard": {
    "memory.available": "100Mi",
    "nodefs.available": "10%",
    "nodefs.inodesFree": "5%"
  },
  "kubeReserved": {
    "cpu": "80m",
    "ephemeral-storage": "1Gi",
    "memory": "893Mi"
  },
  "providerID": "aws:///ap-southeast-2c/i-02182ad4752ca0ab7",
  "systemReservedCgroup": "/system",
  "kubeReservedCgroup": "/runtime"
}
```
```bash
[root@ip-10-20-72-17 ~]# ps aux | grep kubelet
root        3185  4.0  0.7 2388784 127572 ?      Ssl  Oct09   8:57 /usr/bin/kubelet --config /etc/kubernetes/kubelet/kubelet-config.json --kubeconfig /var/lib/kubelet/kubeconfig --container-runtime-endpoint unix:///run/containerd/containerd.sock --image-credential-provider-config /etc/eks/image-credential-provider/config.json --image-credential-provider-bin-dir /etc/eks/image-credential-provider --node-ip=10.20.72.17 --pod-infra-container-image=602401143452.dkr.ecr.ap-southeast-2.amazonaws.com/eks/pause:3.5 --v=2 --hostname-override=ip-10-20-72-17.ap-southeast-2.compute.internal --cloud-provider=external --node-labels=karpenter.sh/capacity-type=on-demand,karpenter.sh/nodepool=secondary,type=karpenter --register-with-taints=karpenter.sh/unregistered:NoExecute --max-pods=52 --pods-per-core=13 --system-reserved=ephemeral-storage=1Gi,memory=1Gi,cpu=200m --kube-reserved=ephemeral-storage=3Gi,memory=1Gi,cpu=300m --eviction-hard=nodefs.available<10%,nodefs.inodesFree<10%,memory.available<5% --eviction-soft=nodefs.inodesFree<15%,memory.available<10%,nodefs.available<15% --eviction-soft-grace-period=nodefs.available=1m30s,nodefs.inodesFree=2m0s,memory.available=2m0s --eviction-max-pod-grace-period=120 --image-gc-high-threshold=85 --image-gc-low-threshold=80 --cpu-cfs-quota=true
root        4646  0.0  0.1 1244940 18688 ?       Ssl  Oct09   0:00 /csi-node-driver-registrar --csi-address=/csi/csi.sock --kubelet-registration-path=/var/lib/kubelet/plugins/ebs.csi.aws.com/csi.sock --v=2
nfsnobo+    4784  0.2  0.0 1241700 15712 ?       Ssl  Oct09   0:36 /bin/node_exporter --path.procfs=/host/proc --path.sysfs=/host/sys --path.rootfs=/host/root --path.udev.data=/host/root/run/udev/data --web.listen-address=[0.0.0.0]:9100 --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/) --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
root      183166  0.0  0.0 119424   992 pts/0    S+   00:16   0:00 grep --color=auto kubelet
```
**Expected Behavior**:
Nodes being recycled to take in the the new kubelet configuration
**Reproduction Steps** (Please include YAML):
```yaml
Name:         default
Namespace:    
Labels:       <none>
Annotations:  karpenter.k8s.aws/ec2nodeclass-hash: 16202142606489697909
              karpenter.k8s.aws/ec2nodeclass-hash-version: v3
              karpenter.sh/stored-version-migrated: true
              kubernetes.io/description: General purpose EC2NodeClass for running Amazon Linux 2 nodes for prod workloads
API Version:  karpenter.k8s.aws/v1
Kind:         EC2NodeClass
Metadata:
  Creation Timestamp:  2024-08-09T03:08:53Z
  Finalizers:
    karpenter.k8s.aws/termination
  Generation:        3
  Resource Version:  103128342
  UID:               06d2dec2-f1db-4018-9e18-1e1f3602c491
Spec:
  Ami Family:  AL2
  Ami Selector Terms:
    Alias:  al2@latest
  Block Device Mappings:
    Device Name:  /dev/xvda
    Ebs:
      Encrypted:    true
      Volume Size:  50Gi
      Volume Type:  gp3
  Kubelet:
    Cpu CFS Quota:  true
    Eviction Hard:
      memory.available:             5%
      nodefs.available:             10%
      nodefs.inodesFree:            10%
    Eviction Max Pod Grace Period:  120
    Eviction Soft:
      memory.available:   10%
      nodefs.available:   15%
      nodefs.inodesFree:  15%
    Eviction Soft Grace Period:
      memory.available:               2m
      nodefs.available:               1m30s
      nodefs.inodesFree:              2m
    Image GC High Threshold Percent:  85
    Image GC Low Threshold Percent:   80
    Kube Reserved:
      Cpu:                  300m
      Ephemeral - Storage:  3Gi
      Memory:               1Gi
    Pods Per Core:          13
    System Reserved:
      Cpu:                  200m
      Ephemeral - Storage:  1Gi
      Memory:               1Gi
  Metadata Options:
    Http Endpoint:                enabled
    httpProtocolIPv6:             disabled
    Http Put Response Hop Limit:  2
    Http Tokens:                  required
  Role:                           Karpenter-staging-au-1-20240809025645274500000005
  Security Group Selector Terms:
    Tags:
      karpenter.sh/discovery:  staging-au-1
  Subnet Selector Terms:
    Tags:
      karpenter.sh/discovery:  shared
  Tags:
    karpenter.sh/discovery:  staging-au-1
Status:
  Amis:
    Id:    ami-00d416f6c42cd5d88
    Name:  amazon-eks-gpu-node-1.30-v20240928
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        amd64
      Key:       karpenter.k8s.aws/instance-accelerator-count
      Operator:  Exists
    Id:          ami-00d416f6c42cd5d88
    Name:        amazon-eks-gpu-node-1.30-v20240928
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        amd64
      Key:       karpenter.k8s.aws/instance-gpu-count
      Operator:  Exists
    Id:          ami-01637a5ffbb75ef5c
    Name:        amazon-eks-node-1.30-v20240928
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        amd64
      Key:       karpenter.k8s.aws/instance-gpu-count
      Operator:  DoesNotExist
      Key:       karpenter.k8s.aws/instance-accelerator-count
      Operator:  DoesNotExist
    Id:          ami-0f9b86b5fcf375aca
    Name:        amazon-eks-arm64-node-1.30-v20240928
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        arm64
      Key:       karpenter.k8s.aws/instance-gpu-count
      Operator:  DoesNotExist
      Key:       karpenter.k8s.aws/instance-accelerator-count
      Operator:  DoesNotExist
  Conditions:
    Last Transition Time:  2024-08-19T23:34:24Z
    Message:               
    Reason:                AMIsReady
    Status:                True
    Type:                  AMIsReady
    Last Transition Time:  2024-08-19T23:34:24Z
    Message:               
    Reason:                InstanceProfileReady
    Status:                True
    Type:                  InstanceProfileReady
    Last Transition Time:  2024-08-19T23:34:24Z
    Message:               
    Reason:                Ready
    Status:                True
    Type:                  Ready
    Last Transition Time:  2024-08-19T23:34:24Z
    Message:               
    Reason:                SecurityGroupsReady
    Status:                True
    Type:                  SecurityGroupsReady
    Last Transition Time:  2024-08-19T23:34:24Z
    Message:               
    Reason:                SubnetsReady
    Status:                True
    Type:                  SubnetsReady
  Instance Profile:        staging-au-1_8146430464388342579
  Security Groups:
    Id:    sg-03f35e64fbbc952d4
    Name:  eks-cluster-sg-staging-au-1-746507050
    Id:    sg-064a1d9058acbe876
    Name:  staging-au-1-cluster-20240325003942944300000001
    Id:    sg-0ad4bffed2a0cbd9a
    Name:  staging-au-1-node-20240325003942945500000003
  Subnets:
    Id:       subnet-002f21f5bd759e51a
    Zone:     ap-southeast-2b
    Zone ID:  apse2-az1
    Id:       subnet-0143c7c8e6e3a171a
    Zone:     ap-southeast-2a
    Zone ID:  apse2-az3
    Id:       subnet-0c815e8132a9139b7
    Zone:     ap-southeast-2c
    Zone ID:  apse2-az2
Events:       <none>
```
**Versions**:
- Chart Version: `1.0.6`
- Kubernetes Version (`kubectl version`):`1.30`
- Kubelet Version: `v1.30.4-eks-a737599`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
