### ISSUE TITLE
Upgrade to v1.0.4 breaks kubelet config using EC2NodeClass's spec.kubelet.clusterDNS

### ISSUE THREAD

**Issue by schahal** [aws/karpenter-provider-aws#7235]
### Description

**Observed Behavior**:

After upgrading from `karpenter-provider-aws:v1.0.3`  to `v1.0.4`, the new Kubernetes nodes that Karpenter provisions does not have the EC2NodeClass's `spec.kubelet.clusterDNS` value in its `/etc/kubernetes/kubelet/config`.

For example, one of our EC2NodeClass's (e.g., `default-ebs`) looks like this:

<details><summary><b><i>Click to view EC2NodeClass</b></i></summary>

```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "<redacted>"
    karpenter.k8s.aws/ec2nodeclass-hash-version: v3
    karpenter.sh/stored-version-migrated: "true"
  finalizers:
  - karpenter.k8s.aws/termination
  generation: 18
  name: default-ebs
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
  - alias: bottlerocket@1.24.1
  ...
  kubelet:
    clusterDNS:
    - 169.254.20.11
    evictionHard:
      imagefs.available: 30%
      imagefs.inodesFree: 15%
      ...
    evictionSoft:
      ...
```

</details>

Notice, `spec.kubelet.clusterDNS: [169.254.20.11]`

However, on the new node, we see:

```
$ grep -A1 "clusterDNS" /.bottlerocket/rootfs/etc/kubernetes/kubelet/config
clusterDNS:
- 172.20.0.10
```

<details><summary>Also confirmed the NodePool the node is part of refers to the same EC2NodeClass as above </summary>

```
      Node Class Ref:
        Group:  karpenter.k8s.aws
        Kind:   EC2NodeClass
        Name:   default-ebs
```
</details>

**Expected Behavior**:

After reverting back to `v1.0.3`, we see the correct (expected) value on a new node:

```
$ grep -A1 "clusterDNS" /.bottlerocket/rootfs/etc/kubernetes/kubelet/config
clusterDNS:
- 169.254.20.11
```

**Reproduction Steps** (Please include YAML):

See above:

1. Run `karpenter-provider-aws:v1.0.3`
2. Make sure to have an EC2NodeClass which includes a custom `spec.kubelet.clusterDNS`
3. Confirm `/etc/kubernetes/kubelet/config` on node has that same value
4. Upgrade to `karpenter-provider-aws:v1.0.4`
5. Repeat steps (2)-(3) and you'll see that the config file on the new node does _**not**_ have that value

**Versions**:
- ~~Chart~~ Image Version: `v1.0.4`
- Kubernetes Version (`kubectl version`): `Server Version: v1.30.4-eks-a737599`
- Node version: `bottlerocket v1.24.1`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
