### ISSUE TITLE
Karpenter v1.0.7 - expireAfter not respected

### ISSUE THREAD

**Issue by aido123** [aws/karpenter-provider-aws#7319]
### Description

**Observed Behavior**:

I am trying to use the expireAfter field in the nodepool cr to trigger a new node to be provisioned, but when I apply the nodepool, the expireAfter setting always gets defaulted back to 720h.

I can see in the nodepool resource in the cluster that the generation field goes to 2 straight away indicating that something is changing it. I can seen my orginal expireAfter value in the last applied configuration.

Karpenter behaves normally for provisioning nodes etc.

**Expected Behavior**:

The expireAfter field should be respected in the nodepool config in the cluster and should show up in the corresponding nodeclaims etc

**Reproduction Steps** (Please include YAML):

EKS 1.30

1. Setup preqs for Karpenter (https://karpenter.sh/docs/getting-started/migrating-from-cas/)
2. Checkout  tag v1.0.7 (https://github.com/aws/karpenter-provider-aws/tree/v1.0.7)
3. Create overrides.yaml file. Note I create the service account separately.

```
controller:
  env:
  - name: https_proxy
    value: REMOVED
  - name: HTTPS_PROXY
    value: REMOVED
  - name: http_proxy
    value: REMOVED
  - name: HTTP_PROXY
    value: REMOVED
  - name: NO_PROXY
    value: REMOVED
  - name: no_proxy
    value: REMOVED
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
settings:
  clusterName: "REMOVED"
toleration:
- key: REMOVED
  operator: Exists
- effect: NoSchedule
  key: REMOVED
  operator: Equal
  value: "true"
serviceAccount:
  create: false
  name: karpenter
webhook:
  enabled: false
logLevel: debug
```

4. Install CRDS

```
helm install karpenter-crd karpenter-provider-aws/charts/karpenter-crd -f overrides.yaml -n kube-system
```

5. Install Karpenter

```
helm install karpenter karpenter-provider-aws/charts/karpenter -f overrides.yaml -n kube-system
```

6. Create Ec2 Node Class. 

```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: ec2-node-class
spec:
  amiFamily: AL2
  instanceProfile: "KarpenterNodeRole-<CLUSTERNAME>"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<CLUSTERNAME>"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<CLUSTERNAME>"
  amiSelectorTerms:
    - id: ami-025b796cea8b0422b
  userData: |
    DELETED
```

7. Create Nodepool

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: np1
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        DELETED
    spec:
      expireAfter: 24h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: ec2-node-class
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - c3.large
            - c4.large
            - c5.large
            - c5.xlarge
            - c5a.large
            - c5a.xlarge
            - c5ad.large
            - c5ad.xlarge
            - c5d.large
            - c5d.xlarge
            - c5n.large
            - c6a.large
            - c6a.xlarge
            - c6i.large
            - c6i.xlarge
            - c6id.large
            - c6in.large
            - c7a.large
            - c7i-flex.large
            - c7i-flex.xlarge
            - c7i.large
            - c7i.xlarge
            - m3.large
            - m4.large
            - m5.large
            - m5.xlarge
            - m5a.large
            - m5a.xlarge
            - m5ad.large
            - m5d.large
            - m5dn.large
            - m5n.large
            - m5zn.large
            - m6a.large
            - m6a.xlarge
            - m6i.large
            - m6i.xlarge
            - m6id.large
            - m6idn.large
            - m6in.large
            - m7a.large
            - m7i-flex.large
            - m7i-flex.xlarge
            - m7i.large
            - r3.large
            - r4.large
            - r5.large
            - r5a.large
            - r5ad.large
            - r5b.large
            - r5d.large
            - r5dn.large
            - r5n.large
            - r6a.large
            - r6i.large
            - r6id.large
            - r6in.large
            - r7a.large
            - r7i.large
            - r7iz.large
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - c
            - m
            - r
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - '2'
      taints:
        - key: DELETED
          effect: NoSchedule
          value: "true"
```

8. The above nodepool expireAfter field shows as 720h after been applied to the cluster

**Versions**:
- Chart Version: 0.37.0 (both crd and core karpenter charts)

- Kubernetes Version (`kubectl version`): 
Server Version: version.Info{Major:"1", Minor:"30+", GitVersion:"v1.30.5-eks-ce1d5eb", GitCommit:"194b08f0b9db51e750f3a3dcc2ffe5dda0103c0d", GitTreeState:"clean", BuildDate:"2024-09-21T09:31:42Z", GoVersion:"go1.22.6", Compiler:"gc", Platform:"linux/amd64"}
