### ISSUE TITLE
Bug Report: consolidateAfter and consolidationPolicy Field Validation Issue

### ISSUE THREAD

**Issue by shad-zam** [aws/karpenter-provider-aws#7328]
### Description

**Observed Behavior**:

When configuring the disruption field in a NodePool CRD, setting consolidationPolicy to "WhenEmptyOrUnderutilized" alongside a consolidateAfter duration (e.g., "5m") triggers an error. The following message appears:

```The NodePool "general-purpose" is invalid: spec.disruption: Invalid value: "object": consolidateAfter cannot be combined with consolidationPolicy=WhenUnderutilized``` 

**Expected Behavior**:

The consolidateAfter field should be compatible with consolidationPolicy: WhenEmptyOrUnderutilized, allowing configurations to apply successfully as documented. Alternatively, if this combination is not valid, it should be documented in the schema or guide.

**Reproduction Steps** (Please include YAML):

Configure the NodePool CRD with the following YAML

```
apiVersion: karpenter.sh/v1alpha5
kind: NodePool
metadata:
  name: general-purpose
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 5m

```

**Versions**:
- Chart Version: 
  karpenter-1.0.7
  karpenter-crd-1.0.7
- Kubernetes Version (`kubectl version`): v1.29.3

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
