### ISSUE TITLE
consolidateAfter keeps resetting to 0s in Karpenter v1

### ISSUE THREAD

**Issue by ketozhang** [aws/karpenter-provider-aws#7347]
### Description

**Observed Behavior**: `consolidateAfter` keeps resetting back to `0s`. I'm also seeing the annotation `compatibility.karpenter.sh/v1beta1-nodeclass-reference: '{"kind":"EC2NodeClass","name":"default"}'` added automatically. The migration docs mention this, but I don't understand how to avoid v1beta1 compatibility features if all my resources are already v1.

**Expected Behavior**: `consolidateAfter` respects value specified in NodePool definition

**Reproduction Steps** (Please include YAML):

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot", "on-demand"] # TODO: Does order matter? Spot goes first for opt-out.
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: ["c", "m", "r"]
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values: ["2"]
      - key: "topology.kubernetes.io/zone"
        operator: In
        values: ["us-east-1a", "us-east-1b"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default

      expireAfter: 720h # 30 days

  limits:
    cpu: 1000
    memory: "8000Gi"

  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 20m
```

**Versions**:
- Chart Version: 1.0.6
- Kubernetes Version (`kubectl version`): 
```
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.29.9-eks-ce1d5eb
WARNING: version difference between client (1.31) and server (1.29) exceeds the supported minor version skew of +/-1
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
