### ISSUE TITLE
Karpenter is aggressively replacing my nodes before pods have finished starting up on the node

### ISSUE THREAD

**Issue by nabeelpaytrix** [aws/karpenter-provider-aws#7356]
### Description

**Observed Behavior**:

When creating a new NodePool, I have specified the config seen below.
When provisioning Spring boot Java apps onto these nodes, the pods take a while to become ready, but Karpenter has launched a new NodeClaim is trying to remove my existing NodeClaim only 2 mins after it was created.

This Node Churn prevents any of my pods from being deployed.

**Expected Behavior**:

Karpenter should follow the consolidationAfter config I have set, and allow this node some time for the pods to finish starting up.

**Reproduction Steps** (Please include YAML):

You can use this yaml for provisioning the NodePool and EC2NodeClass:

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        # Usage: workloads
        Karpenter: "true"
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: Lt
          values: ["9"]
        - key: "karpenter.k8s.aws/instance-memory"
          operator: Lt
          values: ["18000"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: 720h # 30 days
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 20m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  instanceProfile: "development-karpenter-node-profile" 
  subnetSelectorTerms: # Feel free to replace with identifiers for your own Subnets
    - tags:
        karpenter.sh/discovery: "nonproduction"
        karpenter.sh/access: "private"
  securityGroupSelectorTerms: # Feel free to replace with identifiers for your own SGs
    - tags:
        karpenter.sh/discovery: "nonproduction"
  amiSelectorTerms:
    - alias: "al2@v20241024" # Changelog of versions here: https://github.com/awslabs/amazon-eks-ami/blob/main/CHANGELOG.md
  tags:
    Name: "development-karpenter-node"
    # Type: "workload"
```

The pods I try to deploy onto the nodes with label `Karpenter: "true"` can be created with this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-pod-a
  name: deployment-test-pod-a
  namespace: default
spec:
  revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: test-pod-a
  template:
    metadata:
      labels:
        app: test-pod-a
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: test-pod-a
            topologyKey: kubernetes.io/hostname
      containers:
      - imagePullPolicy: Always
        image: springcommunity/spring-petclinic-rest:latest
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 10
        name: test-pod-a
        ports:
        - containerPort: 8080
          name: http-svc
        resources:
          limits:
            memory: 750Mi
          requests:
            cpu: 2000m
            memory: 750Mi
        startupProbe:
          failureThreshold: 27
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      nodeSelector:
        Karpenter: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-pod-b
  name: deployment-test-pod-b
  namespace: default
spec:
  revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: test-pod-b
  template:
    metadata:
      labels:
        app: test-pod-b
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: test-pod-b
            topologyKey: kubernetes.io/hostname
      containers:
      - imagePullPolicy: Always
        image: springcommunity/spring-petclinic-rest:latest
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 10
        name: test-pod-b
        ports:
        - containerPort: 8080
          name: http-svc
        resources:
          limits:
            memory: 750Mi
          requests:
            cpu: 2000m
            memory: 750Mi
        startupProbe:
          failureThreshold: 27
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      nodeSelector:
        Karpenter: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-pod-c
  name: deployment-test-pod-c
  namespace: default
spec:
  revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: test-pod-c
  template:
    metadata:
      labels:
        app: test-pod-c
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: test-pod-c
            topologyKey: kubernetes.io/hostname
      containers:
      - imagePullPolicy: Always
        image: springcommunity/spring-petclinic-rest:latest
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 10
        name: test-pod-c
        ports:
        - containerPort: 8080
          name: http-svc
        resources:
          limits:
            memory: 750Mi
          requests:
            cpu: 2000m
            memory: 750Mi
        startupProbe:
          failureThreshold: 27
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      nodeSelector:
        Karpenter: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-pod-d
  name: deployment-test-pod-d
  namespace: default
spec:
  revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: test-pod-d
  template:
    metadata:
      labels:
        app: test-pod-d
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: test-pod-d
            topologyKey: kubernetes.io/hostname
      containers:
      - imagePullPolicy: Always
        image: springcommunity/spring-petclinic-rest:latest
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 10
        name: test-pod-d
        ports:
        - containerPort: 8080
          name: http-svc
        resources:
          limits:
            memory: 750Mi
          requests:
            cpu: 2000m
            memory: 750Mi
        startupProbe:
          failureThreshold: 27
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      nodeSelector:
        Karpenter: "true"
```

I've replaced my private spring boot 2 java images with an opensource image `springcommunity/spring-petclinic-rest:latest`. But I see the same behaviour with this image, whereby the pods are not ready within a min, and Karpenter starts nuking the pending node.

**What I have tried**:

- Setting `consolidateAfter` in the NodePool to 20mins, with hopes that Karpenter will leave the node alone for 20 mins, but the logs show that new NodeClaims are being created to replace my existing ones, **just 20 seconds after the original NodeClaim was created**.
- My Spring Boot pods use up a large chunk of CPU when they start up, but once started, the CPU level is around `50m`. So I have set the CPU request to be `250m`. But this caused the startup to bee too slow, so I tried to increase the CPU request to `2000m` to handle the initial startup, and it doesn't prevent Karpenter from killing my nodes.
- I switched to on-demand instance types, in case the disruption was caused by spot interruptions, but no luck.

**Karpenter Controller logs**

```
{"level":"INFO","time":"2024-11-08T18:01:13.945Z","logger":"controller","caller":"provisioning/provisioner.go:134","message":"found provisionable pod(s)","commit":"901a5dc","controller":"provisioner","namespace":"","name":"","reconcileID":"f958041e-ad11-48d4-b9fd-08e5782c0b6e","Pods":"default/deployment-test-pod-d-57c89565d6-r8jcc, default/deployment-test-pod-d-57c89565d6-tcv8q, default/deployment-test-pod-a-5db959df7c-lhksj, default/deployment-test-pod-c-79677886b7-6rb4d, default/deployment-test-pod-b-6c8f468dd4-tf5v9 and 7 other(s)","duration":"71.324145ms"}
{"level":"INFO","time":"2024-11-08T18:01:13.945Z","logger":"controller","caller":"provisioning/provisioner.go:359","message":"computed new nodeclaim(s) to fit pod(s)","commit":"901a5dc","controller":"provisioner","namespace":"","name":"","reconcileID":"f958041e-ad11-48d4-b9fd-08e5782c0b6e","nodeclaims":4,"pods":12}
{"level":"INFO","time":"2024-11-08T18:01:13.959Z","logger":"controller","caller":"provisioning/provisioner.go:155","message":"created nodeclaim","commit":"901a5dc","controller":"provisioner","namespace":"","name":"","reconcileID":"f958041e-ad11-48d4-b9fd-08e5782c0b6e","NodePool":{"name":"default"},"NodeClaim":{"name":"default-xb72p"},"requests":{"cpu":"6290m","memory":"2534Mi","pods":"8"},"instance-types":"c4.2xlarge, c5.2xlarge, c5a.2xlarge, c5d.2xlarge, c6a.2xlarge and 5 other(s)"}
{"level":"INFO","time":"2024-11-08T18:01:13.966Z","logger":"controller","caller":"provisioning/provisioner.go:155","message":"created nodeclaim","commit":"901a5dc","controller":"provisioner","namespace":"","name":"","reconcileID":"f958041e-ad11-48d4-b9fd-08e5782c0b6e","NodePool":{"name":"default"},"NodeClaim":{"name":"default-pf29b"},"requests":{"cpu":"6290m","memory":"2534Mi","pods":"8"},"instance-types":"c4.2xlarge, c5.2xlarge, c5a.2xlarge, c5d.2xlarge, c6a.2xlarge and 5 other(s)"}
{"level":"INFO","time":"2024-11-08T18:01:13.966Z","logger":"controller","caller":"provisioning/provisioner.go:155","message":"created nodeclaim","commit":"901a5dc","controller":"provisioner","namespace":"","name":"","reconcileID":"f958041e-ad11-48d4-b9fd-08e5782c0b6e","NodePool":{"name":"default"},"NodeClaim":{"name":"default-z6qqm"},"requests":{"cpu":"6290m","memory":"2534Mi","pods":"8"},"instance-types":"c4.2xlarge, c5.2xlarge, c5a.2xlarge, c5d.2xlarge, c6a.2xlarge and 5 other(s)"}
{"level":"INFO","time":"2024-11-08T18:01:13.966Z","logger":"controller","caller":"provisioning/provisioner.go:155","message":"created nodeclaim","commit":"901a5dc","controller":"provisioner","namespace":"","name":"","reconcileID":"f958041e-ad11-48d4-b9fd-08e5782c0b6e","NodePool":{"name":"default"},"NodeClaim":{"name":"default-vpf9w"},"requests":{"cpu":"6290m","memory":"2534Mi","pods":"8"},"instance-types":"c4.2xlarge, c5.2xlarge, c5a.2xlarge, c5d.2xlarge, c6a.2xlarge and 5 other(s)"}
{"level":"DEBUG","time":"2024-11-08T18:01:14.154Z","logger":"controller","caller":"launchtemplate/launchtemplate.go:203","message":"created launch template","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-xb72p"},"namespace":"","name":"default-xb72p","reconcileID":"558070b5-d88b-4284-9594-2bc988d3f5be","launch-template-name":"karpenter.k8s.aws/1769955589050201676","id":"lt-0013e74bf0f880f5e"}
{"level":"INFO","time":"2024-11-08T18:01:15.730Z","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-vpf9w"},"namespace":"","name":"default-vpf9w","reconcileID":"ed4aa0d6-7a75-41db-b789-534b055a4cb4","provider-id":"aws:///eu-west-2a/i-0c5e46c4cf9f06af8","instance-type":"c6a.2xlarge","zone":"eu-west-2a","capacity-type":"on-demand","allocatable":{"cpu":"7910m","ephemeral-storage":"17Gi","memory":"14162Mi","pods":"58","vpc.amazonaws.com/pod-eni":"38"}}
{"level":"INFO","time":"2024-11-08T18:01:15.731Z","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-xb72p"},"namespace":"","name":"default-xb72p","reconcileID":"558070b5-d88b-4284-9594-2bc988d3f5be","provider-id":"aws:///eu-west-2a/i-0d5a14a11bb945624","instance-type":"c6a.2xlarge","zone":"eu-west-2a","capacity-type":"on-demand","allocatable":{"cpu":"7910m","ephemeral-storage":"17Gi","memory":"14162Mi","pods":"58","vpc.amazonaws.com/pod-eni":"38"}}
{"level":"INFO","time":"2024-11-08T18:01:15.732Z","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-pf29b"},"namespace":"","name":"default-pf29b","reconcileID":"08844b79-06d2-4a9d-b14d-f0e0d131e930","provider-id":"aws:///eu-west-2a/i-0cd1463c1d01696c0","instance-type":"c6a.2xlarge","zone":"eu-west-2a","capacity-type":"on-demand","allocatable":{"cpu":"7910m","ephemeral-storage":"17Gi","memory":"14162Mi","pods":"58","vpc.amazonaws.com/pod-eni":"38"}}
{"level":"INFO","time":"2024-11-08T18:01:16.566Z","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-z6qqm"},"namespace":"","name":"default-z6qqm","reconcileID":"288f6d6a-2d6f-4f85-b6ea-55d8cde941f9","provider-id":"aws:///eu-west-2b/i-0020b1afef4daeb4e","instance-type":"c6a.2xlarge","zone":"eu-west-2b","capacity-type":"on-demand","allocatable":{"cpu":"7910m","ephemeral-storage":"17Gi","memory":"14162Mi","pods":"58","vpc.amazonaws.com/pod-eni":"38"}}
{"level":"INFO","time":"2024-11-08T18:01:33.782Z","logger":"controller","caller":"lifecycle/controller.go:111","message":"registered nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-pf29b"},"namespace":"","name":"default-pf29b","reconcileID":"5ae17ff7-3c48-43e5-b4ff-76488be87ef4","provider-id":"aws:///eu-west-2a/i-0cd1463c1d01696c0","Node":{"name":"ip-10-12-133-112.eu-west-2.compute.internal"}}
{"level":"INFO","time":"2024-11-08T18:01:35.088Z","logger":"controller","caller":"lifecycle/controller.go:111","message":"registered nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-vpf9w"},"namespace":"","name":"default-vpf9w","reconcileID":"837a48fd-3bf6-4d71-ac5c-9902f258f28c","provider-id":"aws:///eu-west-2a/i-0c5e46c4cf9f06af8","Node":{"name":"ip-10-12-158-126.eu-west-2.compute.internal"}}
{"level":"INFO","time":"2024-11-08T18:01:36.966Z","logger":"controller","caller":"lifecycle/controller.go:111","message":"registered nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-xb72p"},"namespace":"","name":"default-xb72p","reconcileID":"3e0ac922-39fa-4df5-b2bf-0440c9a0dd88","provider-id":"aws:///eu-west-2a/i-0d5a14a11bb945624","Node":{"name":"ip-10-12-141-178.eu-west-2.compute.internal"}}
{"level":"INFO","time":"2024-11-08T18:01:40.504Z","logger":"controller","caller":"lifecycle/controller.go:111","message":"registered nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-z6qqm"},"namespace":"","name":"default-z6qqm","reconcileID":"31a326b0-8c7a-4b93-acd3-5fe067aa23d9","provider-id":"aws:///eu-west-2b/i-0020b1afef4daeb4e","Node":{"name":"ip-10-12-108-125.eu-west-2.compute.internal"}}
{"level":"INFO","time":"2024-11-08T18:01:46.624Z","logger":"controller","caller":"lifecycle/controller.go:111","message":"initialized nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-pf29b"},"namespace":"","name":"default-pf29b","reconcileID":"9edccead-7bbd-4fac-b44b-3a1b32b687fa","provider-id":"aws:///eu-west-2a/i-0cd1463c1d01696c0","Node":{"name":"ip-10-12-133-112.eu-west-2.compute.internal"},"allocatable":{"cpu":"7910m","ephemeral-storage":"18242267924","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"14991800Ki","pods":"58"}}
{"level":"INFO","time":"2024-11-08T18:01:47.928Z","logger":"controller","caller":"lifecycle/controller.go:111","message":"initialized nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-vpf9w"},"namespace":"","name":"default-vpf9w","reconcileID":"683e5be8-9798-4ee4-9942-31ec2cf61474","provider-id":"aws:///eu-west-2a/i-0c5e46c4cf9f06af8","Node":{"name":"ip-10-12-158-126.eu-west-2.compute.internal"},"allocatable":{"cpu":"7910m","ephemeral-storage":"18242267924","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"14991800Ki","pods":"58"}}
{"level":"INFO","time":"2024-11-08T18:01:50.489Z","logger":"controller","caller":"lifecycle/controller.go:111","message":"initialized nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-xb72p"},"namespace":"","name":"default-xb72p","reconcileID":"8c2637fa-d1c4-4fe0-902a-ec10fd4dd5af","provider-id":"aws:///eu-west-2a/i-0d5a14a11bb945624","Node":{"name":"ip-10-12-141-178.eu-west-2.compute.internal"},"allocatable":{"cpu":"7910m","ephemeral-storage":"18242267924","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"14991808Ki","pods":"58"}}
{"level":"INFO","time":"2024-11-08T18:01:53.726Z","logger":"controller","caller":"lifecycle/controller.go:111","message":"initialized nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-z6qqm"},"namespace":"","name":"default-z6qqm","reconcileID":"fa08a71a-34c3-4cb0-86ac-26f2d610efec","provider-id":"aws:///eu-west-2b/i-0020b1afef4daeb4e","Node":{"name":"ip-10-12-108-125.eu-west-2.compute.internal"},"allocatable":{"cpu":"7910m","ephemeral-storage":"18242267924","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"14991800Ki","pods":"58"}}
{"level":"DEBUG","time":"2024-11-08T18:02:20.220Z","logger":"controller","caller":"launchtemplate/launchtemplate.go:367","message":"deleted launch template","commit":"901a5dc","id":"lt-0013e74bf0f880f5e","name":"karpenter.k8s.aws/1769955589050201676"}
{"level":"DEBUG","time":"2024-11-08T18:04:23.426Z","logger":"controller","caller":"disruption/controller.go:91","message":"marking drifted","commit":"901a5dc","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-z6qqm"},"namespace":"","name":"default-z6qqm","reconcileID":"62e27dbf-987f-479c-9390-16d41338e285","reason":"SecurityGroupDrift"}
{"level":"DEBUG","time":"2024-11-08T18:04:23.605Z","logger":"controller","caller":"disruption/controller.go:91","message":"marking drifted","commit":"901a5dc","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-z6qqm"},"namespace":"","name":"default-z6qqm","reconcileID":"b95a3b24-4b87-4a3b-bdea-11d073d510cf","reason":"SecurityGroupDrift"}
{"level":"INFO","time":"2024-11-08T18:04:29.489Z","logger":"controller","caller":"termination/controller.go:105","message":"tainted node","commit":"901a5dc","controller":"node.termination","controllerGroup":"","controllerKind":"Node","Node":{"name":"ip-10-12-108-125.eu-west-2.compute.internal"},"namespace":"","name":"ip-10-12-108-125.eu-west-2.compute.internal","reconcileID":"7bc046a6-3619-470b-b6b4-bd26a0f09cb2","taint.Key":"karpenter.sh/disrupted","taint.Value":"","taint.Effect":"NoSchedule"}
{"level":"INFO","time":"2024-11-08T18:04:29.729Z","logger":"controller","caller":"termination/controller.go:105","message":"tainted node","commit":"901a5dc","controller":"node.termination","controllerGroup":"","controllerKind":"Node","Node":{"name":"ip-10-12-133-112.eu-west-2.compute.internal"},"namespace":"","name":"ip-10-12-133-112.eu-west-2.compute.internal","reconcileID":"80fd770f-1448-4a69-bf0d-9df33b44a5cc","taint.Key":"karpenter.sh/disrupted","taint.Value":"","taint.Effect":"NoSchedule"}
{"level":"INFO","time":"2024-11-08T18:04:29.829Z","logger":"controller","caller":"termination/controller.go:124","message":"deleted node","commit":"901a5dc","controller":"node.termination","controllerGroup":"","controllerKind":"Node","Node":{"name":"ip-10-12-108-125.eu-west-2.compute.internal"},"namespace":"","name":"ip-10-12-108-125.eu-west-2.compute.internal","reconcileID":"7bc046a6-3619-470b-b6b4-bd26a0f09cb2"}
{"level":"INFO","time":"2024-11-08T18:04:30.115Z","logger":"controller","caller":"termination/controller.go:124","message":"deleted node","commit":"901a5dc","controller":"node.termination","controllerGroup":"","controllerKind":"Node","Node":{"name":"ip-10-12-133-112.eu-west-2.compute.internal"},"namespace":"","name":"ip-10-12-133-112.eu-west-2.compute.internal","reconcileID":"80fd770f-1448-4a69-bf0d-9df33b44a5cc"}
{"level":"INFO","time":"2024-11-08T18:04:31.231Z","logger":"controller","caller":"provisioning/provisioner.go:134","message":"found provisionable pod(s)","commit":"901a5dc","controller":"provisioner","namespace":"","name":"","reconcileID":"50853152-e961-4f62-8ca4-2c4cb2c1013b","Pods":"default/deployment-test-pod-a-5db959df7c-fjtgl, default/deployment-test-pod-b-6c8f468dd4-lpvwp, default/deployment-test-pod-b-6c8f468dd4-x68bx, default/deployment-test-pod-c-79677886b7-f2krs, default/deployment-test-pod-a-5db959df7c-w6vxz and 1 other(s)","duration":"30.749113ms"}
```

**Versions**:
- Chart Version: 1.0.7
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
