### ISSUE TITLE
UnauthorizedOperation - ec2:RunInstances

### ISSUE THREAD

**Issue by ricardorqr** [aws/karpenter-provider-aws#7370]
### Description

Hi everyone,

I'm a bit lost with this error. I've been having the message below for a while.
```json
{
   "level":"ERROR",
   "time":"2024-11-12T16:46:59.426Z",
   "logger":"controller",
   "message":"Reconciler error",
   "commit":"fb4d75f",
   "controller":"nodeclaim.lifecycle",
   "controllerGroup":"karpenter.sh",
   "controllerKind":"NodeClaim",
   "NodeClaim":{
      "name":"default-w2zlj"
   },
   "namespace":"",
   "name":"default-w2zlj",
   "reconcileID":"7a1e88bc-1169-4e4a-a4db-4ff689f2bd59",
   "error":"launching nodeclaim, creating instance, with fleet error(s), UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::123456789:assumed-role/karpeter-controller-role/1731429849551905269 is not authorized to perform: ec2:RunInstances on resource: arn:aws:ec2:us-east-2:123456789:instance/* with an explicit deny in a service control policy. Encoded authorization failure message: g4oZPBqZ4Bni8dE5dGjxYTnOZ..."
}
```

The funny part is that I'm able to launch instances. I deleted one node and I could see Karpenter creating a new one.

This is my NodePool.
```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h
```

This is my EC2NodeClass.
```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "${module.karpenter.node_iam_role_name}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "dev-network1"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "dev-network1"
```

And this is my policy (I deleted the resto and kept only what matters)
```json
{
    "Statement": [
        {
            "Action": [
                "ec2:RunInstances",
                "ec2:CreateFleet"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*::snapshot/*",
                "arn:aws:ec2:*::image/*",
                "arn:aws:ec2:*:*:subnet/*",
                "arn:aws:ec2:*:*:spot-instances-request/*",
                "arn:aws:ec2:*:*:security-group/*",
                "arn:aws:ec2:*:*:launch-template/*"
            ],
            "Sid": "AllowScopedEC2InstanceActions"
        },
        {
            "Action": [
                "ec2:RunInstances",
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/kubernetes.io/cluster/dev-network1": "owned"
                },
                "StringLike": {
                    "aws:RequestTag/karpenter.sh/nodepool": "*"
                }
            },
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*:*:volume/*",
                "arn:aws:ec2:*:*:spot-instances-request/*",
                "arn:aws:ec2:*:*:network-interface/*",
                "arn:aws:ec2:*:*:launch-template/*",
                "arn:aws:ec2:*:*:instance/*",
                "arn:aws:ec2:*:*:fleet/*"
            ],
            "Sid": "AllowScopedEC2InstanceActionsWithTags"
        },
        ...
    ],
    "Version": "2012-10-17"
}
```

I tested removing all conditions for AllowScopedEC2InstanceActions and AllowScopedEC2InstanceActionsWithTags and I still have the error. Any idea where I should start investigating?

I'm suing Karpenter 0.36.1 and Kubernetes 1.29.

**Comment by ricardorqr** [comment]
This is weird. I did a test. I scaled out a pod for 100 replicas and Karpenter terminated an old node and created a huge new one. Then, that error I talked about before disappeared. 
I think we are okay with closing this problem. If I see anything related to this problem again, I'll reopen it. Thanks guys.

**Comment by elouanKeryell-Even** [comment]
Encountering the same issue rn

EC2NodeClass is not ready because of this `status.condition`:

```yaml
status:
    conditions:
    - lastTransitionTime: "2025-06-16T12:27:16Z"
      message: Controller isn't authorized to call ec2:RunInstances
      observedGeneration: 1
      reason: RunInstancesAuthCheckFailed
      status: "False"
      type: ValidationSucceeded
```

... and we see the following error message in Cloud Trail:

> You are not authorized to perform this operation. User: arn:aws:sts::xxx:assumed-role/xxx-karpenter-controller-iam-role/1750076833277970979 is not authorized to perform: ec2:RunInstances on resource: arn:aws:ec2:eu-west-1::image/ami-0a915a467a87d1c66 with an explicit deny in a service control policy
