### ISSUE TITLE
Custom AMI never ready despite taint being applied - missing required startup taint, karpenter.sh/unregistered

### ISSUE THREAD

**Issue by geoffo-dev** [aws/karpenter-provider-aws#7399]
### Description

**Observed Behavior**:

When deploying a custom AMI NodeClass to Karpenter, it happily spins up the nodes, however they terminate after 15 minutes. After looking through the logs, the following errors occur:

```json
{
    "level": "ERROR",
    "time": "2024-11-15T18:18:38.433Z",
    "logger": "controller",
    "caller": "controller/controller.go:261",
    "message": "Reconciler error",
    "commit": "a2875e3",
    "controller": "nodeclaim.lifecycle",
    "controllerGroup": "karpenter.sh",
    "controllerKind": "NodeClaim",
    "NodeClaim": {
        "name": "default-g8nd2"
    },
    "namespace": "",
    "name": "default-g8nd2",
    "reconcileID": "c771433a-5731-4e0b-99f7-ad33361ec0d6",
    "error": "missing required startup taint, karpenter.sh/unregistered"
}
``` 

However these taints are included on the nodes when they are powered on and are subsequently removed. 

![Screenshot 2024-11-15 at 17 27 32](https://github.com/user-attachments/assets/ce45263f-5731-417e-b72b-d8ecf99e0c7c)

However the node claims themselves never enter a state of 'ready' as it states the taint has never been applied

![Screenshot 2024-11-18 at 10 51 19](https://github.com/user-attachments/assets/08a5c16a-fcc7-4999-b312-7994f83ed6e5)

(Please ignore timings as I have scaled karpenter to 0 pods to stop it from removing and readding nodes).

**Expected Behavior**:

Once the taints have been removed, Karpenter should confirm the nodeclaim as 'ready' so the nodes will not be recreated.

**Reproduction Steps** (Please include YAML):

Loosely following the guide here for deployment into Fargate:

https://aws-ia.github.io/terraform-aws-eks-blueprints/patterns/karpenter/ 

The nodeclass yaml is as follows:

```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Custom
  blockDeviceMappings:
  - deviceName: /dev/sda1
    ebs:
      volumeSize: 150Gi
      volumeType: gp3
      encrypted: true
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  userData: |
    #!/bin/bash
    set -e
    B64_CLUSTER_CA=${module.eks.cluster_certificate_authority_data}
    API_SERVER_URL=${module.eks.cluster_endpoint}
    /etc/eks/bootstrap.sh ${module.eks.cluster_name} --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL \
      --kubelet-extra-args='--register-with-taints="karpenter.sh/unregistered:NoExecute"'
    echo "Updating selinux to support the use of mountpoints"
    cd /tmp || exit
    cat > ./allow_mounton.te<< EOF
    module allow_mounton 1.1;
    require {
            type unconfined_service_t;
            class file mounton;
    }
    allow unconfined_service_t self:file mounton;
    EOF
    # Create and install the new code
    checkmodule -M -m -o allow_mounton.mod allow_mounton.te
    semodule_package -o allow_mounton.pp -m allow_mounton.mod
    semodule -i allow_mounton.pp

    # Make buffers bigger for lots of data
    echo "Setting UDP buffer sizes"
    tee /etc/sysctl.d/98-udpbuffer.conf > /dev/null <<EOT
    net.core.rmem_max=26214400
    net.core.wmem_max=26214400
    EOT
    sysctl -w net.core.rmem_max=26214400
    sysctl -w net.core.wmem_max=26214400
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${module.eks.cluster_name}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${module.eks.cluster_name}
    - id: ${data.terraform_remote_state.vpc.outputs.consumer_endpoint_egress_sg_id}
  instanceProfile: ${aws_iam_instance_profile.eks_node_karpenter_group.name}
  amiSelectorTerms:
    - name: custom-eks-amazon2-1.31-goldenimage-*
      owner: "xxxxxxxx"
  tags:
    karpenter.sh/discovery: ${module.eks.cluster_name}
```

As per the documentation the taint is being applied (and seen when the node is spun up) however it is not registering with the operator and never enters a ready state. 

**Versions**:
- Chart Version: 1.0.8
- Kubernetes Version (`kubectl version`): 1.31

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
