### ISSUE TITLE
nodes created with flavor not in karpenter.k8s.aws/instance-family filter

### ISSUE THREAD

**Issue by grandich** [aws/karpenter-provider-aws#7409]
### Description

**Observed Behavior**:

NODEPOOL
```
requirements:
- key: karpenter.k8s.aws/instance-category
  operator: In
  values:
  - m
  - r
- key: karpenter.k8s.aws/instance-cpu
  operator: In
  values:
  - "16"
  - "32"
- key: kubernetes.io/arch
  operator: In
  values:
  - amd64
  - arm64
- key: karpenter.sh/capacity-type
  operator: In
  values:
  - on-demand
- key: karpenter.k8s.aws/instance-family
  operator: NotIn
  values:
  - m1
  - m2
  - m3
  - m4
  - m5
  - c1
  - c3
  - c4
  - r3
  - r4
  - r5
```

RESULTING NODECLAIM
```
Spec:
  Requirements:
    Key:       karpenter.sh/capacity-type
    Operator:  In
    Values:
      on-demand
    Key:       karpenter.k8s.aws/instance-category
    Operator:  In
    Values:
      m
      r
    Key:       kubernetes.io/arch
    Operator:  In
    Values:
      amd64
    Key:       karpenter.k8s.aws/instance-cpu
    Operator:  In
    Values:
      16
      32
    Key:       node.kubernetes.io/instance-type
    Operator:  In
    Values:
      m5a.4xlarge
      m5a.8xlarge
      m5ad.4xlarge
      m5ad.8xlarge
      m5d.4xlarge
      m5d.8xlarge
      m5dn.4xlarge
      m5dn.8xlarge
      m5n.4xlarge
      m5n.8xlarge
      m6a.4xlarge
      m6a.8xlarge
      m6i.4xlarge
      m6i.8xlarge
      m6id.4xlarge
      m6id.8xlarge
      m6idn.4xlarge
      m6idn.8xlarge
      m6in.4xlarge
      m6in.8xlarge
      m7a.4xlarge
      m7a.8xlarge
      m7i-flex.4xlarge
      m7i-flex.8xlarge
      m7i.4xlarge
      m7i.8xlarge
      r5a.4xlarge
      r5a.8xlarge
      r5ad.4xlarge
      r5ad.8xlarge
      r5b.4xlarge
      r5b.8xlarge
      r5d.4xlarge
      r5d.8xlarge
      r5dn.4xlarge
      r5dn.8xlarge
      r5n.4xlarge
      r5n.8xlarge
      r6a.4xlarge
      r6a.8xlarge
      r6i.4xlarge
      r6i.8xlarge
      r6id.4xlarge
      r6id.8xlarge
      r6idn.4xlarge
      r6idn.8xlarge
      r6in.4xlarge
      r6in.8xlarge
      r7a.4xlarge
      r7a.8xlarge
      r7i.4xlarge
      r7i.8xlarge
      r7iz.4xlarge
      r7iz.8xlarge
    Key:       karpenter.k8s.aws/instance-family
    Operator:  NotIn
    Values:
      c1
      c3
      c4
      m1
      m2
      m3
      m4
      m5
      r3
      r4
      r5
```

RESULTING NODE
```
ip-10-43-xxxx.ec2.internal   Ready    2024-11-19T16:43:29Z   v1.27.16-eks-a737599   aws:///us-east-1a/i-xxxxxx   us-xxxxx-1a   ......   on-demand      m5a.4xlarge
```

**Expected Behavior**:

Not to launch m5a instances, as m5 instance type family is excluded in nodepool spec.

**Versions**:
- Karpenter 0.32.10
- Kubernetes Version (`kubectl version`): 1.27
