### ISSUE TITLE
When handling spot interruptions containers preStop hooks are not respected

### ISSUE THREAD

**Issue by ThomasJamesCrawford** [aws/karpenter-provider-aws#7419]
### Description

**Observed Behavior**:

I have prestop hooks like this

```
lifecycle:
  preStop:
    exec:
      command:
      - /bin/sh
      - -c
      - sleep 30
```

using on-demand instances I don't see any issues, but when using spot instances the preStop hook isn't respected when there is a spot termination.

I receive a log like this when a spot interruption is received

```
{"level":"INFO","time":"2024-11-21T07:12:57.754Z","logger":"controller.node.termination","message":"tainted node","commit":"e719109","node":"ip-10-73-60-90.ap-southeast-2.compute.internal"}
```

And immediately my pods on that node receive a SIGTERM. (Rather than having a 30s grace period before receiving a SIGTERM.)

**Expected Behavior**:

Pods should still respect the `preStop` hook even for a spot interruption.

**Reproduction Steps** (Please include YAML):

Have a deployment with this and log the signals when triggering a spot interruption.
```
lifecycle:
  preStop:
    exec:
      command:
      - /bin/sh
      - -c
      - sleep 20
```

**Versions**:
- Chart Version: 0.36.2
- Kubernetes Version (`kubectl version`): 1_29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
