### ISSUE TITLE
NodeClaim: up to 50 minutes between initialized and registered, causing pending pods

### ISSUE THREAD

**Issue by mcorbin** [aws/karpenter-provider-aws#7424]
### Description

**Observed Behavior**:

We recently upgraded Karpenter to 1.0.8 and noticed pending pods on our clusters.

After investigations, we noticed this behavior:

- **17:44:13.944**:  Karpenter registers a new nodeclaim **general-purpose-cb9b7** ("registered nodeclaim" in the logs)
- **18:12:45.012**: A new pod is scheduled on this nodeclaim: ("Pod should schedule on: nodeclaim/general-purpose-cb9b7" event)
- **18:35:14.286**: the nodeclaim is initialized( log "initialized nodeclaim").

During this whole periods pods scheduled on the registered nodeclaim are pending.

I couldn't find any log explaining this behavior, and we don't have the behavior on all nodes, only occasionally.

<br class="Apple-interchange-newline">

**Expected Behavior**:

The Nodeclaim should immediately being registered.

**Reproduction Steps** (Please include YAML):

We install Karpenter and CRDs using Terraform:

```
module "addons" {
  source            = "aws-ia/eks-blueprints-addons/aws"
  version           = "v1.16.3"
  ...
  enable_karpenter = true
  karpenter = {
    chart_version = "1.0.8"
    values        = [templatefile("${path.module}/karpenter-values.yaml", {})]
  }
...
}
```

```
resource "helm_release" "karpenter_crd" {
  name       = "karpenter-crd"
  namespace  = "karpenter"
  repository = "oci://public.ecr.aws/karpenter"
  version    = "1.0.8"
  chart      = "karpenter-crd"
}
```

Helm values file:

```
tolerations:
- key: dedicated
  operator: Equal
  value: orchestration
  effect: NoSchedule
nodeSelector:
  purpose: orchestration
podLabels:
  part-of: karpenter
  team: sre
serviceMonitor:
  enabled: true
controller:
  resources:
    requests:
      cpu: 1
      memory: 3Gi
    limits:
     memory: 3Gi
settings:
  aws:
    defaultInstanceProfile: ...
```

**Versions**:

- Chart Version: 1.0.8
- Kubernetes Version (kubectl version): 1.30.4

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
