### ISSUE TITLE
 karpenter cluster_state.synced metrics drops to 0 and stop provisioning any nodes until start controller (or remove the nodeclaims)

### ISSUE THREAD

**Issue by Yufeireal** [aws/karpenter-provider-aws#7428]
### Description

**Observed Behavior**:

karpenter.cluster_state.synced metrics drops to 0 for ~30 minutes and no new nodes can come up, causing lots of pods pending. Worstly, we are undergoing spot eviction from AWS, which make the failure even worse.
At the meantime, we saw some nodeclaims Reconciler errors from the logs.

Restart controller + deleting the nodeclaims(remove the finalizer) make the controller cluster state sync again.

I am not sure these are related or not:
 https://github.com/kubernetes-sigs/karpenter/issues/1767
https://github.com/aws/karpenter-provider-aws/issues/6643

Unfortuantely, we don't have info level logs exposed in datadog and pods were restarted already. But very similar to these,  previously first time it happens, I saw it has an infinate loop around certain nodeclaims objects.

Metrics node created:
No new nodes created when cluster sync status is 0. For some reason, it's back to 1, provisioned some nodes and all of sudden drops to 0 again.

<img width="1691" alt="image" src="https://github.com/user-attachments/assets/606d9e35-5649-4e55-9a2e-3643ec7fc0ea">

Metrics cluster sync status:

<img width="1385" alt="image" src="https://github.com/user-attachments/assets/df89da8c-1f16-4246-b765-30f15adc0a2b">

**Expected Behavior**:

I think we should expect karpenter.cluster_state.synced to be always 1 or self-recover to 1 very soon? But I don't understand what could drive this to be 0 and why it stucks in 0 for such a long time without manual operations.

**Reproduction Steps** (Please include YAML):

I don't know how to reproduce it.. Our cluster is kind of huge 2500 nodes at peak time, it's really difficult for me to simulate those massive events which could stuck karpenter controller process if this is the case. 

And noted It's not happening frequently but whenever it happens, it's an incident to us.. 

For more info, here are two types of logs we saw:
log_1
```
launching nodeclaim, creating instance, truncating instance types, validating minValues, minValues requirement is not met for "karpenter.k8s.aws/instance-category"
nodeclaims: sqs-burstable-spot-*
```
log_2
```
can't drain node, PDB "default/vmule" is blocking evictions
nodeclaims: sqs-burstable-spot-*
```
log_3
```
controller: eviction-queue
error:
This pod has more than one PodDisruptionBudget, which the eviction subresource does not support.
```
And please notice, nearly at the same time, aws triggers a huge amount of Spot Instances reclaims, they reclaimed 150+ nodes, I am not sure will this pose Karpenter in a bad state or not. 
But one thing is I found log_1 was emitted days ago, at that time, karpenter cluster is also out of sync, is this something related to "minValues"? Saw that's a pretty new feature.

FYi, nodepool:
sqs-burstable-spot:
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  labels:
    app.kubernetes.io/instance: vkarpenter
  name: sqs-burstable-spot
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        asg-name: sqs-burstable-spot
        dedicated: sqs-burstable
        descheduler: "true"
        pool_type: dedicated
        type: amd
    spec:
      expireAfter: 336h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-tier3
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
        - arm64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-category
        operator: In
        minValues: 2
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-family
        operator: In
        minValues: 4
        values:
        - c5
        - c5n
        - c5a
        - c5d
        - c5ad
        - c6a
        - c6i
        - c6id
        - c6in
        - m5
        - m5a
        - m5ad
        - m5d
        - m5dn
        - m5n
        - m5zn
        - m6a
        - m6i
        - m6id
        - m6idn
        - m6in
        - r5
        - r5a
        - r5ad
        - r5d
        - r5dn
        - r5n
        - r6a
        - r6i
        - r6id
        - r6idn
        - r6in
        - c6g
        - c6gd
        - c6gn
        - c7g
        - c7gd
        - c7gn
        - m6g
        - m6gd
        - m7g
        - m7gd
        - r6g
        - r6gd
        - r7g
        - r7gd
      - key: node.kubernetes.io/instance-type
        minValues: 6
        operator: Exists
      - key: karpenter.k8s.aws/instance-cpu
        operator: Gt
        values:
        - "31"
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-west-2a
        - us-west-2b
        - us-west-2c
      taints:
      - effect: NoSchedule
        key: dedicated
        value: sqs-burstable
      terminationGracePeriod: 1h
  weight: 20
```

**Versions**:
- Chart Version: 1.0.0
- Kubernetes Version (`kubectl version`): 1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
