### ISSUE TITLE
"failed to discover any AMIs" and "no subnets found" error when using bottlerocket@latest alias

### ISSUE THREAD

**Issue by sammoseley** [aws/karpenter-provider-aws#7457]
### Description

**Observed Behavior**:
When specifying the following ami selector:
```
  amiSelectorTerms:
    - alias: bottlerocket@latest
```

We get this error repeatedly:
`{"level":"ERROR","time":"2024-11-27T16:39:59.085Z","logger":"controller","caller":"disruption/helpers.go:149","message":"failed listing instance types for spot-default","commit":"901a5dc","controller":"disruption","namespace":"","name":"","reconcileID":"b498b292-ab97-45c8-a27f-8653f5614768","error":"no subnets found"}`

and (less frequently for some reason, but seems more accurate):

`{"level":"ERROR","time":"2024-11-27T12:35:40.807Z","logger":"controller","message":"Reconciler error","commit":"a2875e3","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"bottlerocket-default"},"namespace":"","name":"bottlerocket-default","reconcileID":"65cf9ace-195e-4bd8-906d-74df0ac6f749","error":"getting amis, getting AMI queries, failed to discover any AMIs for alias \"bottlerocket@latest\""}`

If the alias is swapped for name, pinning a specific AMI version, eg:
  ```
amiSelectorTerms:
    - name: bottlerocket-aws-k8s-1.31-aarch64-v1.27.1-efd46c32
```
      
It works fine, and Karpenter scales as expected.

The subnets are labelled as required, and this hasn't changed, so I think the "subnet" error is a bit misleading.

**Expected Behavior**:

Specifying alias: bottlerocket@latest should successfully select an AMI, as we're observing in Karpenter v0.37 elsewhere.

**Reproduction Steps** (Please include YAML):

Use this in the ec2nodeclass def:
```
amiSelectorTerms:
    - alias: bottlerocket@latest
```

**Versions**:

- Chart Version: v1.0.8
- Kubernetes Version (`kubectl version`): 1.31

Also seeing the same issue in v1.0.7, but that appears to throw the "no subnets found" error rather than the AMI discovery error.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sammoseley** [comment]
Getting the same issue using an alias (eg. a valid version number) other than “latest” also. The only way it works is to not use alias: and use name:

**Comment by jonathan-innis** [comment]
@sammoseley Can you share the whole EC2NodeClass that you are using here?

**Comment by jonathan-innis** [comment]
Can you also share the full log output from an installation of Karpenter that is showing these errors? I just tried the following EC2NodeClass and I was successfully able to discover the AMIs and successfully launch nodes that joined my cluster

```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: KarpenterNodeRole-scale-test
  amiSelectorTerms:
  - alias: bottlerocket@latest
  subnetSelectorTerms:                             
    - tags:
        karpenter.sh/discovery: scale-test
  securityGroupSelectorTerms:                      
    - tags: 
        karpenter.sh/discovery: scale-test
```
