### ISSUE TITLE
karpenter 1.0.8 Node not registered with cluster

### ISSUE THREAD

**Issue by TSjhkim** [aws/karpenter-provider-aws#7469]
### Description

**Observed Behavior**:
I install on clean EKS Cluster 1.31, with Karpenter 1.0.8 follow the [Karpenter Docs](https://karpenter.sh/v1.0/getting-started/getting-started-with-karpenter/), and karpenter pod running successful, EC2 instance was created.
But EC2 instance does not join to EKS Cluster.

I will attach the created EC2 instance's kubelet log file.
[kubelet log.txt](https://github.com/user-attachments/files/17974010/kubelet.log.txt)

I add the **_karpenter.sh/discovery_** tag on **_Subnet_** that node will created, **_SG_** that node will use, and **_Cluster_**.
nodeclaim status as below.
```
  Conditions:
    Last Transition Time:  2024-12-02T06:26:37Z
    Message:               Node not registered with cluster
    Reason:                NodeNotFound
    Status:                Unknown
    Type:                  Initialized
    Last Transition Time:  2024-12-02T06:26:37Z
    Message:               
    Reason:                Launched
    Status:                True
    Type:                  Launched
    Last Transition Time:  2024-12-02T06:26:37Z
    Message:               Initialized=Unknown, Registered=Unknown
    Reason:                UnhealthyDependents
    Status:                Unknown
    Type:                  Ready
    Last Transition Time:  2024-12-02T06:26:37Z
    Message:               Node not registered with cluster
    Reason:                NodeNotFound
    Status:                Unknown
    Type:                  Registered
  Image ID:                ami-0ea66fbd857bd1152
  Provider ID:             aws:///ap-northeast-2c/i-0e0eeead5a52836fc
Events:
  Type    Reason             Age                From       Message
  ----    ------             ----               ----       -------
  Normal  Launched           6m5s               karpenter  Status condition transitioned, Type: Launched, Status: Unknown -> True, Reason: Launched
  Normal  Launched           6m5s               karpenter  Status condition transitioned, Type: Launched, Status: Unknown -> True, Reason: Launched
  Normal  DisruptionBlocked  3s (x4 over 6m3s)  karpenter  Cannot disrupt NodeClaim: state node doesn't contain both a node and a nodeclaim
```
I configure aws-auth as below.
```
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::123456781234:role/KarpenterNodeRole-clustername
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
.
.
```
nodepool and nodeclasss as below.
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 20s
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "KarpenterNodeRole-${CLUSTER_NAME}" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  amiSelectorTerms:
    - id: "ami-0e94e1ac5ec599153"
    - id: "ami-0ea66fbd857bd1152"
```

**Expected Behavior**:
EC2 instance is join to cluster.

**Reproduction Steps** (Please include YAML):
1. Set the variable such as KARPENTER_NAMESPACE, ARM_AMI_ID ... etc on Karpenter Docs
2. Create resources with CloudFormation stack
3. Create the IRSA
4. Create the IAMIdentityMapping
5. Edit aws-auth
6. Install eks-pod-identity-agent
7. Install Karpenter Helm 1.0.8
8. Add the Tag to Subnet, SG, Cluster
9. Create Nodepool & EC2NodeClass

**Versions**:
- Chart Version: 1.0.8
- Kubernetes Version (`kubectl version`): 1.31

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
