### ISSUE TITLE
I made changes only to NodePool, but NodeClass has changed as well

### ISSUE THREAD

**Issue by EigoOda** [aws/karpenter-provider-aws#7470]
### Description

**Observed Behavior**:

When I changed only the NodePool setting and applied, the NodeClass setting was also changed.
The only place to change is in NodePool resource value of key: “karpenter.k8s.aws/instance-cpu”.

The only unexpected change is the value of `.spec.metadataOptions.httpPutResponseHopLimit` in NodeClass, which is changed from 2 to 1.

The httpPutResponseHopLimit was not defined in Yaml, but used the default. (I intentionally set it to 2 now because of this issue)
As I assume, we upgraded from v0.37 to v1 about a month ago.
At that time, I did not take any action because the httpPutResponseHopLimit did not change to 1, which is the v1 default, without changing httpPutResponseHopLimit to 2.

Is it possible that this has now been changed to the default of 1?

before
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodepool
spec:
  template:
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["m6i"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["16", "32", "48"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: nodeclass
      expireAfter: 720h # 30days
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    budgets:
      - nodes: 25
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: nodeclass
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - name: amazon-eks-node-al2023-x86_64-standard-1.29-v20241024
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "dev"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "dev"
  role: "noderole"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 60Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
        throughput: 125
  tags:
    CostEnv: dev
    CostService: service
    CostTeam: team
  userData: |
    #!/bin/bash
    modprobe iptable_nat
    modprobe ip6table_nat
    dnf -y install rsyslog
    systemctl enable --now rsyslog
```

after
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodepool
spec:
  template:
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["m6i"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32", "48"] <-- here
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: nodeclass
      expireAfter: 720h # 30days
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    budgets:
      - nodes: 25
```

**Expected Behavior**:

- Change only where expected.

**Reproduction Steps** (Please include YAML):

- Checking

**Versions**:
- Chart Version: 1.0.6(oci://public.ecr.aws/karpenter/karpenter)
- Kubernetes Version (`kubectl version`): v1.29.10-eks-7f9249a

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
