### ISSUE TITLE
nodeClaim label domain is invalid after 1.1.0 update

### ISSUE THREAD

**Issue by joke** [aws/karpenter-provider-aws#7471]
### Description

**Observed Behavior**:

After upgrading to 1.1.0 karpenter can not create nodeclaims any more.

```yaml
level: ERROR
time: '2024-12-02T11:57:49.729Z'
logger: controller
message: Reconciler error
commit: 0a85efb
controller: provisioner
namespace: ''
name: ''
reconcileID: 65e78b27-e60a-4763-9a77-820b60957497
error: >-
  creating node claim, NodeClaim.karpenter.sh "infrastructure-7zhm2" is invalid:
  spec.requirements[5].key: Invalid value: "string": label domain
  "karpenter.k8s.aws" is restricted; creating node claim, NodeClaim.karpenter.sh
  "infrastructure-t62zd" is invalid: spec.requirements[7].key: Invalid value:
  "string": label domain "karpenter.k8s.aws" is restricted; creating node claim,
  NodeClaim.karpenter.sh "infrastructure-hchvj" is invalid:
  spec.requirements[6].key: Invalid value: "string": label domain
  "karpenter.k8s.aws" is restricted
errorCauses:
  - error: >-
      creating node claim, NodeClaim.karpenter.sh "infrastructure-7zhm2" is
      invalid: spec.requirements[5].key: Invalid value: "string": label domain
      "karpenter.k8s.aws" is restricted
  - error: >-
      creating node claim, NodeClaim.karpenter.sh "infrastructure-t62zd" is
      invalid: spec.requirements[7].key: Invalid value: "string": label domain
      "karpenter.k8s.aws" is restricted
  - error: >-
      creating node claim, NodeClaim.karpenter.sh "infrastructure-hchvj" is
      invalid: spec.requirements[6].key: Invalid value: "string": label domain
      "karpenter.k8s.aws" is restricted
```

**Expected Behavior**:

The node claims should be created without problem and new node should join the cluster.

**Reproduction Steps** (Please include YAML):

The node pool definition. If you need any more information I happy to help.

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: infrastructure
spec:
  disruption:
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        istio-version: 1.24.1
    spec:
      expireAfter: 168h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: bottlerocket
      requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - m8g
        - m7g
        - m7a
        - m6g
        - m6a
        - m5a
        - c8g
        - c7g
        - c7a
        - c6g
        - c6a
        - c5a
        - r8g
        - r7g
        - r7a
        - r6g
        - r6a
        - r5a
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
        - spot
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      startupTaints:
        - key: cni.istio.io/not-ready
          value: 'true'
          effect: NoExecute
```

**Versions**:
- Chart Version: 1.1.0
- Kubernetes Version (`kubectl version`): v1.31.2-eks-7f9249a
