### ISSUE TITLE
karpenter.sh/unregistered taint must be present on Karpenter-managed nodes

### ISSUE THREAD

**Issue by sylr** [aws/karpenter-provider-aws#7486]
### Description

**Observed Behavior**:

My nodeclaims stay uninitialized:

NodeClaim events:
```
  Type    Reason             Age                From       Message
  ----    ------             ----               ----       -------
  Normal  Launched           4m5s               karpenter  Status condition transitioned, Type: Launched, Status: Unknown -> True, Reason: Launched
  Normal  DisruptionBlocked  4m5s               karpenter  Cannot disrupt NodeClaim: nodeclaim does not have an associated node
  Normal  Registered         3m42s              karpenter  Status condition transitioned, Type: Registered, Status: Unknown -> False, Reason: UnregisteredTaintNotFound, Message: Invariant violated, karpenter.sh/unregistered taint must be present on Karpenter-managed nodes
  Normal  Ready              3m42s              karpenter  Status condition transitioned, Type: Ready, Status: Unknown -> False, Reason: UnhealthyDependents, Message: Registered=False, Initialized=Unknown
  Normal  DisruptionBlocked  4s (x2 over 2m4s)  karpenter  Cannot disrupt NodeClaim: state node isn't initialized
```

EC2NodeClass:

```yaml
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: al2023-default
spec:
  # Required, resolves a default ami and userdata
  amiFamily: AL2023
  amiSelectorTerms:
  - alias: al2023@v20241121

  # Required, discovers subnets to attach to instances
  subnetSelectorTerms:
  - tags:
      "kubernetes.io/cluster/eks-euc1-dev-06": "owned"

  # Required, discovers security groups to attach to instances
  securityGroupSelectorTerms:
  - id: sg-xxxxxxxxxxxxxxxx # eks-euc1-dev-06-nodes
  - id: sg-yyyyyyyyyyyyyyyy # eks-cluster-sg-eks-euc1-dev-06-208106163

  # Optional, IAM role to use for the node identity.
  # The "role" field is immutable after EC2NodeClass creation. This may change in the
  # future, but this restriction is currently in place today to ensure that Karpenter
  # avoids leaking managed instance profiles in your account.
  # Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  #role: "EKSClusterKarpenterNodeRole"

  # Optional, IAM instance profile to use for the node identity.
  # Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  instanceProfile: "EKSClusterKarpenterNodeProfile"

  # Optional, overrides autogenerated userdata with a merge semantic
  userData: |
    Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
    MIME-Version: 1.0

    --MIMEBOUNDARY
    Content-Transfer-Encoding: 7bit
    Content-Type: application/node.eks.aws
    Mime-Version: 1.0

    ---
    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      cluster:
        cidr: 172.20.0.0/16
        name: eks-euc1-dev-06
      kubelet:
        config:
          clusterDNS:
          - 172.20.0.10
        flags:
        - --register-with-taints=node.cilium.io/agent-not-ready=true:NoExecute

    --MIMEBOUNDARY--

  # Optional, propagates tags to underlying EC2 resources
  tags:
    artex.io/scope: kubernetes

  # Optional, configures IMDS for the instance
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required

  # Optional, configures storage devices for the instance
  blockDeviceMappings:
  # Root device
  - deviceName: /dev/xvda
    rootVolume: true
    ebs:
      volumeSize: 50Gi
      volumeType: gp3
      encrypted: true

  # Optional, configures detailed monitoring for the instance
  detailedMonitoring: true
```

NodePool:

```yaml
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default-arm64
spec:
  # Template section that describes how to template out NodeClaim resources that Karpenter will provision
  # Karpenter will consider this template to be the minimum requirements needed to provision a Node using this NodePool
  # It will overlay this NodePool with Pods that need to schedule to further constrain the NodeClaims
  # Karpenter will provision to launch new Nodes for the cluster
  template:
    spec:
      # References the Cloud Provider's NodeClass resource, see your cloud provider specific documentation
      nodeClassRef:
        name: al2023-default
        kind: EC2NodeClass
        group: karpenter.k8s.aws

      # Provisioned nodes will have these taints
      # Taints may prevent pods from scheduling if they are not tolerated by the pod.
      taints: []

      # Provisioned nodes will have these taints, but pods do not need to tolerate these taints to be provisioned by this
      # NodePool. These taints are expected to be temporary and some other entity (e.g. a DaemonSet) is responsible for
      # removing the taint after it has finished initializing the node.
      startupTaints:
      - key: karpenter.sh/unregistered
        value: "true"
        effect: NoExecute
      - key: node.cilium.io/agent-not-ready
        value: "true"
        effect: NoExecute

      # Requirements that constrain the parameters of provisioned nodes.
      # These requirements are combined with pod.spec.topologySpreadConstraints, pod.spec.affinity.nodeAffinity, pod.spec.affinity.podAffinity, and pod.spec.nodeSelector rules.
      # Operators { In, NotIn, Exists, DoesNotExist, Gt, and Lt } are supported.
      # https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#operators
      requirements:
      - key: "karpenter.k8s.aws/instance-family"
        operator: In
        values: ["c6g", "m6g", "r6g"]
      - key: "karpenter.k8s.aws/instance-size"
        operator: In
        values: ["xlarge", "2xlarge", "4xlarge"]
      - key: "topology.kubernetes.io/zone"
        operator: In
        values: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["arm64"]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot", "on-demand"]

      expireAfter: 720h
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 90s

  # Resource limits constrain the total size of the cluster.
  # Limits prevent Karpenter from creating new instances once the limit is exceeded.
  limits:
    cpu: "100"
    memory: 1000Gi

  # Priority given to the NodePool when the scheduler considers which NodePool
  # to select. Higher weights indicate higher priority when comparing NodePools.
  # Specifying no weight is equivalent to specifying a weight of 0.
  weight: 1
```

NodeClaim:

```yaml
Name:         default-arm64-rtgc8
Namespace:
Labels:       karpenter.k8s.aws/ec2nodeclass=al2023-default
              karpenter.k8s.aws/instance-category=c
              karpenter.k8s.aws/instance-cpu=4
              karpenter.k8s.aws/instance-cpu-manufacturer=aws
              karpenter.k8s.aws/instance-cpu-sustained-clock-speed-mhz=2500
              karpenter.k8s.aws/instance-ebs-bandwidth=4750
              karpenter.k8s.aws/instance-encryption-in-transit-supported=false
              karpenter.k8s.aws/instance-family=c6g
              karpenter.k8s.aws/instance-generation=6
              karpenter.k8s.aws/instance-hypervisor=nitro
              karpenter.k8s.aws/instance-memory=8192
              karpenter.k8s.aws/instance-network-bandwidth=1250
              karpenter.k8s.aws/instance-size=xlarge
              karpenter.sh/capacity-type=spot
              karpenter.sh/nodepool=default-arm64
              kubernetes.io/arch=arm64
              kubernetes.io/os=linux
              node.kubernetes.io/instance-type=c6g.xlarge
              topology.k8s.aws/zone-id=euc1-az1
              topology.kubernetes.io/region=eu-central-1
              topology.kubernetes.io/zone=eu-central-1c
Annotations:  karpenter.k8s.aws/ec2nodeclass-hash: 17602244626171913199
              karpenter.k8s.aws/ec2nodeclass-hash-version: v4
              karpenter.sh/nodepool-hash: 626892256260369355
              karpenter.sh/nodepool-hash-version: v3
API Version:  karpenter.sh/v1
Kind:         NodeClaim
Metadata:
  Creation Timestamp:  2024-12-05T14:59:52Z
  Finalizers:
    karpenter.sh/termination
  Generate Name:  default-arm64-
  Generation:     1
  Owner References:
    API Version:           karpenter.sh/v1
    Block Owner Deletion:  true
    Kind:                  NodePool
    Name:                  default-arm64
    UID:                   45b4cf87-aa2c-4202-bff2-c8167e319ad0
  Resource Version:        3361078
  UID:                     c53d04fa-9119-4c6b-81bd-45360a982fae
Spec:
  Expire After:  720h
  Node Class Ref:
    Group:  karpenter.k8s.aws
    Kind:   EC2NodeClass
    Name:   al2023-default
  Requirements:
    Key:       node.kubernetes.io/instance-type
    Operator:  In
    Values:
      c6g.2xlarge
      c6g.4xlarge
      c6g.xlarge
      m6g.2xlarge
      m6g.4xlarge
      m6g.xlarge
      r6g.2xlarge
      r6g.4xlarge
      r6g.xlarge
    Key:       karpenter.k8s.aws/instance-family
    Operator:  In
    Values:
      c6g
      m6g
      r6g
    Key:       topology.kubernetes.io/zone
    Operator:  In
    Values:
      eu-central-1a
      eu-central-1b
      eu-central-1c
    Key:       kubernetes.io/os
    Operator:  In
    Values:
      linux
    Key:       karpenter.sh/nodepool
    Operator:  In
    Values:
      default-arm64
    Key:       karpenter.k8s.aws/instance-size
    Operator:  In
    Values:
      2xlarge
      4xlarge
      xlarge
    Key:       kubernetes.io/arch
    Operator:  In
    Values:
      arm64
    Key:       karpenter.sh/capacity-type
    Operator:  In
    Values:
      on-demand
      spot
    Key:       karpenter.k8s.aws/ec2nodeclass
    Operator:  In
    Values:
      al2023-default
  Resources:
    Requests:
      Cpu:     200m
      Memory:  110Mi
      Pods:    3
  Startup Taints:
    Effect:  NoExecute
    Key:     karpenter.sh/unregistered
    Value:   true
    Effect:  NoExecute
    Key:     node.cilium.io/agent-not-ready
    Value:   true
Status:
  Allocatable:
    Cpu:                        3920m
    Ephemeral - Storage:        44Gi
    Memory:                     6525Mi
    Pods:                       58
    vpc.amazonaws.com/pod-eni:  18
  Capacity:
    Cpu:                        4
    Ephemeral - Storage:        50Gi
    Memory:                     7518Mi
    Pods:                       58
    vpc.amazonaws.com/pod-eni:  18
  Conditions:
    Last Transition Time:  2024-12-05T14:59:52Z
    Message:               object is awaiting reconciliation
    Observed Generation:   1
    Reason:                AwaitingReconciliation
    Status:                Unknown
    Type:                  Initialized
    Last Transition Time:  2024-12-05T14:59:54Z
    Message:
    Observed Generation:   1
    Reason:                Launched
    Status:                True
    Type:                  Launched
    Last Transition Time:  2024-12-05T15:00:17Z
    Message:               Invariant violated, karpenter.sh/unregistered taint must be present on Karpenter-managed nodes
    Observed Generation:   1
    Reason:                UnregisteredTaintNotFound
    Status:                False
    Type:                  Registered
    Last Transition Time:  2024-12-05T15:00:17Z
    Message:               Registered=False, Initialized=Unknown
    Observed Generation:   1
    Reason:                UnhealthyDependents
    Status:                False
    Type:                  Ready
  Image ID:                ami-04a8bf5c19de8e195
  Last Pod Event Time:     2024-12-05T15:02:13Z
  Provider ID:             aws:///eu-central-1c/i-0c6b8152bf75e8efd
Events:
  Type    Reason             Age                From       Message
  ----    ------             ----               ----       -------
  Normal  Launched           4m5s               karpenter  Status condition transitioned, Type: Launched, Status: Unknown -> True, Reason: Launched
  Normal  DisruptionBlocked  4m5s               karpenter  Cannot disrupt NodeClaim: nodeclaim does not have an associated node
  Normal  Registered         3m42s              karpenter  Status condition transitioned, Type: Registered, Status: Unknown -> False, Reason: UnregisteredTaintNotFound, Message: Invariant violated, karpenter.sh/unregistered taint must be present on Karpenter-managed nodes
  Normal  Ready              3m42s              karpenter  Status condition transitioned, Type: Ready, Status: Unknown -> False, Reason: UnhealthyDependents, Message: Registered=False, Initialized=Unknown
  Normal  DisruptionBlocked  4s (x2 over 2m4s)  karpenter  Cannot disrupt NodeClaim: state node isn't initialized
```

User Data taken from the instance:

```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: application/node.eks.aws

---
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    cidr: 172.20.0.0/16
    name: eks-euc1-dev-06
  kubelet:
    config:
      clusterDNS:
      - 172.20.0.10
    flags:
    - --register-with-taints=node.cilium.io/agent-not-ready=true:NoExecute

--//
Content-Type: application/node.eks.aws

# Karpenter Generated NodeConfig
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
metadata:
  creationTimestamp: null
spec:
  cluster:
    apiServerEndpoint: https://<redacted>
    certificateAuthority: <redacted>
    cidr: 172.20.0.0/16
    name: eks-euc1-dev-06
  containerd: {}
  instance:
    localStorage: {}
  kubelet:
    config:
      clusterDNS:
      - 172.20.0.10
      maxPods: 58
      registerWithTaints:
      - effect: NoExecute
        key: karpenter.sh/unregistered
        value: "true"
      - effect: NoExecute
        key: node.cilium.io/agent-not-ready
        value: "true"
    flags:
    - --node-labels="karpenter.k8s.aws/ec2nodeclass=al2023-default,karpenter.sh/capacity-type=spot,karpenter.sh/nodepool=default-arm64"

--//--
```

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 1.1.0
- Kubernetes Version (`kubectl version`): 1.31
