### ISSUE TITLE
Tag templating

### ISSUE THREAD

**Issue by sylr** [aws/karpenter-provider-aws#7506]
### Description

**What problem are you trying to solve?**

I would like to be able to use go templates to generate dynamic AWS tags for the EC2 instances generated by karpenter, e.g:

```yaml
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: al2023-default
spec:
  # Required, resolves a default ami and userdata
  amiFamily: AL2023
  amiSelectorTerms:
  - alias: al2023@v20241121

  ...

  # Optional, propagates tags to underlying EC2 resources
  tags:
    Name: eks.amazonaws.com/{{ .ClusterName }}/{{ .EC2NodeClassName }}
```
 

**How important is this feature to you?**

Nice to have.
