### ISSUE TITLE
FAQs "Attribute-based requests are currently not possible."

### ISSUE THREAD

**Issue by Gladskih** [aws/karpenter-provider-aws#7513]
Could someone clarify that answer to ["Can I restrict EC2 instance types?"](https://karpenter.sh/docs/faq/#can-i-restrict-ec2-instance-types)?
> Attribute-based requests are currently not possible.
> You can select instances with special hardware, such as gpu

Does it mean that if my app needs to be run only on "c7i.2xlarge" I cannot achieve that using Karpenter?
But what's wrong with this:
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
spec:
  template:
    spec:
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["c7i.2xlarge"]
```
?
