### ISSUE TITLE
WhenEmpty nodepools suddenly no longer scale down with no pods running

### ISSUE THREAD

**Issue by theothermike** [aws/karpenter-provider-aws#7523]
### Description

**Observed Behavior**:

We've been using karpenter 0.37  for several months and its been working great. All of a sudden last week (as best as we can tell), only in our dev cluster, several nodepools we have configured with `consolidationPolicy: WhenEmpty` stopped scaling down (we have 60s and 300s for `consolidateAfter` depending on the pool).   

Looking at the karpenter logs (with enabled debug logging) I see logs for creating the nodeclaims and starting the node - but then the nodes are never mentioned again.    Other nodepools configured with `WhenUnderutilized` work as expected, and there are log lines for creating and deleting nodeclaims

doing a kubectl describe on the affected node shows it's transitioned to the `Empty` state after the last pod finished running, and there are only a handful of the kube-system daemonsets left running, confirmed none of them have any kind of weird annotations preventing them from being counted as empty (indeed have same daemonsets on nodepools that work fine).   There are no karpenter related events on the node, the last events are always the kubelet reporting healthy after startup.

```
  - lastTransitionTime: "2024-12-12T14:37:07Z"
    message: ""
    reason: Empty
    status: "True"
    type: Empty
```

I tried deleting the karpenter pods to see if maybe they got into a bad state and would reconcile on startup, but that doesnt happen, there are still no mentions of the nodes.  triggering a `kubectl rollout restart deployment` however did work, and the cleanup would happen, but all new pods  on those pools, but with this procedure  it does at least cleanup.

**Expected Behavior**:

scale down the empty node

**Reproduction Steps** (Please include YAML):

This is the tricky part.  We are not aware of any changes we've made that could cause this.  We did install kserve/knative on that cluster in the past several weeks, so it's possible there is some weird interaction karpenter. 

only other interesting log entry from karpenter is this 

```
{"level":"INFO","time":"2024-12-12T18:54:03.305Z","logger":"controller","message":"pod redacted/redacted-deployment-6b494f9c8f-4xjgn has a preferred Anti-Affinity which can prevent consolidation","commit":"490ef94","controller":"provisioner"}                                      
```

Knative apparently adds this anti affinity.   I wonder if this triggers the bug, because even running and killing a pod without the anti-affinity (like an ubuntu test pod) on a fresh node in the nodepool  triggers the bug (doesnt scale down)

```
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              serving.knative.dev/revision: redacted-00006
          topologyKey: kubernetes.io/hostname
        weight: 100
```

and this

```
{"level":"DEBUG","time":"2024-12-12T19:11:15.495Z","logger":"controller","message":"found and delete leaked lease","commit":"490ef94","controller":"lease.garbagecollection","controllerGroup":"coordination.k8s.io","controllerKind":"Lease","Lease":{"name":redacted.compute.internal","namespace":"k
ube-node-lease"},"namespace":"kube-node-lease","name":"redacted.compute.internal","reconcileID":"16657082-3473-4bbc-8c08-30a3066faa2a"}
```

happens every few minutes about a dozen times.  that could totally be unrelated

I'm hoping by describing the weird way to trigger the cleanup by forcing rollout restart might point the way to the root cause.

I'd like to try the latest version, but as you know going from 0.37 to latest isnt trivial

**Versions**:
- Chart Version: 0.37
- Kubernetes Version (`kubectl version`): 1.28 (eks)

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment]
Hi @theothermike,
Do you mind sharing a more complete set of logs and nodepools and nodeclaims in the cluster?

**Comment by theothermike** [comment]
@jigisha620 

Unfortunately I cant provide the raw logs due to security concerns, but doing some more analysis on the `"found and delete leaked lease"`,  even though there are many log entries, they always talk about the same 2 nodes, which are not actually a part of the cluster.  

```
 $ kubectl logs -n kube-system karpenter-5dd4fb655c-ltxjt | grep "found and delete" | jq '.name' | sort | uniq
"ip-10-75-23-110.redacted.compute.internal"
"ip-10-75-53-92.redacted.compute.internal"
```

I do remember  on rare occasion seeing in the Grafana dashboard for Karpenter, the `NodeClaimNotFoundError'.  I can only speculate these particular 2 nodes were at some point, since I can find no reference in our cluster Loki logs going back as far as we retain (30days) 

here's yaml of a nodepool that works (`WhenUnderutilized`)

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
  name: cloud-platform
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: cloud-platform
      requirements:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - az-1a
        - az-1b
        - az-1d
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - m
        - c
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "5"
      taints:
      - effect: NoSchedule
        key: nodepool
        value: cloud-platform
```

and here's yaml from one that doesnt

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
  name: team1
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 60s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: team1
      requirements:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - az-1a
        - az-1b
        - az-1d
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - m
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "5"
      taints:
      - effect: NoSchedule
        key: nodepool
        value: team1
```

pretty standard stuff.   I'll collect logs pertaining to the nodeclaims and nodepools over next day or so as our devs run on the problematic nodepools
