### ISSUE TITLE
Getting label domain \"karpenter.k8s.aws\" is restricted

### ISSUE THREAD

**Issue by c-buisson** [aws/karpenter-provider-aws#7534]
### Description

**Observed Behavior**:
During a node claim I am seeing this error:
```
{
  "level": "INFO",
  "time": "2024-12-16T17:32:56.474Z",
  "logger": "controller",
  "message": "found provisionable pod(s)",
  "commit": "3298d91",
  "controller": "provisioner",
  "namespace": "",
  "name": "",
  "reconcileID": "7d3230ca-a490-444a-84ac-d9fb691f7103",
  "Pods": "default/simple-http-75647f464b-nqzz6",
  "duration": "82.797562ms"
}
{
  "level": "INFO",
  "time": "2024-12-16T17:32:56.474Z",
  "logger": "controller",
  "message": "computed new nodeclaim(s) to fit pod(s)",
  "commit": "3298d91",
  "controller": "provisioner",
  "namespace": "",
  "name": "",
  "reconcileID": "7d3230ca-a490-444a-84ac-d9fb691f7103",
  "nodeclaims": 1,
  "pods": 1
}
{
  "level": "ERROR",
  "time": "2024-12-16T17:32:56.486Z",
  "logger": "controller",
  "message": "Reconciler error",
  "commit": "3298d91",
  "controller": "provisioner",
  "namespace": "",
  "name": "",
  "reconcileID": "7d3230ca-a490-444a-84ac-d9fb691f7103",
  "error": "creating node claim, NodeClaim.karpenter.sh \"shared-nodes-8j5kl\" is invalid: spec.requirements[4].key: Invalid value: \"string\": label domain \"karpenter.k8s.aws\" is restricted"
}
```
**Expected Behavior**:
Install the Helm chart `v1.1.0` or `v1.1.1`, add this nodepool:
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: shared-nodes
  namespace: kube-system
spec:
  template:
    spec:
      nodeClassRef:
        kind: EC2NodeClass
        group: karpenter.k8s.aws
        name: shared-nodes
      expireAfter: 1h
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.large", "t3.xlarge"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t3"]
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values: ["large", "xlarge"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: In
          values: ["3"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
          # values: ["spot", "on-demand"]
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 10m
  limits:
    cpu: 48
    memory: 192Gi
```
and this EC2nodeclass:
```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: shared-nodes
  labels:
    shared: "t3_xlarge"
spec:
   amiFamily: AL2
  role: "KarpenterNodeRole_eks-dev"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-dev"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-dev"
  amiSelectorTerms:
    - id: "ami-03e3d5f1e9559ede2"
```
**Reproduction Steps** (Please include YAML):
Launch a pod that requests more CPU/Memory currently available.

**Versions**:
- Chart Version: `1.1.1`
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.2-eks-7f9249a
```
