### ISSUE TITLE
Pods are not scheduled with the message "incompatible requirements, label \"workload\" does not have known values".

### ISSUE THREAD

**Issue by azafar212** [aws/karpenter-provider-aws#7535]
### Description

**Observed Behavior**:
5 Pods are in pending status, and are not scheduled finally with below the message "incompatible requirements, label \"workload\" does not have known values".

**Events**:
`{"level":"ERROR","time":"2024-12-16T21:48:24.279Z","logger":"controller","message":"could not schedule pod","commit":"6174c75","controller":"provisioner","namespace":"","name":"","reconcileID":"8f62e2d4-ad75-47dc-9b95-a3cc56c6bfaf","Pod":{"name":"inflate-5c97b884d6-rp2fk","namespace":"default"},"error":"incompatible with nodepool \"default\", daemonset overhead={\"cpu\":\"180m\",\"memory\":\"120Mi\",\"pods\":\"5\"}, incompatible requirements, label \"workload\" does not have known values"}`

**Expected Behavior**:
Karpenter provisions a proper node to schedule the pods.

**Versions**:
Chart Version: v1.0.6
Kubernetes Version (kubectl version): 1.31

**ec2nodeclass/nodepool**
```
    apiVersion: karpenter.k8s.aws/v1beta1
    kind: EC2NodeClass
    metadata:
      name: default
    spec:
      amiFamily: AL2
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            volumeSize: ${var.ebs_volume_size}
      role: ${module.karpenter.node_iam_role_name}
      subnetSelectorTerms:
        - tags:
            karpenter.sh/discovery: ${module.eks.cluster_name}
      securityGroupSelectorTerms:
        - tags:
            karpenter.sh/discovery: ${module.eks.cluster_name}
      tags:
        karpenter.sh/discovery: ${module.eks.cluster_name}
        
    apiVersion: karpenter.sh/v1beta1
    kind: NodePool
    metadata:
      name: default
    spec:
      template:
        spec:
          nodeClassRef:
            name: default
          requirements:
          - key: karpenter.sh/capacity-type
            operator: In
            values:
            - spot
            - on-demand
          - key: karpenter.k8s.aws/instance-cpu
            operator: In
            values:
            - "4"
            - "8"
          - key: karpenter.k8s.aws/instance-generation
            operator: Gt
            values:
            - "4"
          - key: karpenter.k8s.aws/instance-category
            operator: In
            values:
            - m
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
          labels:
            workload: inflate
          taints:
            - key: workload
              value: inflate
              effect: "NoSchedule"
      limits:
        cpu: 1000
      disruption:
        consolidationPolicy: WhenEmpty
        consolidateAfter: 30s
``` 
**inflate/deployment**

```
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: inflate
    spec:
      replicas: 5
      selector:
        matchLabels:
          app: inflate
      template:
        metadata:
          labels:
            app: inflate
        spec:
          terminationGracePeriodSeconds: 0
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                    - inflate
          containers:
            - name: inflate
              image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          tolerations:
            - key: "workload"
              operator: "Equal"
              value: "inflate"
              effect: NoSchedule
```
