### ISSUE TITLE
EC2 is created, but it is not recognized as an EKS node

### ISSUE THREAD

**Issue by SUJI-J** [aws/karpenter-provider-aws#7541]
1. kubernetes (v.1.31)
2. karpenter (v1.0.5)

* nodepool.yml
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ts-nodepool
  namespace: karpenter
spec:
  template:
    metadata:
      labels:
        nodegroup: karpenter # 노드에 추가할 레이블
        eks:nodegroup-name: ts-karpenter-ng
    spec:
      requirements:
        - key: "nodegroup"
          operator: In
          values: ["karpenter"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t2"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["small", "medium"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: ts-ec2nodeclass
      expireAfter: 720h
  limits:
    cpu: 4
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
```

* nodeclass.yml
```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: ts-ec2nodeclass
  namespace: karpenter
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-ts-eks"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ts-eks"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ts-eks"
  amiSelectorTerms:
    - id: "ami-0ea66fbd857bd11"
```

* deployment.yml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      nodeSelector:
        nodegroup: karpenter
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
```

I'm gradually increasing the number of deployment replicas to see if I create new nodes
When I set the number of replica to 5, a new EC2 was created, but EKS does not recognize it as a node.

kubectl logs -f -n karpenter -l app.kubernetes.io/name=karpenter -c controller | jq '.'
```bash
{
  "level": "ERROR",
  "time": "2024-12-18T04:46:34.243Z",
  "logger": "controller",
  "message": "Reconciler error",
  "commit": "652e6aa",
  "controller": "migration.resource.nodeclaim",
  "controllerGroup": "karpenter.sh",
  "controllerKind": "NodeClaim",
  "NodeClaim": {
    "name": "ts-nodepool-f8pgv"
  },
  "namespace": "",
  "name": "ts-nodepool-f8pgv",
  "reconcileID": "8227ae78-0907-49e7-bda9-468714b3ea8d",
  "error": "adding karpenter.sh/stored-version-migrated annotation to karpenter.sh/v1, Kind=NodeClaim, Operation cannot be fulfilled on nodeclaims.karpenter.sh \"ts-nodepool-f8pgv\": the object has been modified; please apply your changes to the latest version and try again"
}
{
  "level": "INFO",
  "time": "2024-12-18T04:46:37.259Z",
  "logger": "controller",
  "message": "launched nodeclaim",
  "commit": "652e6aa",
  "controller": "nodeclaim.lifecycle",
  "controllerGroup": "karpenter.sh",
  "controllerKind": "NodeClaim",
  "NodeClaim": {
    "name": "ts-nodepool-f8pgv"
  },
  "namespace": "",
  "name": "ts-nodepool-f8pgv",
  "reconcileID": "05574723-9673-46be-a00d-9e233d27e2dd",
  "provider-id": "aws:///ap-northeast-2a/i-0de98d835ca251549",
  "instance-type": "t2.small",
  "zone": "ap-northeast-2a",
  "capacity-type": "on-demand",
  "allocatable": {
    "cpu": "940m",
    "ephemeral-storage": "17Gi",
    "memory": "1418Mi",
    "pods": "11"
  }
}
```

The new instance is in NotReady state.

I'm a student, and I'm not good at English, so I'm using a translator. Please understand if it's awkwar
Please let me know if you need anything else
