### ISSUE TITLE
PODs within Karpenter nodes are not able to assume roles.

### ISSUE THREAD

**Issue by ricardorqr** [aws/karpenter-provider-aws#7548]
### Description

Hi everyone,

I'm using Karpenter 1.1.1. My pod within the Karpenter node is not able to assume roles. I have an EKS cluster with 2 nodes. One node is managed by node groups and Karpenter manages the second node. PODs within the node in the node group can assume roles. PODs within the node managed by Karpenter are not able to assume roles.

Here is an example. This is the POD within the node managed by the node groups.
```sh
bash-4.2# aws sts get-caller-identity
{
    "UserId": "SDFGBSFGBSFGBSFGBSFG:i-123456789",
    "Account": "123456789",
    "Arn": "arn:aws:sts::123456789:assumed-role/us-east-2-node-group-role/i-123456789"
}
bash-4.2#
```

This is the POD within the node managed by Karpenter.
```sh
bash-4.2# aws sts get-caller-identity

Unable to locate credentials. You can configure credentials by running "aws configure".
bash-4.2# 
```

I checked the roles attached to both nodes and they have `AmazonS3FullAccess` policy attached. 

Here is my EC2NodeClass
```yaml
    apiVersion: karpenter.k8s.aws/v1
    kind: EC2NodeClass
    metadata:
      name: default
    spec:
      amiSelectorTerms:
        - alias: al2@v20241205
      role: "${module.karpenter.node_iam_role_name}"
      subnetSelectorTerms:
        - tags:
            karpenter.sh/discovery: "${local.eks-name}"
      securityGroupSelectorTerms:
        - tags:
            karpenter.sh/discovery: "${local.eks-name}"
```

And here is my NodePool,
```yaml
    apiVersion: karpenter.sh/v1
    kind: NodePool
    metadata:
      name: default
    spec:
      template:
        spec:
          requirements:
            - key: kubernetes.io/arch
              operator: In
              values: ["amd64"]
            - key: kubernetes.io/os
              operator: In
              values: ["linux"]
            - key: karpenter.sh/capacity-type
              operator: In
              values: ["${local.karpenter-capacity-type}"]
            - key: karpenter.k8s.aws/instance-category
              operator: In
              values: ["c", "m", "r"]
            - key: karpenter.k8s.aws/instance-generation
              operator: Gt
              values: ["2"]
          nodeClassRef:
            group: karpenter.k8s.aws
            kind: EC2NodeClass
            name: default
          expireAfter: 720h # 30 * 24h = 720h
      limits:
        cpu: 1000
      disruption:
        consolidationPolicy: WhenEmptyOrUnderutilized
        consolidateAfter: 1m
```

Any idea what this problem can be?
