### ISSUE TITLE
Issue with Karpenter Consolidation Schedule and API Version Mismatch on EKS

### ISSUE THREAD

**Issue by citiatish** [aws/karpenter-provider-aws#7557]
### Description

**Observed Behavior**:

Nodes are being deleted or consolidated outside the defined disruption budget schedule. Even though the NodePool is configured with a budget policy (schedule: "@daily", duration: "1h", nodes: "20%"), Karpenter is deleting or consolidating nodes at arbitrary times instead of adhering to the specified schedule. Additionally, the kubectl describe nodepool output shows an API version mismatch (expected: v1beta1, observed: v1).

**Expected Behavior**:

Nodes should only be deleted or consolidated during the defined budget window (12:00 AM to 1:00 AM daily).

The API version (v1beta1) used for creating the NodePool and EC2NodeClass should be consistent and reflected in the resource metadata.

In the nodepool describe event it showing **No allowed disruptions due to blocking budget** but karpenter still consolidate node outside of define budget policy. 

**Reproduction Steps** 

Installed Karpenter version 0.37.6 using the Helm chart karpenter-0.37.6.
Created the following NodePool and EC2NodeClass resources using the v1beta1 API version.

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: nodepool-non-system
spec:
  template:
    metadata:
      labels:
        diskattached: non-system
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: non-system-ec2nodeclass
      requirements:
        - key: "kubernetes.io/arch"
          operator: "In"
          values: ["amd64"]
        - key: "kubernetes.io/os"
          operator: "In"
          values: ["linux"]
        - key: "karpenter.sh/capacity-type"
          operator: "In"
          values: ["on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: "In"
          values: ["r5a.large"]
        - key: "topology.kubernetes.io/zone"
          operator: "In"
          values: ["us-east-1a"]
  disruption:
    budgets:
      - schedule: "@daily"
        duration: "1h"
        nodes: "20%"
    consolidationPolicy: WhenUnderutilized
    expireAfter: "4320h" # 6 months


apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: non-system-ec2nodeclass
spec:
  amiFamily: "AL2"
  role: "<cluster-name>-node-role"
  subnetSelectorTerms:
    - tags:
        "karpenter.sh/discovery": "<cluster-name>-nonsystem"
  securityGroupSelectorTerms:
    - tags:
        "karpenter.sh/discovery": "<cluster-name>"
  blockDeviceMappings: []
```
  
**kubectl describe  nodepool nodepool-non-system**

```
Name:         nodepool-non-system
Namespace:
Labels:       <none>
Annotations:  compatibility.karpenter.sh/v1beta1-nodeclass-reference:
                {"kind":"EC2NodeClass","name":"non-system-ec2nodeclass","apiVersion":"karpenter.k8s.aws/v1beta1"}
              karpenter.sh/nodepool-hash: 15569228928812372362
              karpenter.sh/nodepool-hash-version: v2
API Version:  karpenter.sh/v1
Kind:         NodePool
Metadata:
  Creation Timestamp:  2024-12-31T06:42:35Z
  Generation:          3
  Resource Version:    93355
  UID:                 e05b4aba-c9a1-4e6f-b812-54fca031786b
Spec:
  Disruption:
    Budgets:
      Duration:            1h0m0s
      Nodes:               20%
      Schedule:            @daily
    Consolidate After:     0s
    Consolidation Policy:  WhenEmptyOrUnderutilized
  Template:
    Metadata:
      Labels:
        Diskattached:  non-system
    Spec:
      Expire After:  4320h
      Node Class Ref:
        Group:  karpenter.k8s.aws
        Kind:   EC2NodeClass
        Name:   non-system-ec2nodeclass
      Requirements:
        Key:       kubernetes.io/arch
        Operator:  In
        Values:
          amd64
        Key:       kubernetes.io/os
        Operator:  In
        Values:
          linux
        Key:       karpenter.sh/capacity-type
        Operator:  In
        Values:
          on-demand
        Key:       node.kubernetes.io/instance-type
        Operator:  In
        Values:
          r5a.large
        Key:       topology.kubernetes.io/zone
        Operator:  In
        Values:
          us-east-1a
        Key:       karpenter.k8s.aws/instance-generation
        Operator:  Gt
        Values:
          2
Status:
  Resources:
    Cpu:                  6
    Ephemeral - Storage:  25128900Ki
    Memory:               48343688Ki
    Pods:                 87
Events:
  Type    Reason             Age                  From       Message
  ----    ------             ----                 ----       -------
  Normal  DisruptionBlocked  26m (x43 over 129m)  karpenter  No allowed disruptions due to blocking budget
```

**Versions**:
- Helm Chart Version: karpenter-0.37.6
- Kubernetes Version (`kubectl version`): 1.30
