### ISSUE TITLE
Node not joining cluster :(

### ISSUE THREAD

**Issue by tony-engineering** [aws/karpenter-provider-aws#7558]
### Description

started to happen after re-creating a cluster and re-installing. upgraded karpenter to latest version but didn't help.
Would be very grateful if someone can help here 🙏

**Observed Behavior**:

EC2 instance created, but not joining cluster. No error message is shown in Karpenter logs. 

**Expected Behavior**:

After EC2 node is created, it should join cluster so that my pod is scheduled OR see some relevant error message that helps me 

**Reproduction Steps** (Please include YAML):

Create nodepool
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
  annotations:
    kubernetes.io/description: "General purpose NodePool for generic workloads"
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            {{- range .Values.defaultNodePool.capacityType }}
            - "{{ . }}"
            {{- end }}
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values: [ "4", "8" ]
      nodeClassRef:
        group: karpenter.k8s.aws  # Updated since only a single version will be served
        kind: EC2NodeClass
        name: default

      kubelet:
        systemReserved:
          cpu: 100m
          memory: 100Mi
          ephemeral-storage: 1Gi
        kubeReserved:
          cpu: 200m
          memory: 100Mi
          ephemeral-storage: 3Gi
        evictionHard:
          memory.available: 5%
          nodefs.available: 10%
          nodefs.inodesFree: 10%
        evictionSoft:
          memory.available: 500Mi
          nodefs.available: 15%
          nodefs.inodesFree: 15%
        evictionSoftGracePeriod:
          memory.available: 1m
          nodefs.available: 1m30s
          nodefs.inodesFree: 2m
  limits:
    cpu: 100
    memory: 400Gi # make sure RAM to CPU ratio is 4:1 (otherwise limit is reached pretty fast)
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1h
    budgets:
      # On Weekdays during business hours, don't do any de-provisioning.
      - schedule: "0 6 * * mon-fri"
        duration: 12h
        nodes: "0"
```

create nodeclass
```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: 'karpenter-node-{{ .Values.clusterName }}'
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery/{{ .Values.clusterName }}: 'true'
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery/{{ .Values.clusterName }}: 'true'
  amiSelectorTerms:
    - id: ami-01816d07b1128cd2d
```

observe nodeclaim created, events are showing
```
Status condition transitioned, Type: Launched, Status: Unknown -> True, Reason: Launched (count 1)
Cannot disrupt NodeClaim: nodeclaim does not have an associated node (count 5)
```

schedule pod, events should show
```
Pod should schedule on: nodeclaim/default-tfv4l
```

observe instance created in EC2, with following tags
```
karpenter.sh/nodepool
default

eks:eks-cluster-name
beta4-cluster

aws:ec2:fleet-id
fleet-45b527b5-9484-468d-0630-8920c1f358bb

aws:ec2launchtemplate:version
1

karpenter.k8s.aws/ec2nodeclass
default

aws:ec2launchtemplate:id
lt-0679a69f9834d5696

kubernetes.io/cluster/beta4-cluster
owned
```

observe no errors shown in karpenter logs
```
{"level":"INFO","time":"2024-12-31T16:22:33.560Z","logger":"controller","message":"pod(s) have a preferred Anti-Affinity which can prevent consolidation","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"f8123087-a0e6-42b0-ba85-f7a2b471c858","pods":"monitoring/kube-prometheus-kube-state-metrics-7cc64f9c97-rzmc8, sealed-secrets/sealed-secrets-d8794b48c-wg4r8"}
{"level":"INFO","time":"2024-12-31T16:23:33.640Z","logger":"controller","message":"found provisionable pod(s)","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"3ab63d8f-1186-4aba-bcde-af72d21212a5","Pods":"default/api-deployment-685fd45dcf-bjgb5, default/api-deployment-685fd45dcf-wjxv6, default/pdf-generator-deployment-585df547d7-zd928, default/web-deployment-7dcfccdbb-v7pkb, sealed-secrets/sealed-secrets-d8794b48c-wg4r8 and 2 other(s)","duration":"76.162213ms"}
{"level":"INFO","time":"2024-12-31T16:23:33.640Z","logger":"controller","message":"computed new nodeclaim(s) to fit pod(s)","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"3ab63d8f-1186-4aba-bcde-af72d21212a5","nodeclaims":1,"pods":7}
{"level":"INFO","time":"2024-12-31T16:23:33.658Z","logger":"controller","message":"created nodeclaim","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"3ab63d8f-1186-4aba-bcde-af72d21212a5","NodePool":{"name":"default"},"NodeClaim":{"name":"default-tfv4l"},"requests":{"cpu":"3380m","ephemeral-storage":"100Mi","memory":"823694976","pods":"10"},"instance-types":"c4.2xlarge, c4.xlarge, c5a.xlarge, c5ad.2xlarge, c5d.2xlarge and 50 other(s)"}
{"level":"INFO","time":"2024-12-31T16:23:35.982Z","logger":"controller","message":"launched nodeclaim","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-tfv4l"},"namespace":"","name":"default-tfv4l","reconcileID":"95e6172d-4d6d-40d7-b58a-211d9ae0f472","provider-id":"aws:///us-east-1b/i-02a591c321d7945ea","instance-type":"c4.xlarge","zone":"us-east-1b","capacity-type":"spot","allocatable":{"cpu":"3920m","ephemeral-storage":"17Gi","memory":"6111Mi","pods":"58"}}
```

**Versions**:
- Chart Version: 1.1.0
- Kubernetes Version (`kubectl version`):
Client Version: v1.28.15
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.3-eks-56e63d8
WARNING: version difference between client (1.28) and server (1.31) exceeds the supported minor version skew of +/-1

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
