### ISSUE TITLE
How is the load distributed in the following three instances? Which type of instance would be prioritized for use?

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter-provider-aws#7573]
### Description

How is the load distributed in the following three instances? Which type of instance would be prioritized for use?

Premise: The pod's requested resources can be fulfilled by all three instances.

```
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c7i-flex.xlarge
        - c7i.large
        - c7gd.2xlarge
```
