### ISSUE TITLE
AMI drift triggers node recreation outside Disruption schedule

### ISSUE THREAD

**Issue by duncanwraight** [aws/karpenter-provider-aws#7592]
### Description

We have a non-HA legacy application which must only go offline during an agreed maintenance window.

We have created a separate NodePool to our other applications, with taints and labels to make its single node used only by this application. I have configured a Disruption schedule on this NodePool in an attempt to ensure its node is not consolidated or recreated outside this window.

We have also configured the underlying `EC2NodeClass` to look for tagged AMIs. When we produce a new AMI, it is tagged and Karpenter picks it up to apply to our clusters' nodes.

### Observed Behavior
The single node belonging to this legacy application does not appear to be consolidated or recreated in any other situation, apart from during the specified maintenance window.  However, when a new AMI is found, the node is replaced regardless of time.

### Expected Behavior
The NodePool should adhere to the Disruption schedule, regardless of why a Disruption may have been encountered - including drift due to AMI changes.

**Reproduction Steps** (Please include YAML):

NodePool disruption budget:

```yaml
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 10m
    budgets:
      # NB: Karpenter budgets use a "most restrictive" permission so we have to set
      # a schedule to disable disruption, and then a "default" maximum of 1 node
      # to disrupt outside of these schedules
      - schedule: "0 0 * * 1"   # Monday 00:00
        duration: 95h           # Until Thursday 23:00
        nodes: "0"
      - schedule: "0 1 * * 5"   # Friday 01:00
        duration: 71h           # Until Monday 00:00
        nodes: "0"
      ### ^ These durations should add up to 166 hours, leaving 2 hours for the maintenance window
      - nodes: "1"              # Outside of these schedules, allow a maximum of 1 node to be disrupted
```

AMI selection configuration:

```yaml
  #!! Using a name with a wildcard allows Karpenter to pick the latest version
  amiSelectorTerms:
    #!! Specified in ancillary::packer/eks_ami.pkr.hcl under "ami_name" parameter
    - name: "my-company-name-al2-x86_64-eks-${clusterVersion}-*"
      owner: "006411612559"
      # This tag gets added after successful deployment of pipeline: custom-ami-build-test
      tags:
        ami-status: ready
```

### Versions
- Chart Version: `1.0.1`
- Kubernetes Version (`kubectl version`):  `1.31`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
