### ISSUE TITLE
Some metrics are gone sometimes even promethues still collect metrics

### ISSUE THREAD

**Issue by davidt-gh** [aws/karpenter-provider-aws#7615]
### Description

**Observed Behavior**:
I'm collecting metrics from 2 clusters, dev & prod.
In my dev cluster I saw sometimes a gap on metrics, and in prod, it worked well, but after few days I go to dashboard and no metrics at all.
To better understand, I used promethues container and `curl` for metrics, to compare between dashboard metrics (see what query used in dashboard view) and what metrics are actually I'm getting using `metrics` directly.
This is the metrics I got when prod was no show metrics, my example from dashboard was `karpenter_nodes_created_total` which not exists in here.
[output.txt](https://github.com/user-attachments/files/18478124/output.txt)

I've restart the deployment and look on dashboard, all metrics are back to work, here is example how dashboard is look after restart:
![Image](https://github.com/user-attachments/assets/5f9eaacc-66f1-45be-b5df-6b32b3fcf61f)

I'm not sure what is going on.
This is my dev cluster:

![Image](https://github.com/user-attachments/assets/b4e52413-2bda-4ac0-9366-7340ef5db916)
You can see gap, but I didn't do any change during this time range.

**Expected Behavior**:
Get stable metrics 24/7

**Reproduction Steps** (Please include YAML):
here is my `values.yaml`:
```YAML
karpenter:
  roleName: "ROLE-ARN"
  priorityClassName: system-node-critical
  settings:
    clusterName: "clustername-us-east-1-eks"
    interruptionQueue: "clustername-us-east-1-eks"
  serviceAccount:
    annotations:
      "eks.amazonaws.com/role-arn": "KARPENTER-ROLE"
  controller:
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 1Gi
```

**Versions**:
- Chart Version: `1.1.1`
- Kubernetes Version (`kubectl version`):
dev cluster:
```
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.30.8-eks-2d5f260
WARNING: version difference between client (1.32) and server (1.30) exceeds the supported minor version skew of +/-1
```
prod cluster:
```
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.30.8-eks-2d5f260
WARNING: version difference between client (1.32) and server (1.30) exceeds the supported minor version skew of +/-1
```

**Comment by rschalo** [comment]
I see there are resource requests and limits set for the deployment - did Karpenter crash from OOM? Do you get this same behavior if you don't set those limits?

**Comment by davidt-gh** [comment]
> I see there are resource requests and limits set for the deployment - did Karpenter crash from OOM? Do you get this same behavior if you don't set those limits?


No it not crashed. and it's not getting to the limit, it just to be on the safe side.

**Comment by davidt-gh** [comment]
Anyone?

**Comment by davidt-gh** [comment]
@rschalo Can you help in here?

**Comment by davidt-gh** [comment]
It seem after restart of the pods, the metrics are working. A workaround I made for now is adding a new cronjob to restart Karpenter every night.
If someone want to use it:
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-karpenter
  namespace: kube-system
spec:
  schedule: "0 3 * * *" # Every day at 3 AM UTC
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: restart-karpenter-sa
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - kubectl rollout restart deployment karpenter -n kube-system
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restart-karpenter-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-karpenter-role
  namespace: kube-system
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-karpenter-binding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: restart-karpenter-sa
    namespace: kube-system
roleRef:
  kind: Role
  name: restart-karpenter-role
  apiGroup: rbac.authorization.k8s.io
```
