### ISSUE TITLE
Error pulling chart: error getting credentials

### ISSUE THREAD

**Issue by BeyondEvil** [aws/karpenter-provider-aws#7621]
### Description

**Observed Behavior**:

```
❯ docker logout public.ecr.aws
Removing login credentials for public.ecr.aws

❯ helm registry logout public.ecr.aws
Error: not logged in

❯ helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "external-dns" chart repository
...Successfully got an update from the "eks" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "istio" chart repository
...Successfully got an update from the "redis" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading karpenter from repo oci://public.ecr.aws/karpenter
Save error occurred:  could not download oci://public.ecr.aws/karpenter/karpenter: error getting credentials - err: signal: killed, out: ``
Error: could not download oci://public.ecr.aws/karpenter/karpenter: error getting credentials - err: signal: killed, out: ``
````

**Expected Behavior**:

Chart should download successfully.

**Reproduction Steps** (Please include YAML):

```yaml
apiVersion: v2
name: karpenter
description: AWS Karpenter
type: application
version: 0.1.0
dependencies:
  - name: karpenter
    version: 1.1.0
    repository: oci://public.ecr.aws/karpenter
```

**Versions**:
- Chart Version: 1.1.0 (and 1.1.1)
- Kubernetes Version (`kubectl version`): v1.31.1

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
