### ISSUE TITLE
Add option to define blockLists with larger-than and smaller-than operators

### ISSUE THREAD

**Issue by gal-shraga** [aws/karpenter-provider-aws#7627]
### Description

**What problem are you trying to solve?**
To prevent karpenter from provisioning nodes that are too large, for example to prevent karpenter from creating nodes with less than 4 CPUs and more than 64 CPUs, I need to define it like this:
```
blockList / globalBlockList:
  cpu: ["1","2","3","66","68","70","72","74","76","78","80","82","84","86","88","90","92","94","96","98","100","102","104","106","108","110","112","114","116","118","120","122","124","126","128","130","132","134","136","138","140","142","144","146","148","150","152","154","156","158","160","162","164","166","168","170","172","174","176","178","180","182","184","186","188","190", "192", "224", "448"]
```
I would prefer that I would just have an option to define it as something similar to this: 
```
cpu:
  gt: 64  # Greater than 64
  lt: 4  # Less than 4
```
Or something similar to this.
Note that this might be relevant for other objects, such as `size`.
I assumed I needed to open the issue here and not at [kubernetes-sigs/karpenter](https://github.com/kubernetes-sigs/karpenter/issues/new/choose) since it is related to AWS EC2 instance types.
**How important is this feature to you?**
Would be very convenient and my code would look much better.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Since requirements are anded together, you should be able to achieve this today:

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
spec:
  template:
    spec:
      requirements:
      - key: "karpenter.k8s.aws/instance-cpu"
        operator: Gt
        values: ['3']
      - key: "karpenter.k8s.aws/instance-cpu"
        operator: Lt
        values: ['65']
```

Is there any reason this doesn't meet your use case?

> I assumed I needed to open the issue here and not at [kubernetes-sigs/karpenter](https://github.com/kubernetes-sigs/karpenter/issues/new/choose) since it is related to AWS EC2 instance types.

As a general rule, anything NodePool related is going to be against the upstream repo since that's where instance type selection logic is implemented. In the future that's where I'd open NodePool related feature requests and issues, but it's not too big of a deal.
