### ISSUE TITLE
validating kubernetes version, karpenter version is not compatible with K8s version 1.32

### ISSUE THREAD

**Issue by Boniker** [aws/karpenter-provider-aws#7630]
### Description

**Observed Behavior**:
Karpenter Helm chart version 1.1.1 is deployed.

In the controller logs:
`validating kubernetes version, karpenter version is not compatible with K8s version 1.32`

**Expected Behavior**:
The latest version of the Helm chart would support the latest Kubernetes version. Furthermore, there would be no error logs about version compatibility issues.

**Reproduction Steps** (Please include YAML):
```
controller:
  containerName: controller
  healthProbe:
    port: 8081
  image:
    digest: sha256:fe383abf1dbc79f164d1cbcfd8edaaf7ce97a43fbd6cb70176011ff99ce57523
    repository: public.ecr.aws/karpenter/controller
    tag: 1.1.1
  metrics:
    port: 8080
hostNetwork: true
imagePullPolicy: IfNotPresent
priorityClassName: system-cluster-critical
replicas: 2
revisionHistoryLimit: 2
schedulerName: default-scheduler
service:
  annotations: {}
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account_id>:role/<role_name>
  create: true
  name: ""
settings:
  batchIdleDuration: 1s
  batchMaxDuration: 10s
  clusterCABundle: ""
  clusterEndpoint: <cluster_endpoint>
  clusterName: <cluster_name>
  eksControlPlane: false
strategy:
  rollingUpdate:
    maxUnavailable: 1
```

**Versions**:
- Chart Version: 1.1.1
- Kubernetes Version (kubectl version): 1.32

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
