### ISSUE TITLE
Karpenter does not launch new nodes on pending pods when pods in cluster is over 40,000

### ISSUE THREAD

**Issue by ofekifergan** [aws/karpenter-provider-aws#7658]
### Description

**Observed Behavior**:
New pods stuck in Pending state when our cluster reach ~40,000 pods, no logs regarding the error

I can see that karpenter is computing pod scheduling and ites taking a lot of time.

{"level":"INFO","time":"2025-01-29T13:46:56.910Z","logger":"controller","message":"computing pod scheduling...","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"xxx","pods-scheduled":19769,"pods-remaining":13163,"duration":"33m11s","scheduling-id":"xxx"}

**Expected Behavior**:
New nodes should be launched on pending pods regardless the amount of pods.
Eks should support up to 150,000 pods

**Reproduction Steps** (Please include YAML):

**Versions**: 1.1
- Chart Version:
- Kubernetes Version (`kubectl version`): 1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ofekifergan** [comment]
Update: Karpenter is stuck on "pods-remaining":13163, this is really critical issue

**Comment by rschalo** [comment]
Also, can you share your nodepool and nodeclass configs?

**Comment by ofekifergan** [comment]
@jmdeal @rschalo 
Karpenter is running on m6a.2xlarge on these resources:
```
resources:
        limits:
          cpu: '1'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 8Gi
```
It crashed on OOM, becuase of the amount of pods so I had to increase the memory.

The nodegroup config:
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gp-ondemand
spec:
  disruption:
    budgets:
      - nodes: '1'
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    memory: 1500Gi
  template:
    metadata:
      labels:
        nodeGroup: gp-ondemand
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: karpenter-gp-ondemand-template
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - m6a.2xlarge
      taints:
        - effect: NoSchedule
          key: nodeGroup
          value: gp-ondemand
``` 
Nodeclass:
```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: karpenter-gp-ondemand-template
spec:
  amiFamily: AL2
  amiSelectorTerms:
    - id: xxx
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 100Gi
        volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
  role: eks-worker-node-role-prod-eu-west
  securityGroupSelectorTerms:
    - id: x
    - id: y
    - id: z
  subnetSelectorTerms:
    - id: x
    - id: y
    - id: z
  tags:
    ClusterName: <env>
    Environment: <env>
    Name: karpenter-eks-<env>-gp-ondemand-gp
    nodeGroup: gp-ondemand
```



Currently I dont have the logs because I restarted Karpenter but the recent logs was:
```
{"level":"INFO","time":"2025-01-29T13:46:56.910Z","logger":"controller","message":"computing pod scheduling...","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"xxx","pods-scheduled":19769,"pods-remaining":13163,"duration":"33m11s","scheduling-id":"xxx"}
```
and it got stuck on `pods-remaining:13163` and basiclly hanged forever.
Only after reducing the amount of pods it worked again.



This happend to me at production and it must be fixed as we rely on karpenter to be able to handle this kind of load.
