### ISSUE TITLE
Node added by karpenter not joining cluster

### ISSUE THREAD

**Issue by BorisDr** [aws/karpenter-provider-aws#7660]
### Description

**Observed Behavior**:
Node deployed by karpenter fails to join cluster due to cloud-init failure. 
In the logs I can observe the following string:
`Jan 30 05:37:13 ip-10-1-93-84 cloud-init: Jan 30 05:37:13 cloud-init[2217]: __init__.py[WARNING]: Unhandled unknown content-type (application/node.eks.aws) userdata: '# Karpenter Generated No...'`
Nodes deployed using managed nodegroups can join cluster.
**Reproduction Steps** (Please include YAML):
```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default-al2023
spec:
  amiFamily: AL2023
  role: KarpenterNodes-cluster
  amiSelectorTerms:
    - name: "amazon-eks-node-1.31-v20250123"
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: cluster
      kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: cluster
  associatePublicIPAddress: false
  detailedMonitoring: false
  tags:
    karpenter.sh/discovery: cluster
    karpenter.sh/discovery/cluster: cluster
    cluster: cluster
    managed-by: karpenter
    env: common
    os: AL2023
  blockDeviceMappings: 
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      encrypted: false
      iops: 3000
      throughput: 150
      volumeSize: 100Gi
      volumeType: gp3
```
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: node-pool-system
spec:
  weight: 70
  template:
    metadata:
      labels: 
        aa/instance-compute-type: "true"
        aa/node-group: system-svc
        managed-by: karpenter
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-al2023
      requirements:
      - key: "topology.kubernetes.io/zone"
        operator: In
        values: 
        - us-east-1a
        - us-east-1b
        - us-east-1c
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: 
        - on-demand
      - key: "kubernetes.io/arch"
        operator: In
        values: 
        - amd64
      - key: "kubernetes.io/os"
        operator: In
        values: 
        - linux
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values: 
        - t3.large
        - m6a.large
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
```

**Versions**:
- Chart Version: 0.37, 1.1.0m 1.2.0
- Kubernetes Version (`kubectl version`): v1.31.4-eks-2d5f260

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
