### ISSUE TITLE
Metadata Option Prevent Node Instantiation in Isolated Regions

### ISSUE THREAD

**Issue by mmitchell57** [aws/karpenter-provider-aws#7667]
### Description

**Observed Behavior**: In an isolated AWS region using Karpenter 0.37 or 1.0.1 we are unable to provision nodes due to a metadata option not supported in the region. Even when removing all metadata options from the ec2nodepool, karpenter still attempt to specify the metatdata options. A ticket was submitted to AWS but was told no change will be made to accommodate and was told we should reach out and submit a ticket to the project on github. The metadata options throwing an error is `.spec.metadataOptions.httpProtocolIPv6`.  Setting to enabled, disabled, or removing it completely still results in karpenter logs showing an error and new nodes not instantiating.  

**Expected Behavior**:  Karpenter would not attempt to issue the configuration since it is not specified in the ec2nodeclass. THus allowing the nodes to instantiate and join the cluster in a region that does not support the given metadata options. 

**Reproduction Steps** (Please include YAML):
Create a ec2nodeclass with metadata option in a region that does not support a metadata option. In this case the metadata option is the `httpProtocolIPv6` option.  Then inflate the cluster so pods cannot be schedule. Karpenter attemps to instantiate a node but never finishes. This is immediately evident due to the nodeclaim remaining in a "false" state.  Yaml location in the ec2nodeclass: 

```yaml
Name:         default-ec2nodeclass
Kind:         EC2NodeClass
...
Spec:
  Metadata Options:
    Http Endpoint:                <snipped>
    httpProtocolIPv6:             disabled
    Http Put Response Hop Limit:  <snipped>
    Http Tokens:                  <snipped>
...
```

**Versions**:
- Chart Version:  0.37 and 1.0.1
- Kubernetes Version (`kubectl version`): 1.29.x

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
