### ISSUE TITLE
request to convert CR from an invalid group/version: karpenter.sh/v1beta1

### ISSUE THREAD

**Issue by mcleantom** [aws/karpenter-provider-aws#7694]
### Description

**Observed Behavior**:

I'm trying to install karpenter to my k8s cluster, but maybe did something wrong and installed the wrong version to my cluster. When I try to install karpenter now, it says:
```
$ helm upgrade --install karpente
r . -f values.yaml -n karpenter --create-namespace
Error: UPGRADE FAILED: Unable to continue with update: could not get information about the resource NodePool "default" in namespace "": request to convert CR from an invalid group/version: karpenter.sh/v1beta1
```
And I cant delete it or do anything to do with node pools, for example:
```
AWS/argocd/apps/karpenter$ kubectl get nodepool -A
Error from server: request to convert CR from an invalid group/version: karpenter.sh/v1beta1
```
I cant try to delete the resource as it hangs, and if I try to change the finalizers, it throws the same error:
```
(base) PS C:\Users\tom.mclean\src\tmp\ARL-AWS\argocd\apps\karpenter> kubectl get nodepools.karpenter.sh -o yaml > nodepools.karpenter.sh.yaml
Error from server: request to convert CR from an invalid group/version: karpenter.sh/v1beta1
```

**Expected Behavior**:
Run `helm upgrade --install` without errors

**Reproduction Steps** (Please include YAML):
```
export KARPENTER_NAMESPACE=karpenter
helm upgrade --install karpenter-crd oci://public.ecr.aws/karpenter/karpenter-crd --version 1.2.1 --namespace karpenter --create-namespace
```
Then, my Chart.yaml:
```
apiVersion: v2
name: karpenter
description: Umbrella chart for karpenter
type: application
version: 0.1.0
appVersion: v1.31.0
dependencies:
  - name: karpenter
    version: 1.2.1
    repository: oci://public.ecr.aws/karpenter
```
values.yaml:
```
karpenter:
  logLevel: debug
  controller:
    containerName: controller
    image:
      repository: public.ecr.aws/karpenter/controller
      tag: 1.1.2
  serviceMonitor:
    enabled: true
  serviceAccount:
    create: true
    name: karpenter
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::442042521319:role/eks-sandbox-karpenter
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: karpenter.sh/nodepool
                operator: DoesNotExist
  priorityClassName: system-cluster-critical
  logConfig:
    logEncoding: json
  settings:
    clusterName: eks-sandbox
    # interruptionQueue:
```
and `templates/node.yaml`:
```
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.k8s.aws/instance-gpu-manufacturer
          operator: DoesNotExist
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values: ["metal"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1
        kind: EC2NodeClass
        name: default
  limits:
    cpu: 100
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 14 * 24h = 288h
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "init-eks-node-group-20250203103832920500000003"
  subnetSelectorTerms:
    - tags:
        kubernetes.io/role/elb: "1"
  securityGroupSelectorTerms:
    - tags:
        Name: "eks-sandbox-node"
```
Then try and install:
```
helm upgrade --install karpenter . -f values.yaml -n karpenter --create-namespace
```

**Versions**:
- Chart Version: 1.2.1
- Kubernetes Version (`kubectl version`):
```
mcleantom@ARL-145:~$ kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.32.0-eks-5ca49cb
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
