### ISSUE TITLE
Trying to install karpenter on an existing EKS cluster, I get: request to convert CR from an invalid group/version: karpenter.sh/v1beta1

### ISSUE THREAD

**Issue by mcleantom** [aws/karpenter-provider-aws#7696]
### Description

**Observed Behavior**:

I was following the docs for Migrating from Cluster Autoscaler, and got to Create default NodePool where I tried to run:
```
cat <<EOF | envsubst | kubectl apply -f -
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "KarpenterNodeRole-${CLUSTER_NAME}" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  amiSelectorTerms:
    - id: "${ARM_AMI_ID}"
    - id: "${AMD_AMI_ID}"
#   - id: "${GPU_AMI_ID}" # <- GPU Optimized AMD AMI 
#   - name: "amazon-eks-node-${K8S_VERSION}-*" # <- automatically upgrade when a new AL2 EKS Optimized AMI is released. This is unsafe for production workloads. Validate AMIs in lower environments before deploying them to production.
EOF
```
But it outputted:
```
Error from server: error when retrieving current configuration of:
Resource: "karpenter.sh/v1, Resource=nodepools", GroupVersionKind: "karpenter.sh/v1, Kind=NodePool"
Name: "default", Namespace: ""
from server for: "STDIN": request to convert CR from an invalid group/version: karpenter.sh/v1beta1
```
I've tried deleting the nodepool definition and re running but I cant delete it:
```
mcleantom@ARL-145:/mnt/c/Users/tom.mclean/src/tmp/ARL-AWS/argocd/apps/karpenter$ kubectl delete nodepool default
Error from server: request to convert CR from an invalid group/version: karpenter.sh/v1beta1
```
**Expected Behavior**:
Command runs without errors

**Reproduction Steps** (Please include YAML):
I first tried to install karpenter from this helm chart: https://github.com/vtatarin/lgtm/tree/main/argocd/apps/karpenter
but on a v1.32 cluster, which failed but it looked like it made the nodegroup definition from that chart. I then tried to install it from the [migration guide](https://karpenter.sh/v1.2/getting-started/migrating-from-cas/#create-default-nodepool) But I am getting errors to do with v1beta1.

**Versions**:
- Chart Version: 1.2.1
- Kubernetes Version (`kubectl version`):
```
$ kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.32.0-eks-5ca49cb
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
