### ISSUE TITLE
karpenter Failed to schedule pod when using topology.kubernetes.io/zone, it doesn't create node

### ISSUE THREAD

**Issue by ziyi-bear** [aws/karpenter-provider-aws#7713]
### Description

**Observed Behavior**:

Have a Deployment with to specific zone, but it cant schedule pod or create new node on that zone

incompatible with nodepool "coder", daemonset overhead={"cpu":"956m","memory":"409Mi","pods":"10"}, incompatible requirements, key topology.kubernetes.io/zone, topology.kubernetes.io/zone DoesNotExist not in topology.kubernetes.io/zone In [ap-northeast-1a ap-northeast-1c ap-northeast-1d]

**Expected Behavior**:

if doesn't have node on that zone, create a match node then schedue pod

**Reproduction Steps** (Please include YAML):

```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default-bottlerocket
spec:
  amiSelectorTerms:
  - alias: bottlerocket@latest
  associatePublicIPAddress: false
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      volumeSize: 4Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      volumeSize: 20Gi
      volumeType: gp3
  detailedMonitoring: false
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  role: Karpenter-maas-eks-20240622103453032500000006
  securityGroupSelectorTerms:
  - name: XXXX
  - name: XXXX
  - name: XXXX
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: XXXX
  tags:
    app: team-a-app
    team: team-a

---

apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: coder
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 1800s
    consolidationPolicy: WhenEmpty
  template:
    metadata:
      annotations:
        systex.com/owner: coder
      labels:
        coder.workspace: "true"
    spec:
      expireAfter: 4h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-bottlerocket
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - ap-northeast-1a
        - ap-northeast-1c
        - ap-northeast-1d
      taints:
      - effect: NoSchedule
        key: ha
        value: none
      - effect: NoSchedule
        key: workspace
        value: coder
```

describe deployment and pod 
```bash
Name:               coder-2100889-ip-1aa
Namespace:          coder
CreationTimestamp:  Sat, 08 Feb 2025 03:08:23 +0000
Labels:             app.kubernetes.io/instance=coder-workspace-2100889-ip-1aa
                    app.kubernetes.io/name=coder-workspace
                    app.kubernetes.io/part-of=coder
                    com.coder.resource=true
                    com.coder.user.id=b7728b23-3a93-48d8-a240-a649a43656e9
                    com.coder.user.username=2100889
                    com.coder.workspace.id=b59b5056-3e1d-4afe-afec-d21c426be62e
                    com.coder.workspace.name=ip-1aa
Annotations:        com.coder.user.email: ziyiwang@systex.com
                    deployment.kubernetes.io/revision: 1
Selector:           app.kubernetes.io/name=coder-workspace
Replicas:           1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:  app.kubernetes.io/name=coder-workspace
  Containers:
   dev:
    Image:      jlesage/firefox
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      #!/usr/bin/env sh
      set -eux
      exec ./${BINARY_NAME} agent
      
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:     2
      memory:  2Gi
    Environment:
      CODER_AGENT_TOKEN:  00b5e822-18f6-46c2-9574-1fd32593e0df
      USER_ID:            0
      GROUP_ID:           0
      KEEP_APP_RUNNING:   1
      ENABLE_CJK_FONT:    1
    Mounts:
      /docker/appdata/firefox from home (rw)
  Volumes:
   home:
    Type:          PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:     coder-2100889-ip-1aa-home
    ReadOnly:      false
  Node-Selectors:  coder.workspace=true
                   kubernetes.io/arch=amd64
  Tolerations:     ha=none:NoSchedule
                   workspace=coder:NoSchedule
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  <none>
NewReplicaSet:   coder-2100889-ip-1aa-66b7b47968 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  43m   deployment-controller  Scaled up replica set coder-2100889-ip-1aa-66b7b47968 from 0 to 1

Name:             coder-2100889-ip-1aa-66b7b47968-ggdvj
Namespace:        coder
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app.kubernetes.io/name=coder-workspace
                  pod-template-hash=66b7b47968
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/coder-2100889-ip-1aa-66b7b47968
Containers:
  dev:
    Image:      harbor.gopengyo.b300systex.com/hub-proxy/jlesage/firefox
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      #!/usr/bin/env sh
      set -eux
      exec ./${BINARY_NAME} agent
      
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:     2
      memory:  2Gi
    Environment:
      CODER_AGENT_TOKEN:  00b5e822-18f6-46c2-9574-1fd32593e0df
      USER_ID:            0
      GROUP_ID:           0
      KEEP_APP_RUNNING:   1
      ENABLE_CJK_FONT:    1
    Mounts:
      /docker/appdata/firefox from home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w78bw (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  home:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  coder-2100889-ip-1aa-home
    ReadOnly:   false
  kube-api-access-w78bw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              coder.workspace=true
                             kubernetes.io/arch=amd64
Tolerations:                 ha=none:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                             workspace=coder:NoSchedule
Events:
  Type     Reason             Age                    From                Message
  ----     ------             ----                   ----                -------
  Warning  FailedScheduling   20m (x6 over 45m)      karpenter           Failed to schedule pod, incompatible with nodepool "infra-storage", daemonset overhead={"cpu":"956m","memory":"409Mi","pods":"10"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "infra-security", daemonset overhead={"cpu":"1506m","memory":"690Mi","pods":"13"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "infra-networking", daemonset overhead={"cpu":"1506m","memory":"690Mi","pods":"13"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "infra-monitoring-logging", daemonset overhead={"cpu":"956m","memory":"409Mi","pods":"11"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "infra-database", daemonset overhead={"cpu":"1506m","memory":"690Mi","pods":"13"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "infra-cicd", daemonset overhead={"cpu":"1506m","memory":"690Mi","pods":"13"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "coder", daemonset overhead={"cpu":"956m","memory":"409Mi","pods":"10"}, incompatible requirements, key topology.kubernetes.io/zone, topology.kubernetes.io/zone DoesNotExist not in topology.kubernetes.io/zone In [ap-northeast-1a ap-northeast-1c ap-northeast-1d]
  Warning  FailedScheduling   13m (x2 over 13m)      default-scheduler   0/20 nodes are available: 15 node(s) had untolerated taint {role: infra}, 5 node(s) didn't match Pod's node affinity/selector. preemption: 0/20 nodes are available: 20 Preemption is not helpful for scheduling.
  Normal   NotTriggerScaleUp  5m29s (x241 over 45m)  cluster-autoscaler  pod didn't trigger scale-up: 2 node(s) didn't match Pod's node affinity/selector
  Warning  FailedScheduling   4m41s (x4 over 19m)    karpenter           Failed to schedule pod, incompatible with nodepool "infra-storage", daemonset overhead={"cpu":"956m","memory":"409Mi","pods":"10"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "infra-security", daemonset overhead={"cpu":"1506m","memory":"690Mi","pods":"13"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "infra-networking", daemonset overhead={"cpu":"1506m","memory":"690Mi","pods":"13"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "infra-monitoring-logging", daemonset overhead={"cpu":"956m","memory":"409Mi","pods":"11"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "infra-database", daemonset overhead={"cpu":"1506m","memory":"690Mi","pods":"13"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "infra-cicd", daemonset overhead={"cpu":"1506m","memory":"690Mi","pods":"13"}, did not tolerate role=infra:NoSchedule; incompatible with nodepool "coder", daemonset overhead={"cpu":"956m","memory":"409Mi","pods":"10"}, incompatible requirements, key topology.kubernetes.io/zone, topology.kubernetes.io/zone DoesNotExist not in topology.kubernetes.io/zone In [ap-northeast-1a ap-northeast-1c ap-northeast-1d]
  Warning  FailedScheduling   106s (x12 over 45m)    default-scheduler   0/19 nodes are available: 14 node(s) had untolerated taint {role: infra}, 5 node(s) didn't match Pod's node affinity/selector. preemption: 0/19 nodes are available: 19 Preemption is not helpful for scheduling.
  Warning  FailedScheduling   49s                    default-scheduler   0/20 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }, 14 node(s) had untolerated taint {role: infra}, 5 node(s) didn't match Pod's node affinity/selector. preemption: 0/20 nodes are available: 20 Preemption is not helpful for scheduling.
  Warning  FailedScheduling   38s                    default-scheduler   0/21 nodes are available: 14 node(s) had untolerated taint {role: infra}, 2 node(s) had untolerated taint {node.kubernetes.io/not-ready: }, 5 node(s) didn't match Pod's node affinity/selector. preemption: 0/21 nodes are available: 21 Preemption is not helpful for scheduling.
  Normal   NotTriggerScaleUp  27s (x4 over 57s)      cluster-autoscaler  pod didn't trigger scale-up: 2 max node group size reached
  Warning  FailedScheduling   27s                    default-scheduler   0/24 nodes are available: 14 node(s) had untolerated taint {role: infra}, 5 node(s) didn't match Pod's node affinity/selector, 5 node(s) had untolerated taint {node.kubernetes.io/not-ready: }. preemption: 0/24 nodes are available: 24 Preemption is not helpful for scheduling.
  Warning  FailedScheduling   15s                    default-scheduler   0/24 nodes are available: 14 node(s) had untolerated taint {role: infra}, 4 node(s) had untolerated taint {node.kubernetes.io/not-ready: }, 6 node(s) didn't match Pod's node affinity/selector. preemption: 0/24 nodes are available: 24 Preemption is not helpful for scheduling.
  Warning  FailedScheduling   4s                     default-scheduler   0/24 nodes are available: 14 node(s) had untolerated taint {role: infra}, 3 node(s) had untolerated taint {node.kubernetes.io/not-ready: }, 7 node(s) didn't match Pod's node affinity/selector. preemption: 0/24 nodes are available: 24 Preemption is not helpful for scheduling.

```

**Versions**:
- Chart Version: 1.2.1
- Kubernetes Version (`kubectl version`): 1.32

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
