### ISSUE TITLE
Not considering instance EBS volume limits when scheduling statefulset pods

### ISSUE THREAD

**Issue by wesley-yep-canva** [aws/karpenter-provider-aws#7725]
### Description

**Observed Behavior**:
Karpenter keeps trying to launch d3.8xlarge nodes for a statefulset pod. The pod keeps getting stuck in pending due to `node(s) exceed max volume count`. When explicitly blocking `d3` family instances in the nodeSelector it's able to schedule onto another node (in this case, a `m6a` instance). Presumably as `d3` instances have lower EBS volume count limits as per https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html#shared-limit

**Expected Behavior**:

Karpenter should take into account the max volume limits per instance type. 

I wonder if it's similar to this [issue](https://github.com/kubernetes-sigs/karpenter/pull/293) previously, but for StatefulSets instead of deployment pods with ephemeral volumes.

**Reproduction Steps** (Please include YAML):

Create a statefulset with the following `volumeClaimTemplates` in the spec:
```
  volumeClaimTemplates:
    - metadata:
        name: aggregator-db-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 512Gi
        storageClassName: null
    - metadata:
        name: persistent-configs
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: null
```

Can pin it to `d3` instance-family for easier reproduction:
```
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: karpenter.k8s.aws/instance-family
                  operator: In
                  values:
                  - d3
                  - d3en
```

**Versions**:
- Chart Version: 1.1.2
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
