### ISSUE TITLE
Daemon consumption are not taken into acount for creation of new node creating case of unschedulable pod due to insufficient memory

### ISSUE THREAD

**Issue by victor-smg** [aws/karpenter-provider-aws#7727]
### Description

**Observed Behavior**:
For job requesting 1GB, Karpenter created a new node with 1,4GB which should have enough space to schedule the job.
However the DaemonSets on the cluster took slightly more than 400MB not leaving enough space for the job to be schedule.

**Expected Behavior**:
Karpenter should create new node with a margin to take into account the consumption of existing Daemonset
 
**Reproduction Steps** (Please include YAML):
Case happened using medium EC2 with with 1471156Ki (1,4Gi), and a cronjob requesting 1GB of mem
```
{"level":"INFO","time":"2025-01-22T16:22:37.630Z","logger":"controller","message":"initialized nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"XXX-worker-2xw2d"},"namespace":"","name":"XXX-worker-2xw2d","reconcileID":"9c919ed6-a695-4f29-9239-e54cda3c6f50","provider-id":"aws:///eu-central-1b/i-042d1c2799bcebefc","Node":{"name":"XXX.compute.internal"},"allocatable":{"cpu":"940m","ephemeral-storage":"18181869946","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"1471156Ki","pods":"8"}}
```
We had various daemonset that took too much memory.
We avoid the issue, by dropping this node size out of the Karpenter instance size pool

**Versions**:
- Chart Version: 1.0.7
- Kubernetes Version (`kubectl version`): 1.31.4

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you post the DaemonSet and the Job that you are trying to schedule to this node? We need the resources as well as the scheduling constraints on each.

**Comment by imunhatep** [comment]
DaemonSet

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "32Gi"
          limits:
            memory: "32Gi"
        ports:
        - containerPort: 80
          protocol: TCP
      terminationGracePeriodSeconds: 30
```

Deploy
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "32Gi"
          limits:
            memory: "32Gi"
        ports:
        - containerPort: 80
          protocol: TCP
      terminationGracePeriodSeconds: 30
```

Nodepool
```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: NodePool
metadata:
  name: default-nodepool
  namespace: karpenter
spec:
  template:
    metadata:
      labels:
        app: workload
    spec:
      subnetSelectorTerms:
        - tags:
            kubernetes.io/cluster/my-cluster: owned
      securityGroupSelectorTerms:
        - tags:
            karpenter.sh/discovery: my-cluster
  limits:
    cpu: "1000"
    memory: "2000Gi"
  disruption:
    consolidationPolicy: "WhenUnderutilized"
  weight: 50
```
