### ISSUE TITLE
Question: terminationGracePeriod and draining in expired nodes

### ISSUE THREAD

**Issue by nicanor-asana** [aws/karpenter-provider-aws#7729]
Hi,

I am trying to get clarity regarding the behaviour of Karpenter v1.1 with the expiration of nodes, and I am bit doubtful in the relation between expiration, draining and  [terminationGracePeriod](https://karpenter.sh/docs/concepts/disruption/#terminationgraceperiod). I would like to get confirmation about whether my understanding is correct. I have browsed through the issues and have seen that there is a request for a [soft expiration feature](https://github.com/kubernetes-sigs/karpenter/issues/1750) but I still feel that what I want to achieve can be achieved with the current toolset.

**Scenario**
A deployment `deployment-a`:
- labeled `app=deployment-a` 
- replicas set to 20
- pods a `terminationGracePeriodSeconds` set to 60
- which has the following PodDisruptionPolicy:
  ```
  apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    name: deployment-a
    namespace: some-namespace
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        app: deployment-a
  ```
- the pods of this deployment run in the following NodePool (simplified):
  ```
  apiVersion: karpenter.sh/v1
  kind: NodePool
  metadata:
    name: my-pool
  spec:
    disruption:
      budgets:
      - nodes: 10%
      consolidateAfter: 0s
      consolidationPolicy: WhenEmptyOrUnderutilized
    template:
      spec:
        expireAfter: 24h
        terminationGracePeriod: 1h
  ```
- each replica of `deployment-a` runs in a different node (not relevant, but due to resource requests)

**Questions**
if:
- The 20 nodes hosting were created at 10AM
- Their expiration is 10AM of the next day

Will the draining of the pods of `deployment-a` start at 10AM, respecting the PDB?
Will the pods non graceful termination start at 11AM, meaning that there is 1 hour for the pods to be drained gracefully (provided no `do-not-disrupt` label is used)?

Thanks in advance, and apologies for the clutter.
