### ISSUE TITLE
NodeClass for GPU nodes and special AMIs

### ISSUE THREAD

**Issue by obervinov** [aws/karpenter-provider-aws#7731]
### Description

I am trying to configure EC2NodeClass for GPU instances, which should work with the corresponding AMI `amazon-eks-node-al2023-x86_64-nvidia-*`:
```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - name: amazon-eks-node-*-nvidia-*
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 50Gi
        volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: Karpenter
  securityGroupSelectorTerms:
    - tags:
        Name: eks-node
```
However, all my attempts to resolve the expected AMIs in NodeClass are failing.
The resolved AMI list includes images with an incompatible Kubernetes version:
```yaml
status:
  amis:
    - id: ami-0430b7e46a1aa97be
      name: amazon-eks-node-al2023-x86_64-nvidia-1.27-v20250203
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
```
Do I understand correctly that the only way to make this work is to:
- Specify a specific AMI ID?
- Specify a specific Kubernetes version in the wildcard name?

Both of these methods are inconvenient and resource-intensive when dealing with multiple NodeClass resources. Any cluster update then requires modifying dozens of manifests, which is inefficient.

**Expected Behavior**:
- NodeClass should return the relevant AMI for the current Kubernetes version.
- NodeClass should return the latest version of the AMI for the current Kubernetes version.

**Reproduction Steps** (Please include YAML):
```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - name: amazon-eks-node-*-nvidia-*
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 50Gi
        volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: Karpenter
  securityGroupSelectorTerms:
    - tags:
        Name: eks-node
```

**Versions**: 
- Chart Version: 1.2.1
- Kubernetes Version (`kubectl version`): 1.31

I might be misunderstanding the concept of NodeClass, so I would appreciate any recommendations.

The main goal I am trying to achieve is to automatically get the latest AMI versions without explicitly specifying the AMI ID or Kubernetes version.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
