### ISSUE TITLE
Adding expire to disruption reasons

### ISSUE THREAD

**Issue by wufengzlw** [aws/karpenter-provider-aws#7797]
### Description

**What problem are you trying to solve?**

We are running Karpenter 1.0 right now.
To rotate EKS nodes for security reason, we have `expireAfter` config.
We can control disruption time period with budgets for consolidation and drifted, but the nodes and pods will be killed during peak hours.
If we can control time period of expire disruption like consolidation, so we can ensure the availability of key services.
```
  disruption:
    consolidateAfter: 5m
    consolidationPolicy: WhenEmpty
    budgets:
    - nodes: "10%"
      reasons:
      - Drifted
    - nodes: "0"
      schedule: "0 12 * * mon-fri"
      duration: 8h30m0s
      reasons:
      - Drifted
    - nodes: 100%
      reasons:
      - Empty
# if we can add similar config like this:
    - nodes: "10%"
      reasons:
      - Expire
    - nodes: "0"
      schedule: "0 12 * * mon-fri"
      duration: 8h30m0s
      reasons:
      - Expire
```

BTW, another question, if we have `expireAfter`, `terminationGracePeriod` and `karpenter.sh/do-not-disrupt` configured at the same time, when we reach `expireAfter` + `terminationGracePeriod`, there will be a forcefully kill, does it like
```
kubectl delete pod
```
or like
```
kubectl delete node
```

**How important is this feature to you?**
8/10

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
