### ISSUE TITLE
Karpenter Creates 2 Instead of 1 Node

### ISSUE THREAD

**Issue by robertvanloenhout** [aws/karpenter-provider-aws#7800]
### Description

Regularly Karpenter is creating 2 nodes for 1 pod. Is this known behaviour?
This doesn't happen always, but it is a waste to create a node that won't be used for anything.
We are using the default batch time settings.
We see in the logs that the "found provionable pod(s)" entry occurs twice (or more) for the same pod and also see multiple "created nodeclaim" entries.
We see this behaviour in Karpenter version 1.0.5, 1,2.0 and 1.2.1 so far.
Any advice is appreciated.

Here is an example of the log when this happens:

```
{"level":"INFO","time":"2025-02-25T16:29:29.941Z","logger":"controller","message":"found provisionable pod(s)","commit":"652e6aa","controller":"provisioner","namespace":"","name":"","reconcileID":"2e7aa4fd-e611-40a4-8010-adae318d1938","Pods":"myns/mypod-88ec2e12-666e-4035-98c9-7528a8033b6c-6khwj","duration":"66.788305ms"}
{"level":"INFO","time":"2025-02-25T16:29:29.941Z","logger":"controller","message":"computed new nodeclaim(s) to fit pod(s)","commit":"652e6aa","controller":"provisioner","namespace":"","name":"","reconcileID":"2e7aa4fd-e611-40a4-8010-adae318d1938","nodeclaims":1,"pods":1}
{"level":"INFO","time":"2025-02-25T16:29:29.953Z","logger":"controller","message":"created nodeclaim","commit":"652e6aa","controller":"provisioner","namespace":"","name":"","reconcileID":"2e7aa4fd-e611-40a4-8010-adae318d1938","NodePool":{"name":"karpenter-mypod-nodepool"},"NodeClaim":{"name":"karpenter-mypod-nodepool-9tfpn"},"requests":{"cpu":"1780m","memory":"2832Mi","pods":"7"},"instance-types":"t3.medium"}
{"level":"INFO","time":"2025-02-25T16:29:31.976Z","logger":"controller","message":"launched nodeclaim","commit":"652e6aa","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-mypod-nodepool-9tfpn"},"namespace":"","name":"karpenter-mypod-nodepool-9tfpn","reconcileID":"13108887-0d8b-43f8-b9a6-a9730c172e1d","provider-id":"aws:///us-west-2a/i-0ff00702eb67c678e","instance-type":"t3.medium","zone":"us-west-2a","capacity-type":"spot","allocatable":{"cpu":"1930m","ephemeral-storage":"44Gi","memory":"3246Mi","pods":"17"}}
{"level":"INFO","time":"2025-02-25T16:29:33.786Z","logger":"controller","message":"found provisionable pod(s)","commit":"652e6aa","controller":"provisioner","namespace":"","name":"","reconcileID":"9e21a352-9a94-41a7-bed2-9d64650a03e0","Pods":"myns/mypod-88ec2e12-666e-4035-98c9-7528a8033b6c-6khwj","duration":"68.817987ms"}
{"level":"INFO","time":"2025-02-25T16:29:33.786Z","logger":"controller","message":"computed new nodeclaim(s) to fit pod(s)","commit":"652e6aa","controller":"provisioner","namespace":"","name":"","reconcileID":"9e21a352-9a94-41a7-bed2-9d64650a03e0","nodeclaims":1,"pods":1}
{"level":"INFO","time":"2025-02-25T16:29:33.798Z","logger":"controller","message":"created nodeclaim","commit":"652e6aa","controller":"provisioner","namespace":"","name":"","reconcileID":"9e21a352-9a94-41a7-bed2-9d64650a03e0","NodePool":{"name":"karpenter-mypod-nodepool"},"NodeClaim":{"name":"karpenter-mypod-nodepool-jnck5"},"requests":{"cpu":"1780m","memory":"2832Mi","pods":"7"},"instance-types":"t3.medium"}
{"level":"INFO","time":"2025-02-25T16:29:35.885Z","logger":"controller","message":"launched nodeclaim","commit":"652e6aa","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-mypod-nodepool-jnck5"},"namespace":"","name":"karpenter-mypod-nodepool-jnck5","reconcileID":"3e25b307-339b-4268-abf7-cbfccc87c14d","provider-id":"aws:///us-west-2b/i-041f7faa982af5d80","instance-type":"t3.medium","zone":"us-west-2b","capacity-type":"spot","allocatable":{"cpu":"1930m","ephemeral-storage":"44Gi","memory":"3246Mi","pods":"17"}}
{"level":"INFO","time":"2025-02-25T16:30:09.305Z","logger":"controller","message":"registered nodeclaim","commit":"652e6aa","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-mypod-nodepool-jnck5"},"namespace":"","name":"karpenter-mypod-nodepool-jnck5","reconcileID":"6ea766b3-d456-4bef-8b43-9ca61c385e9d","provider-id":"aws:///us-west-2b/i-041f7faa982af5d80","Node":{"name":"ip-xx-xx-xxx-xxx.us-west-2.compute.internal"}}
{"level":"INFO","time":"2025-02-25T16:30:25.718Z","logger":"controller","message":"initialized nodeclaim","commit":"652e6aa","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-mypod-nodepool-jnck5"},"namespace":"","name":"karpenter-mypod-nodepool-jnck5","reconcileID":"d2963818-eb06-4ca9-89ee-8b27c1d9030c","provider-id":"aws:///us-west-2b/i-041f7faa982af5d80","Node":{"name":"ip-xx-xx-xxx-xxx.us-west-2.compute.internal"},"allocatable":{"cpu":"1930m","ephemeral-storage":"47233297124","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"3388292Ki","pods":"17"}}
{"level":"INFO","time":"2025-02-25T16:30:51.952Z","logger":"controller","message":"registered nodeclaim","commit":"652e6aa","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-mypod-nodepool-9tfpn"},"namespace":"","name":"karpenter-mypod-nodepool-9tfpn","reconcileID":"68f57d13-ab33-42ca-b882-c9e4e40d1214","provider-id":"aws:///us-west-2a/i-0ff00702eb67c678e","Node":{"name":"ip-yy-yy-yyy-yy.us-west-2.compute.internal"}}
{"level":"INFO","time":"2025-02-25T16:31:13.347Z","logger":"controller","message":"initialized nodeclaim","commit":"652e6aa","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-mypod-nodepool-9tfpn"},"namespace":"","name":"karpenter-mypod-nodepool-9tfpn","reconcileID":"a25af346-c53a-42ca-b075-c2fd8fb05c00","provider-id":"aws:///us-west-2a/i-0ff00702eb67c678e","Node":{"name":"ip-yy-yy-yyy-yy.us-west-2.compute.internal"},"allocatable":{"cpu":"1930m","ephemeral-storage":"47233297124","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"3388300Ki","pods":"17"}}

```

**Comment by liafizan** [comment]
Might be similar: https://github.com/aws/karpenter-provider-aws/issues/6355. Please do check for taints and share any nodepool config is possible.

**Comment by robertvanloenhout** [comment]
Hi @liafizan . We are not using Cilium or any startup node taints.
Here is my nodepool configuration.

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/stored-version-migrated: 'true'
  name: karpenter-mypod-nodepool
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 5m
    consolidationPolicy: WhenEmpty
  template:
    metadata:
      labels:
        project: myproject
        team: myteam
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: karpenter-mypod-ec2-nodeclass
      requirements:
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: k8s.mydomain.com/karpenter-group
          operator: In
          values:
            - mypod
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - t3.medium
            - m5.large
            - m5a.large
            - m7a.large
            - m7a.xlarge
            - m7i.large
            - m7i.xlarge
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
      taints:
        - effect: NoSchedule
          key: k8s.mydomain.com/karpenter-group
          value: mypod

```
