### ISSUE TITLE
Define Cloudwatch Alarms

### ISSUE THREAD

**Issue by kaykhan** [aws/karpenter-provider-aws#7824]
### Description

**What problem are you trying to solve?**

We would like to be able to define a set of cloudwatch alarms for ec2 instance. 

```
spec:
  cloudWatchAlarms:
    - alarmName: "HighCPUUtilization"
      alarmDescription: "CPU utilization is too high"
      metricName: "CPUUtilization"
      namespace: "AWS/EC2"
      statistic: "Average"
      period: 300
      evaluationPeriods: 2
      threshold: 80
      comparisonOperator: "GreaterThanThreshold"
      alarmActions:
        - "arn:aws:sns:us-west-2:123456789012:MyTopic"
      actionsEnabled: true

```
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html

Currently we have to do this independently with a custom solution of listening to new ec2 instances. I don’t like this approach because it separates alarm creation from the definition of Karpenter node pools/classes. It makes more sense for these to be managed together since the entity defining the node pools/classes has better context on which CPU or other metrics to target and when to trigger alarms.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

---

I would be interested in contributing, although it will be my first time working on an operator so i would need a lot of hand holding.
