### ISSUE TITLE
Node created but nodeadm failure (EKS 1.31, eks.20) Karpenter 1.3.2

### ISSUE THREAD

**Issue by cogentist-yann** [aws/karpenter-provider-aws#7889]
### Description

**Observed Behavior**:
Karpenter is able to launch a node, the node use the correct IAM Role and permissions. 
The node is created in the correct security group/subnet, and the security group seems able to reach the cluster API as AWS managed nodegroup nodes uses the same.
No error in the Karpenter logs.

NodeClaim are stuck in `Unknow` status
I am unable to ssh into the node but logs show
```sh
Failed to start nodeadm-co.service - EKS Nodeadm Config
Dependency failed for nodeadm-run.service - EKS Nodeadm Run.
```
also node are reporter as `Node not registered with cluster`, `NodeNotFound` in the `NodeClaim` status

**Expected Behavior**:
Node are able to join the cluster

**Reproduction Steps** (Please include YAML):
Create an EKS 1.31 version (eks.20) 
Use the helm install of karpenter

```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  labels:
    app.kubernetes.io/instance: karpenter
  name: provider-default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: ami-02af5816582540b35
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        volumeSize: 100Gi
        volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: KarpenterIRSA-stag-sr-green
  securityGroupSelectorTerms:
    - tags:
        Name: sr-stag-eks-green-node
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery/sr-stag-eks-green: karpenter
  tags:
    Name: sr-stag-eks-green
    karpenter.sh/discovery: sr-stag-eks-green
    project: sr-stag-eks-green
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  labels:
    app.kubernetes.io/instance: karpenter
  name: worker-default 
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        project: sr-stag-eks-green
        tegaki.ai/nodepool: worker-default 
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: provider-default
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - c5.large
            - c5.xlarge
            - c5.2xlarge
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - ap-northeast-1a
            - ap-northeast-1c
            - ap-northeast-1d
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
      taints:
        - effect: NoSchedule
          key: tegaki.ai/nodepool
          value: worker-default
```

**Versions**:
- Chart Version: 1.3.2
- Kubernetes Version (`kubectl version`): 1.31.X

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
