### ISSUE TITLE
Nodeclaim does not have an associated node

### ISSUE THREAD

**Issue by allwin-yubi** [aws/karpenter-provider-aws#7917]
<img width="1373" alt="Image" src="https://github.com/user-attachments/assets/4a433434-2225-4efc-ae14-1344b4f3e874" />

### Description:
Hello team,
I'm encountering an issue where the Karpenter nodeclaim does not have an associated node. This error has been occurring intermittently, with the following details:

**Error Message: Normal DisruptionBlocked 86s (x2 over 3m28s) karpenter Nodeclaim does not have an associated node**

**Frequency**: The error has occurred twice in the last 3 minutes and 28 seconds.

**Environment**: [Kubernetes version 1.31, Karpenter version: 1.3.2 , cloud provider:AWS]

**Expected Behavior:**

The nodeclaim should successfully associate with a node without disruptions.

**Actual Behavior:**

The nodeclaim fails to associate with a node, leading to disruptions in the cluster.

**Additional Information:**

**nodepool.sh**

```
cat <<EOF | envsubst | kubectl apply -f -
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: "KarpenterNodeRole-${CLUSTER_NAME}" # replace with your cluster name
  amiSelectorTerms:
    - alias: "al2023@${ALIAS_VERSION}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
EOF
```

**Comment by allwin-yubi** [comment]
@jonathan-innis

**Comment by jmdeal** [comment]
Has the node registered with the cluster? If the node hasn't joined, this is expected behavior - Karpenter isn't going to perform consolidation or drift against a node which hasn't registered with the cluster. I would recommend consulting this [troubleshooting entry](https://karpenter.sh/docs/troubleshooting/#node-notready) to help diagnose node join failures. 

If the node has registered with the cluster, and Karpenter does not appear to be detecting it, please provide the node and nodeclaim manifests along with Karpenter logs.

**Comment by allwin-yubi** [comment]
@jmdeal 
The node is created but not getting registered with the cluster.,

<img width="1291" alt="Image" src="https://github.com/user-attachments/assets/14b98f72-bc96-4a8c-b9cb-a8e78e89f752" />

### node and nodeclaim manifest

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
```
```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  role: "KarpenterNodeRole-eks-cluster"
  amiSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-cluster"
        environment: test
    - name: my-ami
    - id: "ami-00089ba4dea0ff91c"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-cluster" 
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-cluster" 

```

### karpenter logs

`{"level":"INFO","time":"2025-03-18T19:26:17.243Z","logger":"controller","message":"no nodepools found","commit":"1c39126","controller":"provisioner","namespace":"","name":"","reconcileID":"707ad546-6462-4dd0-8406-d5c37e369e2e"}
{"level":"INFO","time":"2025-03-18T19:26:27.369Z","logger":"controller","message":"found provisionable pod(s)","commit":"1c39126","controller":"provisioner","namespace":"","name":"","reconcileID":"c5343e57-2e32-4e90-b43d-5dd982c446fd","Pods":"test/inflate-55cb7b99dd-sgjnb, test/inflate-55cb7b99dd-bkgkr, test/inflate-55cb7b99dd-g9jxh, test/inflate-55cb7b99dd-vbntk, test/inflate-55cb7b99dd-vt565","duration":"125.78678ms"}
{"level":"INFO","time":"2025-03-18T19:26:27.369Z","logger":"controller","message":"computed new nodeclaim(s) to fit pod(s)","commit":"1c39126","controller":"provisioner","namespace":"","name":"","reconcileID":"c5343e57-2e32-4e90-b43d-5dd982c446fd","nodeclaims":1,"pods":5}
{"level":"INFO","time":"2025-03-18T19:26:27.388Z","logger":"controller","message":"created nodeclaim","commit":"1c39126","controller":"provisioner","namespace":"","name":"","reconcileID":"c5343e57-2e32-4e90-b43d-5dd982c446fd","NodePool":{"name":"default"},"NodeClaim":{"name":"default-5fz6l"},"requests":{"cpu":"5150m","pods":"7"},"instance-types":"c4.2xlarge, c4.4xlarge, c5.2xlarge, c5.4xlarge, c5a.2xlarge and 55 other(s)"}
{"level":"INFO","time":"2025-03-18T19:26:29.616Z","logger":"controller","message":"launched nodeclaim","commit":"1c39126","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-5fz6l"},"namespace":"","name":"default-5fz6l","reconcileID":"d9d0f837-cba0-4dd8-903b-a90e033a8d42","provider-id":"aws:///ap-south-1c/i-06a1a6a2fe6f90c1d","instance-type":"c7i-flex.2xlarge","zone":"ap-south-1c","capacity-type":"spot","allocatable":{"cpu":"7910m","ephemeral-storage":"17Gi","memory":"14162Mi","pods":"58","vpc.amazonaws.com/pod-eni":"18"}}`
