### ISSUE TITLE
Capacity cache is never populated with multiple AMIs discovered by bottlerocket alias in amiSelector

### ISSUE THREAD

**Issue by BEvgeniyS** [aws/karpenter-provider-aws#7925]
### Description

**Observed Behavior**:
Karpenter keeps launching the node that is not able to host a triggering pod

**Expected Behavior**:
Karpenter should learn true instance capacity after first attempt

**Reproduction Steps** (Please include YAML):

nodeclass has the following amiSelector
```yaml
  amiSelectorTerms:
  - alias: bottlerocket@1.32.0-cacc4ce9
```
and discovered amis:
```yaml
  - id: ami-09ede7349be463f40
    name: bottlerocket-aws-k8s-1.30-nvidia-x86_64-v1.32.0-cacc4ce9
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: Exists
  - id: ami-0de231197f45db6bb
    name: bottlerocket-aws-k8s-1.30-nvidia-aarch64-v1.32.0-cacc4ce9
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: Exists
  - id: ami-0af46b2a82c2d83fe
    name: bottlerocket-aws-k8s-1.30-x86_64-v1.32.0-cacc4ce9
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
  - id: ami-0af46b2a82c2d83fe
    name: bottlerocket-aws-k8s-1.30-x86_64-v1.32.0-cacc4ce9
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: Exists
  - id: ami-038cf9675815cb406
    name: bottlerocket-aws-k8s-1.30-aarch64-v1.32.0-cacc4ce9
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
```

The capacity cache never gets populated because MapToInstanceTypes only returns first AMI for each instance type. And in this case it's nvidia ami, which never matches

**Versions**:
- Chart Version: v3.3.1
- Kubernetes Version (`kubectl version`): `Client Version: v1.32.3`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
