### ISSUE TITLE
ARM64 Nodes Not Registering in Kubernetes Cluster via Karpenter

### ISSUE THREAD

**Issue by manjeet1987** [aws/karpenter-provider-aws#7926]
### Description
Deploying ARM64 pods using Karpenter with a dedicated node pool (`cicd-armapps`) is failing due to node registration issues. Specifically, pods are not being scheduled because the nodes are not registering with the correct labels.

#### Mixed Architecture Configurations:
- Mixing ARM64 and AMD64 node configurations within a single template is not a suitable approach because the instance-family does not support it.
- It is better to create separate node pools per architecture (ARM64 and AMD64) with distinct configurations.

#### ARM64 Node Pool Configuration:
- A dedicated node pool `cicd-armapps` has been created for ARM64 nodes using the `t4g` instance family.
- The node pool uses the nodeSelector `pod-type: armapp`.

#### Deployment with Node Selector:
- A sample deployment (`armapp-deployment.yaml`) with nodeSelector `pod-type: armapp` and `kubernetes.io/arch: arm64` was deployed.
- The pod failed to schedule with the error:
  ```
  0/6 nodes are available: 6 node(s) didn't match Pod's node affinity/selector.
  Preemption: 0/6 nodes are available: 6 Preemption is not helpful for scheduling.
  ```
- `kubectl get nodepool` shows the `cicd-armapps` nodepool is created, but no nodes have joined.
- `kubectl get nodeclaim` shows a nodeclaim was created, but the node is not registered.

#### NodeClaim Details:
- `kubectl describe nodeclaim cicd-armapps-w5lst` reveals:
  - NodeClaim was created with the correct labels and requirements (ARM64, `t4g` instance family, `pod-type: armapp`, etc.).
  - The nodeclaim status shows `Node not registered with cluster`.
  - The nodeclaim has the correct labels, including `pod-type=armapp` and `kubernetes.io/arch=arm64`.

#### Deployment with Node Affinity:
- A modified deployment (`armapp-deployment.yaml` with node affinity) was deployed, using node affinity instead of node selector for `pod-type: armapp` and keeping the node selector for `kubernetes.io/arch: arm64`.
- This deployment succeeded, and the pod was scheduled on an ARM64 node.
- The pod is running with multiple restarts.

### Possible Cause: Node Registration Issue
- The primary issue is likely that the nodes are not registering with the Kubernetes cluster.
- While Karpenter successfully launches the EC2 instances, they are not joining the cluster as expected.
- The issue does not seem to be with Karpenter creating the nodes; rather, the nodes are failing to register.

### Steps to Reproduce
1. Create an ARM64 node pool using Karpenter with the following configuration:
   - Instance family: `t4g`
   - Node selector: `pod-type: armapp`
2. Deploy an ARM64-based sample application using nodeSelector and nodeAffinity.
3. Observe that the node claim is created, but the node itself does not register.
4. Check Karpenter logs and node claim details for any issues.

### Expected Behavior
- ARM64 nodes should register properly and be available for scheduling.
- Pods should be scheduled onto the ARM64 nodes without requiring node affinity workarounds.

### Actual Behavior
- Nodes are created but fail to register with the cluster.
- Pods fail to schedule when using nodeSelector but succeed when using nodeAffinity.

### Logs and Debugging Information
**Karpenter Logs:**
```
INFO controller found provisionable pod(s)
INFO controller computed new nodeclaim(s) to fit pod(s)
INFO controller created nodeclaim
INFO controller launched nodeclaim
INFO controller deleted nodeclaim
```

**NodeClaim Status:**
```
NodeClaim status: Node not registered with cluster
```

### Environment Details
- **Kubernetes Version:** 1.32
- **Karpenter Version:** 1.0.2
- **AWS Region:** `eu-west-1`
- **Instance Type:** `t4g.small`
- **Cluster Provisioning Tool:** Terraform

### Additional Context
- Workaround: Using node affinity instead of nodeSelector allows pods to be scheduled.
- Further debugging is needed to determine why the node registration is failing.

---
Please investigate and suggest possible fixes or additional debugging steps.

**Comment by jmdeal** [comment]
> because the nodes are not registering with the correct labels

Can you clarify - are nodes successfully joining the cluster with the incorrect labels, or are they not joining at all? This sentence seems to contradict the rest of the issue.

Node registration failures are typically due to misconfiguration outside of Karpenter. I recommend following the [troubleshooting guide](https://karpenter.sh/docs/troubleshooting/#node-notready), particularly checking out the kubelet logs.

**Comment by manjeet1987** [comment]
We can see that a new nodeclaim is getting created which is always in unknown status, this node claim creates a new instance which can be seen in karpenter logs but that instance is not getting registered with eks cluster. So basically the insance is not joining the cluster at all.


**This is working:**

NodePool
```yaml
    apiVersion: karpenter.sh/v1
    kind: NodePool
    metadata:
      name: cicd-apps
    spec:
      template:
        metadata:
          labels:
            intent: app
            pod-type: app
        spec:
          requirements:
            - key: "karpenter.k8s.aws/instance-category"
              operator: In
              values: ["c", "m", "r"]
            - key: "karpenter.k8s.aws/instance-family"
              operator: In
              values: ["m7a", "m6a", "c6a", "c7a"]
            - key: "karpenter.k8s.aws/instance-cpu"
              operator: In
              values: ["4", "8", "16"]
            - key: "karpenter.k8s.aws/instance-hypervisor"
              operator: In
              values: ["nitro"]
            - key: "topology.kubernetes.io/zone"
              operator: In
              values: ["eu-west-1a", "eu-west-1b","eu-west-1c"]
            - key: "kubernetes.io/arch"
              operator: In
              values: ["amd64"]
            - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
              operator: In
              values: ["on-demand"]
          nodeClassRef:
            group: karpenter.k8s.aws
            kind: EC2NodeClass
            name: cicd-apps
          expireAfter: Never
          terminationGracePeriod : 6h
      limits:
        cpu: 220
        memory: 880Gi
      disruption:
        consolidationPolicy: WhenEmpty
        consolidateAfter: 10m
        expireAfter: Never
        budgets:
        - nodes: "0"
          reasons:
          - Drifted
          - Underutilized
        - nodes: "100%"
          reasons:
          - Empty
```

EC2NodeClass:
```yaml
    apiVersion: karpenter.k8s.aws/v1
    kind: EC2NodeClass
    metadata:
      name: cicd-apps
    spec:
      amiFamily: AL2023
      role: ${module.karpenter.node_iam_role_name}
      subnetSelectorTerms:
      - tags:
          karpenter.sh/discovery: "true"
          Environment: "${upper(var.environment)}"
      securityGroupSelectorTerms:
      - tags:
          karpenter.sh/discovery: ${module.eks.cluster_name}
      amiSelectorTerms:
      - tags:
          karpenter.sh/discovery: "true"
          environment: "${upper(var.environment)}"
      - id: ami-0b429fd2c7bbec0d5
      blockDeviceMappings:
          - deviceName: /dev/xvda
            ebs:
              volumeSize: 100Gi
              volumeType: gp3
              iops: 3000
              encrypted: true
              deleteOnTermination: true
              throughput: 750
      userData: |
          #!/bin/bash
          set -o xtrace
          dnf install -y amazon-efs-utils
          mkdir /efs-mount-nexus
          mount -t efs "${element(aws_efs_file_system.efs.*.id, 0)}":/ /efs-mount-nexus
          cd /efs-mount-nexus
          if [ ! -d "nexus-data" ]; then
            mkdir "nexus-data"
            chmod 777 "nexus-data" -R
          fi
          sed -i '/^\[mount\]/,/^\[/ s/^\[mount\].*/[mount]\nregion = eu-west-1/' /etc/amazon/efs/efs-utils.conf
          mkdir /efs-mount-sonar
          mount -t efs "${element(aws_efs_file_system.efs.*.id, 1)}":/ /efs-mount-sonar
          cd /efs-mount-sonar
          if [ ! -d "sonar-data" ]; then
            mkdir "sonar-data"
            chmod 777 "sonar-data"
          fi
          mount -t bpf bpffs /sys/fs/bpf
      tags:
        Name: "${module.eks.cluster_name}/karpenter.sh/cicd-apps"
        karpenter.sh/discovery: ${module.eks.cluster_name}
        KarpenterProvisionerName: "cicd-apps"
        IntentLabel: "app"
        Environment: "${upper(var.environment)}"
```


**This is not working:**

armapp template: 

NodePool
```yaml
   apiVersion: karpenter.sh/v1
    kind: NodePool
    metadata:
      name: cicd-armapps
    spec:
      template:
        metadata:
          labels:
            intent: armapp
            pod-type: armapp
        spec:
          requirements:
            - key: "karpenter.k8s.aws/instance-category"
              operator: In
              values: ["t"]
            - key: "karpenter.k8s.aws/instance-family"
              operator: In
              values: ["t4g"]
            - key: "karpenter.k8s.aws/instance-cpu"
              operator: In
              values: ["2", "4"]
            - key: "karpenter.k8s.aws/instance-hypervisor"
              operator: In
              values: ["nitro"]
            - key: "topology.kubernetes.io/zone"
              operator: In
              values: ["eu-west-1a", "eu-west-1b","eu-west-1c"]
            - key: "kubernetes.io/arch"
              operator: In
              values: ["arm64"]
            - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
              operator: In
              values: ["on-demand"]
          nodeClassRef:
            group: karpenter.k8s.aws
            kind: EC2NodeClass
            name: cicd-armapps
          expireAfter: Never
          terminationGracePeriod : 6h
      limits:
        cpu: 220
        memory: 880Gi
      disruption:
        consolidationPolicy: WhenEmpty
        consolidateAfter: 30m
        expireAfter: Never
        budgets:
        - nodes: "0"
          reasons:
          - Drifted
          - Underutilized
        - nodes: "100%"
          reasons:
          - Empty
 ```

EC2NodeClass
```yaml
    apiVersion: karpenter.k8s.aws/v1
    kind: EC2NodeClass
    metadata:
      name: cicd-armapps
    spec:
      amiFamily: AL2023
      role: ${module.karpenter.node_iam_role_name}
      subnetSelectorTerms:
      - tags:
          karpenter.sh/discovery: "true"
          Environment: "${upper(var.environment)}"
      securityGroupSelectorTerms:
      - tags:
          karpenter.sh/discovery: ${module.eks.cluster_name}
      amiSelectorTerms:
      - tags:
          karpenter.sh/discovery: "true"
          environment: "${upper(var.environment)}"
      - id: ami-0dccaebf83bd2addc
      blockDeviceMappings:
          - deviceName: /dev/xvda
            ebs:
              volumeSize: 20Gi
              volumeType: gp3
              iops: 600
              encrypted: true
              deleteOnTermination: true
              throughput: 750
      userData: |
          #!/bin/bash
          set -o xtrace
          dnf install -y amazon-efs-utils
          mkdir /efs-mount-nexus
          mount -t efs "${element(aws_efs_file_system.efs.*.id, 0)}":/ /efs-mount-nexus
          cd /efs-mount-nexus
          if [ ! -d "nexus-data" ]; then
            mkdir "nexus-data"
            chmod 777 "nexus-data" -R
          fi
          sed -i '/^\[mount\]/,/^\[/ s/^\[mount\].*/[mount]\nregion = eu-west-1/' /etc/amazon/efs/efs-utils.conf
          mkdir /efs-mount-sonar
          mount -t efs "${element(aws_efs_file_system.efs.*.id, 1)}":/ /efs-mount-sonar
          cd /efs-mount-sonar
          if [ ! -d "sonar-data" ]; then
            mkdir "sonar-data"
            chmod 777 "sonar-data"
          fi
          mount -t bpf bpffs /sys/fs/bpf
      tags:
        Name: "${module.eks.cluster_name}/karpenter.sh/cicd-armapps"
        karpenter.sh/discovery: ${module.eks.cluster_name}
        KarpenterProvisionerName: "cicd-armapps"
        IntentLabel: "armapp"
        Environment: "${upper(var.environment)}"
```
