### ISSUE TITLE
EC2Node Class validation errors - InvalidBlockDeviceMapping volume size do not match

### ISSUE THREAD

**Issue by alex-berger** [aws/karpenter-provider-aws#7928]
### Description

**Observed Behavior**:

After upgrading to Karpenter 1.3.3 we started getting errors like the following ones, and it also looked like Karpenter is stuck (not provisioning new nodes). 

```
InvalidBlockDeviceMapping: Volume of size 2GB is smaller than snapshot 'snap-0f59de5aef3442431', expect size>= 4GB
```

Here some full log examples:

```
{"level":"ERROR","time":"2025-03-19T12:41:08.734Z","logger":"controller","message":"Reconciler error","commit":"ad71530","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"bottlerocket-private-v1"},"namespace":"","name":"bottlerocket-private-v1","reconcileID":"c5f58ed7-5e6a-4f92-bbf2-b239be4c994e","error":"validating ec2:RunInstances authorization, operation error EC2: RunInstances, https response error StatusCode: 400, RequestID: 4cf8f824-6ca6-4cdb-8c57-ab6e87c70a4e, api error InvalidBlockDeviceMapping: Volume of size 2GB is smaller than snapshot 'snap-0f59de5aef3442431', expect size>= 4GB"}
{"level":"ERROR","time":"2025-03-19T12:56:19.105Z","logger":"controller","message":"Reconciler error","commit":"ad71530","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"bottlerocket-private-v1"},"namespace":"","name":"bottlerocket-private-v1","reconcileID":"f9884623-9d0d-4699-a756-b7ee3ba5306f","error":"validating ec2:RunInstances authorization, operation error EC2: RunInstances, https response error StatusCode: 400, RequestID: 6cf3d367-1329-4876-a68b-719bbe8b6fb2, api error InvalidBlockDeviceMapping: Volume of size 2GB is smaller than snapshot 'snap-0ed2a0f02bda54daa', expect size>= 4GB"}
```

The `blockDeviceMappings` of the corresponding EC2NodeClass looks like this:

```yaml
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 2Gi
        volumeType: gp3
    - deviceName: /dev/xvdb
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 64Gi
        volumeType: gp3
```

It looks like Karpenter is for some (unknown) reasons using the wrong AMIs for validation. It uses the NVIDIA / GPU AMIs instead of the non-GPU ones. Since the GPU ones have a 4Gi snapshot for the the root volume (`/dev/xvda`) validation fails. 

In our cluster we **do not** use GPU instance and therefore we would expect Karpenter to never consider GPU AMIs. I can prove/verify this with the following command:

```shell
kubectl get nodeclaims -A -o yaml | grep 'ami-' | sort | uniq
    imageID: ami-0afff2858e4667019
    imageID: ami-0ddfac8e6e88e2c6d
```

The two snapshots referenced in the error messages, both correspond to NVIDIA AMIs:

|Snapshot|AMI|AMI Name|
|-|-|-|
|[snap-0ed2a0f02bda54daa](https://323827171370-kkbyhb4f.eu-central-1.console.aws.amazon.com/ec2/home?region=eu-central-1#SnapshotDetails:snapshotId=snap-0ed2a0f02bda54daa)|[ami-078f0312a7cdbc609](https://323827171370-kkbyhb4f.eu-central-1.console.aws.amazon.com/ec2/home?region=eu-central-1#ImageDetails:imageId=ami-078f0312a7cdbc609)|bottlerocket-aws-k8s-1.31-nvidia-x86_64-v1.34.0-18d04e52|
|[snap-0f59de5aef3442431](https://323827171370-kkbyhb4f.eu-central-1.console.aws.amazon.com/ec2/home?region=eu-central-1#SnapshotDetails:snapshotId=snap-0f59de5aef3442431)|[ami-0bb9630ee34d36074](https://323827171370-kkbyhb4f.eu-central-1.console.aws.amazon.com/ec2/home?region=eu-central-1#ImageDetails:imageId=ami-0bb9630ee34d36074)|bottlerocket-aws-k8s-1.31-nvidia-aarch64-v1.34.0-18d04e52|

**Expected Behavior**:

Karpenter should select the appropriate AMI for validation.

|Snapshot|AMI|AMI Name|
|-|-|-|
|[snap-00dbc564d868750fd](https://323827171370-kkbyhb4f.eu-central-1.console.aws.amazon.com/ec2/home?region=eu-central-1#SnapshotDetails:snapshotId=snap-00dbc564d868750fd)|[ami-0afff2858e4667019](https://323827171370-kkbyhb4f.eu-central-1.console.aws.amazon.com/ec2/home?region=eu-central-1#ImageDetails:imageId=ami-0afff2858e4667019)|bottlerocket-aws-k8s-1.31-x86_64-v1.34.0-18d04e52|
|[snap-07523a6b5d7442da2](https://323827171370-kkbyhb4f.eu-central-1.console.aws.amazon.com/ec2/home?region=eu-central-1#SnapshotDetails:snapshotId=snap-07523a6b5d7442da2)|[ami-0ddfac8e6e88e2c6d](https://323827171370-kkbyhb4f.eu-central-1.console.aws.amazon.com/ec2/home?region=eu-central-1#ImageDetails:imageId=ami-0ddfac8e6e88e2c6d)|bottlerocket-aws-k8s-1.31-aarch64-v1.34.0-18d04e52|

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 1.3.3
- Kubernetes Version (`kubectl version`): v1.31.6-eks-bc803b4

**Workaround**:

As workaround we adapted the `blockDeviceMappings` of the corresponding EC2NodeClass, increasing the 
`volumeSize` to `4Gi` like this:

```yaml
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 4Gi
        volumeType: gp3
    - deviceName: /dev/xvdb
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 64Gi
        volumeType: gp3
```

This solved the problem and allowed Karpenter to make progress again. However, at the cost of additional 2Gi of storage per node. 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
