### ISSUE TITLE
Daemonset Overhead and the number of pods

### ISSUE THREAD

**Issue by obervinov** [aws/karpenter-provider-aws#7938]
### Description

**How can the docs be improved?**
I couldn't find a more detailed description of this point in the documentation.
Sometimes I get an error like this `daemonset overhead={"cpu":"100m","memory":"334Mi","pods":"11"}`.
Could you tell me if this pod count (screenshot) correlates with the number of daemosets in the kubrentes cluster?
Do I understand correctly that if an instance in the resource table (screenshot), for example, has `pods: 8`, and the number of running `DaemonSets` in my cluster is 11, this EC2 instance will not be created?

<img width="1496" alt="Image" src="https://github.com/user-attachments/assets/ba089525-1770-4b34-ad53-348768157192" />

Thanks!

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
> Could you tell me if this pod count (screenshot) correlates with the number of daemosets in the kubrentes cluster?

It's the number of daemonsets Karpenter expects to schedule to that Node. This may not be the total number of daemonsets in the cluster (e.g. if your NodePool has a taint the daemonset doesn't tolerate). 

> Do I understand correctly that if an instance in the resource table (screenshot), for example, has pods: 8, and the number of running DaemonSets in my cluster is 11, this EC2 instance will not be created?

Yes, the values in the docs represent the maximum number of pods that can schedule to a node given Karpenter's default configuration. This could be overriden (e.g. via `ec2nodeclass.spec.kubelet.maxPods`) but by default it's based on the number of available ENIs. If the number of pods a NodeClaim is created for (including daemonset overhead) exceeds the number of pods an instance can support, it won't be launched.

**Comment by obervinov** [comment]
@jmdeal thanks for the detailed answer! It worked.
But it seems that this creates a duplication of parameters in the case of using `AL2023` and the Nodeadm configuration in User-Data. Or will it be enough for me to specify `maxpods` in the ec2nodeclass spec and there is no need to do it again in NodeConfig?
```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: generic
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest
  kubelet:
    maxPods: 1000
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="//"

    --//
    Content-Type: application/node.eks.aws

    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      kubelet:
        flags:
          - --max-pods=1000
```
