### ISSUE TITLE
Getting Client.InvalidLaunchTemplateName.NotFoundException For Automatically Deleted Launch Template

### ISSUE THREAD

**Issue by DolevGel** [aws/karpenter-provider-aws#7941]
### Description

**Observed Behavior**:

Karpenter attempts to describe a Launch Template that does not exist, resulting in the following error:

Client.InvalidLaunchTemplateName.NotFoundException: At least one of the launch templates specified in the request does not exist.
The missing Launch Template name: karpenter.k8s.aws/12345

Role: karpenter-controller-role

Event: DescribeLaunchTemplates

Karpenter automatically creates and deletes the launch template and this is why it is trying to catch the non-existing launch templates.

**Expected Behavior**:

If the referenced Launch Template does not exist, Karpenter should not be repeat failures due to missing Launch Templates for Launch Template that are being terminated automatically.

**Reproduction Steps** (Please include YAML):
```
additionalAnnotations: {}
additionalClusterRoleRules: []
additionalLabels: {}
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: karpenter.sh/nodepool
          operator: DoesNotExist
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: kubernetes.io/hostname
controller:
  env: []
  envFrom: []
  extraVolumeMounts: []
  healthProbe:
    port: 8081
  image:
    digest: sha256:157f478f5db1fe999f5e2d27badcc742bf51cc470508b3cebe78224d0947674f
    repository: public.ecr.aws/karpenter/controller
    tag: 0.37.0
  metrics:
    port: 8000
  resources: {}
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  sidecarContainer: []
  sidecarVolumeMounts: []
dnsConfig: {}
dnsPolicy: ClusterFirst
extraVolumes: []
fullnameOverride: ""
hostNetwork: false
imagePullPolicy: IfNotPresent
imagePullSecrets: []
logConfig:
  enabled: false
  errorOutputPaths:
  - stderr
  logEncoding: json
  logLevel:
    controller: info
    global: info
    webhook: error
  outputPaths:
  - stdout
logLevel: info
nameOverride: ""
nodeSelector:
  kubernetes.io/os: linux
podAnnotations: {}
podDisruptionBudget:
  maxUnavailable: 1
  name: karpenter
podLabels: {}
podSecurityContext:
  fsGroup: 65532
priorityClassName: system-cluster-critical
replicas: 2
revisionHistoryLimit: 10
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::867824819688:role/hadc-7342179-karpenter-controller-role
  create: true
  name: hadc-7342179-karpenter-sa
serviceMonitor:
  additionalLabels: {}
  enabled: false
  endpointConfig: {}
settings:
  assumeRoleARN: ""
  assumeRoleDuration: 15m
  batchIdleDuration: 1s
  batchMaxDuration: 10s
  clusterCABundle: ""
  clusterEndpoint: https://9C6E31BC1F5D5E66AB5E7361233556AE.gr7.ap-south-1.eks.amazonaws.com
  clusterName: hadc-7342179-eks
  featureGates:
    drift: true
    spotToSpotConsolidation: false
  interruptionQueue: ""
  isolatedVPC: false
  reservedENIs: "0"
  vmMemoryOverheadPercent: 0.075
strategy:
  rollingUpdate:
    maxUnavailable: 1
terminationGracePeriodSeconds: null
tolerations:
- key: CriticalAddonsOnly
  operator: Exists
topologySpreadConstraints:
- maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: ScheduleAnyway
webhook:
  enabled: false
  metrics:
    port: 8001
  port: 8443
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

```
**Versions**:
- Chart Version:
    karpenter-0.37.0
- Kubernetes Version (`kubectl version`):
   v1.30.1
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
