### ISSUE TITLE
Diversifying instance types on spot nodepools

### ISSUE THREAD

**Issue by gomesdigital** [aws/karpenter-provider-aws#7949]
### Problem
Workloads have down time due to spot-interruption and latency in acquiring new nodes.

### Context
We have a cluster which is required to run in a single zone to minimize network costs. It is optimized to run on ```spot``` nodes to save on costs as well.

I've observed that sometimes when a spot interruption happens, a large portion of the cluster is affected because Karpenter has repeatedly selected the same instance type. Thereby, the blast radius of a single spot interruption can be very large. At times, more than 50% of the cluster.

![Image](https://github.com/user-attachments/assets/0156ebf9-d597-4721-8def-4ad20c52f8e4)

If a particular service is running across the dominant node type, that service can become impaired until there are enough nodes to scale out again.

Note - the services are configured to shut down gracefully and spawn quickly. It is only in these large spot interruptions of a particular type do we see the down time occur.

### Options
* Dedicating a portion of the services  to ```on-demand``` nodes. This would improve tolerance to the spot interruptions. It  is the least attractive option and a last resort due to the increased costs.

* Improving time to provision new nodes. I've observed it take ~ 3min 30s to get back to the original node capacity after a big interruption, which implies there is ~ 1min 30s of pending workloads when considering the AWS  spot-interruption interval of 2min. The default SQS queue is being used as prescribed by the official documentation. It is understood that the time it takes to provision new nodes is not entirely under Karpenter's control, so this is not being explored.

It can be seen in the image above that the instance types in use are already very diverse. We would like to determine if there is a way to make their distribution more uniform, while still running on spot. That would reduce the blast radius of a single spot interruption and still beat the cost of running ```on-demand``` nodes. e.g. Karpenter round robins the available instance types, rather than persistently choosing the cheapest. As far as I've seen there is no configuration to achieve this through the current nodepool API.

#### Detail
EKS 1.32
Karpenter v1.2.1

Nodepool:
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: # (redacted)
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 0s
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: # (redacted)
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ['amd64', 'arm64']
        - key: karpenter.sh/capacity-type
          operator: In
          values: ['spot', 'on-demand']
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ['c', 'm', 'r']
        - key: karpenter.k8s.aws/instance-family
          operator: NotIn
          values: ['m5', 'm5d', 'm5n', 'm5dn', 'm5a', 'm5ad', 'r5', 'r5d', 'r5n', 'r5dn', 'r5b', 'r5a', 'r5ad', 'c7i-flex', 'm7i-flex']
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ['4']
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ['2xlarge','4xlarge']
        - key: topology.kubernetes.io/zone
          operator: In
          values: # (redacted)
```
