### ISSUE TITLE
top wants - ec2NodeClass kmsKeyAlias option instead of ID and a bottlerocket fips alias

### ISSUE THREAD

**Issue by drduker** [aws/karpenter-provider-aws#7952]
### Description

**What problem are you trying to solve?**
simplify deployment

blockDeviceMappings would be way more dynamic if selection of kmsKeyID were instead selected by a new "kmsKeyAlias" key like this:
```
  - deviceName: '/dev/xvda'
    rootVolume: true
    ebs:
      encrypted: true
      volumeType: gp3
      volumeSize: 100Gi
      kmsKeyAlias: "encryption-key"  # instead of guid from ID
      deleteOnTermination: true
```

and then this would be super useful:
```
  amiSelectorTerms:
    - alias: "bottlerocket-fips@latest"
```
**How important is this feature to you?**
huuuuge

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by drduker** [comment]
following - https://github.com/aws/karpenter-provider-aws/pull/7756

**Comment by drduker** [comment]
just found that yup - https://github.com/aws/karpenter-provider-aws/pull/7934

**Comment by drduker** [comment]
usage of kms alias should just be:
```
  - deviceName: '/dev/xvda'
    rootVolume: true
    ebs:
      encrypted: true
      volumeType: gp3
      volumeSize: 100Gi
      kmsKeyID: "encryption-key" 
      deleteOnTermination: true
```
