### ISSUE TITLE
Instance tags based on placeholders

### ISSUE THREAD

**Issue by pierreact** [aws/karpenter-provider-aws#7973]
### Description

**What problem are you trying to solve?**

- Why is this node here?
- What created it?

I would like to have placeholders for EC2 instance tags.

```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  namespace: karpenter
spec:
  ...
  ...
  tags:
    LaunchTime: $${LaunchTime}
    NodePool: $${NodePool}
    NodeClass: $${NodeClass}
    ClusterName: $${ClusterName}
    TriggeringNewNodePodUID: $${PodUID}
```

**How important is this feature to you?**

Would be quite useful

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
