### ISSUE TITLE
Regression: Karpenter is launching more smaller nodes (with higher costs) after 1.0->1.3 upgrade

### ISSUE THREAD

**Issue by nantiferov** [aws/karpenter-provider-aws#7984]
### Description

**Observed Behavior**:

I'm observing strange behavior of v1.3.3 of Karpenter, which I cannot find in the changelog. It seems to me that it might be related to AWS provider more, but please let me know if I should open it in https://github.com/kubernetes-sigs/karpenter instead.

Looks like something is changed between v1.0.8 and 1.3.3, which causes Karpenter to launch more smaller nodes, which slightly improves CPU utilization, but drops drastically memory utilization and increases costs.

Issue appeared not directly after Karpenter update to v1.3, but later after EKS update to 1.32 and draining old nodes and launching new ones.

I can provide example for one of the nodepools. Before nodes recreation there were `2 x c6g.large` nodes, which costs hourly `2*0.0776=0,155` in eu-central-1  and after there were `8 x c6g.medium`, which costs `8*0.0388=0,31` in eu-central-1 (on-demand). There were no changes to resources requests for stuff running in  nodepool, so increase in amount of nodes is only related to Karpenter. 

Screenshot from Karpenter dashboard showing diff in cpu/mem requests/total:
<img width="1690" alt="Image" src="https://github.com/user-attachments/assets/b3c4365e-2918-45f5-9230-b0f960f81627" />

When I check describe on nodeclaim, it shows that it's impossible to optimize them: `Normal  Unconsolidatable  13m (x3 over 44m)  karpenter  Can't replace with a cheaper node`.

I also checked older v1.2.3 and v1.1.5, they have same issue with suboptimal consolidation. So I guess something changed in v1.0->v1.1

**Expected Behavior**:

Karpenter keeps nodes costs optimized according to requested resources, like before.

**Reproduction Steps** (Please include YAML):

I'm not sure, but something like:

* deploy some stuff to cluster with Karpenter 1.0.8
* update Karpenter to 1.3.3
* drain old nodes and check which nodes launched instead
* compare prices

Nodepool configuration wasn't changed, budgets part snippet:

```yaml
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 0s
    budgets:
      - nodes: 10% # set a baseline disruption budget
        reasons: [Empty, Underutilized]
      - nodes: "0" # disable drift disruption
        reasons: [Drifted]
      - schedule: 0 0,16 * * mon-fri # restrict disruption from 00:00-8:00 and 16:00-00:00 on weekdays
        duration: 8h
        nodes: "0"
      - schedule: 0 0 * * sat,sun # restrict disruption on weekends
        duration: 24h
        nodes: "0"
```

**Versions**:
- Chart Version: 1.3.3
- Kubernetes Version (`kubectl version`): v1.32.3-eks-bcf3d70

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
