### ISSUE TITLE
High CPU usage after upgrading Karpenter

### ISSUE THREAD

**Issue by rahmedrbx** [aws/karpenter-provider-aws#7986]
We upgraded our karpenter deployment from v0.36.1 to v1.3.3 and noticed that the CPU usage more than doubled (see before and after images) The charts compare a similar workload. 

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/4b2fcbd8-b85e-4329-bc19-94790226af1e" />

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/41ccfe2c-1d72-44de-9425-6d61d2d8c54c" />

Looking at the controller logs, we see reconciliation logs roughly once every 2-3 seconds so it doesn't seem like it's doing much. Yet the CPU utilization remains high. What could be the problem and is there anything we can do to reduce the usage? We already bumped the CPU limits from 1 to 2 and then to 3 but utilization was close to 100% each time. On v.0.36.1, we ran the same workload with 1 CPU with no issues and utilization hovered around 80%. 

karpenter version: 1.3.3 (upgraded from 0.36.1) 
k8s version: 1.29

**Comment by stijndehaes** [comment]
I can confirm this, I did some CPU profiling:

![Image](https://github.com/user-attachments/assets/b3a3eb5c-76b2-4acd-93aa-390f0252e02b)

Looking at the code this might be introduced by the changes for capacity reservations as the main code path that is using up the CPU has been changed in that.

If that is the case version 1.2 would reduce the load again, I will test this out

**Comment by nantiferov** [comment]
I can confirm that we observe same situation across multiple clusters.
On average, CPU usage increased ~4x comparing with v0.36. Something like 0.36->1.0 switch required 2x more CPU resources and then update to v1.3 2x more.

**Comment by nantiferov** [comment]
Also it was mentioned in [this issue](https://github.com/kubernetes-sigs/karpenter/issues/1733#issuecomment-2699952334) that recently there were performance improvements, maybe CPU usage increase is coming from it.

**Comment by engedaam** [comment]
@stijndehaes @nantiferov  Have you enabled capacity reservation? Can you share your karpenter deployment?

**Comment by kppullin** [comment]
We've seen the same moving from 1.0.7 to 1.3.2.  Here's 3 minute CPU flamegraphs comparing the two:

1.0.7
<img width="1509" alt="Image" src="https://github.com/user-attachments/assets/ce7f8f0a-9e23-4b1f-b13c-a03e811dc111" />

1.3.2
<img width="1510" alt="Image" src="https://github.com/user-attachments/assets/75fd43e0-728c-4ccd-acc0-0856bf016126" />

In 1.3.2, `GetInstanceTypes` (41% of total CPU) and `buildDomainGroups` (17.5%) jump out as new sources of CPU load.  I think https://github.com/aws/karpenter-provider-aws/pull/7898 helps with some of this, by reducing how frequently the metrics are updated, but still a lot of other activity going on.

Are dev builds published? I could try capturing a profile using an image build from `main`.

**Comment by rahmedrbx** [comment]
@engedaam we have not enabled capacity reservation. we've kept the default settings. See relevant container envs - 
```
containers:
  - env:
    - name: KUBERNETES_MIN_VERSION
      value: 1.19.0-0
    - name: KARPENTER_SERVICE
      value: karpenter
    - name: MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: controller
          divisor: "0"
          resource: limits.memory
    - name: FEATURE_GATES
      value: ReservedCapacity=false,SpotToSpotConsolidation=false,NodeRepair=false
    - name: BATCH_MAX_DURATION
      value: 10s
    - name: BATCH_IDLE_DURATION
      value: 1s
    - name: VM_MEMORY_OVERHEAD_PERCENT
      value: "0.075"
    - name: RESERVED_ENIS
      value: "0"
```

**Comment by jonathan-innis** [comment]
> Are dev builds published? I could try capturing a profile using an image build from main.

Yes! You should be able to find the "release" GHA on main and then use that image URI to pull the image.

**Comment by kppullin** [comment]
> > Are dev builds published? I could try capturing a profile using an image build from main.
> 
> Yes! You should be able to find the "release" GHA on main and then use that image URI to pull the image.

Ah, found it - thank you!  Initial results look quite promising.  I'll follow up in a couple days to make sure what I'm seeing is accurate and things are working as intended.

**Comment by nantiferov** [comment]
> Have you enabled capacity reservation? 

@engedaam - nope, we don't have capacity reservation enabled.

> Can you share your karpenter deployment?

Sure, it's deployed from official Helm chart, yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 1.3.3
    helm.sh/chart: karpenter-1.3.3
    helm.toolkit.fluxcd.io/name: karpenter
    helm.toolkit.fluxcd.io/namespace: kube-system
  name: karpenter
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: karpenter
      app.kubernetes.io/name: karpenter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: karpenter
        app.kubernetes.io/name: karpenter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: DoesNotExist
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: karpenter
                app.kubernetes.io/name: karpenter
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: true
      containers:
      - env:
        - name: KUBERNETES_MIN_VERSION
          value: 1.19.0-0
        - name: KARPENTER_SERVICE
          value: karpenter
        - name: LOG_LEVEL
          value: info
        - name: LOG_OUTPUT_PATHS
          value: stdout
        - name: LOG_ERROR_OUTPUT_PATHS
          value: stderr
        - name: METRICS_PORT
          value: "8080"
        - name: HEALTH_PROBE_PORT
          value: "8081"
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: controller
              divisor: "0"
              resource: limits.memory
        - name: FEATURE_GATES
          value: ReservedCapacity=false,SpotToSpotConsolidation=false,NodeRepair=false
        - name: BATCH_MAX_DURATION
          value: 30s
        - name: BATCH_IDLE_DURATION
          value: 5s
        - name: CLUSTER_NAME
          value: cluster-name
        - name: VM_MEMORY_OVERHEAD_PERCENT
          value: "0.075"
        - name: INTERRUPTION_QUEUE
          value: interruption-queue-name
        - name: RESERVED_ENIS
          value: "0"
        image: public.ecr.aws/karpenter/controller:1.3.3@sha256:9920f14b8e302ff7a8a4154c7386acaf952009bc8f7d117c60f7a906b44d6281
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: controller
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        - containerPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 1700m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65532
      serviceAccount: karpenter
      serviceAccountName: karpenter
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: karpenter
            app.kubernetes.io/name: karpenter
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
```

**Comment by stijndehaes** [comment]
> Have you enabled capacity reservation?

@engedaam Like the rest we do not have capacity reservation enabled

> Can you share your karpenter deployment?

We use the helm chart:
```
controller:
  env:
  - name: ENABLE_PROFILING
    value: "true"
  metrics:
    port: 8000
settings:
  clusterName: "CLUSTER_NAME"
  clusterEndpoint: "CLUSTER_ENDPOINT"
  vmMemoryOverheadPercent: "0.0"
```

Remove all no relevant settings, only kept environment variables and settings values.
Nothing too special going on here
