### ISSUE TITLE
Node is running out of resources due to huge maxPods was set automatically

### ISSUE THREAD

**Issue by maxsxu** [aws/karpenter-provider-aws#7989]
### Description

**Observed Behavior**:

The selected instance type is m7a.4xlarge (16C64G), and the Node maxPod was set to **234** as shown below.
The behavior is new Pods keep been scheduled to that Node, and the Node become not ready eventually due to run out of cpu/memory.

```yaml
apiVersion: v1
kind: Node
status:
  allocatable:
    cpu: 15890m
    ephemeral-storage: "95491281146"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 61422956Ki
    pods: "234"
  capacity:
    cpu: "16"
    ephemeral-storage: 104779756Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 64422252Ki
    pods: "234"
```

and the AMI id is `ami-0195c0d495b6a0988`

**Expected Behavior**:

First It should not have so huge maxPods set, K8s's recommendation is 110 Pods,
second it should stop schedule new Pods to that Node.

**Reproduction Steps** (Please include YAML):

- EC2NodeClass

```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: spot
spec:
  amiSelectorTerms:
  - alias: al2023@v20250317
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 100Gi
      volumeType: gp3
    rootVolume: true
  metadataOptions:
    httpPutResponseHopLimit: 2
  role: xxx-ng-role
  securityGroupSelectorTerms:
  - tags:
      karpenter: "true"
  subnetSelectorTerms:
  - tags:
      karpenter: "true"
```

- NodePool

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot
spec:
  disruption:
    budgets:
    - nodes: "1"
    consolidateAfter: 1h
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        nodepool: spot
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: spot
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "5"
      - key: karpenter.k8s.aws/instance-cpu
        operator: Gt
        values:
        - "4"
      - key: karpenter.k8s.aws/instance-memory
        operator: Gt
        values:
        - "16384"
      taints:
      - effect: NoSchedule
        key: nodepool
        value: spot
```

My workloads are pretty small, the requests is 0.2C410Mi, and the limits is 1C4Gi.

**Versions**:
- Chart Version: 1.3.3
- Kubernetes Version (`kubectl version`): v1.31.6

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
