### ISSUE TITLE
Karpenter Not able to delete Empty Nodes

### ISSUE THREAD

**Issue by RamanujShastri** [aws/karpenter-provider-aws#8033]
### Description

We upgraded Karpenter from 0.37.7 to 1.3.3, after upgrading we are seeing that karpenter is not able to delete the node even when there are no pods running except Daemon Sets. We are facing this issue in production clusters due to which 60+ nodes are in cluster when these are empty
Sharing  the Nodepool configuration  as below
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  labels:
    argocd.argoproj.io/instance: karpenter-provisioners
  name: ai-eng-dedicated

spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 2400
    memory: 9600Gi
  template:
    metadata:
      labels:
        workload: dedicated
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: dedicated
      requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: NotIn
        values:
        - c1
        - cc1
        - cc2
        - cg1
        - cg2
        - cr1
        - g1
        - g2
        - hi1
        - hs2
        - m1
        - m2
        - m3
        - t1
        - f2
      - key: karpenter.k8s.aws/instance-family
        operator: NotIn
        values:
        - c1
        - cc1
        - cc2
        - cg1
        - cg2
        - cr1
        - g1
        - g2
        - hi1
        - hs2
        - m1
        - m2
        - m3
        - t1
        - f2
      - key: kubernetes.io/arch
        operator: NotIn
        values:
        - arm64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      taints:
      - effect: NoSchedule
        key: workload
        value: dedicated
```

**Observed Behavior**:
Karpenter Not able to delete Empty Nodes
**Expected Behavior**:
Karpenter Should able to delete Empty Nodes
**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 1.3.3
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
