### ISSUE TITLE
Drift reconciliation not treating selector terms as OR

### ISSUE THREAD

**Issue by jicowan** [aws/karpenter-provider-aws#8055]
### Description

**Observed Behavior**:
Karpenter will consider nodes as drifted when you add another AMI ID to the amiSelectorTerms block. 

**Expected Behavior**:
Karpenter should treat the addition of an AMI ID as an OR not an AND. 

**Reproduction Steps** (Please include YAML):
EC2NodeClass (v1)
```yaml
  amiFamily: AL2023
    amiSelectorTerms:
    - id: ami-007672b66bd72c80f
```
EC2NodeClass (v2)
``` yaml
   amiFamily: AL2023
    amiSelectorTerms:
    - id: ami-007672b66bd72c80f
    - id: ami-0d0c16662b0265526
```
Nodes provisioned from the AMI ending in 80f are immediately replaced with the new AMI. Nodes that were provisioned from 80f should continue running until that ID is removed from the amiSelectorTerms. 

**Versions**:
- Chart Version: 1.4.0
- Kubernetes Version (`kubectl version`): 1.32

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jicowan** [comment]
There may be an issue with this code, https://github.com/aws/karpenter-provider-aws/blob/f4fa759bea61e0550398971823cfd82862a134c1/pkg/cloudprovider/drift.go#L76-L96

**Comment by engedaam** [comment]
Today, Karpenter will check if a AMI is within the provided set of AMIs in the EC2NodeClass before considering drift: https://github.com/aws/karpenter-provider-aws/blob/f4fa759bea61e0550398971823cfd82862a134c1/pkg/cloudprovider/drift.go#L91-L92. Can you share your full nodeclass including the status? Today, Karpenter does check the latest AMI to use as provisioning nodes that both contain the same requirement. I think we are updating status to only provided the latest AMI: https://github.com/aws/karpenter-provider-aws/blob/f4fa759bea61e0550398971823cfd82862a134c1/pkg/providers/amifamily/ami.go#L184

**Comment by jicowan** [comment]
@engedaam I found the node class. I realize now that the Kubernetes versions are different. The AMI ending in 0f is for v1.32 where as 26 is for v1.30. Could that explain why all the nodes were immediately replaced? I didn't see anything in drift.go that would do that.  
```
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: ami-007672b66bd72c80f
    - id: ami-0d0c16662b0265526
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  role: ex-karpenter-mng
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ex-karpenter-mng
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ex-karpenter-mng
  tags:
    karpenter.sh/discovery: ex-karpenter-mng
```

And here is the status
```
status:
  amis:
    - id: ami-0d0c16662b0265526
      name: amazon-eks-node-al2023-x86_64-standard-1.32-v20250501
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
  conditions:
    - lastTransitionTime: '2025-05-06T19:31:34Z'
      message: ''
      observedGeneration: 16
      reason: SubnetsReady
      status: 'True'
      type: SubnetsReady
    - lastTransitionTime: '2025-05-06T19:31:34Z'
      message: ''
      observedGeneration: 16
      reason: SecurityGroupsReady
      status: 'True'
      type: SecurityGroupsReady
    - lastTransitionTime: '2025-05-06T19:31:34Z'
      message: ''
      observedGeneration: 16
      reason: InstanceProfileReady
      status: 'True'
      type: InstanceProfileReady
    - lastTransitionTime: '2025-05-08T18:50:33Z'
      message: ''
      observedGeneration: 16
      reason: AMIsReady
      status: 'True'
      type: AMIsReady
    - lastTransitionTime: '2025-05-08T18:50:34Z'
      message: ''
      observedGeneration: 16
      reason: ValidationSucceeded
      status: 'True'
      type: ValidationSucceeded
    - lastTransitionTime: '2025-05-08T18:56:05Z'
      message: ''
      observedGeneration: 16
      reason: Ready
      status: 'True'
      type: Ready
  instanceProfile: ex-karpenter-mng_4067990795380418201
  securityGroups:
    - id: sg-06d56cd8061da0e9b
      name: ex-karpenter-mng-node-20250506190409553300000003
  subnets:
    - id: subnet-016378f5b4cff8daa
      zone: us-west-2b
      zoneID: usw2-az1
    - id: subnet-063aa1e17fd850c58
      zone: us-west-2a
      zoneID: usw2-az2
    - id: subnet-0fdc0dbddcc1d236d
      zone: us-west-2c
      zoneID: usw2-az3
```
