### ISSUE TITLE
Karpenter still removing Nodes even expireAfter: Never

### ISSUE THREAD

**Issue by saar-win** [aws/karpenter-provider-aws#8058]
Hey, Using Karpenter 1.0.8.
I'm trying to avoid Node deletion. Here is my NodePoll manifest:
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  labels:
    argocd.argoproj.io/instance: karpenter-provisioners
  name: XXX-np
spec:
  disruption:
    budgets:
      - nodes: '0'
    consolidateAfter: Never
    consolidationPolicy: WhenEmpty
  template:
    metadata:
      annotations:
        karpenter.sh/do-not-disrupt: 'true'
      labels:
        loora.ai/capacity: XXX-np
        loora.ai/pool: XXX-np
        provisioner: XXX-np
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: XXX-np
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - r7a
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            - '4'
            - '8'
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - xlarge
            - 2xlarge
        - key: karpenter.k8s.aws/instance-generation
          operator: In
          values:
            - '7'
      taints:
        - effect: NoSchedule
          key: XXXX
          value: default
```
And this is the logs from Karpenter pods:
```
{"level":"DEBUG","time":"2025-05-10T10:05:48.729Z","logger":"controller","caller":"reconcile/reconcile.go:142","message":"deleting expired nodeclaim","commit":"a2875e3","controller":"nodeclaim.expiration","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"XXX-np-sxph8"},"namespace":"","name":"XXX-np-sxph8","reconcileID":"08162f67-5a50-41df-85b3-5397430e4a62"}
```
What can be the reason?
(I don't have the do-not-disrupt label on the pod itself if it matters)
Thanks!
