### ISSUE TITLE
Duplicate NodeClaim Creation When Using Kyverno ClusterPolicy

### ISSUE THREAD

**Issue by iamhansko** [aws/karpenter-provider-aws#8066]
### Description

**Observed Behavior**: When using **Karpenter NodePool** to add **Taints** and **Kyverno ClusterPolicy** to add **Tolerations**, Karpenter appears to recognize **the same pod as "provisionable" twice-resulting** (duplicate "`found provisionable pod(s)`" events for a single pod). This leads to unnecessary NodeClaim and Node being created. 

If Tolerations are specified directly in the Deployment manifest(YAML, replicas:1), this duplication does not occur. However, when Tolerations are added by Kyverno ClusterPolicy (mutate.patchStrategicMerge), duplicate events are observed. It seems that the Kyverno MutatingWebhook causes the existing pod to be patched, and Karpenter treats the pod before and after mutation as two distinct provisionable pods, even though they are actually the same resource.

**Expected Behavior**: Karpenter should create a single NodeClaim for a single Pending Pod.

**Reproduction Steps** (Please include YAML):
1. Install Karpenter (v1.4.0)
2. Install Kyverno (v1.13.0)
    `kubectl create -f https://github.com/kyverno/kyverno/releases/download/v1.13.0/install.yaml`
3. Create ClusterPolicy (Tolerations)
    `kubectl apply -f clusterpolicy.yaml`
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    policies.kyverno.io/category: Karpenter, EKS Best Practices
  name: pod-policy
spec:
  admission: true
  background: true
  emitWarning: false
  rules:
  - match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - default
    mutate:
      patchStrategicMerge:
        spec:
          nodeSelector:
            nodepool: spot-nodepool
          tolerations:
          - effect: NoSchedule
            key: nodepool/spot
            operator: Exists
    name: pod-toleration-rule
```
4. Create Deployment(1Pod, Pending at First)
    `kubectl apply -f deployment.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.9
```
5. Create EC2NodeClass & NodePool (Taints)
    `kubectl apply -f nodepool.yaml`
```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: spot-class
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: # Add Value
  subnetSelectorTerms:
    - id: # Add Value
    - id: # Add Value
  securityGroupSelectorTerms:
    - tags:
        Name: # Add Value
  role: # Add Value
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-nodepool
spec:
  template:
    metadata:
      labels:
        nodepool: spot-nodepool
    spec:
      taints:
      - key: nodepool/spot
        effect: NoSchedule
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["small","medium", "large"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: spot-class
```
6. Karpenter Creates 2 NodeClaims(Nodes) for a single Pod ("`found provisionable pod(s)`" x2)

```
(Karpenter Controller Pod Log)
{"level":"INFO","time":"2025-05-07T21:15:58.029Z","logger":"controller","message":"found provisionable pod(s)","commit":"0871602","controller":"provisioner","namespace":"","name":"","reconcileID":"6c0b5f41-8a12-4394-b01e-7a13b2502eda","Pods":"default/inflate-59d5649b5b-9s5fc","duration":"112.683297ms"}
{"level":"INFO","time":"2025-05-07T21:15:58.029Z","logger":"controller","message":"computed new nodeclaim(s) to fit pod(s)","commit":"0871602","controller":"provisioner","namespace":"","name":"","reconcileID":"6c0b5f41-8a12-4394-b01e-7a13b2502eda","nodeclaims":1,"pods":1}
{"level":"INFO","time":"2025-05-07T21:15:58.041Z","logger":"controller","message":"created nodeclaim","commit":"0871602","controller":"provisioner","namespace":"","name":"","reconcileID":"6c0b5f41-8a12-4394-b01e-7a13b2502eda","NodePool":{"name":"spot-nodepool"},"NodeClaim":{"name":"spot-nodepool-9xbj5"},"requests":{"cpu":"150m","pods":"3"},"instance-types":"c1.medium, c3.large, c4.large, c5.large, c5a.large and 55 other(s)"}
{"level":"INFO","time":"2025-05-07T21:16:01.730Z","logger":"controller","message":"launched nodeclaim","commit":"0871602","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"spot-nodepool-9xbj5"},"namespace":"","name":"spot-nodepool-9xbj5","reconcileID":"d2da9ab4-ca2f-418c-9861-45f30d2f36f9","provider-id":"aws:///us-east-1b/i-0fb26272cfa0bb076","instance-type":"t3.small","zone":"us-east-1b","capacity-type":"spot","allocatable":{"cpu":"1930m","ephemeral-storage":"17Gi","memory":"1493356Ki","pods":"8"}}
{"level":"INFO","time":"2025-05-07T21:16:25.878Z","logger":"controller","message":"registered nodeclaim","commit":"0871602","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"spot-nodepool-9xbj5"},"namespace":"","name":"spot-nodepool-9xbj5","reconcileID":"b265f555-17c3-40aa-ab9e-233aa4ebc6b5","provider-id":"aws:///us-east-1b/i-0fb26272cfa0bb076","Node":{"name":"ip-10-0-144-109.ec2.internal"}}
{"level":"INFO","time":"2025-05-07T21:16:38.011Z","logger":"controller","message":"found provisionable pod(s)","commit":"0871602","controller":"provisioner","namespace":"","name":"","reconcileID":"03d369af-952d-4b8b-b0f4-19895e486ee0","Pods":"default/inflate-59d5649b5b-9s5fc","duration":"92.167354ms"}
{"level":"INFO","time":"2025-05-07T21:16:38.012Z","logger":"controller","message":"computed new nodeclaim(s) to fit pod(s)","commit":"0871602","controller":"provisioner","namespace":"","name":"","reconcileID":"03d369af-952d-4b8b-b0f4-19895e486ee0","nodeclaims":1,"pods":1}
{"level":"INFO","time":"2025-05-07T21:16:38.025Z","logger":"controller","message":"created nodeclaim","commit":"0871602","controller":"provisioner","namespace":"","name":"","reconcileID":"03d369af-952d-4b8b-b0f4-19895e486ee0","NodePool":{"name":"spot-nodepool"},"NodeClaim":{"name":"spot-nodepool-c9fk2"},"requests":{"cpu":"150m","pods":"3"},"instance-types":"c1.medium, c3.large, c4.large, c5.large, c5a.large and 55 other(s)"}
{"level":"INFO","time":"2025-05-07T21:16:40.430Z","logger":"controller","message":"launched nodeclaim","commit":"0871602","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"spot-nodepool-c9fk2"},"namespace":"","name":"spot-nodepool-c9fk2","reconcileID":"831841c7-683c-4abb-b41e-494b39045d00","provider-id":"aws:///us-east-1b/i-0114e6239f1ca2588","instance-type":"t3.small","zone":"us-east-1b","capacity-type":"spot","allocatable":{"cpu":"1930m","ephemeral-storage":"17Gi","memory":"1493356Ki","pods":"8"}}
{"level":"INFO","time":"2025-05-07T21:16:44.861Z","logger":"controller","message":"initialized nodeclaim","commit":"0871602","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"spot-nodepool-9xbj5"},"namespace":"","name":"spot-nodepool-9xbj5","reconcileID":"6383c9fd-0525-4bcd-80c5-f55924fb9574","provider-id":"aws:///us-east-1b/i-0fb26272cfa0bb076","Node":{"name":"ip-10-0-144-109.ec2.internal"},"allocatable":{"cpu":"1930m","ephemeral-storage":"18181869946","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"1459568Ki","pods":"8"}}
{"level":"INFO","time":"2025-05-07T21:17:02.076Z","logger":"controller","message":"registered nodeclaim","commit":"0871602","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"spot-nodepool-c9fk2"},"namespace":"","name":"spot-nodepool-c9fk2","reconcileID":"f8e3a655-236a-475a-b988-f9c4103ba29f","provider-id":"aws:///us-east-1b/i-0114e6239f1ca2588","Node":{"name":"ip-10-0-154-228.ec2.internal"}}
{"level":"INFO","time":"2025-05-07T21:17:21.670Z","logger":"controller","message":"initialized nodeclaim","commit":"0871602","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"spot-nodepool-c9fk2"},"namespace":"","name":"spot-nodepool-c9fk2","reconcileID":"2773fc88-8732-44b9-a866-ab4f1a12e934","provider-id":"aws:///us-east-1b/i-0114e6239f1ca2588","Node":{"name":"ip-10-0-154-228.ec2.internal"},"allocatable":{"cpu":"1930m","ephemeral-storage":"18181869946","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"1459568Ki","pods":"8"}}
{"level":"INFO","time":"2025-05-07T21:17:41.487Z","logger":"controller","message":"disrupting node(s)","commit":"0871602","controller":"disruption","namespace":"","name":"","reconcileID":"fff2eb1c-e082-44c0-87e6-d4006d7da623","command-id":"89bae48d-ecd5-4108-b791-76f08ebff5e2","reason":"empty","decision":"delete","disrupted-node-count":1,"replacement-node-count":0,"pod-count":0,"disrupted-nodes":[{"Node":{"name":"ip-10-0-154-228.ec2.internal"},"NodeClaim":{"name":"spot-nodepool-c9fk2"},"capacity-type":"spot","instance-type":"t3.small"}],"replacement-nodes":[]}
{"level":"INFO","time":"2025-05-07T21:17:41.947Z","logger":"controller","message":"tainted node","commit":"0871602","controller":"node.termination","controllerGroup":"","controllerKind":"Node","Node":{"name":"ip-10-0-154-228.ec2.internal"},"namespace":"","name":"ip-10-0-154-228.ec2.internal","reconcileID":"c2b34d4d-f348-41a4-bad0-01d63f6ce56d","NodeClaim":{"name":"spot-nodepool-c9fk2"},"taint.Key":"karpenter.sh/disrupted","taint.Value":"","taint.Effect":"NoSchedule"}
{"level":"INFO","time":"2025-05-07T21:18:13.948Z","logger":"controller","message":"deleted node","commit":"0871602","controller":"node.termination","controllerGroup":"","controllerKind":"Node","Node":{"name":"ip-10-0-154-228.ec2.internal"},"namespace":"","name":"ip-10-0-154-228.ec2.internal","reconcileID":"6c7422c2-490f-4947-a558-6bc39dd6ec3d","NodeClaim":{"name":"spot-nodepool-c9fk2"}}
{"level":"INFO","time":"2025-05-07T21:18:14.223Z","logger":"controller","message":"deleted nodeclaim","commit":"0871602","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"spot-nodepool-c9fk2"},"namespace":"","name":"spot-nodepool-c9fk2","reconcileID":"7a7ef4eb-748f-4ff1-a07e-53650c7aa896","provider-id":"aws:///us-east-1b/i-0114e6239f1ca2588","Node":{"name":"ip-10-0-154-228.ec2.internal"}}
```

**Versions**:
- Chart Version: v1.4.0
- Kubernetes Version (`kubectl version`): v1.31

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
