### ISSUE TITLE
cannot get GPU scaling to work for anything other than 0->1

### ISSUE THREAD

**Issue by pfrydids** [aws/karpenter-provider-aws#8068]
### Description

**Observed Behavior**:

When I create more than one pod requiring GPU nodes, the GPU node pool only creates one GPU node and the second pod remains in pending state.

The pod events show messages like

```
  Warning  FailedScheduling  23m (x54 over 4h48m)    default-scheduler  0/3 nodes are available: 3 Insufficient nvidia.com/gpu. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod.
  Warning  FailedScheduling  3m50s (x58 over 4h48m)  karpenter          Failed to schedule pod, incompatible with nodepool "spot-pool", daemonset overhead={"cpu":"1566m","memory":"930Mi","pods":"11"}, no instance type has enough resources, requirements=eks.amazonaws.com/instance-category In [c m t], eks.amazonaws.com/nodeclass In [spot-default], karpenter.sh/capacity-type In [spot], karpenter.sh/nodepool In [spot-pool], kubernetes.io/arch In [amd64], resources={"cpu":"1566m","memory":"930Mi","nvidia.com/gpu":"1","pods":"12"}; all available instance types exceed limits for nodepool (NodePool=gpu-nodepool)
```

**Expected Behavior**:

Karpenter scales up the GPU nodepool to more than one instance so that the second pod can run concurrently.

**Reproduction Steps** (Please include YAML):
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  generation: 4
  name: gpu-nodepool
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 10
  template:
    metadata:
      labels:
        nvidia.com/gpu: "true"
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: gpu-nodeclass
      requirements:
      - key: eks.amazonaws.com/instance-family
        operator: In
        values:
        - g4dn
        - g5
        - g6
        - g6e
      - key: eks.amazonaws.com/instance-size
        operator: In
        values:
        - xlarge
        - 2xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      taints:
      - effect: NoSchedule
        key: nvidia.com/gpu
```
the pod is similar to this:
```
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
...
  tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
```

**Versions**:
EKS automode

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
