### ISSUE TITLE
Karpenter on EKS fails to remove 'uninitialized' taint from nodes

### ISSUE THREAD

**Issue by ian-forrest** [aws/karpenter-provider-aws#8106]
### Description

**Observed Behavior**:
Karpenter provisions a new node, and it successfully joins the EKS cluster. However, the taint "node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule" is not removed, preventing the node from being scheduled with pods from deployments. As a result, the node only runs the default add-on pods (e.g., kube-proxy, VPC CNI) but does not receive workload pods.

If the taint is manually removed from the node, everything works as expected, and the pods are scheduled without issues.

**Expected Behavior**:
When Karpenter provisions a new node and it successfully joins the EKS cluster, the taint "node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule" should be automatically removed once the node is fully initialized. This would allow pods from deployments to be scheduled on the node alongside the default add-on pods (e.g., kube-proxy, VPC CNI).

Nodes should not require manual intervention to remove the taint, and workload pods should be scheduled as soon as the node becomes available, ensuring no pods remain in a Pending state due to this issue.

**Reproduction Steps** (Please include YAML):
node class yaml:
```
apiVersion: {{ .Values.nodePoolApiVersion }}
kind: NodePool
metadata:
  name: {{ .Values.clusterName }}-x86-64-node-pool
spec:
  template:
    metadata:
      labels:
        role: {{ .Values.clusterName }}-node-pool
        nodeGroup: karpenter-nodes
    spec:
      expireAfter: 72h
      terminationGracePeriod: 2h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.clusterName }}-x86-64-node-class
      taints:
        - key: x.mycase.com/karpenter-x86-64-nodes
          effect: NoSchedule
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: [ "m" ]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: [ "m7a" ]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: [ "2", "4", "8", "16" ]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: [ "nitro" ]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: [ "2" ]
        - key: "kubernetes.io/arch"
          operator: In
          values: [ "amd64" ]
        - key: kubernetes.io/os
          operator: In
          values: [ "linux" ]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "on-demand" ]

  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 0s
    budgets:
      - nodes: "0"
        schedule: "0 10 * * mon-fri"
        duration: 14h0m0s

  limits:
    cpu: 1k
    memory: 1200Gi
  weight: 10
```

values.yaml:
```
clusterName: ''
securityGroupSelectorTerms: []
subnetSelectorTerms: []
karpenterNodeRole: ''
tags: {}
nodeClassApiVersion: karpenter.k8s.aws/v1beta1
nodePoolApiVersion: karpenter.sh/v1beta1
arm64AmiSelectorTerms: []
x86AmiSelectorTerms: []
```

discussed in another issue: https://github.com/aws/karpenter-provider-aws/issues/7426

**Versions**:
- Chart Version: v1.0.9
- Kubernetes Version (`kubectl version`): EKS v1.31

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
