### ISSUE TITLE
Validate RunInstancesAuthCheck Fails For ~10 Minutes In Ec2NodeClaim

### ISSUE THREAD

**Issue by sschafftc1** [aws/karpenter-provider-aws#8114]
### Description

**Observed Behavior**:
We are seeing an issue where immediately after attaching a karpenter pass role, when attempting to create an EC2 node class, the node class remains in a NotReady state for ten minutes before becoming ready. The same  configuration works correctly in karpenter `1.3.2`, this issue only appears once upgraded to `1.4.0`.

These are the events in the EC2 node class:
| Type                     | Reason                | Age  | From       | Message                                                                                                          |
|--------------------------|-----------------------|------|------------|------------------------------------------------------------------------------------------------------------------|
| Normal                   | AMIsReady            | 10m  | karpenter  | Status condition transitioned, Type: AMIsReady, Status: Unknown -> True, Reason: AMIsReady                       |
| Normal                   | SubnetsReady         | 10m  | karpenter  | Status condition transitioned, Type: SubnetsReady, Status: Unknown -> True, Reason: SubnetsReady                 |
| Normal                   | SecurityGroupsReady  | 10m  | karpenter  | Status condition transitioned, Type: SecurityGroupsReady, Status: Unknown -> True, Reason: SecurityGroupsReady   |
| Normal                   | InstanceProfileReady | 10m  | karpenter  | Status condition transitioned, Type: InstanceProfileReady, Status: Unknown -> True, Reason: InstanceProfileReady |
| Normal                   | ValidationSucceeded  | 10m  | karpenter  | Status condition transitioned, Type: ValidationSucceeded, Status: Unknown -> False, Reason: RunInstancesAuthCheck, Message: Controller isn't authorized to call ec2:RunInstances |
| Normal                   | Ready                | 10m  | karpenter  | Status condition transitioned, Type: Ready, Status: Unknown -> False, Reason: UnhealthyDependents, Message: ValidationSucceeded=False |
| Normal                   | ValidationSucceeded  | 44s  | karpenter  | Status condition transitioned, Type: ValidationSucceeded, Status: False -> True, Reason: ValidationSucceeded     |
| Normal                   | Ready                | 44s  | karpenter  | Status condition transitioned, Type: Ready, Status: False -> True, Reason: Ready                                 |

**Expected Behavior**:
The expected behavior is for the EC2 node class to reach a ready state in ~2 minutes as it does in the `1.3.2` version of karpenter.

**Reproduction Steps** (Please include YAML):
EC2 node class YAML:
```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  annotations:
    kubernetes.io/description: OneKube node class
  name: onekube-node-class
spec:
  amiFamily: AL2
%{ if amiId != ""}
  amiSelectorTerms:
  - id: ${amiId}
%{ endif }
  detailedMonitoring: true
%{ if instanceProfile != "" }
  instanceProfile: ${instanceProfile}
%{ endif }
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
```

**Versions**:
- Chart Version: 1.4.0
- Kubernetes Version (`kubectl version`): 1.31

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
