### ISSUE TITLE
ec2nodeclass with bottlerocket userdata for bootstrap-containers makes nodes stuck

### ISSUE THREAD

**Issue by benben** [aws/karpenter-provider-aws#8131]
### Description

**Observed Behavior**:

new nodes do not come up with this userData:

```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: example
spec:
  amiSelectorTerms:
  - alias: bottlerocket@v1.30.0
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  userData: |
    [settings.bootstrap-containers.myscript]
    mode = "once"
    user-data = "IyEvdXNyL2Jpbi9lbnYgc2gKc2V0IC1ldW8gcGlwZWZhaWwKZWNobyAiVXNlci1kYXRhIHNjcmlwdCBleGVjdXRlZC4iCg=="
```

user-data script is base64 of

```
#!/usr/bin/env sh
set -euo pipefail
echo "User-data script executed."
```

karpenter logs

```
{"level":"INFO","time":"2025-05-22T09:09:05.334Z","logger":"controller","message":"created nodeclaim","commit":"1c39126","controller":"disruption","namespace":"","name":"","reconcileID":"276c1c9b-8cd6-43d4-8971-2be74109ff67","NodePool":{"name":"runner-ng-arm"},"NodeClaim":{"name":"runner-ng-arm-f7m5k"},"requests":{"cpu":"1753m","memory":"7627Mi","pods":"6"},"instance-types":"c6g.2xlarge, c6g.4xlarge, c6gd.2xlarge, c6gd.4xlarge, c6gn.2xlarge and 42 other(s)"}
{"level":"INFO","time":"2025-05-22T09:09:07.719Z","logger":"controller","message":"launched nodeclaim","commit":"1c39126","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"runner-ng-arm-f7m5k"},"namespace":"","name":"runner-ng-arm-f7m5k","reconcileID":"d877e106-8ee1-4a33-bf0f-b6a17f0f3722","provider-id":"aws:///eu-west-2b/i-00a02edc503ae1818","instance-type":"is4gen.large","zone":"eu-west-2b","capacity-type":"spot","allocatable":{"cpu":"1930m","ephemeral-storage":"17Gi","memory":"10633Mi","pods":"29","vpc.amazonaws.com/pod-eni":"9"}}
```
nodeclaim looks like this

```
$ k get nodeclaim
NAME                  TYPE              CAPACITY   ZONE         NODE                                         READY     AGE
runner-ng-arm-f7m5k   is4gen.large      spot       eu-west-2b                                                Unknown   10m
```

**Expected Behavior**:

I expect the node to come up as normal and execute the user-data script.

**Reproduction Steps** (Please include YAML):

use the YAML above. when removing `[settings.bootstrap-containers.myscript]` from the `userData` and using other fields there, all works fine.

**Versions**:
- Chart Version:

```
1.3.2
```

- Kubernetes Version (`kubectl version`):

```
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.7-eks-bcf3d70
```

See also https://github.com/bottlerocket-os/bottlerocket-bootstrap-container

ref https://github.com/kubernetes-sigs/karpenter/issues/2242
