### ISSUE TITLE
Support VolumeInitializationRate of creating EBS volume

### ISSUE THREAD

**Issue by yubingjiaocn** [aws/karpenter-provider-aws#8154]
### Description

**What problem are you trying to solve?**
AWS launched [Provisioned Rate for Volume Initialization](https://aws.amazon.com/about-aws/whats-new/2025/05/ebs-provisioned-rate-volume-initialization/?nc1=h_ls) for creating EBS volumes from snapshot. This feature can be enabled in launch template. Karpenter can support this feature by adding this parameter in generated launch template.

**How important is this feature to you?**

When baked container image or large-sized asset to EBS snapshot, using Provisioned Rate for Volume Initialization can provide a stable and faster speed for volume initialize. 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rlanhellas** [comment]
@engedaam  may you assign it to me ? I'd like to work on this.

**Comment by rlanhellas** [comment]
@engedaam may you assign this to me ? would like to work on this

**Comment by rlanhellas** [comment]
@yubingjiaocn , this feature already exist. Here is how to use it 

```
  blockDeviceMappings:
    - deviceName: "/dev/sdc"
      ebs:
        volumeSize: 20Gi
        volumeType: "gp3"
        deleteOnTermination: true
        volumeInitializationRate: 120 # 120 MiB/s
        snapshotID: "snap-0ff7465309a2e6bc7"
```

Just tested it on real environment and EBS was created with correct rate:

<img width="265" height="337" alt="Image" src="https://github.com/user-attachments/assets/185e0cb0-bb22-4380-824c-3dccacd09c76" />
