### ISSUE TITLE
Karpenter killing pod immediately after receiving a spot interruption message

### ISSUE THREAD

**Issue by ArnaldoMoralesSirt** [aws/karpenter-provider-aws#8160]
### Description

**Observed Behavior**: Karpenter is killing pods just after getting the spot interrption message, despite of speciying grace periods everywhere.

**Expected Behavior**: Karpenter should not perform a Forceful Termination on pods.
Deployment YAML:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snow-production
    app.kubernetes.io/managed-by: Helm
  name: snow-production
  namespace: snow
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: snow-production
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: snow-production
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values:
                - snow
      containers:
      - image: ...........................
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                echo "PreStop hook called at $(date)" > /proc/1/fd/1
                sleep 100
        name: snow-production
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 8Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 100
      tolerations:
      - effect: NoSchedule
        key: workload/snow
        operator: Exists
```

Nodepool YAML:

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: snow
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 50
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "3"
      taints:
      - effect: NoSchedule
        key: workload/snow
      terminationGracePeriod: 10m
  weight: 10
```

**Reproduction Steps** (Please include YAML): Just wait for a spot interruption message. Running a kubectl drain works as expected and the pods do not get killed immediately.

**Versions**: v1.32.5
- Chart Version: 1.5.0
- Kubernetes Version (`kubectl version`): 1.32

**Logs**

```
default                    43m         Normal    SpotRebalanceRecommendation      nodeclaim/snow-dlfhm                                       Spot rebalance recommendation was triggered
default                    43m         Warning   TerminatingOnInterruption        node/ip-172-31-23-229.eu-west-1.compute.internal           Interruption triggered termination for the Node
default                    43m         Warning   TerminationGracePeriodExpiring   nodeclaim/snow-dlfhm                                       All pods will be deleted by 2025-06-04T09:42:10Z
default                    43m         Warning   TerminatingOnInterruption        nodeclaim/snow-dlfhm                                       Interruption triggered termination for the NodeClaim
default                    43m         Warning   SpotInterrupted                  nodeclaim/snow-dlfhm                                       Spot interruption warning was triggered
default                    43m         Warning   SpotInterrupted                  node/ip-172-31-23-229.eu-west-1.compute.internal           Spot interruption warning was triggered
default                    43m         Normal    SpotRebalanceRecommendation      node/ip-172-31-23-229.eu-west-1.compute.internal           Spot rebalance recommendation was triggered
default                    43m         Warning   FailedDraining                   node/ip-172-31-23-229.eu-west-1.compute.internal           Failed to drain node, 2 pods are waiting to be evicted
snow                       43m         Normal    Evicted                          pod/snow-production-5c67bc54d-tcrmn                        Evicted pod: Forceful Termination
snow                       43m         Normal    Killing                          pod/snow-production-5c67bc54d-tcrmn                        Stopping container snow-production
snow                       43m         Normal    SuccessfulCreate                 replicaset/snow-production-5c67bc54d                       Created pod: snow-production-5c67bc54d-n82vj
snow                       43m         Normal    Nominated                        pod/snow-production-5c67bc54d-n82vj                        Pod should schedule on: nodeclaim/snow-86tms
```
