### ISSUE TITLE
EC2NodeClass fails with: "ec2:RunInstances [...] explicit deny in a service control policy"

### ISSUE THREAD

**Issue by elouanKeryell-Even** [aws/karpenter-provider-aws#8190]
### Description

**TL;DR : karpenter v0.30 used to make calls to ec2:runInstances through AWS service `ec2fleet.amazonaws.com`, now karpenter v1.5 makes the call himself directly, and it gets denied by a SCP policy from our org. We are looking for tips/workarounds to make our karpenter v1.5 install compliant with our org SCP.**

---

**Observed Behavior**:

We are currently upgrading Karpenter from v0.30 to v1.5

Our company has an AWS SCP (Service Control Policy) which denies calls to  `ec2:runInstances`, except when it's called by an AWS service.

Our AWSNodeTemplates worked fine in v0.30, but in v1.5 our EC2NodeClass fails with the following `status.condition`:

```yaml
status:
  conditions:
    - lastTransitionTime: "2025-06-16T12:27:16Z"
      message: Controller isn't authorized to call ec2:RunInstances
      observedGeneration: 1
      reason: RunInstancesAuthCheckFailed
      status: "False"
      type: ValidationSucceeded
```

In AWS Cloud Trail we see the associated error event, with the following message:

> "errorMessage": "You are not authorized to perform this operation. User: arn:aws:sts::xxx:assumed-role/xxx-karpenter-controller-iam-role/xxx is not authorized to perform: ec2:RunInstances on resource: arn:aws:ec2:eu-west-1::image/ami-0a915a467a87d1c66 with an explicit deny in a service control policy"

The key difference we noticed between the runInstances call in v0.30 (working) versus v1.5 (failing) is, in v0.30 the call was made by `ec2fleet.amazonaws.com`, while in v1.5 the call is made directly by the Karpenter Controller inside our EKS cluster.

---

v0.30, extract from the Cloud Trail event for the runInstances call:

```json
{
  "userIdentity": {
    "invokedBy": "ec2fleet.amazonaws.com"
  },
  "sourceIPAddress": "ec2fleet.amazonaws.com",
  "userAgent": "ec2fleet.amazonaws.com",
  "requestParameters": {
    "clientToken": "fleet-xxx",
  }
}
```

---

v1.5, extract from the Cloud Trail event for the runInstances call:

```json
{
    "sourceIPAddress": "x.x.x.x",
    "userAgent": "aws-sdk-go-v2/1.36.3 ua/2.1 os/linux lang/go#1.24.2 md/GOOS#linux md/GOARCH#amd64 api/ec2#1.215.0 karpenter.sh-1.5.0 m/h",
  "requestParameters": {
        "clientToken": "xxx"
  }
}
```

We can see v1.5 is missing the `userIdentity.invokedBy` field.

---

**Question:**

Does anyone have encountered the same issue?

Would you have a tip or a workaround to continue complying to our org SCP policy, which denies calls to runInstance not made by an AWS Service?

---

**Full files:**

<details>

<summary>EC2NodeClass</summary>

```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
status:
  amis:
    - id: ami-0a915a467a87d1c66
      name: amazon-eks-node-1.27-v20250610
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
  conditions:
    - lastTransitionTime: "2025-06-16T12:27:15Z"
      message: ""
      observedGeneration: 1
      reason: AMIsReady
      status: "True"
      type: AMIsReady
    - lastTransitionTime: "2025-06-16T12:27:15Z"
      message: ""
      observedGeneration: 1
      reason: SubnetsReady
      status: "True"
      type: SubnetsReady
    - lastTransitionTime: "2025-06-16T12:27:15Z"
      message: ""
      observedGeneration: 1
      reason: SecurityGroupsReady
      status: "True"
      type: SecurityGroupsReady
    - lastTransitionTime: "2025-06-16T12:27:15Z"
      message: ""
      observedGeneration: 1
      reason: InstanceProfileReady
      status: "True"
      type: InstanceProfileReady
    - lastTransitionTime: "2025-06-16T12:27:16Z"
      message: Controller isn't authorized to call ec2:RunInstances
      observedGeneration: 1
      reason: RunInstancesAuthCheckFailed
      status: "False"
      type: ValidationSucceeded
    - lastTransitionTime: "2025-06-16T12:27:16Z"
      message: ValidationSucceeded=False
      observedGeneration: 1
      reason: UnhealthyDependents
      status: "False"
      type: Ready
  instanceProfile: terraform-xxx-xxx-1-node
  securityGroups:
    - id: sg-xxx
      name: xxx-xxx-1-eks-workers-sg
  subnets:
    - id: xxx
      zone: eu-west-1a
      zoneID: euw1-az1
    - id: subnet-xxx
      zone: eu-west-1b
      zoneID: euw1-az2
    - id: subnet-xxx
      zone: eu-west-1c
      zoneID: euw1-az3
spec:
  amiFamily: AL2
  amiSelectorTerms:
    - name: amazon-eks-node-1.27-*
      owner: self
    - name: amazon-eks-node-1.27-*
      owner: amazon
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        encrypted: true
        kmsKeyID: arn:aws:kms:eu-west-1:xxx:alias/xxx-ec2-cmk
        volumeSize: 20Gi
        volumeType: gp3
  instanceProfile: terraform-xxx-xxx-1-node
  kubelet:
    maxPods: 110
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  securityGroupSelectorTerms:
    - id: sg-xxx
  subnetSelectorTerms:
    - id: xxx
    - id: subnet-xxx
    - id: subnet-xxx
```
</details>

<details>

<summary>Cloud Trail event for call to runInstance in karpenter v1.5 (error)</summary>

```json
{
    "eventVersion": "1.10",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "xxx",
        "arn": "arn:aws:sts::xxx:assumed-role/xxx-xxx-xxx-xxx-1-karpenter-controller-iam-role/xxx",
        "accountId": "xxx",
        "accessKeyId": "xxx",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "xxx",
                "arn": "arn:aws:iam::xxx:role/xxx-xxx-xxx-xxx-1-karpenter-controller-iam-role",
                "accountId": "xxx",
                "userName": "xxx-xxx-xxx-xxx-1-karpenter-controller-iam-role"
            },
            "webIdFederationData": {
                "federatedProvider": "arn:aws:iam::xxx:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/xxx",
                "attributes": { }
            },
            "attributes": {
                "creationDate": "2025-06-16T12:27:13Z",
                "mfaAuthenticated": "false"
            }
        }
    },
    "eventTime": "2025-06-16T12:27:16Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "RunInstances",
    "awsRegion": "eu-west-1",
    "sourceIPAddress": "x.x.x.x",
    "userAgent": "aws-sdk-go-v2/1.36.3 ua/2.1 os/linux lang/go#1.24.2 md/GOOS#linux md/GOARCH#amd64 api/ec2#1.215.0 karpenter.sh-1.5.0 m/h",
    "errorCode": "Client.UnauthorizedOperation",
    "errorMessage": "You are not authorized to perform this operation. User: arn:aws:sts::xxx:assumed-role/xxx-xxx-xxx-xxx-1-karpenter-controller-iam-role/xxx is not authorized to perform: ec2:RunInstances on resource: arn:aws:ec2:eu-west-1::image/ami-0a915a467a87d1c66 with an explicit deny in a service control policy. Encoded authorization failure message: xxx...",
    "requestParameters": {
        "instancesSet": {
            "items": [
                {
                    "imageId": "ami-0a915a467a87d1c66",
                    "minCount": 1,
                    "maxCount": 1
                }
            ]
        },
        "userData": "<sensitiveDataRemoved>",
        "instanceType": "t3.medium",
        "blockDeviceMapping": {
            "items": [
                {
                    "deviceName": "/dev/xvda",
                    "ebs": {
                        "volumeSize": 20,
                        "deleteOnTermination": true,
                        "volumeType": "gp3",
                        "encrypted": true,
                        "kmsKeyId": "arn:aws:kms:eu-west-1:xxx:alias/xxx-ec2-cmk"
                    }
                }
            ]
        },
        "monitoring": {
            "enabled": false
        },
        "disableApiTermination": false,
        "disableApiStop": false,
        "clientToken": "xxx",
        "networkInterfaceSet": {
            "items": [
                {
                    "deviceIndex": 0,
                    "subnetId": "xxx",
                    "groupSet": {
                        "items": [
                            {
                                "groupId": "sg-xxx"
                            }
                        ]
                    }
                }
            ]
        },
        "iamInstanceProfile": {
            "name": "terraform-xxx-xxx-1-node"
        },
        "tagSpecificationSet": {
            "items": [
                {
                    "resourceType": "network-interface",
                    "tags": [ "xxx"
                    ]
                },
                {
                    "resourceType": "instance",
                    "tags": [ "xxx"
                    ]
                },
                {
                    "resourceType": "volume",
                    "tags": [ "xxx"
                    ]
                }
            ]
        },
        "metadataOptions": {
            "httpTokens": "required",
            "httpPutResponseHopLimit": 1,
            "httpEndpoint": "enabled",
            "httpProtocolIpv6": "disabled",
            "instanceMetadataTags": "disabled"
        }
    },
    "responseElements": null,
    "requestID": "xxx",
    "eventID": "xxx",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "xxx",
    "sharedEventID": "xxx",
    "vpcEndpointId": "vpce-xxx",
    "vpcEndpointAccountId": "xxx",
    "eventCategory": "Management",
    "tlsDetails": {
        "tlsVersion": "TLSv1.3",
        "cipherSuite": "TLS_AES_128_GCM_SHA256",
        "clientProvidedHostHeader": "ec2.eu-west-1.amazonaws.com"
    }
}
```

</details>

<details>

<summary>Cloud Trail event for call to runInstance in karpenter v0.30 (success)</summary>

```json
{
  "eventVersion": "1.10",
  "userIdentity": {
    "type": "AssumedRole",
    "principalId": "xxx",
    "arn": "arn:aws:sts::xxx:assumed-role/xxx-xxx-xxx-xxx-1-karpenter-controller-iam-role/xxx",
    "accountId": "xxx",
    "sessionContext": {
      "sessionIssuer": {
        "type": "Role",
        "principalId": "xxx",
        "arn": "arn:aws:iam::xxx:role/xxx-xxx-xxx-xxx-1-karpenter-controller-iam-role",
        "accountId": "xxx",
        "userName": "xxx-xxx-xxx-xxx-1-karpenter-controller-iam-role"
      },
      "webIdFederationData": {
        "federatedProvider": "arn:aws:iam::xxx:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/xxx",
        "attributes": { }
      },
      "attributes": {
        "creationDate": "2025-06-16T12:11:13Z",
        "mfaAuthenticated": "false"
      }
    },
    "invokedBy": "ec2fleet.amazonaws.com"
  },
  "eventTime": "2025-06-16T12:35:03Z",
  "eventSource": "ec2.amazonaws.com",
  "eventName": "RunInstances",
  "awsRegion": "eu-west-1",
  "sourceIPAddress": "ec2fleet.amazonaws.com",
  "userAgent": "ec2fleet.amazonaws.com",
  "requestParameters": {
    "instancesSet": {
      "items": [
        {
          "minCount": 1,
          "maxCount": 1
        }
      ]
    },
    "instanceType": "t3.2xlarge",
    "blockDeviceMapping": { },
    "availabilityZone": "eu-west-1b",
    "monitoring": {
      "enabled": false
    },
    "disableApiTermination": false,
    "disableApiStop": false,
    "clientToken": "fleet-xxx",
    "networkInterfaceSet": {
      "items": [
        {
          "deviceIndex": 0,
          "subnetId": "subnet-xxx",
          "associatePublicIpAddress": false,
          "groupSet": {
            "items": [
              {
                "groupId": "sg-xxx"
              }
            ]
          }
        }
      ]
    },
    "tagSpecificationSet": {
      "items": [
        {
          "resourceType": "instance",
          "tags": [ "xxx"
          ]
        },
        {
          "resourceType": "volume",
          "tags": [ "xxx"
          ]
        }
      ]
    },
    "launchTemplate": {
      "launchTemplateId": "lt-xxx",
      "version": "1"
    }
  },
  "responseElements": {
    "requestId": "xxx",
    "reservationId": "r-xxx",
    "ownerId": "xxx",
    "groupSet": { },
    "instancesSet": {
      "items": [
        {
          "instanceId": "i-xxx",
          "imageId": "ami-0a915a467a87d1c66",
          "currentInstanceBootMode": "legacy-bios",
          "instanceState": {
            "code": 0,
            "name": "pending"
          },
          "privateDnsName": "ip-xxx.eu-west-1.compute.internal",
          "operator": {
            "managed": false
          },
          "amiLaunchIndex": 0,
          "productCodes": { },
          "instanceType": "t3.2xlarge",
          "launchTime": 1750077303000,
          "placement": {
            "availabilityZone": "eu-west-1b",
            "tenancy": "default"
          },
          "monitoring": {
            "state": "disabled"
          },
          "subnetId": "subnet-xxx",
          "vpcId": "vpc-xxx",
          "privateIpAddress": "xxx",
          "stateReason": {
            "code": "pending",
            "message": "pending"
          },
          "architecture": "x86_64",
          "rootDeviceType": "ebs",
          "rootDeviceName": "/dev/xvda",
          "blockDeviceMapping": { },
          "virtualizationType": "hvm",
          "hypervisor": "xen",
          "tagSet": {
            "items": [ "..."
            ]
          },
          "clientToken": "fleet-xxx",
          "groupSet": {
            "items": [
              {
                "groupId": "sg-xxx",
                "groupName": "xxx-xxx-1-eks-workers-sg"
              }
            ]
          },
          "sourceDestCheck": true,
          "networkInterfaceSet": {
            "items": [
              {
                "networkInterfaceId": "eni-xxx",
                "subnetId": "subnet-xxx",
                "vpcId": "vpc-xxx",
                "ownerId": "xxx",
                "operator": {
                  "managed": false
                },
                "status": "in-use",
                "macAddress": "xxx",
                "privateIpAddress": "xxx",
                "privateDnsName": "ip-xxx.eu-west-1.compute.internal",
                "sourceDestCheck": true,
                "interfaceType": "interface",
                "groupSet": {
                  "items": [
                    {
                      "groupId": "sg-xxx",
                      "groupName": "xxx-xxx-1-eks-workers-sg"
                    }
                  ]
                },
                "attachment": {
                  "attachmentId": "eni-attach-xxx",
                  "deviceIndex": 0,
                  "networkCardIndex": 0,
                  "status": "attaching",
                  "attachTime": 1750077303000,
                  "deleteOnTermination": true
                },
                "privateIpAddressesSet": {
                  "item": [
                    {
                      "privateIpAddress": "xxx",
                      "privateDnsName": "ip-xxx.eu-west-1.compute.internal",
                      "primary": true
                    }
                  ]
                },
                "ipv6AddressesSet": { },
                "tagSet": { }
              }
            ]
          },
          "iamInstanceProfile": {
            "arn": "arn:aws:iam::xxx:instance-profile/terraform-xxx-xxx-1-node",
            "id": "xxx"
          },
          "ebsOptimized": false,
          "enaSupport": true,
          "cpuOptions": {
            "coreCount": 4,
            "threadsPerCore": 2
          },
          "capacityReservationSpecification": {
            "capacityReservationPreference": "open"
          },
          "enclaveOptions": {
            "enabled": false
          },
          "metadataOptions": {
            "state": "pending",
            "httpTokens": "required",
            "httpPutResponseHopLimit": 2,
            "httpEndpoint": "enabled",
            "httpProtocolIpv4": "enabled",
            "httpProtocolIpv6": "disabled",
            "instanceMetadataTags": "disabled"
          },
          "maintenanceOptions": {
            "autoRecovery": "default"
          },
          "privateDnsNameOptions": {
            "hostnameType": "ip-name",
            "enableResourceNameDnsARecord": false,
            "enableResourceNameDnsAAAARecord": false
          }
        }
      ]
    },
    "requesterId": "xxx"
  },
  "requestID": "xxx",
  "eventID": "xxx",
  "readOnly": false,
  "eventType": "AwsApiCall",
  "managementEvent": true,
  "recipientAccountId": "xxx",
  "eventCategory": "Management"
}
```

</details>

---

**Expected Behavior**:

Calls to runInstance are still made by `ec2fleet.amazonaws.com`

**Reproduction Steps** (Please include YAML):

N/A

**Versions**:
- Chart Version: 1.5.0
- Kubernetes Version (`kubectl version`): `Server Version: v1.27.16-eks-4096722`

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
I understand the blocker. Regarding the Security Control Policy (SCP), we need more clarity since both CreateFleet and RunInstances APIs can launch EC2 instances. To move forward, it would be helpful to understand what specific SCP conditions are currently in place, any specific instance types or configurations we need to control, and our security requirements for instance launches. Additionally, could you explain why this particular constraint was initially implemented? This information will help us implement comprehensive controls across both APIs and ensure we're addressing the original security concerns effectively.

**Comment by WesselAtWork** [comment]
This happened between v1.2.x to v1.3.x
I think it's the new ec2Class validation hook that was added.  
(v1.3.0 _MIGHT_ work, but v1.3.1 definitely doesn't) 

We are currently stuck on v1.2.4 until we can figure out a workaround or get the org to whitelist the EKS AMI's

> I think what is happening here is a confused-deputy problem, somehow the way that karpenter calls `ec2:RunInstances` involves the "ec2fleet.amazonaws.com" which the Org SCP is not limiting.  So the "duputy" ec2fleet.amazonaws.com is doing something that you shouldn't have permissions to do in the first place.   
maybe. unsure.

The validation hook I am talking about is this one:
```yaml
    - lastTransitionTime: '2025-01-01T00:00:00Z'
      message: Controller isn't authorized to call ec2:RunInstances
      observedGeneration: 1
      reason: RunInstancesAuthCheckFailed
      status: 'False'
      type: ValidationSucceeded
```

@elouanKeryell-Even 
Try with v1.2.4
Remember to delete your ec2class and re-create it
