### ISSUE TITLE
On-demand instances not being consolidated properly

### ISSUE THREAD

**Issue by SmaineTF1** [aws/karpenter-provider-aws#8211]
### Description

**Observed Behavior**:

Since a few days we noticed that the resources optimization is not done properly, we're currently wasting about **50% of our capacity**.

![Image](https://github.com/user-attachments/assets/ae4c474a-4443-48da-9315-26a98c07e484)

**Expected Behavior**:

Better consolidation, resources optimizations > 80%

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: v1.1.1
- Kubernetes Version (`kubectl version`): v1.31.9-eks-5d4a308

We have a pretty simple nodepool defined as follows, which takes handles both on-demand and spot instances.

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "6821555240594823858"
    karpenter.sh/nodepool-hash-version: v3
  name: default
spec:
  disruption:
    budgets:
    - nodes: 50%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 7000
    memory: 8000Gi
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: karpenter.k8s.aws/instance-cpu
        operator: Lt
        values:
        - "49"
      - key: karpenter.k8s.aws/instance-memory
        operator: Lt
        values:
        - "100001"
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
