### ISSUE TITLE
Nodes not getting disrupted because of Drifted reason

### ISSUE THREAD

**Issue by carlospiazza** [aws/karpenter-provider-aws#8212]
### Description

**Observed Behavior**:

We have an on-demand nodepool that sets an alias for the ami selector that triggers an ami drift on the nodes, but the nodes do not get disrupted and replaced even when the budget allows for it.

If we change the schedule to disallow disruption we can see the event: 

```
0s          Normal    DisruptionBlocked           nodepool/default            No allowed disruptions for disruption reason Drifted due to blocking budget
```

But after modifying the schedule to allow it, no disruption occurs.

The status of a nodeclaim that has the ami drift and is not blocked by any pdb, but does not gets replaced is:
```
[...]
status:
  allocatable:
    cpu: 15890m
    ephemeral-storage: "60773787238"
    memory: 27381Mi
    pods: "234"
    vpc.amazonaws.com/pod-eni: "54"
  capacity:
    cpu: "16"
    ephemeral-storage: 64Gi
    memory: 30310Mi
    pods: "234"
    vpc.amazonaws.com/pod-eni: "54"
  conditions:
  - lastTransitionTime: "2025-06-11T10:45:23Z"
    message: ""
    observedGeneration: 1
    reason: Launched
    status: "True"
    type: Launched
  - lastTransitionTime: "2025-06-11T10:45:42Z"
    message: ""
    observedGeneration: 1
    reason: Registered
    status: "True"
    type: Registered
  - lastTransitionTime: "2025-06-11T10:46:10Z"
    message: ""
    observedGeneration: 1
    reason: Initialized
    status: "True"
    type: Initialized
  - lastTransitionTime: "2025-06-11T10:55:23Z"
    message: ""
    observedGeneration: 1
    reason: ConsistentStateFound
    status: "True"
    type: ConsistentStateFound
  - lastTransitionTime: "2025-06-23T20:33:54Z"
    message: AMIDrift
    observedGeneration: 1
    reason: AMIDrift
    status: "True"
    type: Drifted
  - lastTransitionTime: "2025-06-24T15:01:05Z"
    message: ""
    observedGeneration: 1
    reason: Consolidatable
    status: "True"
    type: Consolidatable
  - lastTransitionTime: "2025-06-11T10:46:10Z"
    message: ""
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
```

No error log is shown, even on debug mode. Nodes appear Drifted, but are never replaced, even when we change something different as just the AMI like a tag. This is troublesome as an update of the control plane does will not trigger the update of the nodes with the new version AMI as we would expect.

**Expected Behavior**:

Nodes that are not blocked by a pdb gets replaced

**Reproduction Steps** (Please include YAML):
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "3993609107939410668"
    karpenter.sh/nodepool-hash-version: v3
  name: default
spec:
  disruption:
     budgets:                                                                                                                                                       
     - duration: 24h                                                                                                                                                
       nodes: "1"                                                                                                                                                   
       reasons:                                                                                                                                                     
       - Drifted                                                                                                                                                    
       - Underutilized                                                                                                    
       schedule: 0 0 * * mon-fri 
    consolidateAfter: 10m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: "500"
    memory: 3.5Ti
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
      - key: karpenter.k8s.aws/instance-category
        minValues: 1
        operator: In
        values:
        - t
        - m
        - c
        - r
      - key: karpenter.k8s.aws/instance-family
        minValues: 1
        operator: NotIn
        values:
        - m3
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "2"
        - "4"
        - "8"
        - "16"
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-east-2a
        - us-east-2b
        - us-east-2c
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      startupTaints:
      - effect: NoExecute
        key: node.cilium.io/agent-not-ready
        value: "true"
      terminationGracePeriod: 48h
  weight: 10
```

**Versions**:
- Chart Version: 1.3.4
- Kubernetes Version (`kubectl version`): 1.31

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pandvan** [comment]
We're facing the same issue. Karpenter 1.1.5, EKS just upgraded to 1.31
The nodepool with only on-demand nodes recognizes the drift, but nodes are not replaced.
Looking thoroughly logs, nothing useful has been found.

**Comment by jigisha620** [comment]
>budgets:                                                                                                                                                       
     - duration: 24h                                                                                                                                                
       nodes: "1"                                                                                                                                                   
       reasons:                                                                                                                                                     
       - Drifted                                                                                                                                                    
       - Underutilized                                                                                                    
       schedule: 0 0 * * mon-fri

This budget allows only 1 node to disrupt every 24 hours from Mon-Fri. The nodeclaim that you have shared seems to have drifted on a weekday and in that case only 1 node would be allowed to disrupt so if there's already a disruption that has occurred, I don't think more disruptions can happen. But I can't say that with certainty without looking at more logs. Also if you could share the node id that did not get disrupted and your cluster-arn, I can probably check. But other than that I will have to look at the controller logs.

**Comment by carlospiazza** [comment]
> This budget allows only 1 node to disrupt every 24 hours from Mon-Fri. The nodeclaim that you have shared seems to have drifted on a weekday and in that case only 1 node would be allowed to disrupt so if there's already a disruption that has occurred, I don't think more disruptions can happen. 

That does not seems to be what the documentation implies, from our understanding, that budget should allow a window of 24hs every weekday where only one disruption at a time can be evaluated. Once 1 disruption is taken care of, karpenter can continue with another one inside that window, and so on. Wouldn't otherwise mean that the default "nodes: 10%" when no budget is set allows only 10% of nodes to be disrupted in perpetuity?

Regarding logs, there is no logs, not even in debug mode. We set that budget, we even manually drift the nodes, and nothing happens, so i have no controller logs to show about it, that is also why is so confusing.

Maybe it is related to what is stated [here on #8211](https://github.com/aws/karpenter-provider-aws/issues/8211#issuecomment-3032523749).

**Comment by carlospiazza** [comment]
In an attempt to further test, we have another nodepool with this schedule configured in which we want to allow consolidation of underutilized/drifted nodes restricted to a weekend window, and we are seeing the same behavioud, the drifted nodes do not get consolidated (rest of the configuration is the same):

```
      #  No disruption during week days    
      - schedule: "0 0 * * mon-fri"
        duration: 24h
        reasons:
          - Drifted
          - Underutilized
        nodes: "0"
      # 2. On saturday, we block from 00:00hs to 16:00hs
      - schedule: "0 0 * * sat"
        duration: 16h
        reasons:
          - Drifted
          - Underutilized
        nodes: "0"
      # And on Sunday, we block from 16:00hs to 00:00hs
      - schedule: "0 16 * * sun"
        duration: 8h
        reasons:
          - Drifted
          - Underutilized
        nodes: "0"
      # Outside of that "nodes = 0" schedule,
      # Allow 2 node max at a time on the weekend window 
      # from sat-16:00 to sun-16:00.
      - nodes: "2"
```

**Comment by andrea-pavan** [comment]
We use a very simple disruption policy

```yaml
disruption:
  consolidationPolicy: WhenEmpty
  consolidateAfter: 5m
  budgets:
    - nodes: 10%
```

so the expectation here is that once AMI is changed, nodes start to be disrupted, 10% of them at every "loop".
Nothing happens, even if status in _nodeclaim_ shows it is drifted

```
status:
  conditions:
  - lastTransitionTime: "2025-06-11T12:20:19Z"
    message: ""
    observedGeneration: 1
    reason: Launched
    status: "True"
    type: Launched
  - lastTransitionTime: "2025-06-11T12:20:43Z"
    message: ""
    observedGeneration: 1
    reason: Registered
    status: "True"
    type: Registered
  - lastTransitionTime: "2025-06-11T12:21:13Z"
    message: ""
    observedGeneration: 1
    reason: Initialized
    status: "True"
    type: Initialized
  - lastTransitionTime: "2025-06-11T12:30:20Z"
    message: ""
    observedGeneration: 1
    reason: ConsistentStateFound
    status: "True"
    type: ConsistentStateFound
  - lastTransitionTime: "2025-06-30T09:52:30Z"
    message: AMIDrift
    observedGeneration: 1
    reason: AMIDrift
    status: "True"
    type: Drifted
  - lastTransitionTime: "2025-07-07T09:03:30Z"
    message: ""
    observedGeneration: 1
    reason: Consolidatable
    status: "True"
    type: Consolidatable
  - lastTransitionTime: "2025-06-11T12:21:13Z"
    message: ""
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
```

How can we further debug this issue to get more insights?

**Comment by pandvan** [comment]
We use a very simple disruption policy

```yaml
disruption:
  consolidationPolicy: WhenEmpty
  consolidateAfter: 5m
  budgets:
    - nodes: 10%
```

so the expectation here is that once AMI is changed, nodes start to be disrupted, 10% of them at every "loop".
Nothing happens, even if status in _nodeclaim_ shows it is drifted

```yaml
status:
  conditions:
  - lastTransitionTime: "2025-06-11T12:20:19Z"
    message: ""
    observedGeneration: 1
    reason: Launched
    status: "True"
    type: Launched
  - lastTransitionTime: "2025-06-11T12:20:43Z"
    message: ""
    observedGeneration: 1
    reason: Registered
    status: "True"
    type: Registered
  - lastTransitionTime: "2025-06-11T12:21:13Z"
    message: ""
    observedGeneration: 1
    reason: Initialized
    status: "True"
    type: Initialized
  - lastTransitionTime: "2025-06-11T12:30:20Z"
    message: ""
    observedGeneration: 1
    reason: ConsistentStateFound
    status: "True"
    type: ConsistentStateFound
  - lastTransitionTime: "2025-06-30T09:52:30Z"
    message: AMIDrift
    observedGeneration: 1
    reason: AMIDrift
    status: "True"
    type: Drifted
  - lastTransitionTime: "2025-07-07T09:03:30Z"
    message: ""
    observedGeneration: 1
    reason: Consolidatable
    status: "True"
    type: Consolidatable
  - lastTransitionTime: "2025-06-11T12:21:13Z"
    message: ""
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
```

How can we further debug this issue to get more insights?

**Comment by pandvan** [comment]
Just noted that even if the nodepool drifted, no node will be disrupted.

```yaml
  - lastTransitionTime: "2025-06-30T09:52:30Z"                                                                                                                                           
    message: NodePoolDrifted                                                                                                                                                             
    observedGeneration: 1                                                                                                                                                                
    reason: NodePoolDrifted                                                                                                                                                              
    status: "True"                                                                                                                                                                       
    type: Drifted
```

Could be somehow related to `expireAfter` set to `Never`?
